### PR TITLE
[Unity] Improve error message in webgpu request

### PR DESCRIPTION
**Pull request by tqchen**
Sometimes user may get confused with an old version of browser, add more precise error message

### CODE REVIEW

**Review by junrushao — APPROVED** [review]

**Comment by DustinBrett** [comment]
Are these hard requirements? I am trying to get WebLLM going on Android and the only requirement it can't do is `maxStorageBufferBindingSize`.

**Comment by tqchen** [comment]
the `maxStorageBufferBindingSize` likely is due to the size of the models we are dealing with. I remember trying to halving it and get an error, you can try to reduce it a bit though.

Also i think these constraints will get lifted in the future versions, dawn's matrix channel would be a good place to ask

**Comment by DustinBrett** [comment]
> the `maxStorageBufferBindingSize` likely is due to the size of the models we are dealing with. I remember trying to halving it and get an error, you can try to reduce it a bit though.
> 
> Also i think these constraints will get lifted in the future versions, dawn's matrix channel would be a good place to ask

Ok, thanks for the quick reply! I am using Chrome Canary v115 on my Samsung Galaxy S20, but the limit seems to only be 128MB when it requires 1024MB. I will keep an eye on the progress and am happy to hear this could be lifted in the future. After seeing people running [mlc-llm](https://github.com/mlc-ai/mlc-llm) on mobile I am eager to do the same with WebLLM.

**Comment by beaufortfrancois** [comment]
Any updates on this issue?

**Comment by CharlieFRuan** [comment]
Hi @DustinBrett, the demo now has three models (ones with -1k suffix) that should be able to run with 128MB: https://webllm.mlc.ai/

**Pull request merged**
