### PR TITLE
[TIR] Bind iter domain in analyzer in CreatePrimFunc

### PR DESCRIPTION
**Pull request by vinx13**
cc @Hzfengsy @junrushao1994

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM! BTW, does it guarantee that the PrimFunc created is simplified?

**Comment by vinx13** [comment]
It makes best efforts. But generally arith analyzer doesn't guarantee the result is simplified

**Comment by junrushao1994** [comment]
Do you think it might make sense to call the Simplify pass upon PrimFunc creation?

**Comment by vinx13** [comment]
We've already called `analyzre->Simplify` for each expression, but it might still be helpful to call the `Simplify` pass again

**Pull request merged**
