### PR TITLE
[Relax] Validate StructInfo of variable bindings

### PR DESCRIPTION
**Pull request by Lunderberg**
In Relax, both the variable and the expression in a `VarBinding` may contain `StructInfo` annotations.  Prior to this commit, these `StructInfo` annotations could be inconsistent, assigning an expression to a variable of incompatible type.

This commit updates the Relax well-formed checker to verify that the `StructInfo` of Relax variables accurately describes their contents.

### CODE REVIEW

**Comment by Lunderberg** [comment]
This validation exposed a bug in `StructInfoLCA`, which only inspected the datatype of `PrimStructInfo` and not the known value.  This bug was introduced in https://github.com/apache/tvm/pull/15577, which added tracking fo known `PrimStructInfo`, but didn't update `StructInfoLCA`.  This bug would result in incorrect known value annotations in the `StructInfo`, after a conditional statement.  Since these annotations are later used to simplify known expressions, this bug could have resulted in incorrect simplifications.

The bug in `StructInfoLCA` is fixed as part of this PR.

**Comment by Lunderberg** [comment]
Rebased onto main to resolve conflicts in `test_analysis_well_formed.py`.

**Comment by tqchen** [comment]
cc @yongwww

**Review by yongwww — APPROVED** [review]
Looks good to me!

**Pull request merged**
