### PR TITLE
Add a 'rolling_buffer' scheduling primitive

### PR DESCRIPTION
**Pull request by NicolaLancellotti**
This pr add a rolling buffer scheduling primitive.
The pr is based on @mbaret's pr #7925 , and it differs in that the `InjectRollingBuffer` pass has been rewritten in C++, (originally it was written in Python).
Also since the original pr was written, the TIR changed a bit, and as a consequence, some code has been moved between the visitors' methods.

### CODE REVIEW

**Comment by manupa-arm** [comment]
This is based on #7925 but in C++.
cc : @junrushao1994 @jcf94 @Hzfengsy it would be great if we great if you guys can have another look. TIA

**Comment by NicolaLancellotti** [comment]
I fixed the CI issues.

**Comment by manupa-arm** [comment]
@mbaret -- Would you be able to have a look and see if its matching the original implementation we could get this in ? Possibly follow up if and when concerns arises later ?

**Review by junrushao1994 — APPROVED** [review]
LGTM. It's similar logic with #7925 and re-implemented in C++. Thanks!

**Review by Hzfengsy — APPROVED** [review]
LGTM

**Pull request merged**
