### PR TITLE
[Bugfix][Frontend][Keras] Add a check to reject the invalid input shape

### PR DESCRIPTION
**Pull request by jikechao**
This pr adds a checking for the input_shape.  If the input_shape is invalid, we will reject it immediately!

### CODE REVIEW

**Review by leandron — APPROVED** [review]
LGTM, thanks @jikechao

**Comment by jikechao** [comment]
@leandron Thanks for your review！

**Comment by jikechao** [comment]
@tvm-bot rerun

**Comment by jikechao** [comment]
@Hzfengsy @echuraev @leandron 
CI passed. Could you help me merge this PR?

**Pull request merged**
