### PR TITLE
[CI] Update minor git options

### PR DESCRIPTION
**Pull request by mshr-h**
The changes are listed below.
- avoid git checkout after git clone

### CODE REVIEW

**Review by junrushao — APPROVED** [review]
LGTM! Thanks for improving the git usage :-)

**Comment by driazati** [comment]
I'm good with merging this PR but just curious about `--filter=tree:0`, it seems like from that article that `--depth=1` is still best here since it avoids downloading the whole history and we're not accessing any commits other than the checked out `HEAD`, am I missing something about it?

**Comment by mshr-h** [comment]
@driazati 
Thanks for your comment!
You're right. Unless we need commit history), `--depth=1` is ok.
I guess that's more like a personal preference.

**Comment by mshr-h** [comment]
I noticed that `--filter=tree:0` is supported since git 2.20 and Ubuntu 18.04 LTS has git 2.17.
We can't use `--filter=tree:0`. I'll revert it.

**Review by driazati — APPROVED** [review]

**Pull request merged**
