### PR TITLE
[ETHOSN] Ethos(TM)-N 21.11 update

### PR DESCRIPTION
**Pull request by Leo-arm**
Minor update in inference buffer mapping due to changes in the driver
library

### CODE REVIEW

**Comment by AndrewZhaoLuo** [comment]
Do you have an issue to link for upgrading the CI images?

**Comment by Leo-arm** [comment]
I was waiting for this patch to circle back to our downstream CI so I can update that and flush out any remaining issues, if any, and then we can update the docker images.

**Review by mbaret — APPROVED** [review]
LGTM

**Review by Mousius — APPROVED** [review]

**Comment by Mousius** [comment]
Thanks @Leo-arm / @mbaret!

**Pull request merged**
