### PR TITLE
[usmp] Also remap VarNode to USMP-allocated buffer

### PR DESCRIPTION
**Pull request by areusch**
This PR fixes cases where a USMP buffer is used with tensorization intrinsics. In these cases, it is common to
write schedules that pass Buffers to extern functions using `access_ptr()`. When transforming tir.allocate into
offsets into global_workspace buffers, USMP inserts a let expression that replaces the old Buffer var with a new
var named "<buffer_var>_let." It then attempts to replace all references to the old var with the new one. When
a Buffer was passed via `access_ptr`, USMP would would previously ignore such instances, producing this error
later on in codegen (dense being the name of the Buffer in use):

```
  "src/target/source/codegen_source_base.cc", line 67
  Check failed: (it != var_idmap_.end()) is false: Find undefined
    Variable dense
```

This patch fixes the problem by replacing the old VarNode with the new one.

cc @lhutton1 @Mousius @leandron @manupak @mehrdadh

### CODE REVIEW

**Comment by areusch** [comment]
NOTE: sending this through CI to see what I broke, then will add tests.

**Comment by lhutton1** [comment]
also cc @d-smirnov

**Comment by manupak** [comment]
Hmmmm... I suppose this scenario want to pass a buffer itself to the call (as opposed to a BufferLoad) ?

**Comment by areusch** [comment]
@manupak I think it's ok to pass the buffer's `data` var, since the receiving function expects `T.handle` and will build its own Buffer around it, no? wdyt?

**Comment by manupak** [comment]
Thanks for the fix -- yea I double checked whether buffer info extraction captures this scenario as well -- it seems so. If we can get the tests and LOG(INFO)s removed -- I think we cant get this in...

**Comment by areusch** [comment]
@manupak great, deleted the LOG lines and added a test. please take a look!

**Review by lhutton1 — APPROVED** [review]
Thanks @areusch, LGTM! Will leave for @manupak to take another look :)

**Review by manupak — APPROVED** [review]
LGTM! Thanks @areusch and @lhutton1

**Comment by manupak** [comment]
I think we need a commit message

**Comment by manupak** [comment]
to clarify a bit more -- I just meant to say, according to https://github.com/apache/tvm/blob/main/docs/contribute/pull_request.rst, we might want to put a textual description in here in the body as the test in the PR shows what is being fixed. Also I think we can remove the first bullet point too.

**Comment by areusch** [comment]
gotcha, updated the message.

**Pull request merged**
