### PR TITLE
[Utils] Disable automatic move constructor for tvm::With

### PR DESCRIPTION
**Pull request by Lunderberg**
Previously, `tvm::With` had the default compiler-provided move constructors.  If these were used (e.g. by storing a `With` into a vector), the `ExitWithScope` would be called multiple times.  ~~This commit explicitly removes the copy constructor/assignment, and explicitly implements move constructor/assignment.~~  This commit explicitly disables both copy and move constructors and assignments for `tvm::With` to avoid this failure mode.

### CODE REVIEW

**Comment by Lunderberg** [comment]
This arose as a potential concern for segfaults when making a `std::vector<With<ConstraintContext>>`, as the vector may internally call a copy constructor, resulting in multiple calls to the same `ExitWithScope`.  This never ended up being the issue, but I wanted to remove it from any future debugging.

**Comment by janetsc** [comment]
Looks good

**Comment by tqchen** [comment]
Would be great to think about we really want to enable the case of `vector<With>`. With is originally designed to only as a sugar to enter a context and exit with RAII but not intended to put them into a vector.

Specifically, the default constructor(that initialize optional as nullopt) can be confusing for people who intended to start and use it. Perhaps we can simply disable the copy constructor in this case and make move constructor available only if the underlying Context itself is movable.

This way we would avoid the default copy constructors. Construction of moveable only value would be more tricky but doable through emplace. Finally, we can find alternatives when maintaining multiple such Constraint. E.g. a different constraint context that takes multiple such constraints.

**Comment by Lunderberg** [comment]
> Would be great to think about we really want to enable the case of vector<With>. 

I had found it useful for cases where I had `N` expressions, and I wanted to simplify one of them under the condition that the other `N-1` of them are true.  The `vector<With>` felt like the cleaner solution, as compared to constructing an `And` of the `N-1` conditions, then destructuring it back into `N-1` conditions on the other side.

> Specifically, the default constructor(that initialize optional as nullopt) can be confusing for people who intended to start and use it.

I had been seeing it as a default for cases where a context may or may not be required.  That said, now that we have C++17 we could instead use `std::optional<With<T>>`, so that use case isn't relevant anymore.

> With is originally designed to only as a sugar to enter a context and exit with RAII but not intended to put them into a vector.

This makes sense, though in that case I think we should disable both the copy and move constructor.

> Perhaps we can simply disable the copy constructor in this case and make move constructor available only if the underlying Context itself is movable.

This would work for classes that already function entirely as context managers (e.g. `arith::ConstraintContext`), though in those cases the `With` wrapper becomes unnecessary.  For classes where the class serves as both a data type and as a context (e.g. `tvm::Target`), I think we need to distinguish between whether the context can be moved/copied, and whether the context manager can be moved/copied.

> Finally, we can find alternatives when maintaining multiple such Constraint. E.g. a different constraint context that takes multiple such constraints.

For cases where the order of exiting a context must be the reverse of entering the context, I agree.  For cases where the order of exiting the context is arbitrary, but where several destructors should all be held and called at a later point, that's already the behavior of `std::vector<ContextManager>`, so I don't think we'd need to recreate it.

**Comment by Lunderberg** [comment]
Looking through it again, I think the move constructor only makes sense in cases where it is legal to exit scopes in something other than the reverse order of entering scopes.  For most use cases I could see (e.g. maintaining a stack of a current value), the order of destruction shouldn't be allowed to vary.  My concern was primarily that the implicitly generated copy/move constructors would result in incorrect behavior, and to remove that failure mode.  Disabling the move constructor altogether serves this same purpose, so I can update the PR to instead disable the automatically-generated move constructor.

**Comment by tqchen** [comment]
Agree with removing both constructors and find alternatives

**Review by tqchen — APPROVED** [review]

**Review by tqchen — APPROVED** [review]

**Pull request merged**
