### PR TITLE
[Docs] Fix MetaSchedule Docs

### PR DESCRIPTION
**Pull request by zxybazh**
Following up #14453 to resolve issues in CI.

### CODE REVIEW

**Comment by zxybazh** [comment]
@tvm-bot rerun

**Comment by zxybazh** [comment]
@tvm-bot retun

**Comment by zxybazh** [comment]
@tvm-bot rerun

**Comment by zxybazh** [comment]
@tvm-bot rerun

**Comment by zxybazh** [comment]
@tvm-bot rerun

**Comment by zxybazh** [comment]
@junrushao This PR should be ready for review now.

**Review by Hzfengsy — APPROVED** [review]

**Comment by junrushao** [comment]
Nice! Let’s get it in!

**Pull request merged**
