### PR TITLE
[Relay] Add support of conv2d with NHWC for Mali

### PR DESCRIPTION
**Pull request by AnastasiaStulova**
Added template schedule for conv2d NHWC reusing similar strategy
as for NCHW layout. The schedule is also added to the
corresponding test that can be run to verify correctness.

### CODE REVIEW

**Comment by AnastasiaStulova** [comment]
NOTE that this patch need the fix in https://github.com/apache/tvm/pull/8361 to pass the test cases with deletion > 1.

**Comment by AnastasiaStulova** [comment]
@mbaret

**Comment by AnastasiaStulova** [comment]
@merrymercy @i4oolish

**Review by jcf94 — APPROVED** [review]
LGTM. Thanks! @AnastasiaStulova 
Let's merge #8361 first.

**Pull request merged**
