### PR TITLE
[MetaSchedule] Evo Independence from TaskScheduler

### PR DESCRIPTION
**Pull request by junrushao1994**
Per discussion with @Kathryn-cat, we realized that the current API
design could be verbose if we only want to tune a single task, in which
case a dummy task scheduler still needs to be established to supply
`EvolutionarySearch` with proper `CostModel` and `Database`. This PR
fixes this UX issue.

### CODE REVIEW

**Comment by Kathryn-cat** [comment]
I tested on local and it looks good! Perhaps add a hint showing that `database` is required in some situations like evolutionary search and optional in other situations?

**Comment by junrushao1994** [comment]
Thank you @Kathryn-cat for the valuable feedback! Will do!

**Comment by junrushao1994** [comment]
@Kathryn-cat Hey I improved the error message with clear instructions of what to do. Let me know if it looks good :-)

**Comment by Kathryn-cat** [comment]
Looks good to me!

**Review by Kathryn-cat — APPROVED** [review]
Files in this PR look good! Perhaps `initialize_with_tune_context` can be removed from some test files in the future and be marked for internal use only.

**Review by Hzfengsy — APPROVED** [review]

**Pull request merged**
