### PR TITLE
[CI] Upgrade unity image tag to `20240917-153130-9f281758`

### PR DESCRIPTION
**Pull request by mshr-h**
Part of #17346

### CODE REVIEW

**Comment by mshr-h** [comment]
Seems like we need upload the ci image to somewhere?
cc @tqchen @yongwww @vinx13 

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-unity/detail/PR-17410/1/pipeline
> [2024-09-24T03:29:25.163Z] + docker/bash.sh tlcpack/ci_cpu:20240917-153130-9f281758 ./tests/scripts/task_config_build_cpu.sh build
> [2024-09-24T03:29:35.119Z] REPO_DIR: /tmp/jenkins-005152d0/workspace/exec_0/tvm/build-cpu
> [2024-09-24T03:29:35.119Z] DOCKER CONTAINER NAME: tlcpack/ci_cpu:20240917-153130-9f281758
> [2024-09-24T03:29:35.119Z] 
> [2024-09-24T03:29:35.119Z] Running 'bash --login /docker/with_the_same_user ./tests/scripts/task_config_build_cpu.sh build' inside tlcpack/ci_cpu:20240917-153130-9f281758...
> [2024-09-24T03:29:35.119Z] Unable to find image 'tlcpack/ci_cpu:20240917-153130-9f281758' locally
> [2024-09-24T03:29:35.377Z] docker: Error response from daemon: manifest for tlcpack/ci_cpu:20240917-153130-9f281758 not found: manifest unknown: manifest unknown.
> [2024-09-24T03:29:35.377Z] See 'docker run --help'.
> script returned exit code 125

**Comment by vinx13** [comment]
I pushed them to tlcpack repo in dockerhub

**Comment by mshr-h** [comment]
@tvm-bot rerun

**Comment by mshr-h** [comment]
@tvm-bot rerun

**Review by tqchen — APPROVED** [review]

**Pull request merged**
