### PR TITLE
[release] Bump version numbers to 0.13.0

### PR DESCRIPTION
**Pull request by spectrometerHBH**
This bumps all the version numbers on v0.13.0 branch as correct v0.13.0.

### CODE REVIEW

**Comment by ysh329** [comment]
It seems conflict met as below:
image

**Comment by junrushao** [comment]
@tvm-bot /rerun

**Comment by junrushao** [comment]
@tvm-bot rerun

**Comment by ysh329** [comment]
I think we meet the problem same as [last time](https://github.com/apache/tvm/pull/14712) 😢 . @driazati can you help?

**Comment by Johnson9009** [comment]
Can anybody help to see the CI issue? It seems these thing block the process of release schedule several times.

**Comment by Hzfengsy** [comment]
cc @tqchen

**Comment by leandron** [comment]
I think for next releases we should create a branch which doesn't conform the with pattern that gets automatically protected, and instead, create something like `v0.15.0-rc0`. Once everything is settled, then we just mark that as the official branch, otherwise, we'll always face this issue.

@tqchen do you know any other alternative?

**Comment by ysh329** [comment]
> created https://github.com/apache/tvm/tree/rc-v0.13.0, and confirmed that it do not have protection. as long as v0.13.0 prefix exists the branch is still protected.
> 
> Let us send the PR there and do the release, then we can create a branch later, likely need to do so with manual push. We need signed commits (which merging to the branch achieves)

Great. It seems that in the future, we need to first create a candidate branch named rc-v0.xx.0.

Hi @spectrometerHBH , can you help send the PR to branch `rc-v0.13.0`?

**Comment by ysh329** [comment]
> > created https://github.com/apache/tvm/tree/rc-v0.13.0, and confirmed that it do not have protection. as long as v0.13.0 prefix exists the branch is still protected.
> > Let us send the PR there and do the release, then we can create a branch later, likely need to do so with manual push. We need signed commits (which merging to the branch achieves)
> 
> Great. It seems that in the future, we need to first create a candidate branch named `rc-v0.xx.0`. After version modification ensured, then create a branch named `v0.xx.0` instead.
> 
> Hi @spectrometerHBH , can you help send the PR to branch `rc-v0.13.0`?

I filed a PR https://github.com/apache/tvm/pull/15266

**Comment by tqchen** [comment]
Having a non-protected branch still helps, since that enables us to be able to pick changes in without having to rely on CI

**Comment by ysh329** [comment]
@tvm-bot rerun

**Comment by ysh329** [comment]
After rerun CI of this PR, conflict is existing. It seems is lack of `git pull` latest v0.13.0 with https://github.com/apache/tvm/pull/15267. Due to DDL, I made a PR https://github.com/apache/tvm/pull/15273 doing same thing.

**Comment by Hzfengsy** [comment]
finished in #15273

**Pull request closed without merging**
