### PR TITLE
Add PaddlePaddle dependency in docker file

### PR DESCRIPTION
**Pull request by jiangjiajun**
Add pip dependency of `paddlepaddle` in `docker/docker.ci_cpu` and `docker/docker.ci_gpu`

This pull request will modify TVM ci environment to support UT of PaddlePaddle frontend, the related pull request is here https://github.com/apache/tvm/pull/8645

@leandron

### CODE REVIEW

**Review by leandron — APPROVED** [review]
Thanks. LGTM, happy to merge once CI finishes.

**Review by jroesch — CHANGES_REQUESTED** [review]
Let's block this change until #8725 goes in

**Comment by junrushao1994** [comment]
The PR itself looks pretty good, and there is no conflict between this one and #8725 which requires much greater effort, so @jroesch would you elaborate why we need to block this PR? Thanks in advance!

**Comment by jiangjiajun** [comment]
> Let's block this change until #8725 goes in

Hi, @jroesch
Is there any conflict between this two pull request? Also there's another pull request https://github.com/apache/tvm/pull/8645  need to be merged after this pull request

**Comment by jroesch** [comment]
@jiangjiajun sorry for slowing you down, my worry was mostly about retriggering CI as there have been some CI stability issues lately and I wanted to make sure the CI changes went in since multiple PRs are blocked on that. Feel free to merge now. Sorry again.

**Review by jroesch — APPROVED** [review]

**Comment by junrushao1994** [comment]
Thanks Jared!

**Pull request merged**
