### PR TITLE
[Bugfix][Op] Fix shape inference of adv_index

### PR DESCRIPTION
**Pull request by hgt312**
Current `adv_index` will fail the simple case for it does not broadcast the shapes of indices:

```python
# data - (2, 2)
# ind0 - (1, 2)
# ind1 - (2, 1)
adv_index(data, ind0, ind1)
```

@yzhliu @comaniac

### CODE REVIEW

**Comment by masahi** [comment]
Can you also check if this fixes the issue in https://github.com/apache/tvm/issues/9237?

**Comment by hgt312** [comment]
> Can you also check if this fixes the issue in #9237?

it not fix that, that issue is about boolean index, see https://github.com/apache/tvm/pull/7373
I agree that we can add boolean indices support for `adv_index`

**Comment by hgt312** [comment]
Another question, can the failed CI be retry?

**Comment by masahi** [comment]
The CI has been dead since the last weekend. Please wait until it is back.

**Review by comaniac — APPROVED** [review]
LGTM

**Comment by jroesch** [comment]
@hgt312 can you push and trigger CI again?

**Comment by hgt312** [comment]
> @hgt312 can you push and trigger CI again?

rebased

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Comment by hgt312** [comment]
waiting for the CI issue fixed...

**Comment by masahi** [comment]
Please kick another CI job.

**Comment by hgt312** [comment]
@masahi rebased

**Comment by comaniac** [comment]
Thanks @hgt312 @masahi @junrushao1994

**Pull request merged**
