### PR TITLE
[MetaSchedule] update misc parts

### PR DESCRIPTION
**Pull request by Hzfengsy**
This PR updated misc parts in meta-schedule. 

cc @junrushao1994

### CODE REVIEW

**Comment by junrushao1994** [comment]
Please fix the CI BTW

**Review by zxybazh — APPROVED** [review]
LGTM.

**Review by MasterJH5574 — APPROVED** [review]
LGTM 😆

**Comment by junrushao1994** [comment]
Would you mind rebasing to the latest HEAD?

**Pull request merged**
