### PR TITLE
[Unity] Fix ForceNarrowI32 with pod arguments

### PR DESCRIPTION
**Pull request by tqchen**
This PR fixes ForceNarrowI32 for functions that comes with pod arguments.

Test cases are added

### CODE REVIEW

**Comment by tqchen** [comment]
will send a separate PR to main and cover the force narrow code.

**Review by junrushao — APPROVED** [review]
LGTM!

**Comment by junrushao** [comment]
We might want to send this PR to mainline as well

**Comment by tqchen** [comment]
agree, forcenarrow function is not yet in main, and we should send it later

**Pull request merged**
