### PR TITLE
[Frontend][PaddlePaddle] Add Support for PaddlePaddle Quantized Model

### PR DESCRIPTION
**Pull request by Zheng-Bicheng**
Add Support for PaddlePaddle Quantized Model

### CODE REVIEW

**Comment by Zheng-Bicheng** [comment]
@jiangjiajun

**Comment by Hzfengsy** [comment]
Note that it's not a unity-related PR, I've helped to change the title

**Comment by Zheng-Bicheng** [comment]
> Note that it's not a unity-related PR, I've helped to change the title

Thank you. By the way, I would like to inquire with you. Have you tested whether the `python tests/scripts/ci.py lint` command can work on the M1 mac?

**Comment by Zheng-Bicheng** [comment]
@jiangjiajun The `quantize_linear` operator of `paddle` seems to encounter calculation errors after being transformed into `tvm's` `_qnn.op.dequantize`, particularly in extreme cases. I am unsure if this issue is related to TVM optimization. Is there a way to investigate this? I tested the model used in CI with data ranging from -1 to 1, and the average cosine similarity is around **98%**.

**Pull request closed without merging**
