### PR TITLE
Simple workaround for PyTorch symbol crash problem in meta schedule test

### PR DESCRIPTION
**Pull request by masahi**
Without this, people might see an error like 
```
free(): invalid pointer
Aborted (core dumped)
```

This is a simple workaround for PyTorch vs LLVM symbol crash problem, that doesn't involve rebuild.

@junrushao1994 @zxybazh

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]

**Comment by junrushao1994** [comment]
looks like we couldn't import torch directly:

```
E   ModuleNotFoundError: No module named 'torch'
```

**Review by zxybazh — COMMENTED** [review]
LGTM but torch is not a tvm requirement so it might not work in the mainline.

**Comment by masahi** [comment]
ok added a workaround for `ci-cpu` (`ci-gpu` has PyTorch).

This is a workaround on top of another workaround...

**Review by zxybazh — APPROVED** [review]
LGTM as long as it could pass CI.

**Pull request merged**
