### PR TITLE
[TVMC][microTVM] Fix TVMC AttributeError When USE_MICRO is OFF

### PR DESCRIPTION
**Pull request by mehrdadh**
This PR fixes issue https://github.com/apache/tvm/issues/9679

cc @gromero @leandron

### CODE REVIEW

**Review by gromero — APPROVED** [review]
@mehrdadh Thanks for fixing it. LGTM!

Out of curiosity, on which environment you were able to reproduce it? Was that on the RVM? I've tried on a few ones yesterday (like Ubuntu 20.04 + Python 3.9 5) but I was not able to reproduce it...

**Comment by gromero** [comment]
@mehrdadh btw, the PR title is cool, but the commit title is not as good as the PR title and when there is only one commit in the PR the title that will be used for the commit that gets merged is the one from the commit (if the PR has multiple commits the PR title is used instead). Hence  it would be cool if next time (since we want  to avoid another CI retrigger) we try to be consistent for the sake of merging better commit messages in general :)

**Review by leandron — APPROVED** [review]
LGTM, thanks @mehrdadh @gromero!

**Comment by mehrdadh** [comment]
@gromero this was on ubuntu 18.08 and I was using python3.6
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```
Thanks for checking it. I think this clearly shows that we need nightly test of tlcpack on different OSs.

**Pull request merged**
