### PR TITLE
[TVMSCRIPT] Misc error message improvements

### PR DESCRIPTION
**Pull request by tkonolige**
This PR contains a couple of better error messages I've added to the tvmscript parser.

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Review by Hzfengsy — APPROVED** [review]
LGTM. Let's merge it when CI is green

**Comment by tkonolige** [comment]
@Hzfengsy @junrushao1994 CI is green. Can we merge?

**Comment by junrushao1994** [comment]
Of course! Thanks for improving the error message!

**Pull request merged**
