### PR TITLE
[Relay][dismantler] Added handling of packed func

### PR DESCRIPTION
**Pull request by d-smirnov**
Added handling of CallNode objects created via packed functions invocation + test cases. Related to #7832
@mbrookhart

### CODE REVIEW

**Comment by mbrookhart** [comment]
Can you add some comments to this? It's not clear why there need to be multiple deleter attributes in the CallNode class.

**Comment by d-smirnov** [comment]
There is a need to preform additional action and to preserve original deleter as well, hence an extra field for CallNode

**Comment by mbrookhart** [comment]
Can you add some comments to the code to explain what this is doing?

**Review by mbrookhart — APPROVED** [review]

**Comment by mbrookhart** [comment]
Thanks @d-smirnov

**Pull request merged**
