### PR TITLE
[TIR] Remove LoadNode and StoreNode

### PR DESCRIPTION
**Pull request by vinx13**
`Load` and `Store` were deprecated in [RFC0039](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0039-buffer-physical-layout.md). It has been several releases since the deprecation and it's no longer used in the codebase, now it is time to remove them.

cc @tqchen @Lunderberg @junrushao

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Review by junrushao — APPROVED** [review]
LGTM! This has been dead code for a long time

**Review by Lunderberg — APPROVED** [review]
Thank you for the clean-up!

**Review by MasterJH5574 — APPROVED** [review]
Thanks @vinx13!

**Comment by masahi** [comment]
@tqchen Seems the latest rebase broke build, since `Load/StoreNode` are used by relax code

**Comment by tqchen** [comment]
thanks @masahi for the catching, working to fix it atm, will report back

**Comment by tqchen** [comment]
should be fixed by now, sorry for the trouble

**Pull request merged**
