### PR TITLE
[TVMC] Separate model loading from model compilation in TVMC.

### PR DESCRIPTION
**Pull request by CircleSpin**
This PR moves the load component from compile_module to drive_compile to make it cleaner for python scripting. It prevents "double dipping" the load in frontends more than once. 
The flow is now 
1. mod, params = tvmc.load("whatever") #from frontends.py
2. lib, etc = tvmc.compile(mod, params) #from compiler.py

See PR #7698 for import details.

TVMC behavior from command line won't change, as this only effects compile_module directly from python.

### CODE REVIEW

**Comment by CircleSpin** [comment]
@comaniac @mdw-octoml @leandron @jwfromm

**Comment by comaniac** [comment]
I'm fine with this change. Leave on others.

**Review by leandron — APPROVED** [review]
LGTM as well.

**Review by jwfromm — APPROVED** [review]

**Comment by jwfromm** [comment]
Thanks @CircleSpin, @comaniac, and @leandron. This is now merged.

**Pull request merged**
