### PR TITLE
[DNNL] Fix end of line in test_dnnl UT file

### PR DESCRIPTION
**Pull request by billishyahao**
The end of line in test_dnnl.py is CRLF which is not identical to other python files. This patch is going to fix this by replacing CRLF to LF.

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by billishyahao** [comment]
Hi @masahi , Could you please review this change?

**Comment by masahi** [comment]
Why do we need to fix this?

**Comment by AndrewZhaoLuo** [comment]
If I understand this change correctly this is entirely style; git will handle different line deliminators fine, but the issue is that if a windows dev edits a file with LF, it will replace all lines with CRLF through the entire file which means every line will be changed in diffs. This will make the commit log a bit gummier.

cc @areusch @driazati it seems like a good idea to force LF for new lines? can we lint for this.

**Comment by driazati** [comment]
We should definitely check for this kind of thing in CI, opened #11609

**Comment by billishyahao** [comment]
Hi @masahi , @AndrewZhaoLuo , I hit this issue when I am trying to accomplish my another PR https://github.com/apache/tvm/pull/11513 . It seems that somebody use windows as development environment and unexpectedly reformat the whole LF to CRLF. Git status command shows this change and it is annoying for other developer of tvm. To eliminate this issue, I propose this patch. 
As Andrew 's words, it is better to enable lint to avoid other people to change LF to CRLF unexpectedly.
@AndrewZhaoLuo Hi, may I continue merging this change?

**Review by masahi — APPROVED** [review]

**Pull request merged**
