### PR TITLE
[BugFix][MSC] split name_string with index by colon from the right

### PR DESCRIPTION
**Pull request by psunn**
Fixes a naming mismatch in MSCGraph where tensor_name could formatted as 'string:index:index',and the corresponding node.name is 'string:index'. Splitting tensor_name from the right aligns it correctly.

For example, the TFLite default input name 'serving_default_input:0' becomes 'serving_default_input:0:0' in MSCGraph, while node.name remains 'serving_default_input:0'.

### CODE REVIEW

**Review by lhutton1 — COMMENTED** [review]
Thanks for the fix @psunn, would it be possible to add a test case?

**Comment by Hzfengsy** [comment]
cc @Archermmt

**Comment by psunn** [comment]
> Thanks for the fix @psunn, would it be possible to add a test case?

@lhutton1 Thanks for the review. I've added a test case.

**Comment by psunn** [comment]
Hi @Archermmt, could you help to review this PR? thanks in advance.

**Comment by Archermmt** [comment]
Seem ok for me. The only change in this PR is the split direction, which has no influence on current test. I think the main reason is that: in some corner cases like TFLite model, the node name looks like "NODE:IDX", which is normally the tensor name format.

**Review by lhutton1 — APPROVED** [review]

**Comment by lhutton1** [comment]
Thanks @psunn @Archermmt @Hzfengsy!

**Pull request merged**
