### PR TITLE
[Relax][Frontend][Onnx] add sum and globalavgpool 1d/3d op

### PR DESCRIPTION
**Pull request by chengven027-intellif**
Hi, tvm：
     try to add sum op and gloablavgpool1d and gloablavgpool3d。
     Please have a look. thanks.

### CODE REVIEW

**Comment by chengven027-intellif** [comment]
@tvm-bot rerun

**Comment by chengven027-intellif** [comment]
@tvm-bot  rerun

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
Please rebase to the latest commit:)

**Comment by chengven027-intellif** [comment]
@Hzfengsy please have a look again. thanks.

**Pull request merged**
