### PR TITLE
refactored GraphProto.from_onnx into smaller functions

### PR DESCRIPTION
**Pull request by SebastianBoblestETAS**
I split GraphProto.from_onnx into smaller functions.
I find it useful to see faster what is going on.
Are such refactorings wanted in the TVM codebase?
I am aware that they require careful review without adding any functionality so a comment on that in general would be helpful.

### CODE REVIEW

**Comment by masahi** [comment]
cc @mbrookhart @AndrewZhaoLuo

**Comment by SebastianBoblestETAS** [comment]
I cannot really say why the tests fail now. I am pretty confident they passed and I did not change anything.

**Comment by AndrewZhaoLuo** [comment]
It's probably a spurious failures @SebastianBoblestETAS . Just push an empty commit to your branch to retoggle CI. I'll take a look at this later in the week.

**Review by AndrewZhaoLuo — APPROVED** [review]
LGTM

**Pull request merged**
