### PR TITLE
Fix Metal accuracy problem caused by <dtype>3 vectors usage

### PR DESCRIPTION
**Pull request by elvin-nnov**
On example of float3 datatype:
Using of float3 data type for loading of data cuncurrently into dense array shared
between all threads in Metal threading group can lead to data race between threads.
float3 datatype has size and and alignment eq to 16 bytes while kernel assumes to
copy 12 bytes in arbitrary not aligned places.
Using of packed_float3 datatypes solves the issue

### CODE REVIEW

**Comment by jwfromm** [comment]
@tqchen do you have any ideas on tests we could add to exercise this change or would it be ok to merge as is?

**Comment by tqchen** [comment]
We can merge this in as it is as long as there is a separate reviews say from @echuraev

**Review by echuraev — APPROVED** [review]
LGTM.

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Thanks @elvin-nnov @echuraev !

**Pull request merged**
