### PR TITLE
add onnx reverse sequence op

### PR DESCRIPTION
**Pull request by alter-xp**
add onnx reverse sequence op

### CODE REVIEW

**Comment by mbrookhart** [comment]
@alter-xp Thanks for the contribution! Can you rebase to fix the merge conflict and fix lint? It looks great from a quick pass.

**Comment by mbrookhart** [comment]
It looks like somehow to test is failing on GPU. Is that something you can debug? If you don't have access to a machine with an nvidia GPU, I can take a look.

**Comment by mbrookhart** [comment]
@alter-xp Pinging again. This op is cropping into my view on a model, so I'd like to get this merged. I'm also interested in seeing these tests enabled as part of this PR:
https://github.com/apache/tvm/blob/cea7cf16ce867bb39ff40376f3f25cd2df67c431/tests/python/frontend/onnx/test_forward.py#L4227-L4228

Is this something you can get back to?

Thanks!

**Comment by alter-xp** [comment]
@mbrookhart  OMG, I haven't paid attention to this PR during this time. Let me see what causes the error.

**Comment by alter-xp** [comment]
> https://github.com/apache/tvm/blob/cea7cf16ce867bb39ff40376f3f25cd2df67c431/tests/python/frontend/onnx/test_forward.py#L4227-L4228
My tests include them

**Review by mbrookhart — APPROVED** [review]
LGTM

**Comment by mbrookhart** [comment]
Thanks @alter-xp

**Pull request merged**
