### PR TITLE
[Relay][Frontend][ONNX] Allow condition in if op to be an array.

### PR DESCRIPTION
**Pull request by jwfromm**
This PR is a very small addition to our if converter that unpacks an input condition for an If operator into a scalar if it's passed as an array, which the onnx spec allows.

### CODE REVIEW

**Comment by jwfromm** [comment]
@mbrookhart @tmoreau89 can you take a look at this PR?

**Review by mbrookhart — APPROVED** [review]
LGTM

**Review by tmoreau89 — APPROVED** [review]
Thanks @jwfromm for the fix, LGTM

**Comment by tmoreau89** [comment]
Thanks everyone, the PR has been merged.

**Pull request merged**
