### PR TITLE
[BYOC][ACL] ACL migrated to v21.02

### PR DESCRIPTION
**Pull request by d-smirnov**
This PR switches ACL* version from v20.11 to v21.02

*ACL stands for Compute Library for the Arm® Architecture.

### CODE REVIEW

**Review by lhutton1 — APPROVED** [review]
Approved, assuming tests pass CI. Minor point - maybe it would be good to document what versions of ACL are supported, and even add a check in the runtime to ensure a supported version is being used, I don't believe there are any yet?

**Comment by d-smirnov** [comment]
For now it was decided to stick only the latest version of ACL. There are no checks in runtime

**Review by u99127 — CHANGES_REQUESTED** [review]
Please could you just use the tag instead ? v21.02 would probably be better to use here. 

Also could you update this tag in Dockerfile.ci_arm ?

**Comment by d-smirnov** [comment]
> Please could you just use the tag instead ? v21.02 would probably be better to use here.
Amended
>We need to request regeneration of the ci_cpu and ci_arm images.
@zhiics, @tqchen, @thierrymoreau Could the ci images be regenerated, please?

**Review by u99127 — APPROVED** [review]
@zhiics  , @tqchen , @tmoreau89  - could you regenerate the ci_cpu and ci_arm docker images ?

**Comment by d-smirnov** [comment]
@zhiics , @tqchen , @tmoreau89 
Ping. Could the related ci-images be recreated, please?

**Comment by d-smirnov** [comment]
Ping. @zhiics , @tqchen is there anything we can help to get this patch landed?

**Comment by u99127** [comment]
Hi @d-smirnov  - looks like we have this request coming through. https://github.com/apache/tvm/pull/7745 which should handle it when things land.

**Comment by areusch** [comment]
just to clarify--seems like we have two options:
1. merge #7745 today, then rebuild ci-cpu and ci-arm again and merge a new PR to bump them again
2. rebuild ci-cpu and ci-arm again and push a new patch to #7745 to bump versions including this patch. 

I had built from origin/main when I created ci-cpu and ci-arm for #7745, which didn't have what you want, I believe.

**Comment by d-smirnov** [comment]
@areusch The PR is still relevant. Could we help somehow to let it in?

**Comment by tmoreau89** [comment]
@d-smirnov @u99127 @lhutton1 thank you the PR has been merged.

**Comment by areusch** [comment]
@d-smirnov @u99127 @lhutton1 ok so now we need to do a ci-arm container rebuild, correct?

**Comment by u99127** [comment]
we need a ci_arm and a ci_cpu rebuild.

**Pull request merged**
