### PR TITLE
Enable pylint for the python tests

### PR DESCRIPTION
**Pull request by gigiblender**
This PR enables pylint for the tests and addresses #11414. 

There is a large number of tests that have formatting errors. See the file attached.

[out.txt](https://github.com/apache/tvm/files/8853259/out.txt)

### CODE REVIEW

**Comment by gigiblender** [comment]
@Mousius I don't see a clean way to do this. 

We could have a temporary `pylintrc` file, used only for the tests, that passes the list in #11414 as the [ignore parameter.](https://github.com/apache/tvm/blob/6dc0c624cdd8fb9d7fdd2194a755b0dffbe2de93/tests/lint/pylintrc#L29). However, new tests in existing files would also be ignored in this case.

**Comment by gigiblender** [comment]
> > @Mousius I don't see a clean way to do this.
> > We could have a temporary `pylintrc` file, used only for the tests, that passes the list in #11414 as the [ignore parameter.](https://github.com/apache/tvm/blob/6dc0c624cdd8fb9d7fdd2194a755b0dffbe2de93/tests/lint/pylintrc#L29). However, new tests in existing files would also be ignored in this case.
> 
> Hmmm, I'm unsure whether we want to fill the logs with pylint without actually halting the build? Methinks it's worth doing as you suggested and filtering out the files we know will fail - we then have to lint them ourselves as quickly as we can crying_cat_face

@Mousius, I applied your suggestion. Please have a look when you get the time.

**Comment by Mousius** [comment]
Argh @gigiblender, I didn't realise we would only be able to specify `test_pooling.py`, that means `test_cmsisnn` is ignored by mistake in the last test block - ideally we'd disable all of them and then enable them as we merge PRs to fix them, unsure if we can do that or if we just have to keep adding directories to the list and clean up later 🤔 any ideas @gigiblender ?

**Comment by Mousius** [comment]
Sounds good to me @gigiblender, thanks for raising this and kickstarting the great linting of 2022!

**Pull request closed without merging**
