### PR TITLE
Overriding the StructuralEqual() for easy usage

### PR DESCRIPTION
**Pull request by sdalvi-quic**
Override the StrucutralEqual operator () to ensure easy usage of the function. 

@jverma-quic and @quic-sanirudh can you please take a look.

### CODE REVIEW

**Review by quic-sanirudh — APPROVED** [review]
LGTM, but please fix the lint errors.

**Comment by quic-sanirudh** [comment]
@tvm-bot rerun

**Comment by sdalvi-quic** [comment]
@tvm-bot rerun

**Comment by quic-sanirudh** [comment]
@tvm-bot rerun

**Review by jverma-quic — APPROVED** [review]
LGTM

**Pull request merged**
