### PR TITLE
[MetaSchedule] Fix anchor-block flow with empty design space generator

### PR DESCRIPTION
**Pull request by Icemist**
In the current implementation when creating an empty design space generator for anchor-block module equality, tuning records of no sense are generated (with one operation sch.enter_postproc() which is no-op) but the implementation of anchor trace applying requires meaningful instructions, so it makes sense to filter out such instructions at receiving stage (function GetTopK).

### CODE REVIEW

**Comment by Icemist** [comment]
@tvm-bot rerun

**Comment by Icemist** [comment]
cc @echuraev @masahi

**Comment by Icemist** [comment]
@tvm-bot rerun

**Comment by Icemist** [comment]
cc @vinx13 @junrushao

**Review by masahi — APPROVED** [review]

**Pull request merged**
