### PR TITLE
[Frontend][Relay][Keras] Fix concatenate convert function in axis parsing

### PR DESCRIPTION
**Pull request by jikechao**
This pr fixed the bug in #15174 and added some specific test cases for Concatenate operator.

cc @echuraev @Hzfengsy

### CODE REVIEW

**Review by junrushao — APPROVED** [review]

**Comment by jikechao** [comment]
The newly added test cases cannot pass the CI test. However, It can run well in my local environment. So wired it is.

**Comment by Hzfengsy** [comment]
Is it related to the Karas version?

**Comment by jikechao** [comment]
@Hzfengsy Thanks for your comments!
I have figured out this CI failure. The default value of **layout** in `verify_keras_frontend()`  is 'NCHW', which is different from the default value (i.e., NHWC )for Concatenate layer. Thus in the test, we must specify the layout value.

BTW, if

**Comment by jikechao** [comment]
@Hzfengsy @junrushao  Thanks for your comments and review.
My patch was incomplete and It only considered the layout as 'NHWC'. The CI failed when layout = 'NCHW' for the input will be transposed. I have corrected the patches.  Could you help me review it again? Thanks again!

**Review by echuraev — APPROVED** [review]
LGTM! Thanks.

**Comment by jikechao** [comment]
@echuraev Thanks for your review.

**Comment by jikechao** [comment]
@tvm-bot rerun

**Pull request merged**
