### PR TITLE
[OpenCL] Skip opencl memory operations on empty tensors

### PR DESCRIPTION
**Pull request by mbrookhart**
cc @masahi @tmoreau89

### CODE REVIEW

**Comment by masahi** [comment]
Since this is not a opencl specific problem, ideally we should think about how to handle this case in all backends. For now I think we should have the same change for cuda, rocm, and vk as well.

**Comment by mbrookhart** [comment]
I don't think cuda has this issue, I this cudamalloc does this under the hood, as does standard C malloc. I agree, though, it looks like we need it for rocm and vulkan.

**Comment by tmoreau89** [comment]
Can the runtime attempt to free a buffer that was allocated that is of size 0? Could that trigger a segfault?

**Comment by mbrookhart** [comment]
Feasibly. I didn't see such an issue with opencl, but indeed memory freeing doesn't pass in size, so I can't do the same check:
https://github.com/apache/tvm/blob/e697f03539acce7a6ed78eb7757c207398dd6b72/src/runtime/opencl/opencl_device_api.cc#L129-L136

**Comment by mbrookhart** [comment]
But it would be easy to check for null before freeing

**Comment by masahi** [comment]
Maybe we can implement all book keeping stuff in `DeviceAPI` base class? After we make sure size is valid, we forward calls to derived class.

**Comment by mbrookhart** [comment]
It's messy, but we could write a default method that checks for these things and then calls a helper function. We then mark the default function as final and change ALL of the device classes to override the helper functions.

**Comment by mbrookhart** [comment]
Closing in favor of #7691

**Pull request closed without merging**
