### PR TITLE
 Remove javah support

### PR DESCRIPTION
**Pull request by argrento**
Follow https://openjdk.java.net/jeps/313 and remove 'javah' from scripts and configs for linux platform and some android apps.

### CODE REVIEW

**Comment by elvin-n** [comment]
LGTM

**Review by elvin-n — APPROVED** [review]

**Comment by echuraev** [comment]
Did you check if it works on MacOS? I'm not sure but it might be necessary to modify also this file: https://github.com/apache/tvm/blob/main/jvm/native/osx-x86_64/pom.xml

**Review by echuraev — APPROVED** [review]
LGTM. Thanks

**Review by jwfromm — APPROVED** [review]
LGTM, thanks for this upgrade!

**Pull request merged**
