### PR TITLE
Delete `from __future__ import annotations` since it requires Python …

### PR DESCRIPTION
**Pull request by kparzysz-quic**
…3.7+

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Review by zxybazh — APPROVED** [review]
LGTM. Thanks for reporting this issue!

**Comment by junrushao1994** [comment]
We should never include python 3.7 features in python 3.6. Just curious why the CI slipped it through :-(

**Comment by kparzysz-quic** [comment]
I think python 3.6.9 is the default on Ubuntu 18.04, so it would be a bit surprising it was using 3.7+.

**Pull request merged**
