### PR TITLE
[Tutorial][Executor] Fix the usage of executors in tutorials

### PR DESCRIPTION
**Pull request by ganler**
The optimizations are run in `.evalutate()` API whose optimization level is bounded by the `PassContext`. In the previous tutorial,  `.evaluate()` is called outside the context, making the optimization invalid. 

For details, see: https://discuss.tvm.apache.org/t/questions-about-tvm-executors-and-its-apis/10289/3?u=ganler

@YuchenJin @junrushao1994

### CODE REVIEW

**Comment by YuchenJin** [comment]
Thanks @ganler for finding the issue and the fix! Do you think it would be better to still have the `.evaluate()` statement, but put it into the PassContext scope in the following style?

```
with tvm.transform.PassContext(opt_level=3):
    ex = build_module.create_executor("graph", mod=mod, device=cpu(0))
    res = ex.evaluate()(**data)
```

This will be consistent with code elsewhere: https://github.com/apache/tvm/blob/main/tutorials/dev/bring_your_own_datatypes.py#L137.

**Comment by ganler** [comment]
@YuchenJin Consistency can be resolved by making them consistent. But here IMHO only putting the `.evalutate()` (the compilation phase) under the context would allow greater flexibility, i.e., call inference functions wherever you want instead of making them under the compilation scope. But anyways, this is minor, the major thing is to let users be aware that we should call `evaluate` inside the scope.

**Comment by ganler** [comment]
As is mentioned in this PR https://github.com/apache/tvm/issues/8579 If users get used to putting `.evaluate()` and the callable together, they might be confused by the performance issue if they have a loop in inference (they will compile the model for multiple times, and according to my experience TVM's compilation is much longer than the model execution itself). So I guess if we want to form a consistent API usage style by not breaking existing APIs, we would better also split `.evaluate` and `(**data)`.

**Comment by YuchenJin** [comment]
@ganler Thanks, I agree with you that moving the callable expression outside provides greater flexibility. Btw, one caveat of using the `create_executor` API is that it's better to directly pass params to it, otherwise constant folding will not be applied and it degrades the inference performance (more details in #8418).

I don't like the `create_executor` API actually, I think it's a convenient API to try out different executors. I prefer the following VM style API which is clearer:
```
with tvm.transform.PassContext(opt_level=3):
    exe = relay.vm.compile(mod, target, params)
vm = vm_rt.VirtualMachine(exe, tvm.cpu(0))
vm.run(input_data)
```

It has a clear model->executable->run pattern. However, the graph runtime api has another style. I hope we can unify the APIs in the future...

**Comment by ganler** [comment]
@ I guess this API is usually confusing because even some tutorials misuse it. I did some investigation finding that there're at least 4 public inquiries regarding these APIs on TVM discussion. And I also found some code snippets that misuse it just like the ONNX/Keras tutorial do.

- https://discuss.tvm.apache.org/t/whats-the-difference-between-build-and-create-executor-in-tvm-relay-build-module/1967
- https://discuss.tvm.apache.org/t/what-the-difference-between-relay-build-module-create-executor-and-tvm-contrib-graph-executor-graphmodule/10398
- https://discuss.tvm.apache.org/t/questions-about-tvm-executors-and-its-apis/10289
- https://discuss.tvm.apache.org/t/what-is-the-difference-between-relay-build-module-create-executor-and-relay-build/4675

But I do like its design rationale which is to provide different executor in an unified API. 

This PR is a quick fix regarding the tutorials. I think we may open a channel to discuss if it is necessary to refactor the executor APIs on the TVM discussion.

**Comment by YuchenJin** [comment]
@ganler, yeah, there are lots of misuses. I think it would be good to put some explicit messages in the tutorials to clarify the right way to use this API.

**Comment by ganler** [comment]
Hi @YuchenJin, regarding this PR, what do you think can be further improved or we should have another PR to systematically refactor the API usage? Thanks.

**Comment by YuchenJin** [comment]
> Hi @YuchenJin, regarding this PR, what do you think can be further improved or we should have another PR to systematically refactor the API usage? Thanks.

Hi @ganler, I think for this PR you can pass the `params` directly to `create_executor` as following because it has potential performance benefits, and we should make users become used to this style.
```
executor = relay.build_module.create_executor("graph", mod, tvm.cpu(0), target, params).evaluate()
tvm_output = executor(tvm.nd.array(x.astype(dtype))).numpy()
```

It would be great if you want to systematically refactor the APIs, and I'm happy to discuss! :)

**Comment by YuchenJin** [comment]
@ganler, LGTM! Could you fix the lint?

**Review by YuchenJin — APPROVED** [review]

**Comment by YuchenJin** [comment]
Hi @junrushao1994, could you make a review? I think it can be merged. :)

**Review by junrushao1994 — APPROVED** [review]
The concerns here are indeed valid, and really appreciate you fixing those issues :-)

BTW, the CI error is not related to the PR (HTTP 404 due to some address change in scipy), so please rebase to the mainline to make CI green.

**Comment by junrushao1994** [comment]
I just did the rebase, but saw "cuda: out of memory" errors in doc builds...CC @YuchenJin

**Comment by YuchenJin** [comment]
> I just did the rebase, but saw "cuda: out of memory" errors in doc builds...CC @YuchenJin

Interesting.. I checked the log and it seems that none of the "cuda: out of memory" errors were coming from the files that this PR changed. I think this PR should not affect them. Could it happen to be a bad GPU node?

**Comment by junrushao1994** [comment]
Yeah it is possible :-(

**Comment by junrushao1994** [comment]
Still seeing out of memory issues with irrelevant tests

**Comment by YuchenJin** [comment]
It's so weird that these irrelevant tests still fail, which makes me feel it's not some GPU node issue.

**Comment by junrushao1994** [comment]
CC @comaniac would you like to take a look at this PR?

**Review by comaniac — APPROVED** [review]
LGTM

**Comment by junrushao1994** [comment]
Thanks @ganler! It is finally merged

**Pull request merged**
