### PR TITLE
[Pass] Simplify consecutive casts in Relay

### PR DESCRIPTION
**Pull request by icemelon**
This PR adds a new pattern in the SimplifyExpr in Relay that simplifies consecutive casts into one.

cc @mbrookhart

### CODE REVIEW

**Review by mbrookhart — APPROVED** [review]
LGTM. Thanks!

**Comment by mbrookhart** [comment]
@icemelon9 can you rebase? I'm not sure if this hit a flakey test or if there's an issue with mobilenet.

**Comment by masahi** [comment]
@AndrewZhaoLuo would be great if you can take over this PR.

**Comment by AndrewZhaoLuo** [comment]
@icemelon do you still have interest in merging this PR? If not then I can try to take over.

**Comment by AndrewZhaoLuo** [comment]
Ok I'm going to take over merging this PR, probably in a separate branch

**Comment by AndrewZhaoLuo** [comment]
Closing in favor of https://github.com/apache/tvm/pull/10133

**Pull request closed without merging**
