### PR TITLE
[relay][ir] add string type to relay ir

### PR DESCRIPTION
**Pull request by cloud-mxd**
I am a mlsys engineer who mainly provides server support for the nlp-related model for the company. In the nlp-related business scenario, we found that tvm can provide superior tensor computing performance, so we intend to promote tvm applications within the company.

    Moreover, we prefer to integrate more business processing operations with **tvm relay** and provide end-to-end solutions.

    Currently, TVM already provides data type support such as String/Array/Map at the Runtime level, but there is no corresponding interface at the **relay ir** level, and we sincerely hope to provide corresponding support at the relay level.

    We want to do this in three stages:
    1) Add String IR types and support easy operation of String 
    2) Add Array IR types and support easy operation of Array 
    3) Add MapIR types and support easy operation of Map 

    In this PR, we have add String type, hoping to get community support and feedback, and if possible, merge to tvm master, which can reduce branch maintenance costs here. 

    Good day!

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for bringing up the PR. It would be great to bring up an RFC discussion thread on the https://discuss.tvm.ai/. In particular, while we acknowledge that it is important to support types such as String/Map/Array, we will need to discuss the best way to support them.

We need to discuss the choice of the type data structure, as there are a few ways to support such kind of types. For example, one potential way is to create an RuntimeObjectType that directly maps to the runtime type index.

cc @jroesch

**Comment by cloud-mxd** [comment]
> RuntimeObjectType

Great idea

**Comment by cloud-mxd** [comment]
Thanks for reply and support, RFC link below:

https://discuss.tvm.ai/t/rfc-relay-containers-array-map-string/7560

@tqchen

**Comment by cloud-mxd** [comment]
At the same time, thanks to @MarisaKirisame  for the help and support

**Comment by junrushao1994** [comment]
I suppose this series of change are really big. Would you like to add testcases for this change?

**Comment by cloud-mxd** [comment]
> I suppose this series of change are really big. Would you like to add testcases for this change?

No problem, I will add some test code, thank you.

**Comment by tqchen** [comment]
Sorry that this PR is a bit outstanding at the moment. @jroesch @cloud-mxd can you please follow up ?

**Comment by masahi** [comment]
I assume this is no longer active. Maybe interesting consideration for relax (aka relay 2.0)

**Pull request closed without merging**
