### PR TITLE
[Metaschedule] EvolutionarySearchNode::State constructor typo fix

### PR DESCRIPTION
**Pull request by shtinsa**
This PR fixes internal object initialization in  EvolutionarySearchNode::State  class. Unfortunately there is no way to prepare test case.

### CODE REVIEW

**Comment by shtinsa** [comment]
@tvm-bot rerun

**Review by Mousius — CHANGES_REQUESTED** [review]
Hi @shtinsa ,

It looks like the CI is failing because your PR has no description, could you please add one as well as a test case to demonstrate the issue this fixes?

**Comment by shtinsa** [comment]
@tvm-bot rerun

**Review by junrushao — APPROVED** [review]
LGTM

**Comment by shtinsa** [comment]
> Hi @shtinsa ,
> 
> It looks like the CI is failing because your PR has no description, could you please add one as well as a test case to demonstrate the issue this fixes?

Unfortunately it is a problem to create test.

**Comment by junrushao** [comment]
To be clear, this is not possible to create a test, as the code itself is not a bug

**Comment by Mousius** [comment]
@shtinsa / @junrushao - I've tested similar things in the past, as far as I can see this is simply ensuring a more precise allocation which should be testable. Alas, TVM does not have good testing practices so I don't think there's an easy way forward. Thanks for the contribution @shtinsa, hope it doesn't unfix itself in future 😸

**Review by Mousius — APPROVED** [review]

**Pull request merged**
