### PR TITLE
[microTVM][Zephyr] Hot Fix Bad Merge

### PR DESCRIPTION
**Pull request by mehrdadh**
Fixing bad merge after https://github.com/apache/tvm/pull/8940

### CODE REVIEW

**Comment by elvin-n** [comment]
deadlock - issues with QEMU is fixed in this PR, issue with CPU is fixed in PR8981. Both PR should be merged simultaneously or both changes should go in one PR to see green pre-commit on PR stage

**Comment by mehrdadh** [comment]
@elvin-n great point. Do you mind if I add your changes to my PR?

**Comment by mehrdadh** [comment]
Added changes from this PR: https://github.com/apache/tvm/pull/8981 since we need to merge these together to pass the CI.

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
thanks @elvin-n @u99127 @mehrdadh , the fix is merged!

**Pull request merged**
