### PR TITLE
[TIR] Handle nullptr returned by FindEntryFunc

### PR DESCRIPTION
**Pull request by Icemist**
The FindEntryFunc function can return a null pointer. In development I got this situation, which appears as a segfault.

### CODE REVIEW

**Comment by Icemist** [comment]
cc @masahi @echuraev

**Comment by junrushao** [comment]
Quick question: do you think it’s necessary to add a unittest?

**Review by echuraev — COMMENTED** [review]
In general LGTM. But the same question as @junrushao have already asked. Can you add a unit test?

**Review by echuraev — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
