### PR TITLE
[skip ci] Fix RVM build

### PR DESCRIPTION
**Pull request by areusch**
Fix missing apt-install-and-clear utility clobbered by #11753.

Skipping ci because nothing in this PR is tested in CI.

cc @mehrdadh

### CODE REVIEW

**Review by leandron — CHANGES_REQUESTED** [review]
Just for the sake of consistency, while I acknowledge you fix is trivial, and shouldn't do any harm to the code base, I don't think the usage of the `[skip ci]` here applies within the agreed rules, given this change is not "un-breaking" CI.

Can you rename this PR and trigger CI again, so that we preserve the usage to the accepted/agreed use cases?

**Comment by leandron** [comment]
cc @driazati

**Comment by mehrdadh** [comment]
This is a duplicate of this one:
https://github.com/apache/tvm/pull/11781
Maybe we can close this one since the other PR also does some renaming in the build script.

**Comment by areusch** [comment]
@mehrdadh sgtm. @leandron apologies for the abuse. agreed and will close this one.

**Pull request closed without merging**
