### PR TITLE
[TIR] Flatten SeqStmt on construction

### PR DESCRIPTION
**Pull request by Lunderberg**
Previously, SeqStmt could be nested, making a distinction between the nested `SeqStmt({SeqStmt({a,b}), c})` and the flat `SeqStmt({a,b,c})`, even though the two are semantically equivalent.  This also caused an issue with round-trips through TVMScript, which does not preserve this distinction.

This commit updates the `SeqStmt` constructor and the `SeqStmt` visitor in `StmtMutator` to flatten nested sequential statements provided.

This is part of changes described in https://github.com/apache/tvm/pull/14486, to improve round-trip failures that occur in lowering.

### CODE REVIEW

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
Sorry for the late response. Could you please rebase it again and let's merge it?

**Comment by Lunderberg** [comment]
No worries (this has been on my back burner as well).  Main has been merged into the PR branch to resolve conflicts, and now running through CI.

**Comment by Lunderberg** [comment]
@tvm-bot rerun

**Comment by Hzfengsy** [comment]
Thanks @Lunderberg for the PR :)

**Pull request merged**
