### PR TITLE
[MetaSchedule][Test] Add unittests for NRM

### PR DESCRIPTION
**Pull request by junrushao1994**

### CODE REVIEW

**Comment by junrushao1994** [comment]
CC: @MasterJH5574 @jinhongyii

**Review by MasterJH5574 — APPROVED** [review]
LGTM!

**Comment by junrushao1994** [comment]
@MasterJH5574 After tests for reduction operators (e.g. NRM, SFM) gets in mainline, I will work on merging the tuple reduction PR

**Comment by MasterJH5574** [comment]
@junrushao1994 Ohhhh that'll be so great! I'll try best to get time responding to your comments 😆!

**Pull request merged**
