### PR TITLE
[VTA] Fix vta rpc server, refactor launch cond to not depend on sys.argv

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by tqchen** [comment]
cc @areusch @tmoreau89 @vegaluisjose

**Comment by tqchen** [comment]
Fixes https://github.com/apache/tvm/issues/8603

**Review by tmoreau89 — APPROVED** [review]
Thank you @tqchen for issuing the fix - LGTM

**Review by vegaluisjose — APPROVED** [review]
LGTM

**Pull request merged**
