### PR TITLE
[CMSIS-NN] Moved test_cnn_small to the latest version

### PR DESCRIPTION
**Pull request by ashutosh-arm**
Moved test_cnn_small used for testing CMSIS-NN
to the latest version.
 
  -Updated the test infra to pass on appropriate dtype to the frontend.
  -Follow up from https://github.com/apache/tvm/pull/9887

### CODE REVIEW

**Comment by ashutosh-arm** [comment]
@leandron @Mousius It looks like the test that was updated here fails in CI. Locally the test passes when .tvm_test_data is deleted. It is possible that CI uses the older version of the test. How can it be fixed in CI or at least tried out to make sure its not this issue?

**Comment by Mousius** [comment]
> @leandron @Mousius It looks like the test that was updated here fails in CI. Locally the test passes when .tvm_test_data is deleted. It is possible that CI uses the older version of the test. How can it be fixed in CI or at least tried out to make sure its not this issue?

@ashutosh-arm , you could try using a different second parameter to the download function to make it save to a different file?
https://github.com/apache/tvm/blob/ac1a43bf44e03a80e0c1f4c9c7f9f1fde755479e/python/tvm/contrib/download.py#L139

**Review by Mousius — APPROVED** [review]
LGTM!

**Comment by Mousius** [comment]
Thanks for updating this @ashutosh-arm :smile_cat: !

**Pull request merged**
