### PR TITLE
[Torch] Run torch JIT pass lower_all_tuples before conversion.

### PR DESCRIPTION
**Pull request by YuchiWen**
See the following discuss thread for details
https://discuss.tvm.apache.org/t/bug-frontend-pytorch-relay-ir-is-inconsistent-with-that-of-the-original-model/12010

### CODE REVIEW

**Comment by YuchiWen** [comment]
@masahi

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
oops sorry there is one test failing. I'll take a look.

**Comment by masahi** [comment]
The issue is that `torch._C._jit_pass_lower_all_tuples(graph)` unpack input tuples as well, so 

```
graph(%self : __torch__.LSTMLayer,
      %input.1 : Tensor,
      %state.1 : (Tensor, Tensor)):

``` 

becomes

```
graph(%self : __torch__.LSTMLayer,
      %input.1 : Tensor,
      %72 : Tensor,
      %73 : Tensor):
```

I think this should not happen, since the user would use a tuple in their Python code anyway, so we should respect that. @YuchiWen Can you try to find a way around this problem?

**Comment by masahi** [comment]
See 
https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/csrc/jit/passes/lower_tuples.h#L14-L15

So I suggest disabling this pass when the user input contains a tuple.

**Comment by YuchiWen** [comment]
@masahi I submitted it again, do you have any good suggestions?

**Comment by masahi** [comment]
Yes this looks good, thanks.

**Comment by masahi** [comment]
You have hit a flaky error, please rebase against upstream/main and push to run a new job.

**Comment by masahi** [comment]
cc @YuchiWen

**Comment by YuchiWen** [comment]
@masahi It's Done.

**Comment by masahi** [comment]
@YuchiWen can you take a look at the failed test?

**Comment by YuchiWen** [comment]
@masahi Sorry, I missed the check for ListType, please review it again.

**Pull request merged**
