### PR TITLE
[REFACTOR] Remove legacy nnvm folder

### PR DESCRIPTION
**Pull request by tqchen**
nnvm was the first generation IR that was maintained by TVM before the community moved to a newer generation.
The community keeps it for a few more releases(v0.7 and v0.8).

This PR removes the folder. The source code can still be found in past releases.

### CODE REVIEW

**Comment by tqchen** [comment]
https://discuss.tvm.apache.org/t/should-we-delete-nnvm/12330

**Comment by tqchen** [comment]
cc @kparzysz-quic @szha

**Comment by szha** [comment]
Thanks. @tqchen would you also open a PR to MXNet v1.X and master branches to replace the NNVM submodule with the actual code?

**Comment by tqchen** [comment]
Thanks @szha. The repo should be fine as they already point to a past release which still contain the code. Please feel free to send the PR to mxnet sooner.

**Review by masahi — APPROVED** [review]

**Pull request merged**
