### PR TITLE
[TIR][Arith] Implemented padded inverses in IndexMap

### PR DESCRIPTION
**Pull request by Lunderberg**
The goal of this PR is to allow `IndexMap` to express transformations that introduce padding in the transformed shape.  For an arbitrary input shape, the new method `IndexMap.non_surjective_inverse` determines the inverse transformation, along with a predicate specifying which coordinates in the transformed index space do not contain an inverse in the original index space.  The previous behavior of `IndexMap.inverse`, requiring transformations to be bijective over the range given, is maintained.

This functionality will be used in the future to allow buffer transformations (see #9727 and #10538) to introduce padding to the buffer.

### CODE REVIEW

**Comment by Lunderberg** [comment]
Also, name suggestions for "non-surjective inverse" would be appreciated.  It's something of a mouthful, and describes what it is doing without describing why it would be desired.

**Comment by vinx13** [comment]
Thanks for the PR, I like this change. There is a failing test case `test_reverse_compute_at_floordiv_and_floormod_indices` seems relevant, probably some affine analysis is broken

**Comment by Lunderberg** [comment]
> Thanks for the PR, I like this change.

Thank you, and I'm liking it as well.  It 

> There is a failing test case test_reverse_compute_at_floordiv_and_floormod_indices seems relevant, probably some affine analysis is broken

Yeah, so far I've narrowed it down to the handling of cases like `(iter + 16*var)//16`.  This doesn't introduce padding, but the nonzero offset would make it fail `DetectIterMap` in [this check](https://github.com/apache/tvm/blob/main/src/arith/iter_affine_map.cc#L1147).  This boils up to [the call to `AnalyzerRegionUpperBound`](https://github.com/apache/tvm/blob/main/src/tir/schedule/state.cc#L336), resulting in incorrect results.

**Comment by wrongtest** [comment]
> (iter + 16*var)//16

Hi~ Does it mean pass index like `(dom_irrelavant_base + i) // 16` can not pass `DetectIterMap`? I encounter a similar issue in a different domain, where I try to use `compute_at` schedule to make tiles on computation block with floormod/floordiv indices.

**Comment by Lunderberg** [comment]
> > (iter + 16*var)//16
> 
> Hi~ Does it mean pass index like `(dom_irrelavant_base + i) // 16` can not pass `DetectIterMap`? I encounter a similar issue in a different domain, where I try to use `compute_at` schedule to make tiles on computation block with floormod/floordiv indices.

Prior to this PR, that is correct.  The check on the main branch is [here](https://github.com/apache/tvm/blob/366a5669/src/arith/iter_affine_map.cc#L1147), which requires the offset in a numerator to be zero.  After this PR, an index like `(dom_irrelevant_base + i)//16` could be passed if either (a) `dom_irrelevant_base` can be proven to be a multiple of 16, or (b) you call `DetectPaddedIterMap`, which may introduce padding such that `(left_pad + dom_irrelevant_base) % 16 == 0` and that `(left_pad + dom_irrelevant_base + i.extent + right_pad) % 16 == 0`.

**Review by vinx13 — APPROVED** [review]

**Pull request merged**
