### PR TITLE
[Bugfix] Add check to avoid calling back() on an empty container

### PR DESCRIPTION
**Pull request by syang-ng**
This is related to an issue [here](https://discuss.tvm.apache.org/t/crash-triggered-by-8-lines-of-tir-code/10808/5). 

In a word, function `PrimExpr VisitExpr_(const LoadNode* op)` forgets to check the size of the vector `scope_[op->buffer_var.get()]`, while calling std::vector::back on an empty container will cause undefined behavior. 

This PR fixed this problem by adding the vector size check before calling `back()`.

To reproduce the bug:
```python
from tvm import tir
import tvm

zero = tir.const(0)
nop = tir.Evaluate(zero)
v = tir.Var('i1', 'int32')
for_stmt = tir.For(v, zero, zero, tir.ForKind.SERIAL, nop)
load = tir.Evaluate(tir.Load('int32', v, zero))
seq = tir.SeqStmt([for_stmt, for_stmt, load])
func = tir.PrimFunc([], seq)

tvm.build(func)
```

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @syang-ng , can you add a regression test case?

**Comment by tqchen** [comment]
cc @ZihengJiang @vinx13 please help to manage the PR

**Comment by syang-ng** [comment]
I add a test case to cover the problem in the new commit. Since there is no way to invoke this function directly, I  call the pass `tir.transform.InjectVirtualThread` to trigger this problem. Could you help review this PR :-D @vinx13

**Comment by vinx13** [comment]
please fix ci error

**Comment by syang-ng** [comment]
I updated the test case and it has passed all checks. Could you help to review it? Thanks :-P @vinx13

**Review by vinx13 — APPROVED** [review]

**Pull request merged**
