### PR TITLE
[microTVM] Add fixture to zephyr test

### PR DESCRIPTION
**Pull request by mehrdadh**
This PR:
- Adds pytest fixture to zephyr tests

cc @areusch @leandron @Lunderberg

### CODE REVIEW

**Comment by Lunderberg** [comment]
Looks good to me.

**Comment by mehrdadh** [comment]
@areusch please take a look. thanks!

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
thanks @mehrdadh , the pr is now merged!

**Comment by mehrdadh** [comment]
Thanks @Lunderberg and @areusch!

**Pull request merged**
