### PR TITLE
[microNPU] Remove unused import and command stream printing

### PR DESCRIPTION
**Pull request by ekalda**
This is a follow up to https://github.com/apache/tvm/pull/10695.

### CODE REVIEW

**Comment by ekalda** [comment]
cc: @lhutton1 @manupa-arm

**Review by lhutton1 — APPROVED** [review]
Thanks for the followup @ekalda!

**Review by NicolaLancellotti — APPROVED** [review]

**Review by manupa-arm — APPROVED** [review]
LGTM!

**Comment by manupa-arm** [comment]
Thanks @ekalda for following up!

**Pull request merged**
