### PR TITLE
Remove mutable default arguments in mlp_model

### PR DESCRIPTION
**Pull request by michalpiszczek**
Removes [mutable default arguments](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) in `python/tvm/meta_schedule/cost_model/mlp_model.py`.

### CODE REVIEW

**Comment by michalpiszczek** [comment]
cc @zxybazh @Kathryn-cat PTAL

**Review by junrushao — APPROVED** [review]
Good catch! Thanks for spotting this!

**Comment by Kathryn-cat** [comment]
LGTM!

**Review by zxybazh — APPROVED** [review]

**Comment by michalpiszczek** [comment]
Thank you for the reviews @junrushao @Kathryn-cat !

**Pull request merged**
