### PR TITLE
[Unity] Add LoadParamOnWorker0 function in shard loader

### PR DESCRIPTION
**Pull request by jinhongyii**
In DistIR compilation flow, shard loading is implemented in a Relax func, like
```
a = LoadParamOnWorker0(loader, index=0)
b = broadcast(a)
c = LoadParamOnWorker0(loader, index=1)
d = scatter_from_worker0(c)
```
LoadWholeParamOnWorker0 loads the unsharded param on worker0, and for other workers returns an empty array.

This PR implements LoadWholeParamOnWorker0

### CODE REVIEW

**Comment by jinhongyii** [comment]
cc: @junrushao

**Comment by junrushao** [comment]
The implementation looks good, but not sure what the best name tbh. @tqchen maybe you could suggest?

**Comment by tqchen** [comment]
How about LoadParamOnWorker0. And for future sharded version we can say LoadShardedParams

**Comment by jinhongyii** [comment]
sounds good

**Comment by junrushao** [comment]
Sounds good! Let’s do that then

**Review by junrushao — APPROVED** [review]

**Pull request merged**
