### PR TITLE
[Bugfix][VTA] Fix FSIM compile error on macOS

### PR DESCRIPTION
**Pull request by xhmelon**
VTA FSIM could not be built on macOS, for it leverages malloc.h and memalign, yet both have been deprecated and are not provided by macOS. This issue was captured in #13173.

This commit stops including malloc.h in VTA Runtime as stdlib.h has provided functions we need.

This commit uses posix_memalign instead of memalign. It is a portable standard function.

cc @vegaluisjose @liangfu

### CODE REVIEW

**Comment by xhmelon** [comment]
cc @vegaluisjose

**Review by vegaluisjose — APPROVED** [review]
LGTM

**Comment by xhmelon** [comment]
@vegaluisjose Errors from gpu/pr-head and lint/pr-head have prevented merging. The gpu/pr-head failed to pull the git repo, is it possible to manually trigger the ci run again? Meanwhile, I couldn't find out what's wrong with lint/pr-head from the log, could you give any insight?

**Comment by xhmelon** [comment]
@tvm-bot rerun

**Comment by xhmelon** [comment]
@liangfu Please review this PR.

**Review by liangfu — APPROVED** [review]
LGTM

**Comment by xhmelon** [comment]
@liangfu @vegaluisjose  It seems that merging the PR requires your permission, right? All tests passed, but there is still a prompt "1 workflow awaiting approval".

**Pull request merged**
