### PR TITLE
[CI] Upgrade CI image to `20241105-030952-3e386fd3`

### PR DESCRIPTION
**Pull request by mshr-h**
As per title.

@tqchen @Hzfengsy 
Can you take a look at it? Thanks!

Note that I removed oneflow tutorial (gallery/how_to/compile_models/from_oneflow.py) because during oneflow import, I hit the below error and could not find a way to exclude from sphinx build target.
```
Traceback (most recent call last):
  File "/home/ubuntu/data/project/tvm/gallery/how_to/compile_models/from_oneflow.py", line 49, in <module>
    import flowvision
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/__init__.py", line 1, in <module>
    from flowvision import layers
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/layers/__init__.py", line 1, in <module>
    from .attention import (
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/layers/attention/__init__.py", line 1, in <module>
    from .se import SEModule
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/layers/attention/se.py", line 1, in <module>
    import oneflow as flow
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/oneflow/__init__.py", line 25, in <module>
    import oneflow._oneflow_internal
ImportError: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory
```

### CODE REVIEW

**Comment by mshr-h** [comment]
@vinx13 
Could you upload the new ci image to docker hub?

**Comment by mshr-h** [comment]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-unity/detail/PR-17451/5/pipeline
Tests are failing due to https://github.com/man-group/pytest-plugins/issues/242

> [2024-10-18T04:27:16.218Z] + pytest tests/python/relax
> [2024-10-18T04:27:16.218Z] Traceback (most recent call last):
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/bin/pytest", line 8, in <module>
> [2024-10-18T04:27:16.218Z]     sys.exit(console_main())
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 201, in console_main
> [2024-10-18T04:27:16.218Z]     code = main()
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 156, in main
> [2024-10-18T04:27:16.218Z]     config = _prepareconfig(args, plugins)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
> [2024-10-18T04:27:16.218Z]     config = pluginmanager.hook.pytest_cmdline_parse(
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 513, in __call__
> [2024-10-18T04:27:16.218Z]     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
> [2024-10-18T04:27:16.218Z]     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 139, in _multicall
> [2024-10-18T04:27:16.218Z]     raise exception.with_traceback(exception.__traceback__)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 122, in _multicall
> [2024-10-18T04:27:16.218Z]     teardown.throw(exception)  # type: ignore[union-attr]
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
> [2024-10-18T04:27:16.218Z]     config = yield
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
> [2024-10-18T04:27:16.218Z]     res = hook_impl.function(*args)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
> [2024-10-18T04:27:16.218Z]     self.parse(args)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1494, in parse
> [2024-10-18T04:27:16.218Z]     self._preparse(args, addopts=addopts)
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1384, in _preparse
> [2024-10-18T04:27:16.218Z]     self.known_args_namespace = self._parser.parse_known_args(
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 158, in parse_known_args
> [2024-10-18T04:27:16.218Z]     return self.parse_known_and_unknown_args(args, namespace=namespace)[0]
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 172, in parse_known_and_unknown_args
> [2024-10-18T04:27:16.218Z]     optparser = self._getparser()
> [2024-10-18T04:27:16.218Z]   File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 131, in _getparser
> [2024-10-18T04:27:16.218Z]     arggroup.add_argument(*n, **a)
> [2024-10-18T04:27:16.218Z]   File "/usr/lib/python3.9/argparse.py", line 1440, in add_argument
> [2024-10-18T04:27:16.218Z]     raise ValueError('%r is not callable' % (type_func,))
> [2024-10-18T04:27:16.218Z] ValueError: 'int' is not callable

**Comment by mshr-h** [comment]
Seems like Zephyr-SDK v0.16.x is required.

**Comment by mshr-h** [comment]
@tqchen @Hzfengsy 
Can you take a look at it? Thanks!

Note that I removed oneflow tutorial (gallery/how_to/compile_models/from_oneflow.py) because during oneflow import, I hit the below error and could not find the solution.
```
Traceback (most recent call last):
  File "/home/ubuntu/data/project/tvm/gallery/how_to/compile_models/from_oneflow.py", line 49, in <module>
    import flowvision
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/__init__.py", line 1, in <module>
    from flowvision import layers
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/layers/__init__.py", line 1, in <module>
    from .attention import (
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/layers/attention/__init__.py", line 1, in <module>
    from .se import SEModule
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/flowvision/layers/attention/se.py", line 1, in <module>
    import oneflow as flow
  File "/venv/apache-tvm-py3.9/lib/python3.9/site-packages/oneflow/__init__.py", line 25, in <module>
    import oneflow._oneflow_internal
ImportError: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory
```

**Comment by tqchen** [comment]
@mshr-h is this ready to go?

**Comment by mshr-h** [comment]
Thank you for your review. Yes, it's ready to go.

**Pull request merged**
