### PR TITLE
[FFI][Python] Handle error propagation when line number is missing

### PR DESCRIPTION
**Pull request by Lunderberg**
Prior to this commit, the FFI error propagation in Python assumed that any stack frame with a known file name also had a known line number. This commit updates the error propagation to instead check if a known line number is present.

Closes https://github.com/apache/tvm/issues/15880.

### CODE REVIEW

**Comment by Lunderberg** [comment]
@jinhongyii I have this PR marked as a draft, to prevent merging prior to your confirmation of its effect.

**Comment by junrushao** [comment]
Hey do you think it's ready? I met the same issue and this one seems a good fix to me

**Comment by Lunderberg** [comment]
@junrushao I think it is.  Since you ran into the same issue and can verify that the fix resolves it, I'm marking it as ready for review.  (I wasn't able to reproduce the original error, so I was waiting for confirmation from somebody who could.)

**Review by junrushao — APPROVED** [review]
Cannot wait to get it merged!

**Pull request merged**
