### PR TITLE
[QNN] Fix multi batch matmuls

### PR DESCRIPTION
**Pull request by AndrewZhaoLuo**
The previous version incorrectly broadcasted across the batch dimensions which led to type errors.

I have updated tests to handle multi batch examples and updated the documentation to note the transposed nature of the operator.

### CODE REVIEW

**Comment by AndrewZhaoLuo** [comment]
cc @mbrookhart

**Review by mbrookhart — APPROVED** [review]
LGTM. Need to fix Docs CI.

**Review by anwang2009 — APPROVED** [review]

**Comment by AndrewZhaoLuo** [comment]
@tvm-bot rerun

**Comment by mbrookhart** [comment]
Thanks @AndrewZhaoLuo @anwang2009

**Pull request merged**
