### PR TITLE
[Refactor] Rename .asnumpy() to .numpy()

### PR DESCRIPTION
**Pull request by Lunderberg**
Follow-up from #8083, converting more calls from .asnumpy() to .numpy().

### CODE REVIEW

**Comment by Lunderberg** [comment]
@icemelon Follow-up to your PR #8083, there were a large number of warnings showing up when runnings tests.

**Review by junrushao1994 — APPROVED** [review]
That's nice! Thanks!

**Comment by junrushao1994** [comment]
CC: @icemelon

**Comment by junrushao1994** [comment]
Let's fix the lint

**Comment by Lunderberg** [comment]
Lint errors fixed and pushed.  Not sure why my pre-save hook didn't get them the first time around, but they should be good now.

**Review by icemelon — APPROVED** [review]
lgtm. Thanks for the fix.

**Comment by comaniac** [comment]
Thanks @Lunderberg @junrushao1994 @icemelon

**Pull request merged**
