### PR TITLE
[TORCH] Implement avg_pool1d

### PR DESCRIPTION
**Pull request by cgerum**
This pull request implements avgpool1d support for the relay torch frontend.

### CODE REVIEW

**Comment by masahi** [comment]
Thanks, can you unify the `avg_pool1d` and `2d`? They look identical.

**Comment by cgerum** [comment]
Thanks for the review, I hope this is what you had in mind.

**Comment by masahi** [comment]
Yes thanks, please fix the lint error

**Comment by cgerum** [comment]
Lint error should be fixed, should I squash the commits?

**Comment by masahi** [comment]
No, we do squash merge anyway when the PR is merged.

**Comment by masahi** [comment]
@cgerum Can you try kick CI again? You can rebase and push.

**Comment by cgerum** [comment]
The builder seems to have timed out. Should I just add a fake commit to retrigger the build?

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
Thanks @cgerum

**Pull request merged**
