### PR TITLE
[CI] Pin setuptools to v58.4.0 in CI to circumvent breaking change in v58.5

### PR DESCRIPTION
**Pull request by jtuyls**
Pin setuptools version to v58.4.0 to circumvent a breaking change in v58.5, see https://github.com/apache/tvm/issues/9445

cc @leandron

### CODE REVIEW

**Review by Mousius — CHANGES_REQUESTED** [review]
Thanks for fixing this @jtuyls, I think this is a sensible change but I suggest removing https://github.com/apache/tvm/blob/f656a2274aaac64489da1ece3ed110e214e549e7/docker/install/ubuntu_install_vela.sh#L23 so we aren't surprised by the version of `setuptools` we get in the eventual image, I presume this is a high enough version of `setuptools` given it was working until a few days ago :smile_cat:

**Comment by jtuyls** [comment]
> Thanks for fixing this @jtuyls, I think this is a sensible change but I suggest removing
> 
> https://github.com/apache/tvm/blob/f656a2274aaac64489da1ece3ed110e214e549e7/docker/install/ubuntu_install_vela.sh#L23
> 
> so we aren't surprised by the version of `setuptools` we get in the eventual image, I presume this is a high enough version of `setuptools` given it was working until a few days ago 😸

Done. And yeah, this is the last version that I could find that doesn't have the issue.

**Review by Mousius — APPROVED** [review]
Thanks @jtuyls, this makes sense to me 😸

**Review by leandron — APPROVED** [review]
LGTM, thanks for the fix @jtuyls!

**Pull request merged**
