### PR TITLE
Add temp git dir to test_cc_reviewers test case

### LINKED ISSUE #10044: [CI Problem] test_ci.py::test_cc_reviewers dependent on user git config
Hi everyone,

First of all let me clarify that this is not an upstream CI issue.

The problem is that the test relies on the user's git config and if the user doesn't have a remote named _origin_ or the user's _origin_ doesn't have the correct format the test will fail.

I noticed that `test_ci.py::test_skip_ci` sets up a fresh git in a temp directory, I think it would be a good if this test could follow a familiar pattern.

This is the error log:
```
pr_body = 'abc', expected_reviewers = []

    def run(pr_body, expected_reviewers):
        proc = subprocess.run(
            [str(reviewers_script), "--dry-run"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env={"PR": json.dumps({"number": 1, "body": pr_body})},
            encoding="utf-8",
        )
        if proc.returncode != 0:
>           raise RuntimeError(f"Process failed:\nstdout:\n{proc.stdout}\n\nstderr:\n{proc.stderr}")
E           RuntimeError: Process failed:
E           stdout:
E           Running ['git', 'config', '--get', 'remote.origin.url']
E           
E           
E           stderr:
E           Traceback (most recent call last):
E             File "/workspaces/tvm-sandbox-arm/src/tvm/tests/scripts/github_cc_reviewers.py", line 60, in <module>
E               user, repo = parse_remote(remote)
E             File "/workspaces/tvm-sandbox-arm/src/tvm/tests/scripts/git_utils.py", line 87, in parse_remote
E               raise RuntimeError(f"Unable to parse remote '{remote}'")
E           RuntimeError: Unable to parse remote 'ssh://jacboh01@eu-gerrit-2.euhpc.arm.com:29418/mlg/codegen/dmlc/tvm'

test_ci.py:41: RuntimeError
```

### PR DESCRIPTION
**Pull request by jacobbohlin**
This is a proposal to decouple the `test_cc_reviewers` test case from the user's git configuration. The implementation reuses the TempGit structure from `test_skip_ci` to always use a fresh git environment.

Fixes #10044 which contains some additional information.

### CODE REVIEW

**Comment by jacobbohlin** [comment]
@manupa-arm @Mousius @leandron

**Review by leandron — APPROVED** [review]
LGTM.

cc @driazati

**Review by driazati — APPROVED** [review]
Thanks! This way of testing definitely makes more sense

**Comment by jacobbohlin** [comment]
Thanks @driazati I was not aware of that.

**Review by manupa-arm — APPROVED** [review]
LGTM too!

**Comment by manupa-arm** [comment]
Thanks @jacobbohlin @leandron @driazati . This is merged now!

**Pull request merged**
