### PR TITLE
[TVMScript] Support round-trip for T.Ptr

### PR DESCRIPTION
**Pull request by wrongtest**
Allow print and parse `T.Ptr[T.int32, "scope"]`
cc @Hzfengsy

### CODE REVIEW

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
cc @junrushao1994 @yelite

**Comment by wrongtest** [comment]
BTW,  pyflake will complain  `F722 syntax error in forward annotation 'global'`, so it would be better to omit the scope field for global ptr.

**Comment by junrushao1994** [comment]
We might have to suppress pug lake when it reports such error, because it expects “global” as a type

**Comment by junrushao1994** [comment]
@yelite would be good to have your review too!

**Comment by yelite** [comment]
This looks good to me!

I've been thinking about how to avoid lint errors from treating string as forward type annotation and have some idea. I opened #11192 for discussion.

**Review by yelite — APPROVED** [review]

**Pull request merged**
