### PR TITLE
Update gradle version and other changes in android apps

### PR DESCRIPTION
**Pull request by argrento**
Update gradle configs to remove errors described in https://discuss.tvm.apache.org/t/gradle-build-fail-for-android-rpc-demo/10493

Modified:
* https://github.com/apache/tvm/tree/main/apps/android_camera
* https://github.com/apache/tvm/tree/main/apps/android_deploy
* https://github.com/apache/tvm/tree/main/apps/android_rpc

### CODE REVIEW

**Comment by junrushao1994** [comment]
Thanks for doing that! Also CC @Lyken17

**Comment by areusch** [comment]
I'm not super-knowledgeable about Android stuff, but hopefully someone who is could review this PR?

**Comment by junrushao1994** [comment]
@Lyken17 would love to ask you to try out and review this PR!

**Comment by Lyken17** [comment]
Sry for being late, was busy for some conference experiments. 

I rarely code in Java so I am afraid that I cannot comment much on the modified code. But I have seen @argrento update `javah` command to `javac -h`. This was the cause of building error when using latest JDK https://discuss.tvm.apache.org/t/jvmpkg-fails-to-build-on-mac-osx/11578/2

In my build machine (Intel Mac Mini), JDK version 1.8.0_312, Clang 13.0.0, all three projects `android_camera`, `android_rpc`, `android_camera`, `android_deploy`  can build successfully without error.

```
(base) ligeng@Lgs-Mac-mini➜  tvm2 git:(gradle-update) ✗ gh pr checkout 10867
(base) ligeng@Lgs-Mac-mini➜  tvm2 git:(gradle-update) ✗ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-bre_2021_10_21_00_49-b00)
OpenJDK 64-Bit Server VM (build 25.312-b00, mixed mode)

(base) ligeng@Lgs-Mac-mini➜  tvm2 git:(gradle-update) ✗ clang --version
Homebrew clang version 13.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

(base) ligeng@Lgs-Mac-mini➜  tvm2 git:(gradle-update) ✗ llvm-config --version
13.0.0
```

Due to my limited (human) bandwidth, I may be able to test 2~3 more JDK / NDK versions. Would it be possible to setup CI  auto-build test for the three demos? @argrento

**Comment by argrento** [comment]
New PR because I messed a little bit :(

**Comment by TejashShah** [comment]
@Lyken17  We raised another PR https://github.com/apache/tvm/pull/11241 and please review and give your blessing.

**Pull request closed without merging**
