### PR TITLE
[Unity] Relax BlockBuilder and ExprMutator

### PR DESCRIPTION
**Pull request by YuchenJin**
This PR adds BlockBuilder: the core data structure to construct Relax AST, and ExprMutator: performs AST mutation for implementing transformation passes.

Co-Authored-by: Tianqi Chen <tianqi.tchen@gmail.com>
Co-Authored-by: Altan Haan <altanh@cs.washington.edu>
Co-Authored-by: Andrew Liu <andrewlliu@gmail.com>
Co-Authored-by: Hongyi Jin <3231950289@qq.com>
Co-Authored-by: Jiawei Liu <jaway.liu@gmail.com>
Co-Authored-by: Junru Shao <junrushao1994@gmail.com>
Co-Authored-by: Lesheng Jin <34279105+LeshengJin@users.noreply.github.com>
Co-Authored-by: masahi <masahi129@gmail.com>
Co-Authored-by: Prakalp Srivastava <prakalp@octoml.ai>
Co-Authored-by: Ruihang Lai <ruihangl@cs.cmu.edu>
Co-Authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
Co-Authored-by: Steven S. <Lyubomirsky slyubomirsky@octoml.ai>
Co-Authored-by: Sunghyun Park <49998730+sunggg@users.noreply.github.com>
Co-Authored-by: Yixin Dong <ubospica@gmail.com>
Co-Authored-by: Yong Wu <yongcale@gmail.com>
Co-Authored-by: Ziheng Jiang <ziheng@apache.org>

### CODE REVIEW

**Review by junrushao — APPROVED** [review]

**Comment by gromero** [comment]
@junrushao Is the idea that these PRs (like this one) being merged into `unity` branch will get at some point in the future be merged into `main` branch as-is?

**Comment by tqchen** [comment]
We have not yet decided on how `unity` will get merged into main. Likely the community will need to look at the unity branch as a whole to get enough context for merging into the main. It is unlikely to happen at a single point in time(or even a matter of days), or in the context of one commit. We need a long, extended period of time for branch developers to take feedback and provide examples, code tutorials, walkthroughs, and demos to get buy-in from the community. Branch development offers that flexibility and an extended period of time.

Coming back to the branch establishment stage. It is indeed hard for community members who are not yet in the related code areas to be able to digest and provide feedback under the context of a single commit in the scaffolding commits. By design, scaffolding commits need a broader context that will appear in the future when connecting things together and are subject to future iterations(and rewrites in needed cases such as rebasing to main).

Nevertheless, some initial agility around scaffolding commits is helpful to establish the branch and unblock developments. In the meantime, we would like to experiment with different ways to enable agility with quality. For example, encouraging community members to continue giving feedback after the merging points and requiring the merger to be responsible for reacting to these comments after the merge. 

Additionally, there are more valuable ways to get the community to give feedback and continuously bring iteration suggestions. We can also use forms of interaction, such as discussion posts, demos, code example walkthroughs, community meetups to get us that context through extended period of time

**Comment by Mousius** [comment]
> Coming back to the branch establishment stage. It is indeed hard for community members who are not yet in the related code areas to be able to digest under the context of a single scaffolding commit. By design, a scaffolding commit connect to a broader context that will appear in the future(such as how IR node is being used, printed and parsed exactly) when connecting things together and are subject to future iterations(and rewrites in needed cases such as rebasing to main).

If we cannot review changes in isolation, that indicates the changes are not well broken down and delivered for review. There are foundational issues with this PR, such as being over 8,000 lines, a vague commit message and being merged in 5 hours - all of which work to exclude reviewers who may not see the PR or feel their reviews have no meaning once the PR gets merged.

**Comment by tqchen** [comment]
First of all, it is important indeed important to group things into reasonably isolated components that have reasonable structure.

That does not mean, however, that such logical structures do not require a broader context to be able to understand and iterate. For example, knowing IR nodes themselves is indeed a valuable point of assessment. But to fully access it, we will need to look at the context of how an IR node interacts with parser, printer, and passes. These are contexts that would be helpful to obtain over an extended course of time.

Coming back to the state of branch establishment. There are generally two different ways of establishing the module.

- W0: Start with an initial rough subset of implementations, then iterate to expand the feature
    - As time goes by, these modules have features that get expanded into a broader set. The scaffolding commits are still going to be large. Then small commits are built on top.
- W1: Have a reasonable subset component that gets planned with a decent set of features, documents, and tests. Such scaffolding PRs can indeed contain more lines of code (and requires levels of expertise of the overall architecture) mainly because that represents a squashed view of part of history in W0.

As someone who has ramped up many OSS projects and modules, I would like to say that such a period is not a normal steady state but sometimes can be necessary for the ramping period both in W0 and W1 for us to flexibly bring in pieces. Right now, given our current understanding of unity, we are in a W1-style branch establishment stage. 


Coming back to the technical assessment of this PR. Objectively, I think it is sufficiently isolated in terms of a logical component, `BlockBuilder` which comes with struct info deduction for the full IR. And related minimum operator and te-emission support so to enable a good amount of test coverage. It is indeed long in terms of lines of code, but from an architectural pov clear in terms of how things are isolated. 

If there is an actionable suggestion on further isolating things, this could be great feedback, and we could say rewrite the history of the branch to introduce such a split. The same goes for, say, a suggestion on commit messages. These follow-up comments do have a lot of meanings and are valuable. As again, we can view them as review suggestions to the branch.

Similarly, with some additional context through an extended period of time, we help community members gain a deeper understanding to give more concrete, actionable suggestions. These feedbacks are still valuable and sometimes even more informative throughout development.

The flexibility of branch development offers us a way to react to those comments, and we welcome them wholeheartedly.

**Pull request merged**
