### PR TITLE
[microNPU] add E2E tests with cascader wo striping

### PR DESCRIPTION
**Pull request by manupa-arm**
This commit adds end-to-end tests using the cascader
w/o striping. It needed few adjustments to the order
in which the arugments are provided to the entry point
function in AoT when both memory pools and devices
are present.

cc @Mousius @lhutton1

### CODE REVIEW

**Review by ekalda — APPROVED** [review]
LGTM! :)

**Review by NicolaLancellotti — APPROVED** [review]

**Comment by manupa-arm** [comment]
This is green now. :)

**Review by lhutton1 — APPROVED** [review]
LGTM!

**Comment by lhutton1** [comment]
@ekalda @NicolaLancellotti could you take another look after the further changes to make sure you still approve?

**Comment by NicolaLancellotti** [comment]
LGTM!

**Review by ekalda — APPROVED** [review]
Yeah still looks good to me :)

**Comment by lhutton1** [comment]
Thanks @manupa-arm @NicolaLancellotti @ekalda!

**Pull request merged**
