### PR TITLE
RPCModule get function by searching a symbol recursively

### PR DESCRIPTION
**Pull request by Maximilianxu**
Sometimes the locally built module is wrapped as a submodule after de-serialization of the top module, while the top module is compiled from an empty llvm module to reuse the export_lib API before RPC loading. In such cases, we want to fetch the symbol from the imported modules, other than only searching in the top level.

For the concern that this modification will lead to mismatched symbol that be held by both the top module and a submodule, the symbol search process is implemented with a BFS algo., thus it will not affect the correctness as symbols in the higher level have higher priority.

### CODE REVIEW

**Comment by masahi** [comment]
oh, recently I've hit an error at https://github.com/apache/tvm/blob/d721d320bd2f66d342d24b71600fe1f5e222e952/python/tvm/contrib/graph_executor.py#L161 when working with Android RPC, because the function `get_input_info` doesn't exist in the module.

Does this PR fix it?

**Comment by Maximilianxu** [comment]
@masahi I don't think so. It seems that ```get_input_info``` is a function symbol of GraphExcutor and can be fetched directly from the top level. https://github.com/apache/tvm/blob/f9d8c2b99615f074fd7b0ae95d04825ab443fa33/src/runtime/graph_executor/graph_executor.cc#L643

**Comment by Maximilianxu** [comment]
I think several modules can contain a function with the same name. Before this, you cannot fetch such functions at all. After this, it may return the unexpected function. But when we compile a model from Relay, each function will get a unique name. It is hard to say if we need to check such cases ourselves or just leave it to the user.

**Comment by Maximilianxu** [comment]
@kparzysz-quic I think several modules can contain a function with the same name. Before this, you cannot fetch such functions at all. After this, it may return the unexpected function. But when we compile a model from Relay, each function will get a unique name. It is hard to say if we need to check such cases ourselves or just leave it to the user.

**Review by kparzysz-quic — APPROVED** [review]
I think this should be ok.

**Pull request merged**
