### PR TITLE
[ci][docker] Use RFC image tags only

### PR DESCRIPTION
**Pull request by driazati**
This ignores any images that don't match the pattern laid out in https://github.com/apache/tvm-rfcs/pull/66

cc @Mousius @areusch

### CODE REVIEW

**Comment by areusch** [comment]
@driazati could you give a bit more context here? is there a bug describing what's wrong right now?

**Comment by driazati** [comment]
it ignores any extra images that someone might manually push (or the validated ones that get pushed by ci with the name `123-123-abc-validated`)

**Comment by areusch** [comment]
@gigiblender could you review this one so you can understand how this tool works?

**Comment by gigiblender** [comment]
> @gigiblender could you review this one so you can understand how this tool works?

@areusch Sure

**Comment by gigiblender** [comment]
Thanks @driazati! LGTM!

@areusch

**Review by areusch — APPROVED** [review]

**Pull request merged**
