### PR TITLE
[TVMScript] Use new variable frame in If/Then/Else

### PR DESCRIPTION
**Pull request by Lunderberg**
Previously, while TVMScript introduces a new scope for other contexts (e.g. `for`, `while`, `with`, etc), the `if` and `else` blocks did not introduce a new scope.  This caused erroneous parsing errors if the `if` and `else` blocks each contained a variable with the same name.  Added a `self.var_table.with_frame()` context resolves this issue.

### CODE REVIEW

**Comment by Hzfengsy** [comment]
cc @junrushao @wrongtest-intellif @lightzhan-intellif

**Review by junrushao — APPROVED** [review]
Looks like a nice enhancement! LGTM. @wrongtest-intellif could you take a look?

**Comment by junrushao** [comment]
I do believe this is good to merge. @wrongtest-intellif what do you think?

**Comment by junrushao** [comment]
Thanks @Lunderberg!!

**Pull request merged**
