### PR TITLE
[Hexagon][LLVM][CodeGen] Make CodeGenHexagon a subclass of CodeGenCPU

### PR DESCRIPTION
**Pull request by supersat**
There is a lot of duplicate code between CodeGenCPU and CodeGenHexagon, and I suspect this will increase over time. This PR removes this duplicate code and makes CodeGenHexagon a subclass of CodeGenCPU.

### CODE REVIEW

**Comment by supersat** [comment]
@mehrdadh @kparzysz-quic @areusch

**Comment by kparzysz-quic** [comment]
Nice!  I'll try it downstream, hopefully it still works.  :D

**Review by kparzysz-quic — APPROVED** [review]

**Review by csullivan — APPROVED** [review]
🎉  I'll let @kparzysz-quic merge after checking with downstream.

**Review by mehrdadh — APPROVED** [review]
LGTM!

**Comment by mehrdadh** [comment]
@supersat @kparzysz-quic @csullivan thanks! PR is merged!

**Pull request merged**
