### PR TITLE
Expose FTVMInferCorrectLayout Python interface

### PR DESCRIPTION
**Pull request by kueitang**
Expose FTVMInferCorrectLayout  API to python and expose the output type, InferCorrectLayoutOutput, also.

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by junrushao1994** [comment]
Thanks! Please fix the CI issue

**Comment by kueitang** [comment]
Hi @junrushao1994 Thanks for your reminding! I will fix it and retrigger. :)

**Comment by kueitang** [comment]
Hi @junrushao1994 , the CI error is fixed already! Please take a look at it. Lots of Thanks!

**Comment by junrushao1994** [comment]
CC @yzhliu please review when you got time :-)

**Review by comaniac — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
Thanks @kueitang @junrushao1994

**Pull request merged**
