### PR TITLE
[microNPU] Removing constant args from PrimFunc

### PR DESCRIPTION
**Pull request by manupa-arm**
Before this commit, microNPU creates PrimFunc as if it accepts constants from the callee. This commit changes the PrimFunc to remove the constants as an argument to PrimFunc as they are not provided from the main function.

### CODE REVIEW

**Comment by manupa-arm** [comment]
This is blocked on #9929

**Comment by manupa-arm** [comment]
@mbaret a review here is appreciated!

**Review by mbaret — APPROVED** [review]
lgtm

**Review by Mousius — APPROVED** [review]
LGTM!

**Comment by Mousius** [comment]
Thanks @manupa-arm / @mbaret - I declare this PR merged! :smile_cat:

**Pull request merged**
