### PR TITLE
[BUG]fix batch matmul not set attrs_type_key, when using tvm.parse.parse_expr will raise error.

### PR DESCRIPTION
**Pull request by MeJerry215**
```
df_parsed = tvm.parser.parse_expr(
    '''
    fn (%p0527: Tensor[(16, 256, 256), float16], %p1361: Tensor[(16, 64, 256), float16]) -> Tensor[(16, 256, 64), float16] {
        nn.batch_matmul(%p0527, %p1361, transpose_b=True) /* ty=Tensor[(16, 256, 64), float32] */
    }
    '''
)
```
the code above may fail, cause not set nn.batch_matmul attrs_type_key.

test_code:
```
def test_nn_batch_matmul():
    df_parsed = tvm.parser.parse_expr(
        '''
        fn (%p0527: Tensor[(16, 256, 256), float16], %p1361: Tensor[(16, 64, 256), float16]) -> Tensor[(16, 256, 64), float16] {
        nn.batch_matmul(%p0527, %p1361, transpose_b=True) /* ty=Tensor[(16, 256, 64), float32] */
      }
        ''')


```

image

now the attr has been properly set.

### CODE REVIEW

**Comment by MeJerry215** [comment]
@yzhliu

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
Seems you have hit an flaky error, please run another job (rebase and push, or empty commit)

**Comment by masahi** [comment]
Sorry another flaky errors. You can relax the tolerance in https://github.com/apache/tvm/blob/d35b858ceb5c7157c3faa78c88eb8f8971ba5e96/tests/python/contrib/test_cudnn.py#L308

**Comment by areusch** [comment]
@MeJerry215 please fix the CI problem

**Pull request closed without merging**
