### PR TITLE
[WIP] Add MLIR Relay Dialect, Translate MLIR HLO to MLIR Relay to Relay

### PR DESCRIPTION
**Pull request by yongwww**
The PR implements the basic infra for the RFC (https://discuss.tvm.apache.org/t/rfc-mlir-frontend/6473), we will add more operators after this pr is accepted. Thanks Yanan for prototyping relay dialect and conversion from mlir relay to relay.

@tqchen @zhiics MLIR and mlir hlo are required in CI machines for the build, could you please help install them? (or give me access to the machines?)

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @yongwww . I think it worth discussing the approach a bit further. In particular given that the HLO and relay are pretty close, does it makes sense to directly translate the HLO to relay in c++ without introducing the additional relay dialect to reduce one level of indirection.

**Comment by yongwww** [comment]
@tqchen Thanks for the comment. 

We chose to go with MLIR/HLO instead of XLA HLO, because HLO operations works on tensors with static shape (dynamic ops like [NMS](https://github.com/tensorflow/tensorflow/issues/42879) are not supported by XLA HLO), this limits op/model coverage. MLIR/HLO is possible to represent dynamism, for example, the mhlo lowered from MLIR/TensorFlow. 

Introducing Relay Dialect does bring some extra effort for adding relay operators, and translation from MLIR/HLO to Relay is pretty similar to translation from MLIR/Relay to Relay. 

Considering several dialects are defined already, like [MLIR/TensorFlow](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/tensorflow/ir) (NMS is in it now), [MLIR/TFLite](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/lite), [MLIR/HLO](https://github.com/tensorflow/mlir-hlo), [MLIR/ONNX](https://github.com/onnx/onnx-mlir/), etc. Having Relay Dialect will make the conversion from other potential MLIR Dialects to Relay(via mlir/relay) easy, writing some mlir passes/patterns will make the conversion between dialects happen under MLIR conversion infra. Besides, folks might translate relay to mlir/relay even though personally I don't think we need do this.

If we believe/bet there are translations from other mlir dialects to relay in the future, I think having relay dialect is not a bad thing. I am okay to go with mlir/hlo to relay directly. Please let me know what you guys think. 

cc: @yangjunpro @jroesch

**Comment by tqchen** [comment]
First of all, I do not disagree about the general goal of having a relay dialect in MLIR. The main discussion pt is how can we get to that point.

Right now we have the need to expose relay operators to a few places: (1) python  (2) c++ registration; (3) rust; (4) tablegen(if go with the mlir route),

If we can first streamline the operator schema itself (perhaps relates to the object def schema https://discuss.tvm.apache.org/t/rfc-tvm-object-schema-dsl/7930), then there will be less resistance in adding a MLIR relay dialect later. 

Right now, I feel that direct translation might be a path of less resistance, given that: (1) We can always switch to a dialect later and most of the code are similar; (2) It would be easier to quickly expand the support. (3) We might need some effort in figuring out the control flow support/effect first, then think about how a complete dialect can be built

**Comment by FrozenGene** [comment]
I agree TQ’s point. we introduce this pr’s main goal is to cover more models (include dynamic). However, introducting tablegen will bring overhead to us. We don’t have urgent requirement to interact with other mlir dilaect and beyond the goal of introducing mlir frontend, which shouldn’t introduce more complex development to relay.

**Comment by zhiics** [comment]
Thanks @yongwww for the great effort:) Both paths make sense to me. Adding Relay as a dialect would benefit more other dialects including other projects internally. But it does introduce another layer of transition for TVM. Since converting through MLIR/HLO to Relay shares almost the same amount of efforts, we can probably go this route first. We could either add relay as a dialect later after op schema is done as @tqchen mentioned or go through a dialect to HLO then to Relay first if it is needed. As of now, we probably don't need many dialects to Relay, i.e. we have directly parsers for onnx/TFLite to Relay. If you agree, let's discuss offline to setup the CI so that you can move forward.

**Comment by yongwww** [comment]
Thank you all! @tqchen @FrozenGene @zhiics It makes sense to me, I am going to update the code to go with MLIR-HLO to Relay accordingly, will ask @zhiics for help to setup CI then. Perhaps we could discuss relay dialect later after op schema is done.

**Comment by xqdan** [comment]
@yongwww @tqchen @zhiics I suggest we support a kind of graph ir with boundry in relay. Let me explain a little bit. XLA is expanding big ops with fine-grained primitive ops, but losing high level information, that is the boundry of big ops, and which brings lots of trouble to fusion, since it's very difficult to do fusion for such huge graph with thoudsands of fine-grained primitive ops. But if we can keep the boundry when we expand/convert big ops into relay graph ir, we can avoid the problem above, besides we can do whatever XLA can do with this graph ir with boundry info. with this design, tvm can be a more powerful deep learning compiler, also can be a more powerful plugin optimizer for other ai frameworks.

**Comment by u99127** [comment]
are there any instructions on how to build mlir-hlo and llvm to experiment with this PR ? I'm personally curious to see how this works but I'm not observing any instructions as to how to configure mlir-hlo project alongside this work. 

I've tried the build instructions from here https://github.com/tensorflow/mlir-hlo 

> build_tools/build_mlir.sh ${PWD}/llvm-project/ ${PWD}/llvm-build

and then setting LLVM_PROJ_SRC and LLVM_PROJ_BUILD in my environment to try and build this. 



regards
Ramana

**Comment by yongwww** [comment]
@u99127 Thanks for trying it out, I will work on this in the next or next two weeks hopefully, sorry that I was working on some other stuffs before. Cmake and llvm-mlir need to be upgraded for this project. I have an indepedent private repo for this project, I can add you it if you are interested.

**Comment by yongwww** [comment]
I am going to close this PR at this moment, I am not working on it since it was marked as low priority one by team.

**Pull request closed without merging**
