### PR TITLE
fix bug: KeyError, can't find some parameter key

### PR DESCRIPTION
**Pull request by woobinw**
fix paddle model2tvm, can't find key:
int  relay/frontend/paddlepaddle.py
    self.params[name] = _nd.array(scope[name])
KeyError: 'generated_tensor_0'

@siju-samuel
cc @jiangjiajun @heliqi

### CODE REVIEW

**Comment by heliqi** [comment]
One suggestion: The title could be changed to "[Frontend] [Paddle] fix bug ..".

LGTM!

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Review by jiangjiajun — APPROVED** [review]
LGTM

**Comment by jiangjiajun** [comment]
@junrushao1994 Could you help to merge this pr?

**Comment by junrushao1994** [comment]
Of course! Thanks for the contribution!

**Comment by woobinw** [comment]
> 

OK, thank your suggestion

**Pull request merged**
