### PR TITLE
[BugFix] Print doubles with precision 17 in SaveJSON and TVM script printer

### PR DESCRIPTION
**Pull request by MasterJH5574**
This PR fixes a bug in SaveLoad, which didn't save enough digits for double value and may cause precision loss when loading the value from JSON again. Besides, this PR adds a regression test for the precision loss case.

Before this PR, double value is saved with precision 16. However, actually we should save at least 17 digits to avoid precision loss, according to [IEEE 754-1985 standard](https://standards.ieee.org/standard/754-1985.html):

> When rounding to nearest conversion from binary to decimal and back to binary shall be the identity as long as the
decimal string is carried to the maximum precision specified in Table 2, namely, 9 digits for single and 17 digits for
double.

### Reference

* "IEEE Standard for Binary Floating-Point Arithmetic," in ANSI/IEEE Std 754-1985 , vol., no., pp.1-20, 12 Oct. 1985, doi: 10.1109/IEEESTD.1985.82928.

cc @tqchen @junrushao1994

### CODE REVIEW

**Comment by junrushao1994** [comment]
Thanks for fixing the subtle issue! BTW, would you like to also fix the TVM script printer?

**Comment by MasterJH5574** [comment]
Okay, I'm gonna to take a look soon.

**Comment by MasterJH5574** [comment]
@junrushao1994 I've fixed the TVM script printer. Would you like to take another look? Thanks!

**Review by junrushao1994 — APPROVED** [review]
LGTM. CC: @Hzfengsy

**Review by Hzfengsy — APPROVED** [review]
LGTM

**Comment by tqchen** [comment]
Thanks @Hzfengsy @junrushao1994

**Pull request merged**
