### PR TITLE
[TIR] Support Vector Reinterpret Calls

### PR DESCRIPTION
**Pull request by Hzfengsy**
This PR adds support for vector reinterpret calls in TIR.

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Comment by Hzfengsy** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot  rerun

**Comment by Hzfengsy** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Pull request merged**
