### PR TITLE
[Build] Add CUDA_VERSION and GIT_COMMIT_TIME

### PR DESCRIPTION
**Pull request by comaniac**
1. Add CUDA_VERSION to libinfo so that users can query which CUDA version was used to build TVM. Usage:

```python
>>> import tvm
>>> tvm.support.libinfo()["CUDA_VERSION"]
'10.2'
```

2. Add GIT_COMMIT_TIME to libinfo so that we can do the following
```python
>>> import tvm
>>> tvm.support.libinfo()["GIT_COMMIT_TIME"]
'2021-06-29 22:21:22 +0000'
>>> import datetime
>>> datetime.datetime.strptime(tvm.support.libinfo()["GIT_COMMIT_TIME"], "%Y-%m-%d %H:%M:%S %z")
datetime.datetime(2021, 6, 29, 22, 21, 22, tzinfo=datetime.timezone.utc)
```

cc @junrushao1994

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Comment by junrushao1994** [comment]
Just curious, if a TVM binary fails at loading time due to inconsistent CUDA versions, I imagine we cannot query via libinfo because loading has already failed. Do we have to consider this particular case?

**Comment by jcf94** [comment]
> Just curious, if a TVM binary fails at loading time due to inconsistent CUDA versions, I imagine we cannot query via libinfo because loading has already failed. Do we have to consider this particular case?

Reasonable.
Will it be better to rename this to BINARY_CUDA_VERSION or something like cuda version in build time? @comaniac

**Comment by comaniac** [comment]
> > Just curious, if a TVM binary fails at loading time due to inconsistent CUDA versions, I imagine we cannot query via libinfo because loading has already failed. Do we have to consider this particular case?

It seems out of scope to me. It's more like an environment issue if the binary is incompatible and results in loading failure. The only goal of libinfo is reporting the information of the current binary as a part of the environment logging. If we want to provide the information when failed to load, we should do that in other places such as dlopen.

> Reasonable. The cuda version linked at build time and the cuda version in runtime environment when using tvm python package may be different.
> 
> Will it be better to rename this to BINARY_CUDA_VERSION or something like cuda version in build time? @comaniac 

I would prefer to keep the current one for 2 reasons. First, this is under support.libinfo, which already clearly says this is for the TVM lib instead of the runtime. Second, it consists with LLVM_VERSION.

**Review by jcf94 — APPROVED** [review]

**Pull request merged**
