### PR TITLE
[TFLite] Support quantized GREATER op in TFLite frontend

### PR DESCRIPTION
**Pull request by dchauhan-arm**
Support GREATER quantization operation conversion as part of issue #9187 Continuation of #11519

### CODE REVIEW

**Comment by dchauhan-arm** [comment]
cc @leandron @lhutton1 @Mousius

**Review by leandron — APPROVED** [review]
LGTM, happy for this to be merge once CI is green.

**Review by lhutton1 — APPROVED** [review]
LGTM!

**Comment by lhutton1** [comment]
Thanks @dchauhan-arm @leandron!

**Pull request merged**
