### PR TITLE
Fixed deprecation warning issue in pipeline executor

### PR DESCRIPTION
**Pull request by Raghav-Chakravarthy**
Fixed the deprecation warning issue

### CODE REVIEW

**Review by huajsj — APPROVED** [review]
LGTM, please fix the ci issue(trigger a new build?), thanks @Raghav-Chakravarthy.

**Comment by Raghav-Chakravarthy** [comment]
Hello @huajsj , I will fix this issue.

Thanks

**Review by comaniac — APPROVED** [review]

**Comment by Raghav-Chakravarthy** [comment]
@huajsj 
Hello,

I have fixed the build issue. Please help me merge the commit.

Thanks,
Raghav

**Comment by Raghav-Chakravarthy** [comment]
Thank you @masahi

**Pull request merged**
