### PR TITLE
[FQ2I] Add leaky relu to FQ21

### PR DESCRIPTION
**Pull request by MargaretQian**

### CODE REVIEW

**Comment by MargaretQian** [comment]
@sfvaroglu @AndrewZhaoLuo could you take a look please?

**Comment by AndrewZhaoLuo** [comment]
@MargaretQian I think the main thing is we want this in QNN too. This is so we can better control the lowering process for target dependent hardware.

**Review by mbrookhart — APPROVED** [review]
LGTM

**Comment by mbrookhart** [comment]
Thanks @MargaretQian @AndrewZhaoLuo

**Pull request merged**
