### PR TITLE
 [Dlight] LowBatchGemv rule only apply to function with spatial symbolic var

### PR DESCRIPTION
**Pull request by jinhongyii**
LowBatchGemv rule only apply to function with spatial symbolic var, so that this rule skips matmul in attention kernel which has symbolic_var `kv_seq_len`

### CODE REVIEW

**Comment by jinhongyii** [comment]
@tvm-bot rerun

**Comment by jinhongyii** [comment]
@tvm-bot rerun

**Review by MasterJH5574 — APPROVED** [review]
LGTM!

**Comment by jinhongyii** [comment]
@tvm-bot rerun

**Pull request merged**
