### PR TITLE
[CI][BYORTL] add Verilator regression test to CI

### PR DESCRIPTION
**Pull request by vegaluisjose**
@tqchen @tmoreau89

### CODE REVIEW

**Review by tmoreau89 — APPROVED** [review]
Thank you @vegaluisjose LGTM

**Comment by tqchen** [comment]
Thanks @vegaluisjose , looking at the files, looks like that `libverilator.so` needs to be shared cross stages. Merging this now would create a problem.

It would be great to not do so, and build the library before test

**Comment by vegaluisjose** [comment]
Hey @tqchen ,

I don't think I am following, could you elaborate on what the problem will be?

The library is currently [built](https://github.com/apache/tvm/blob/main/cmake/modules/contrib/Verilator.cmake#L19) when the CMAKE macro `USE_VERILATOR_HW` is `ON`. Also, during this stage the library is [linked](https://github.com/apache/tvm/blob/main/cmake/modules/contrib/Verilator.cmake#L23-L24), so tvm knows where to find such library when selecting that backend in Python.

**Comment by tqchen** [comment]
The main problem would be right after we merge the PR，if there is no library named libverilator(because it is not yet in the rules) the CI on the main will fail. Until we add a PR to build the libverilator hw, given that the hw itself is not hard to build, would be great if we build it at the test stage instead of caching it after build

**Review by tmoreau89 — CHANGES_REQUESTED** [review]
Preventing accidental merges

**Comment by liangfu** [comment]
> It would really be nice if the hw part can be built independently, and loaded on demand.

+1

**Comment by vegaluisjose** [comment]
Hey guys,

The CI is updated now with the new version of Verilator backend. CI (Jenkins) seems to be working.

**Review by tmoreau89 — APPROVED** [review]
That's great, thanks for making sure we land these verilator CI tests @vegaluisjose !

**Comment by tmoreau89** [comment]
Thank you @liangfu @tqchen @vegaluisjose ; the PR has been merged.

**Pull request merged**
