### PR TITLE
[microNPU] Upgrade Vela to v3.5.0

### PR DESCRIPTION
**Pull request by Alexey-Yazev**
Upgrading Vela version to 3.5.0.
cc @manupa-arm @ekalda @leandron

### CODE REVIEW

**Review by junrushao — APPROVED** [review]
LGTM

**Comment by lhutton1** [comment]
@leandron does this also need a CI run to check against the updated docker image?

**Comment by leandron** [comment]
> @leandron does this also need a CI run to check against the updated docker image?
> 
> Edit: pushed a non-forked branch of this commit to trigger CI with the updated docker image

I think the CI run on the non-forked branch failed for an unrelated reason. In parallel I pushed this change to `ci-docker-stage` branch for further validation: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/290/pipeline

**Review by leandron — APPROVED** [review]
Validation completed for this patch, so I'm happy for this to be merged as soon as CI is green here. Thanks @Alexey-Yazev @lhutton1

**Comment by leandron** [comment]
@tvm-bot rerun

**Pull request merged**
