### PR TITLE
Fix test_cublas and relax tolerance

### PR DESCRIPTION
**Pull request by areusch**
* Allows test to pass on ci-gpu with new 18.04 image.

@tkonolige @tqchen

### CODE REVIEW

**Comment by comaniac** [comment]
FYI: It's possible that this error is caused by the CUBLAS math flag: https://github.com/apache/tvm/blob/813136401a11a49d6c15e6013c34dd822a5c4ff6/src/runtime/contrib/cublas/cublas.cc#L38

According to the CUBLAS document, this flag is being deprecated. We also made some tests previously around this flag, and found that it is effective even for float32, meaning that CUBLAS kernel internally casts float32 to float16, does the computation, and casts the results back. As a result, this flag may introduce accuracy issue.

**Comment by areusch** [comment]
@comaniac i was sending this through CI for @tkonolige as he was out friday. I'll let him reply to your comment.

**Comment by tkonolige** [comment]
@comaniac Disabling the flag makes the tests pass. What should we do here? Accept lower accuracy for performance?

**Comment by comaniac** [comment]
> @comaniac Disabling the flag makes the tests pass. What should we do here? Accept lower accuracy for performance?

I personally prefer to keep the accuracy, because it seems not right to tolerate 1e-2 for a single batch_matmul op. It means the end-to-end accuracy of all models with cublas.batch_matmul may be larger than 1e-2. cc @Hzfengsy @Laurawly as they added this flag at the time it hasn't been deprecated.

**Comment by Hzfengsy** [comment]
I also prefer to keep accuracy. Just as @comaniac said, 1e-2 is too low for larger end-to-end workloads

**Pull request closed without merging**
