### PR TITLE
[Relay][Topi] Add max mode to ROI align

### PR DESCRIPTION
**Pull request by electriclilies**
This PR adds max mode to ROI align. 

The ONNX version of max mode in ROI align is incorrect (see https://github.com/microsoft/onnxruntime/issues/6146), so I'm not testing ROI align with max mode against onnx's ROI align with max mode, even though I added max mode to the onnx importer. 

I also add inf and -inf to hybridscript in this PR.
@jwfromm @mbrookhart @CircleSpin please take a look!

### CODE REVIEW

**Review by jwfromm — APPROVED** [review]
I think there's a little code duplication that could be removed but otherwise this LGTM. Thanks Lily!

**Comment by electriclilies** [comment]
@junrushao1994 in case you want to take a look at adding inf, and ninf to hybridscript!

**Comment by junrushao1994** [comment]
thanks @electriclilies! That part looks pretty good to me

**Review by mbrookhart — APPROVED** [review]
LGTM

**Pull request merged**
