### PR TITLE
Consider pad value and input zero point in FoldExplicitPading

### PR DESCRIPTION
**Pull request by ibsidorenko**
This commit adds the following:
Do not fold `nn.pad` and `qnn.conv2d` if padding value is not
equal to input zero point of qnn operation. Added unit test
to check such behaviour.

### CODE REVIEW

**Comment by ibsidorenko** [comment]
cc @masahi

**Comment by ibsidorenko** [comment]
cc @masahi

**Comment by masahi** [comment]
LGTM but does this case happen in practice? It doesn't seem correct to use a different value than zero point for padding before `qnn.conv2d`.

**Comment by apeskov** [comment]
We doesn't face such cases on practice yet. I absolutely agree, it is strange usage of pad+qnn.conv combination, but anyway it may happens.

This change is just to keep pass correct for all possible cases. Relay itself doesn't prevent user from constructing any combination of operators, including case with different pad value by mistake.

**Comment by ibsidorenko** [comment]
Hi, @masahi ! Should we merge this PR or discard it? What's your opinion?

**Comment by apeskov** [comment]
@jwfromm @masahi could you please approve pipeline to start?

**Review by masahi — APPROVED** [review]

**Pull request merged**
