### PR TITLE
[Unity][Hexagon] Allow scalar tensors to have null shape during allocation

### PR DESCRIPTION
**Pull request by ibsidorenko**
Update assert during buffer allocation. Zero dimensional tensors (scalars) can have a null shape.

This PR is attempt to port [PR#14376](https://github.com/apache/tvm/pull/14376) from tvm/main that enables Hexagon tests with Relax.

### CODE REVIEW

**Review by janetsc — APPROVED** [review]
Thanks for porting this fix!

**Review by janetsc — APPROVED** [review]

**Comment by farshidsp** [comment]
Thanks for this PR. LGTM.

**Comment by masahi** [comment]
Can we wait for the next rebase instead of making the same change?

**Comment by ibsidorenko** [comment]
> Can we wait for the next rebase instead of making the same change?
Sure, we can wait If rebase is planned in the near future.

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
yes, we plan to do it sometime this weekend

**Comment by tqchen** [comment]
should be in now

**Pull request closed without merging**
