### PR TITLE
Add link to docs and tutorials in the README.

### PR DESCRIPTION
**Pull request by mdw-octoml**
Most project pages on GitHub have a README.md file with a clear link to installation or tutorial material for new users.
While there is a link to Documentation, it's not that obvious, and adding a more explicit "getting started" link may be
helpful for new TVM users trying to navigate the project.

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by mdw-octoml** [comment]
CC @jroesch @hogepodge

**Comment by hogepodge** [comment]
LGTM. Please note this pre-RFC](https://discuss.tvm.apache.org/t/updated-docs-pre-rfc/10833) to address the larger organization of the docs.

**Review by junrushao1994 — APPROVED** [review]

**Review by tmoreau89 — APPROVED** [review]
Thanks Matt, LGTM

**Comment by tmoreau89** [comment]
Agreed on Chris' note on this being pre-RFC

**Comment by tmoreau89** [comment]
Thanks @mdwelsh @junrushao1994 @hogepodge PR has been merged

**Pull request merged**
