### PR TITLE
[WIP] Revert lower tvm builtin change

### PR DESCRIPTION
**Pull request by zhanghaohit**

### CODE REVIEW

**Comment by junrushao1994** [comment]
I’m not actually an expert in vta or opencl. CC @tmoreau89 if you are interested :-)

**Comment by tmoreau89** [comment]
Thanks for the WIP PR, please let me know when it's ready for review @zhanghaohit  - and also please provide a short summary of the PR in the description box, thanks!

**Comment by tmoreau89** [comment]
@zhanghaohit looks like the CIs are green! Let me know when you'd like to change this PR to not WIP

**Comment by zhanghaohit** [comment]
> @zhanghaohit looks like the CIs are green! Let me know when you'd like to change this PR to not WIP

Hi @tmoreau89, this PR is actually the same as #8274 proposed by @mbrookhart . It is to show how to pass the CI if we want to revert the lower_tvm_builtin_change. 

I think it is better to let @mbrookhart apply the changes to his PR  #8274, which has already much discussion and context there.

I'll close this PR first, in order not to confuse.

**Comment by mbrookhart** [comment]
Huh, I thought I did this, to the tutorial, but it doesn't seem to be in my PR! Oops! I'll do this there, thanks.

**Comment by mbrookhart** [comment]
:flushed: Oops. Apparently I made this change locally and never pushed it upstream. Thank you for double checking me.

**Comment by tmoreau89** [comment]
Ah no problem, my reaction times have been slow lately, I'm glad we're making forward progress.

**Pull request closed without merging**
