### PR TITLE
[CI] Fix Lint Issue

### PR DESCRIPTION
**Pull request by mehrdadh**
We need to set `LC_ALL` and `LANG` before running any `black` command otherwise it has error.

### CODE REVIEW

**Comment by mehrdadh** [comment]
@areusch @tqchen

**Review by tmoreau89 — APPROVED** [review]
LGTM, thank you @mehrdadh

**Comment by tmoreau89** [comment]
Thank you @mehrdadh the PR has been merged

**Review by leandron — COMMENTED** [review]
Sorry or the late review, but this PR was submitted and merged before I had a chance to have a look :).

I looked into this issue a few days back, in the context of https://github.com/apache/tvm/pull/8089. This only reproduces once `black` is updated to the latest version.

I think it would be important to send a PR fixing all the files for new linting issues `black` find, especially the ones that look like the ones sent here, which will happen all over the Python codebase (the root cause is this update on `black` - `https://github.com/psf/black/pull/1740`). Otherwise, we'll have lots of patches which claim they are doing something, and are also including lots of small docstring format updates, which can be confusing.

What do you think?

**Comment by mehrdadh** [comment]
@leandron I had to send a quick fix since two other PRs were waiting on it. But I agree with you that we should reformat all files with new changes to avoid these small changes.
I'll send a PR soon and fix all of the files and I will ping you for review.
Thanks!

**Comment by mehrdadh** [comment]
follow up: https://github.com/apache/tvm/pull/8194

**Pull request merged**
