### PR TITLE
[ETHOSN] Fix requantize output conversion

### PR DESCRIPTION
**Pull request by lhutton1**
Fixes a small issue when converting the output information to the support library API. The `requantize_info` output datatype needed updating with the output datatype from the relay function to ensure the graph is compiled correctly by the support library. Included a test to prevent regression in the future.

cc @NicolaLancellotti @leandron

### CODE REVIEW

**Review by NicolaLancellotti — APPROVED** [review]
Thanks, @lhutton1. LGTM!

**Review by leandron — APPROVED** [review]
LGTM, thanks @NicolaLancellotti @lhutton1!

**Comment by lhutton1** [comment]
@tvm-bot rerun

**Comment by lhutton1** [comment]
Thanks @leandron, @NicolaLancellotti!

**Pull request merged**
