### PR TITLE
[Vulkan][Docs] Minor updates following Vulkan target query implementation

### PR DESCRIPTION
**Pull request by Lunderberg**
- Better error messages, specifying which capability is needed.

- Documentation section outlining the different target capabilities,
  which vulkan properties they correspond to, and which spir-v
  capabilities they are required by.

### CODE REVIEW

**Comment by Lunderberg** [comment]
@masahi

**Comment by masahi** [comment]
please fix the build error.

**Comment by Lunderberg** [comment]
Build error fixed.  Thank you for the catch, and definitely time for me to set up a pre-commit hook, since I've forgotten both this and linting in the past.

**Comment by Lunderberg** [comment]
Rebased on main to start CI again, now that the CI fix #8160 is in.

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
Thanks @Lunderberg

**Pull request merged**
