### PR TITLE
[Vulkan] Some fixes of Vulkan codegen

### PR DESCRIPTION
**Pull request by spectrometerHBH**
- add exp2 dispatch
- handle thread invariant op
- disable smem merge for vulkan

### CODE REVIEW

**Comment by junrushao** [comment]
Cherry-picked to https://github.com/mlc-ai/relax/pull/309

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by Hzfengsy** [comment]
Please rebase :)

**Comment by junrushao** [comment]
I think it's part of https://github.com/apache/tvm/pull/16414 that has been merged

**Pull request closed without merging**
