### PR TITLE
[Bugfix][Relay][Keras] Fix a wrong variable name in keras frontend

### PR DESCRIPTION
**Pull request by jikechao**
Fix a wrong variable name in keras frontend

### CODE REVIEW

**Review by leandron — APPROVED** [review]
Thanks for the fix @jikechao - LGTM

**Comment by leandron** [comment]
@tvm-bot rerun

**Comment by jikechao** [comment]
@tvm-bot rerun

**Comment by jikechao** [comment]
@tvm-bot rerun

**Review by echuraev — APPROVED** [review]

**Comment by echuraev** [comment]
@tvm-bot rerun

**Comment by echuraev** [comment]
@tvm-bot rerun

**Comment by echuraev** [comment]
@jikechao I have updated your PR description, because it was a problem why CI was failed.

**Comment by jikechao** [comment]
@echuraev Thanks for your revision.

**Pull request merged**
