### PR TITLE
[ONNX] only broadcast matmul if the shape has changed

### PR DESCRIPTION
**Pull request by mbrookhart**
cc @AndrewZhaoLuo @jwfromm 

#9911 introduced some extra broadcasting to handle edge cases in shapes. In cases where the broadcasted shape matched the input shape, this ended up being a null op that caused some issues with a model I've been testing.

I think the issue is deeper in how broadcast_to is lowered, but removing the unnecessary broadcast also fixes my bug, so I'm punting and adding the deeper issue to my backlog.

### CODE REVIEW

**Review by AndrewZhaoLuo — APPROVED** [review]
LGTM

**Review by jwfromm — APPROVED** [review]
Lowering to a null op is very interesting behavior. We should make sure to fix that eventually.. This work around in the meantime makes sense to me.

**Comment by AndrewZhaoLuo** [comment]
Can we make a tracking issue for this?

**Comment by jwfromm** [comment]
We might have to poke around a little more to figure out the issue. I wasn't able to replicate a failure using a dedicated script with useless `broadcast_to` calls inserted.

**Comment by mbrookhart** [comment]
Thanks @AndrewZhaoLuo @jwfromm

**Pull request merged**
