### PR TITLE
[Bugfix, CuDNN] fix segfault when cudnnDestroy called with destroyed cuda context

### PR DESCRIPTION
**Pull request by ganler**
## Bug description

Graph executor using 'cuda -libs=cudnn' triggers a segmentation fault error. According to related issues (https://github.com/pytorch/pytorch/issues/17658), it happens on CentOS 7 at least (I am using CentOS 7).  

<details><summary>To reproduce the bug</summary><p>

### Code

```python
import tvm
import tvm.relay as relay
import numpy as np
from tvm.relay import testing

def example():
    out_channels = 16
    batch_size = 1

    data = relay.var("data", relay.TensorType((batch_size, 3, 224, 224), "float32"))
    weight = relay.var("weight")
    bn_gamma = relay.var("bn_gamma")
    bn_beta = relay.var("bn_beta")
    bn_mmean = relay.var("bn_mean")
    bn_mvar = relay.var("bn_var")

    simple_net = relay.nn.conv2d(
        data=data, weight=weight, kernel_size=(3, 3), channels=out_channels, padding=(1, 1)
    )
    simple_net = relay.nn.batch_norm(simple_net, bn_gamma, bn_beta, bn_mmean, bn_mvar)[0]
    simple_net = relay.nn.relu(simple_net)
    simple_net = relay.Function(relay.analysis.free_vars(simple_net), simple_net)

    return testing.create_workload(simple_net)

if __name__ == '__main__':
    data = np.zeros((1, 3, 224, 224))
    mod, params = example()
    target = tvm.target.Target('cuda -libs=cudnn')
    dev = tvm.cuda()
    with tvm.transform.PassContext(opt_level=3):
        executor = relay.build_module.create_executor("graph", mod, dev, target)

    tvm_out = executor.evaluate()(tvm.nd.array(data.astype('float32')), **params)
```

### OS/Compiler/CMake Command

```shell
# OS
> cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 

# Compiler
> clang++ --version                                    
clang version 13.0.0 (https://hub.fastgit.org/llvm/llvm-project.git 551a697c5cf33275b66add4fc467fcf59084cffb)
Target: x86_64-unknown-linux-gnu
Thread model: posix

# CMake (using llvm toolchain)
> cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_PREFIX_PATH=$HOME -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_MODULE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_LINKER=$(which lld)  -DCMAKE_AR=$(which llvm-ar) -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```

### Config

In addition to default one, following options are set as 'ON':
- USE_LLVM
- USE_CUDA
- USE_CUDNN
- USE_GRAPH_EXECUTOR_CUDA_GRAPH

### Linked libraries

```shell
> ldd libtvm.so      
        linux-vdso.so.1 =>  (0x00007ffd9abd3000)
        libnvrtc.so.11.2 => /usr/local/cuda/lib/libnvrtc.so.11.2 (0x00007fc05b46e000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007fc05b266000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fc05b062000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007fc05ae45000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007fc05ab43000)
        libz.so.1 => /home/ljw/lib/libz.so.1 (0x00007fc05a925000)
        libtinfo.so.5 => /usr/lib64/libtinfo.so.5 (0x00007fc05a6fa000)
        libcudart.so.11.0 => /usr/local/cuda/lib/libcudart.so.11.0 (0x00007fc05a46b000)
        libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007fc058d96000)
        libcudnn.so.8 => /usr/local/cuda/lib/libcudnn.so.8 (0x00007fc058b6c000)
        libstdc++.so.6 => /home/ljw/lib64/libstdc++.so.6 (0x00007fc0587e5000)
        libgcc_s.so.1 => /home/ljw/lib64/libgcc_s.so.1 (0x00007fc0585cd000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007fc0581ff000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc063f99000)
```

</p></details>

After execution, the program hangs for about 5 seconds and got segfault.

```
> python tvm-keras.py
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:245:    CUDNN Found 8 fwd algorithms, choosing CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            0) CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM - time: 0.06144 ms, Memory: 0
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            1) CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM - time: 0.104448 ms, Memory: 304000
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            2) CUDNN_CONVOLUTION_FWD_ALGO_GEMM - time: 0.110592 ms, Memory: 5419008
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            3) CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD - time: 0.146432 ms, Memory: 18176
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            4) CUDNN_CONVOLUTION_FWD_ALGO_FFT - time: 0.916384 ms, Memory: 26949312
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            5) CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING - time: 1.10106 ms, Memory: 374272
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            6) CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED - time: 1.79712 ms, Memory: 137288448
[03:09:31] ../src/runtime/contrib/cudnn/conv_forward.cc:248:            7) CUDNN_CONVOLUTION_FWD_ALGO_DIRECT - time: -1 ms, Memory: 0
One or more operators have not been tuned. Please tune your model for better performance. Use DEBUG logging level to see more details.
[1]    134780 segmentation fault (core dumped)  python tvm-keras.py
```

## GDB back trace:

```
#0  0x00007ffe60d2c871 in ?? () from /usr/local/cuda/lib/libcudnn_ops_infer.so.8
#1  0x00007ffe60d4c6bf in ?? () from /usr/local/cuda/lib/libcudnn_ops_infer.so.8
#2  0x00007ffe5f986e1f in cudnnDestroy () from /usr/local/cuda/lib/libcudnn_ops_infer.so.8
#3  0x00007ffee17d07f0 in tvm::contrib::CuDNNThreadEntry::~CuDNNThreadEntry() () from /data/ljw_data/PROJECTS/tvm/build/libtvm.so
#4  0x00007ffed8fd9436 in (anonymous namespace)::run (p=<optimized out>) at ../../../../libstdc++-v3/libsupc++/atexit_thread.cc:75
#5  0x00007ffff6f19ce9 in __run_exit_handlers () from /usr/lib64/libc.so.6
#6  0x00007ffff6f19d37 in exit () from /usr/lib64/libc.so.6
#7  0x00007ffff6f0255c in __libc_start_main () from /usr/lib64/libc.so.6
#8  0x000055555573cf39 in _start ()
```

## Bug Analysis

This bug reminds me of the magic Cuda context error. e.g., when calling the first Cuda runtime API, it will register a function to destroy the Cuda context of the current program. Any CUDA-related calls after that will trigger errors.

For example, in PyTorch `cudnnDestroy` is disabled b.c.

<details><summary>details</summary><p>

(\cite: https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/aten/src/ATen/cudnn/Handle.cpp#L12)
```C++
// this is because of something dumb in the ordering of
// destruction. Sometimes atexit, the cuda context (or something)
// would already be destroyed by the time this gets destroyed. It
// happens in fbcode setting. @colesbury and I decided to not destroy
// the handle as a workaround.
//   - @soumith
//
// Further note: this is now disabled globally, because we are seeing
// the same issue as mentioned above in CUDA 11 CI.
//   - @zasdfgbnm
//
// #ifdef NO_CUDNN_DESTROY_HANDLE
// #else
//   cudnnDestroy(handle);
// #endif
```
</p></details>

### How PyTorch fixes this

Let's first see how PyTorch handles this problem [link](https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/aten/src/ATen/cudnn/Handle.cpp#L12).

In a word, PyTorch does not call any `cudnnDestroy` and they maintain a CuDNN handler pool to do the job (see [this](https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/aten/src/ATen/cudnn/Handle.cpp#L43)).

Because they leverage a global pool and constantly reuse them and the pool's lifetime goes across the program, there's no need to call `cudnnDestroy` when the program is about to exit.

###  This PR's quick workaround

The key is to tell "is the program about to exit"? If so, we do not have to call `cudnnDestroy`, which avoids such failure on some platforms.

To know whether the program is exiting, we can register an `atexit` function in the constructor (later registered function executes first, so this call is ahead of cuda context exit call) to set `cudnn_context_must_exist` to `false`.

### CODE REVIEW

**Comment by ganler** [comment]
@ZihengJiang @tqchen Could you help review this PR :-)

**Comment by ganler** [comment]
Would you also review this PR? Thanks a lot! @comaniac @YuchenJin

**Review by comaniac — APPROVED** [review]
LGTM, but I don't quite familiar with CUDA context APIs so it would be better to get the second approve.

cc @tqchen @vinx13

**Review by junrushao1994 — CHANGES_REQUESTED** [review]
Thanks for the contribution! It is definitely a classic bug on program exit, when cuda context gets destroyed before the handle is released.

I do believe that a better way to handle this issue is to "let it leak": just do not destroy the handle on exit, because the OS is going to handle it anyway.

CC: @icemelon9

**Comment by ganler** [comment]
> Thanks for the contribution! It is definitely a classic bug on program exit, when cuda context gets destroyed before the handle is released.
> 
> I do believe that a better way to handle this issue is to "let it leak": just do not destroy the handle on exit, because the OS is going to handle it anyway.
> 
> CC: @icemelon9

Agreed. PyTorch also applies the "let-it-leak" mechanism b.c. their handlers are maintained by a pool and threads reuse them. But actually, in TVM this handler is called on threads' exit (`thread_local` lifetime). So the leak might be significant if TVM kills and re-creates many threads during the whole program. So I want to confirm is that the case? If not, "let-it-leak" is definitely the best approach.

**Comment by junrushao1994** [comment]
Thanks @ganler for the quick reply! I believe that the thread-local cuDNN handle is only created when a particular thread creates it, and in TVM, there are not many threads creating cuDNN handles, so in this case it is fine IMO.

Would love to have inputs from @kevinthesun @zhiics as well

**Comment by ganler** [comment]
Sorry for the late response. I have applied the 'let-it-leak' mechanism. @junrushao1994

**Review by junrushao1994 — APPROVED** [review]
LGTM! Thanks for the contribution!

**Comment by junrushao1994** [comment]
Cc: @comaniac

**Comment by comaniac** [comment]
Thanks @ganler @junrushao1994

**Pull request merged**
