### PR TITLE
just a typo fixed

### PR DESCRIPTION
**Pull request by SebastianBoblestETAS**

### CODE REVIEW

**Comment by SebastianBoblestETAS** [comment]
Ok, checks fail, but clearly not related to this PR.

**Review by leandron — APPROVED** [review]
LGTM, can you just trigger CI again?

**Comment by SebastianBoblestETAS** [comment]
triggering CI again did not help. I fixed the formatting issues it was complaining about.

**Comment by leandron** [comment]
@lhutton1 fixed the CI issues in #10445, so I guess we can wait for that to be merged and then rebase here.

**Pull request merged**
