### PR TITLE
Bumped Ubuntu version to 18.04 for ci_gpu

### PR DESCRIPTION
**Pull request by d-smirnov**
Bumped Ubuntu version to 18.04 for ci_gpu

### CODE REVIEW

**Comment by d-smirnov** [comment]
Bumped ci_gpu image Ubuntu version to 18.04 (for debug purposes as was unable to run tvm built on my 18.04 inside the 16.04 container) @areusch, @leandron

**Review by leandron — COMMENTED** [review]
I think it is a good move to update it to 18.04, mostly because 16.04 is now EOL (https://ubuntu.com/about/release-cycle).

For the sake of this PR, can you clarify what is the error you see?

**Comment by d-smirnov** [comment]
@leandron I needed to re-run failed unit test inside ci_gpu docker environment, using my local tvm build and had a linkage error against libc.

**Comment by areusch** [comment]
cc @jroesch i think we should move all containers at once rather than just ci_gpu, though.

**Comment by leandron** [comment]
> cc @jroesch i think we should move all containers at once rather than just ci_gpu, though.

So I guess what you're suggesting is to update all the existing 16.04 images to 18.04? Do you think we should do this on this PR? I think we can do that, and I think it is a good move as 16.04 is now EOL, just would like to have a decision on what needs to be done.

 cc @jroesch @areusch

**Comment by areusch** [comment]
> > cc @jroesch i think we should move all containers at once rather than just ci_gpu, though.
> 
> So I guess what you're suggesting is to update all the existing 16.04 images to 18.04? Do you think we should do this on this PR? I think we can do that, and I think it is a good move as 16.04 is now EOL, just would like to have a decision on what needs to be done.
> 
> cc @jroesch @areusch

Jared thinks we should just do it on this PR and perform the update, but let's see what we are currently blocked on. Created a GH tracking issue #7995.

**Review by areusch — APPROVED** [review]
okay sorry I was talking past myself. as @tkonolige pointed out, all other container are on 18.04 already. merging to get this into #7995 .

**Pull request merged**
