### PR TITLE
[UnitTest][Metal] Parametrize allreduce GPU tests

### PR DESCRIPTION
**Pull request by Lunderberg**
As a first step to addressing the Metal codegen errors that required the reversion in https://github.com/apache/tvm/pull/15725, parametrizing the unit tests for `allreduce`.  While these tests are parametrized with `@tvm.testing.parametrize_targets("cuda", "metal")`, the automatic `tvm.testing.requires_metal` marker inserted for the metal parametrization will cause them to be skipped if the metal runtime is unavailable, which includes the current CI.

### CODE REVIEW

**Comment by Lunderberg** [comment]
@junrushao @MasterJH5574

**Review by MasterJH5574 — APPROVED** [review]
Thank you @Lunderberg.

**Comment by Lunderberg** [comment]
Absolutely, @MasterJH5574.  I'd like to get the Metal backend to have at least one CI test of lowering/execution, for testing prior to re-applying the `CodegenC` changes, and to avoid any similar regressions in the future.

Can you verify that the parametrized tests in this PR pass in your environment (pytest command below)?  My dev machine runs Linux, and so all the Metal tests are skipped.

```bash
TVM_TEST_TARGETS="metal" python3 -mpytest -v tests/python/unittest/test_allreduce.py
```

**Comment by MasterJH5574** [comment]
@Lunderberg Yes I can confirm that the test now skips CUDA and passes all Metal tests on mac.

**Comment by Lunderberg** [comment]
Thank you for the confirmation, and I'm now starting https://github.com/apache/tvm/pull/15756 to enable testing in CI.

**Pull request merged**
