### PR TITLE
[TIR] Minor fix to tensor intrin description

### PR DESCRIPTION
**Pull request by masahi**
@junrushao1994 @vinx13 

cc @gigiblender

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM!

**Comment by junrushao1994** [comment]
CC: @cyx-6

**Comment by masahi** [comment]
I wonder why github automatically tagged @gigiblender

**Comment by driazati** [comment]
> I wonder why github automatically tagged gigiblender

for a bit he was signed up to track tir on #10317

**Pull request merged**
