### PR TITLE
[Pass] Make Module Pass always return a new IRModule

### PR DESCRIPTION
**Pull request by hgt312**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @hgt312 , may I ask the motivation of the change? The original intend of the code is that the pass should return a new module if necessary, but can perform copyon write optimization if needed. This change would make us unable to perform the copyon write optimization. We probably need to fix the problematic passes behavior instead of this one.

**Comment by junrushao1994** [comment]
I am curious too. Isn’t copy-on-write good enough?

**Comment by jroesch** [comment]
cc @mbs-octoml

**Comment by mbs-octoml** [comment]
I've also been surprised by our sometimes mutable, sometimes COW semantics in IRModule. However may I propose we don't merge this and, as @tqchen mentions, we solve the root problems. 

This is CORE-124 in the internal OctoML JIRA, in which the suggestion was to make IRModule immutable and, if worthwhile, introduce an IRModuleBuilder for use by module passes. An RFC would be first step in that process.

**Comment by areusch** [comment]
closing due to inactivity, but feel free to reopen!

**Pull request closed without merging**
