### PR TITLE
[AutoTVM, Auto scheduler] Always use VM compiler for task extraction

### PR DESCRIPTION
**Pull request by masahi**
https://discuss.tvm.apache.org/t/autotvm-auto-scheduler-always-use-the-vm-compiler-for-task-extraction/11092

@comaniac @icemelon

### CODE REVIEW

**Review by jroesch — APPROVED** [review]

**Comment by comaniac** [comment]
Looks like some test cases were failed due to unexpected extracted task number. Could you take a look to make sure their behavior are expected? It should be good to go once CI is green.

**Comment by masahi** [comment]
@comaniac Looks like in all cases, task weights are different. Is that expected? I think it is not intuitive (I only swapped the compiler).

**Comment by comaniac** [comment]
Hmm if it's just weight difference maybe we could just let it be. I have no idea why it's the case and your hypothesis makes sense to me.

**Comment by masahi** [comment]
Not sure what this comment is supposed to mean... Is there something unreasonable about the current task extraction mechanism? 

https://github.com/apache/tvm/blob/be37923eca43c5b55793a7162cc5da526ddc8bce/src/relay/backend/te_compiler.cc#L862-L863

**Comment by masahi** [comment]
Something is off in task weights extracted by VM compiler. In the following network (MLP), there is two `dense` ops with identical workload. So there is one task with weight 2. The graph compiler returns the correct weight, but the VM compiler returns 1. Weights returned by the VM compiler are always smaller than the graph compiler.

```
def @main(%data: Tensor[(1, 32), float32], %fc1_weight: Tensor[(32, 32), float32], %fc1_bias: Tensor[(32), float32], %fc2_weight: Tensor[(32, 32), float32], %fc2_bias: Tensor[(32), float32]) -> Tensor[(1, 32), float32] {
  %0 = nn.dense(%data, %fc1_weight, units=32) /* ty=Tensor[(1, 32), float32] */;
  %1 = nn.bias_add(%0, %fc1_bias, axis=-1) /* ty=Tensor[(1, 32), float32] */;
  %2 = nn.relu(%1) /* ty=Tensor[(1, 32), float32] */;
  %3 = nn.dense(%2, %fc2_weight, units=32) /* ty=Tensor[(1, 32), float32] */;
  %4 = nn.bias_add(%3, %fc2_bias, axis=-1) /* ty=Tensor[(1, 32), float32] */;
  nn.relu(%4) /* ty=Tensor[(1, 32), float32] */
}
```

**Comment by masahi** [comment]
@comaniac I figured out why task weights are different between graph vs VM compiler. It turns out that the VM compiler never calls `auto_scheduler.relay_integration.te_compiler_update_weights` callback, because the code path below is only used by the graph compiler.

https://github.com/apache/tvm/blob/be37923eca43c5b55793a7162cc5da526ddc8bce/src/relay/backend/te_compiler.cc#L864-L866

Thus, in the VM case, weight is updated only in this line, which doesn't take multiplicity into account. So in VM, all task weights are 1.
https://github.com/apache/tvm/blob/92903b45659f094df7d41055d3a8da300fe4ff89/python/tvm/auto_scheduler/relay_integration.py#L366

The commit https://github.com/apache/tvm/pull/9069/commits/8c16d40b394f8a837c2b788be1cd821db7eb2fd7 fixed this issue. Now, task weights are identical between graph and VM.

**Comment by comaniac** [comment]
Ah you're right. The TE compiler refactoring introduced this issue and your fix makes perfect sense to me. Thanks!
cc @jroesch

**Pull request merged**
