### PR TITLE
Add support for aten::__lshift__, aten::__rshift__, aten::__ior__

### LINKED ISSUE #10499: [Bug] NotImplementedError ['aten::__lshift__', 'aten::__rshift__', 'aten::__ior__', `aten::fmod`, `aten::remainder`]
Hi,

I am running a pytorch model and I am getting this error.

File "/home/hummingbird/tvm/python/tvm/relay/frontend/pytorch.py", line 3991, in from_pytorch
    converter.report_missing_conversion(op_names)
  File "/home/hummingbird/tvm/python/tvm/relay/frontend/pytorch.py", line 3197, in report_missing_conversion
    raise NotImplementedError(msg)
NotImplementedError: The following operators are not implemented: ['aten::__lshift__', 'aten::__rshift__', 'aten::unique_consecutive', 'aten::__ior__']

My versions are:
torch: 1.10.0
tvm: 0.9.dev708+g17652d341

@masahi 

Thanks!

### PR DESCRIPTION
**Pull request by interesaaat**
Closes #10499.

### CODE REVIEW

**Comment by interesaaat** [comment]
@masahi

**Comment by masahi** [comment]
@interesaaat please run `black` on `test_forward.py`

**Comment by masahi** [comment]
so you are using different `black` version than the one in CI... please remove black change not relevant to this PR.

**Comment by masahi** [comment]
@interesaaat sorry I merged another pytorch PR, please fix the conflict.

**Comment by masahi** [comment]
ok I resolved the conflict via web UI

**Comment by masahi** [comment]
@interesaaat sorry there is a lint error from conflict resolving

**Comment by interesaaat** [comment]
Checking it right now.

**Review by masahi — APPROVED** [review]

**Pull request merged**
