### PR TITLE
[Topi][Relay] Support for FP16 ERF on CPU.

### PR DESCRIPTION
**Pull request by jwfromm**
X86 targets don't have an FP16 erf intrinsic. This causes compilation to fail when such an op is encountered. This PR adds two cases to avoid this failure. I've added an FP16 ERF legalization pass that will just cast to FP32 for the ERF call. I've also extended fast_erf to support FP16 directly. This does lose some precision compared to doing FP32 wrapping around ERF, but since the desire is to be faster I think it's acceptable behavior.

### CODE REVIEW

**Comment by jwfromm** [comment]
@anwang2009 can you take a look at this PR?

**Comment by anwang2009** [comment]
Is the default behavior that FP16 ERF will fallback to FP32 cast for the ERF call? Basically wondering in what cases the different fallbacks are used?

**Comment by jwfromm** [comment]
There's different handling for `relay.erf` and `relay.fast_erf`. When an FP16 `relay.erf` is encountered, itll legalize it to `cast(fp32) -> relay.erf -> cast(fp16)`. When an fp16 `relay.fast_erf` is encountered it will actually implement it in fp16.

**Review by anwang2009 — APPROVED** [review]
gotcha, LGTM!

**Review by AndrewZhaoLuo — APPROVED** [review]

**Pull request merged**
