### PR TITLE
[RPC] Fix cpp_rpc connection to rpc_tracker

### PR DESCRIPTION
**Pull request by echuraev**
Fixed connection cpp_rpc application to rpc_tracker which was broken by
this commit: 0bbaf0e.
Also, made it possible to create a linux shared library on MacOS.
Without this change default tuning didn't work on MacOS.

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by tkonolige** [comment]
I see some lines in rpc_env.cc that reference .so and .dll files. I think you need to expand these to also support .dylib.

**Comment by echuraev** [comment]
> I see some lines in rpc_env.cc that reference .so and .dll files. I think you need to expand these to also support .dylib.

I double-checked and `.dylib` is already supported. We use the modified functions `GenerateUntarCommand`, `LinuxShared` and `CreateShared` only in the function `BuildSharedLibrary` (https://github.com/echuraev/tvm/blob/echuraev/fix_cpp_rpc/apps/cpp_rpc/rpc_env.cc#L292). Function `BuildSharedLibrary` returns the name of the file which will be used in `Module::LoadFromFile` (https://github.com/echuraev/tvm/blob/echuraev/fix_cpp_rpc/apps/cpp_rpc/rpc_env.cc#L129). 

In case when we would like to load `dylib` the `BuildSharedLibrary` should return the name of the `dylib` library. And it works in this way. [Here](https://github.com/echuraev/tvm/blob/echuraev/fix_cpp_rpc/apps/cpp_rpc/rpc_env.cc#L315) we return the name of the `dylib` library. We could do it explicitly by adding a condition (such as: `|| support::EndsWith(file, ".dylib")`) [here](https://github.com/echuraev/tvm/blob/echuraev/fix_cpp_rpc/apps/cpp_rpc/rpc_env.cc#L293). But I think it will be redundantly.

**Comment by echuraev** [comment]
@tkonolige could you please take a look once again on this PR?

**Comment by tkonolige** [comment]
Could you explicitly add the dylib condition.

I'm not an expert on this code. Tagging @tqchen @FrozenGene, can you review?

**Comment by echuraev** [comment]
> Could you explicitly add the dylib condition.

Done.

**Review by tqchen — APPROVED** [review]

**Pull request merged**
