### PR TITLE
Disallow copy to/from external HexagonBuffer

### PR DESCRIPTION
**Pull request by adstraw**
Eventually the goal is to rework the Hexagon Device API to make `HexagonBuffer` a private entity behind the Device API.  Until then, we need support for "external" (outside the Device API) construction of a `HexagonBuffer` but we explicitly disallow copy from / to support with this PR.  Also cleaning up some names for clarity based on feedback from @kparzysz-quic.

### CODE REVIEW

**Review by tmoreau89 — APPROVED** [review]
Thanks @adstraw LGTM

**Comment by adstraw** [comment]
@kparzysz-quic please review as this PR is based on your feedback.

**Review by kparzysz-quic — APPROVED** [review]
LGTM, thanks!

**Comment by tmoreau89** [comment]
Thank you @adstraw and @kparzysz-quic - the PR has been merged.

**Pull request merged**
