### PR TITLE
[LLVM] Register factory function for CodeGenCPU

### PR DESCRIPTION
**Pull request by kparzysz-quic**
Any target that has its own subclass of `CodeGenLLVM` must register a factory function that constructs an object of that class. This factory will then be looked up and used in `CodeGenLLVM::Create`, which is the generic interface to create an LLVM code generator.

However, there is no factory for `CodeGenCPU`, and so the creation of a `CodeGenCPU` object is done inside of `CodeGenLLVM::Create`. To make this happen, codegen_llvm.cc includes codegen_cpu.h, which makes the base class implementation depend on the derived class. This backwards dependency can be resolved by registering a factory for `CodeGenCPU`.

### CODE REVIEW

**Comment by leandron** [comment]
Thanks for the PR @kparzysz-quic. Is there any chance we can have a test case for this fix?

**Comment by kparzysz-quic** [comment]
I'm not sure what such a testcase should do.  The main motivation for this change was to avoid the "reverse dependency" between .cc and .h files.  The aren't any tests that I know of that are specific to the factory functions, but if you have any suggestions, let me know.

**Comment by kparzysz-quic** [comment]
I'll paste the commit comment about why I deleted the cpp test:

The WASM docker has an installation of LLVM without versioned symbols, but the default compiler uses symbol versions. The added test had a reference to `_ZN4llvm24DisableABIBreakingChecksE@@LLVM_11`, but the LLVM library had the unversioned symbol:
```
File: /usr/lib/llvm-11/lib/libLLVMSupport.a(ABIBreak.cpp.o)
     1: 0000000000000000     4 OBJECT  GLOBAL DEFAULT    2 _ZN4llvm24DisableABIBreakingChecksE
```

**Review by leandron — APPROVED** [review]
Thanks @kparzysz-quic! Merging it now.

**Pull request merged**
