### PR TITLE
[TIR][BugFix]Ensure the Var's scope is correct

### PR DESCRIPTION
**Pull request by sisleyli**
In the previous bf16legalize pass, the `storage_scope` of the original BufferVar was not retained, but all changed to the default value (`global`). The purpose of this PR is to ensure that Var's scope is always correct

### CODE REVIEW

**Comment by sisleyli** [comment]
Hi @junrushao @masahi , could you help me review this PR? Thank you!

**Review by Hzfengsy — APPROVED** [review]

**Review by Hzfengsy — COMMENTED** [review]
Please add new testcases instead of changing the existing ones

**Comment by sisleyli** [comment]
@Hzfengsy  Done. Please take another look, thank you.

**Comment by sisleyli** [comment]
@tvm-bot rerun

**Comment by sisleyli** [comment]
this PR has passed CI, could you please help me merge it? Thanks @Hzfengsy

**Comment by Hzfengsy** [comment]
Thanks @sisleyli

**Pull request merged**
