### PR TITLE
[Minor] Typo Fixes

### PR DESCRIPTION
**Pull request by zxybazh**
Fix for a few typos found during upstream.

### CODE REVIEW

**Review by Mousius — APPROVED** [review]
What an amazing PR #10000 @zxybazh!

**Comment by Mousius** [comment]
@zxybazh there was a build failure which just got fixed due to https://github.com/apache/tvm/pull/9998, could you rebase and try it again?

**Review by junrushao1994 — APPROVED** [review]
Congrats on the #10k PR!

**Review by comaniac — APPROVED** [review]
Came here for the 10k PR :D

**Comment by tqchen** [comment]
An amazing milestone for the community :)

**Review by tqchen — APPROVED** [review]

**Review by kparzysz-quic — APPROVED** [review]
I want to be a part of this historic moment too.  :)

**Comment by shingjan** [comment]
#10000 @zxybazh !

**Pull request merged**
