### PR TITLE
[microNPU] Add support for LeakyReLU

### PR DESCRIPTION
**Pull request by lhutton1**
Adds support for offloading an int8 Leaky ReLU activation function to the NPU by leagalizing to a LUT.

### CODE REVIEW

**Comment by lhutton1** [comment]
cc @manupa-arm @ekalda @mbaret @dchauhan-arm @NicolaLancellotti @jacobbohlin

**Review by NicolaLancellotti — APPROVED** [review]
LGTM!

**Comment by lhutton1** [comment]
Friendly ping for comments/approval

**Review by ekalda — APPROVED** [review]
Thanks @lhutton1, looks all good to me!

**Review by manupa-arm — APPROVED** [review]
LGTM!

**Comment by manupa-arm** [comment]
Thanks all!

**Pull request merged**
