### PR TITLE
[BugFix][Relay][GraphExecutor] Fix set_input_zero_copy() precision bug

### PR DESCRIPTION
**Pull request by zhuwenxi**
As stated in https://github.com/apache/tvm/issues/14978

### CODE REVIEW

**Comment by zhuwenxi** [comment]
@Hzfengsy Could you help assign a reviewer here?

**Comment by Hzfengsy** [comment]
cc @vinx13 @masahi

**Comment by Hzfengsy** [comment]
@tvm-bot rerun

**Comment by zhuwenxi** [comment]
@tvm-bot rerun

**Comment by Johnson9009** [comment]
@zhuwenxi It seems the failed test is same as that of https://github.com/apache/tvm/pull/14960#issuecomment-1606434354, so maybe rebase will fix it, can you try it?

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by zhuwenxi** [comment]
> @zhuwenxi It seems the failed test is same as that of [#14960 (comment)](https://github.com/apache/tvm/pull/14960#issuecomment-1606434354), so maybe rebase will fix it, can you try it?

Let me have a try. Thank you, Johnson.

**Comment by zhuwenxi** [comment]
> @zhuwenxi It seems the failed test is same as that of [#14960 (comment)](https://github.com/apache/tvm/pull/14960#issuecomment-1606434354), so maybe rebase will fix it, can you try it?

It doesn't work, still fail at gpu/pr-head. Any suggestions?

**Comment by zhuwenxi** [comment]
Close this PR as CI constantly fails. Will reopen a new one soon.

**Pull request closed without merging**
