### PR TITLE
[TOPI] conv2d nchw gpu scheduler

### PR DESCRIPTION
**Pull request by Laurawly**

### CODE REVIEW

**Comment by arassadin** [comment]
Hi everyone.

I got such error reproducing [toy example](http://nnvm.tvmlang.org/tutorials/from_keras.html#sphx-glr-tutorials-from-keras-py) from `nnvm` but with y own model. Calling
```
m.run()
```
I get the error similar to https://github.com/dmlc/tvm/pull/315#issuecomment-322024643:
```
TVMError: [09:11:33] src/runtime/cuda/cuda_module.cc:93: CUDAError: cuModuleLoadData(&(module_[device_id]), data_.c_str()) failed with error: CUDA_ERROR_INVALID_PTX
```
Can you clarify me what can be wrong now?

Thanks in advance!

---
BTW, I'm a bit confused by `tvm.gpu()` docstring :smiley::
> Construct a CPU device

**Comment by arassadin** [comment]
@tqchen , @Laurawly , @Huyuwei can you take a quick look?..

**Comment by tqchen** [comment]
@arassadin please open new issues for new questions, in your case, it is likely the gpu schedule for nchw did not work for your specific shape of conv2d and the nvcc compiler failed to compile

**Comment by arassadin** [comment]
Ok, thanks

**Pull request merged**
