### PR TITLE
[TensorIR][Bugfix] Fallback Mechanism in Fuse for failure of DetectIterMap

### PR DESCRIPTION
**Pull request by jinhongyii**
Add a fallback mechanism in tir::Fuse if DetectIterMap can't handle the input and throw an error
cc @junrushao1994

### CODE REVIEW

**Comment by junrushao1994** [comment]
1. Is it possible to fix DetectIterMap instead of using a broad try-catch?
2. Please add a regression test for every bug fix

**Comment by junrushao1994** [comment]
CC @spectrometerHBH

**Comment by jinhongyii** [comment]
The new unittest will fail until the DetectIterMap is fixed because DebugVerify will call DetectIterMap.

**Comment by junrushao1994** [comment]
@jinhongyii would you like to coordinate with @spectrometerHBH and get DetectIterMap fixed foundamentally? Here is what we can do: 

1. Make a minimal reproducible example for DetectIterMap to crash, and then convert it to a regression test for it
2. Fix the issue in fusion and make a regression test

**Comment by jinhongyii** [comment]
sure

**Comment by Hzfengsy** [comment]
Will the same error happens in `split`?

**Comment by jinhongyii** [comment]
I'm not sure. But if DetectIterMap is fixed, both split and fuse will not have such error.

**Comment by Hzfengsy** [comment]
@jinhongyii Can you update the PR then we can merge it

**Comment by jinhongyii** [comment]
OK. Let's close this PR and let @spectrometerHBH open a new one after he adds a check.

**Pull request closed without merging**
