### PR TITLE
Add LLVM-13 installation to Docker setup

### PR DESCRIPTION
**Pull request by leandron**
Add LLVM-13 installation to Docker setup:
 * Installs LLVM 13 in for Ubuntu 18.04 Docker images
 * This is needed as a requirement for #9425

cc @masahi @jtuyls @Mousius for reviews

### CODE REVIEW

**Comment by leandron** [comment]
@tqchen @areusch @jroesch @u99127 and all other previously mentioned, I wonder how many LLVM version you consider we should maintain on our pipeline. At this moment we have 5 versions. I was thinking we could remove 9 and 10?

Thoughts?

**Review by Mousius — APPROVED** [review]
Ace @leandron! I like the clean up of the `apt-get` line, though I think maybe a line per version rather than a line of `llvm` then `clang` versions. But don't hold up this going in as I think we should land this and get CI back up to speed then address removing some older versions as a separate piece of work :smile_cat:

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Comment by leandron** [comment]
This log confirms the fix actually works when rebuilding the Docker images: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/109/pipeline

**Pull request merged**
