### PR TITLE
[ci] Add PLATFORM env var to builds

### PR DESCRIPTION
**Pull request by driazati**
This exposes the env var `PLATFORM` during builds so we can use it to
differentiate builds at runtime.

### CODE REVIEW

**Review by yongwww — APPROVED** [review]
LGTM

**Comment by yongwww** [comment]
@tvm-bot  rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Review by tqchen — APPROVED** [review]

**Comment by yongwww** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot  rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Pull request merged**
