### PR TITLE
Fix an issue with dynamic functions overwritting call arg types

### PR DESCRIPTION
**Pull request by mbrookhart**
cc @jroesch @altanh @tmoreau89

### CODE REVIEW

**Comment by altanh** [comment]
not the fault of this PR, but I've noticed some confusing and inconsistent usage of `src` and `dst` in different `Unify` functions (along with non-matching implementation argument names). There might even be a slight bug where the order is exchanged in `TypeSolver` vs `TypeSolver::Unifier`, not sure if this affects correctness.

**Comment by mbrookhart** [comment]
Yeah, it's a little weird. I'd like to run through CI just in case I introduced a bug somewhere, but once that's complete I can take a look at unifying the different versions of Unify.

**Review by altanh — APPROVED** [review]
LGTM (other than confusing naming from before)

**Comment by mbrookhart** [comment]
@jroesch @tmoreau89 Hit a driver bug in a CI node last night than Tianqi fixed, otherwise this passed tests, I think it's ready for review while the rebase runs.

**Review by altanh — APPROVED** [review]
LGTM. Just to confirm, will an unannotated argument still have its type be inferred if it can be deduced elsewhere?

**Comment by mbrookhart** [comment]
Yes, my originally attempt failed a bunch prelude/adt tests because I didn't support that :)

**Review by tmoreau89 — APPROVED** [review]
Thank you @mbrookhart overall LGTM

**Comment by tmoreau89** [comment]
Thank you @mbrookhart  and @altanh the PR has been merged.

**Pull request merged**
