### PR TITLE
[TIR] Add missing narrow down of index within conditions

### PR DESCRIPTION
**Pull request by wrongtest**
Hi, there. This change to `NarrowDataType` pass want to also narrow down int types in index conditions like in buffer indices.

Eg, `T.Int64(1) < i:int64 * T.int64(3)`  => `1 < i:int32 * 3`

### CODE REVIEW

**Comment by junrushao1994** [comment]
in the future, fundamentally speaking, we might want to make sure all values are int64 in the higher-level TIR, and use this pass to narrow dtypes

**Comment by wrongtest** [comment]
> off the topic: in the future, fundamentally speaking, we might want to make sure all values are int64 in the higher-level TIR, and use this pass to narrow dtypes

What if values come from graph level IR？ （eg，K：i32 of topk）

**Comment by junrushao1994** [comment]
we have to cast all indices to int64 at first, otherwise affine analysis could fail because it ignores casting

**Comment by wrongtest** [comment]
> we have to cast all indices to int64 at first, otherwise affine analysis could fail because it ignores casting

Yeah, want to add this change just because failures on predicate if we want to use affine analysis ：）

Very happy to know we have plan to make index type uniform!

**Comment by junrushao1994** [comment]
It's pretty much engineering intensive though. Would be great to have some helping hands from the community @wrongtest

**Comment by junrushao1994** [comment]
@cyx-6

**Comment by junrushao1994** [comment]
I don't have more comments :-) @Hzfengsy would you like to take a second look?

**Review by Hzfengsy — APPROVED** [review]

**Pull request merged**
