### PR TITLE
[FIX] Fix threadpool reset by killing threads before destroying their shared queue

### PR DESCRIPTION
**Pull request by tkonolige**
@electriclilies @mbs-octoml @junrushao1994

### CODE REVIEW

**Comment by electriclilies** [comment]
Thanks for the fix! Just curious, why wasn't this causing a segfault on linux?

**Comment by tkonolige** [comment]
No clue. Maybe the thread kill implementation on linux worked faster than the one on macOS?

**Comment by tqchen** [comment]
LGTM, thanks @tkonolige !

**Review by junrushao1994 — APPROVED** [review]
Thanks Tristan!

**Comment by tkonolige** [comment]
I will note that I introduced this bug, so don't give me too much thanks :)

**Comment by tqchen** [comment]
I would separate the thanks from past events as we work together to make the code base better together.

**Review by tmoreau89 — APPROVED** [review]
LGTM

**Comment by masahi** [comment]
The problem is still there https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8658/1/pipeline/41

**Comment by tkonolige** [comment]
@mashi, I'm not sure that's related (although it is hanging on test_runtime_profiling.py). I believe #8656 fixed that issue. I've rebased, lets see if it has been fixed.

**Review by jcf94 — APPROVED** [review]

**Comment by jcf94** [comment]
Thanks! So is it ready to merge? @tkonolige @masahi

**Comment by masahi** [comment]
I've seen a number of recent CI jobs killed at `test_runtime_profiling.py::test_vm[llvm -device=arm_cpu]`, and I thought this PR was the fix for it. No idea if this is related to the RPC socket error. Let's see if the issue is gone after merging https://github.com/apache/tvm/pull/8656

**Pull request merged**
