### PR TITLE
[relay] preserve the order of input_info of pytorch

### PR DESCRIPTION
**Pull request by sweetcocoa**
This is for resolving https://github.com/apache/tvm/issues/14461

The direct cause of this problem is that the order of input nodes found in `_analysis.free_vars(ret)` is not guaranteed in the order of names in `input_info`. From what I understand, `_analysis.free_vars(ret)` uses DFS to find input nodes from output nodes. Since DFS cannot guarantee the order in which nodes are found, it is intuitive to modify the order of input nodes after DFS, as shown in this PR.

### CODE REVIEW

**Review by masahi — APPROVED** [review]
LGTM, please fix lint

**Comment by sweetcocoa** [comment]
I fixed lint. please re-review.

**Comment by masahi** [comment]
Some tests are broken, please fix them.

**Comment by sweetcocoa** [comment]
@masahi I fixed a test failure. However, I cannot interpret the current test results. `cross-isa-minimal/pr-head — The build of this commit was aborted`. Is this caused by a change in my code?

**Comment by masahi** [comment]
@tvm-bot rerun

**Comment by sweetcocoa** [comment]
@tvm-bot rerun

**Comment by sweetcocoa** [comment]
@masahi Could you run again please?

**Comment by sweetcocoa** [comment]
@tvm-bot rerun

**Comment by masahi** [comment]
@tvm-bot rerun

**Comment by sweetcocoa** [comment]
@masahi Now all checks have passed.

**Pull request merged**
