### PR TITLE
[microTVM] Fix RPC session close on runtime side

### PR DESCRIPTION
**Pull request by mehrdadh**
Currently, the RPC session on C/C++ side does not know if the session was closed on python side which causes extra read/write on transport while the session is already closed. This PR reuses the hexagon approach in microTVM to shutdown the RPC session.

### CODE REVIEW

**Review by alanmacd — APPROVED** [review]

**Review by gromero — APPROVED** [review]
LGTM.

**Comment by gromero** [comment]
CI / Android failed. I'm re-triggering.

**Comment by gromero** [comment]
@tvm-bot rerun

**Comment by gromero** [comment]
@mehrdadh Thank you. The change is now merged.

**Pull request merged**
