### PR TITLE
[do not review] Test PR #11588

### PR DESCRIPTION
**Pull request by driazati**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by mehrdadh** [comment]
Please don't merge this since hexagon tests are skipped in the CI at the moment.

**Comment by mehrdadh** [comment]
@driazati can you rerun this since https://github.com/apache/tvm/pull/11613 is merged?

**Comment by quic-sanirudh** [comment]
> @driazati can you rerun this since #11613 is merged?

@driazati Can you try re-running this patch. I tried re-running #11588, but it did not build the new docker tag and instead it built the old one. If I try it locally, I'm able to both build hexagon docker with the new tag and run the hexagon ci tests.

**Comment by driazati** [comment]
(sorry was out yesterday so I missed these), rebased and pushed so it should have the new fix

**Comment by quic-sanirudh** [comment]
> (sorry was out yesterday so I missed these), rebased and pushed so it should have the new fix (Jenkins will only load the `Jenkinsfile` from certain trusted forked repositories which is why it didn't use the new Docker image for you, pushing to a branch in apache/tvm as the source for your PR would get around that)

@driazati Thanks a lot for the explanation and in helping verify my commit.

**Pull request closed without merging**
