### PR TITLE
[CodeGen][LLVM] Lower if_then_else() with select

### PR DESCRIPTION
**Pull request by wrongtest**
Hi, there. It seems better to use select directly for `if_then_else()` expr. Since `if_then_else()` is common in padding representation, it could hopefully save lots of cross-bb overheads.

My two remaining questions:
(1) Are there any places to test certain codegen features?
(2) Are there known llvm-based target which do not handle `select` instruction well?

### CODE REVIEW

**Comment by junrushao1994** [comment]
Quick question: in TIR, `T.Select` means both branches are executed no matter which value the conditional is evaluated to - which brings benefits that make it vectorizable in certain cases. However, if the conditional is a safeguard to avoid access out of buffer boundary, replacing it with `T.Select` will lead the program to crash. Therefore, I would love to learn if our implementation here in LLVM codegen will lead to the same effect? Thanks a lot!

**Comment by wrongtest** [comment]
> the conditional is a safeguard

Thanks for the reply! So is the `if_then_else`  also take short-circuit evaluation semantic like if stmt? If so I think my replacement is unsafe.  What about add a check like `SideEffect(e) <= kReadState`?

**Comment by wrongtest** [comment]
After some thinking, it seems to be better to make TIR transformation if_then_else() -> T.select if neccesary, thus do not complex the llvm codegen.

Thank you all the same! @junrushao1994

**Comment by junrushao1994** [comment]
@wrongtest Thank you so much for the discussion!

**Pull request closed without merging**
