### PR TITLE
[Codegen] Use "target.build.$TARGET_KIND" for all codegen functions.

### PR DESCRIPTION
**Pull request by Lunderberg**
Noticed while writing documentation that not all codegen functions
follow the same naming pattern.  Made changes below for consistency,
ease of locating a codegen function.

- Removed special case for "micro_dev" target.  Instead, register
  BuildCHost as both "target.build.c" and "target.build.micro_dev".

- Renamed "target.build.build.aocl_sw_emu" to
  "target.build.aocl_sw_emu".  Appears to be a typo introduced in
  #841725cc585

### CODE REVIEW

**Comment by Lunderberg** [comment]
@areusch On second thought, it looks like the special case for a `micro_dev` target should be removed rather than implemented elsewhere, since your commit 745e542e4deaf44f3d6e5665299aa85ef8f4a6b9 removed the `micro_dev` target entirely.  Is that correct?

**Comment by areusch** [comment]
@Lunderberg yeah `micro_dev` can go away now

**Comment by Lunderberg** [comment]
@areusch Awesome.  In that case, removing the special case for `micro_dev`, and removing lots of other references so that it doesn't trip people up in the future.

**Comment by Lunderberg** [comment]
Potential reviewers: @areusch @tqchen

**Review by areusch — APPROVED** [review]
thanks for cleaning this up, @Lunderberg !

**Comment by Lunderberg** [comment]
Thank you!  Rebased this morning to remove conflict with main, no other changes made from the approved version.

**Pull request merged**
