### PR TITLE
RelayViz interface and terminal ast-dump

### PR DESCRIPTION
**Pull request by chiwwang**
This PR follows https://github.com/apache/tvm/pull/8668, with splitting out interfaces class and terminal ast-dump implementation.

This visualizer is aimed for quick look-then-fix, so the interface is simple. Despite that, customization is still possible through implementing interfaces defined in `interface.py` or overriding existent implementations inside a renderer module, like `terminal.py`.

A tutorial is also provided in this PR.

A graphviz renderer will also be contributed after this PR.

### CODE REVIEW

**Comment by chiwwang** [comment]
Sure @masahi 
The error looks unrelated to the change. Let me merge mainline and check again.

**Comment by masahi** [comment]
Ok CI is good now... I need to take some time to understand the context of this PR and the implementation approach.

**Review by masahi — APPROVED** [review]
LGTM. Some people might not like the term "Parser", since parsing is usually associated with reconstructing AST from a textual description. I don't have a strong opinion. 

Looking forward to more fancy renderer.

**Review by echuraev — APPROVED** [review]
LGTM! Thank you for good PR and flexible and extensible interface.

**Pull request merged**
