### PR TITLE
Add metal to list of backends for TVMC

### PR DESCRIPTION
**Pull request by AndrewZhaoLuo**
Need this to test benchmarking for https://github.com/apache/tvm/pull/8069

### CODE REVIEW

**Comment by AndrewZhaoLuo** [comment]
@jwfromm

**Comment by AndrewZhaoLuo** [comment]
cc @elvin-n

**Review by leandron — COMMENTED** [review]
Hi @AndrewZhaoLuo is there any way to add a test case for metal?

In case it is too challenging, it is ok, we just wait for CI and merge it.

**Comment by AndrewZhaoLuo** [comment]
Does our CI even test metal backend?

**Review by echuraev — APPROVED** [review]
LGTM. But I agree with @leandron that it would be nice to have a test case for Metal. 

> Does our CI even test metal backend? Let me ask aroud

Maybe I'm mistaking (please, someone correct me if I'm wrong), but as far as I know, we don't run metal backend tests in our CI. And also unfortunately we have only few tests on Metal. But in case if such test will exist, we could run it locally and check that we didn't break something by some new changes.
Also, we are locally working on extending CI for validation on different Apple devices, so in the future this functionality might be added to tvm repository and such tests for Metal will be executed in the CI.

**Comment by leandron** [comment]
> LGTM. But I agree with @leandron that it would be nice to have a test case for Metal.
> 
> > Does our CI even test metal backend? Let me ask aroud
> 
> Maybe I'm mistaking (please, someone correct me if I'm wrong), but as far as I know, we don't run metal backend tests in our CI. And also unfortunately we have only few tests on Metal. But in case if such test will exist, we could run it locally and check that we didn't break something by some new changes.
> Also, we are locally working on extending CI for validation on different Apple devices, so in the future this functionality might be added to tvm repository and such tests for Metal will be executed in the CI.

Thanks for the clarification, that’s really helpful.

**Review by leandron — APPROVED** [review]

**Comment by leandron** [comment]
Thanks @echuraev @AndrewZhaoLuo!

**Pull request merged**
