### PR TITLE
Add tutorial index redirect

### PR DESCRIPTION
**Pull request by hogepodge**
Add a redirect for the old tutorial index.

### CODE REVIEW

**Comment by driazati** [comment]
Tested via #9534 with `python tests/scripts/ci.py docs --full --tutorial-pattern none`, the redirect successfully sends `<host>/tutorials` -> `<host>/tutorials/index.html`

**Comment by hogepodge** [comment]
@areusch another easy docs redirect fix

**Review by leandron — APPROVED** [review]
LGTM

**Comment by leandron** [comment]
Thanks @hogepodge @driazati, this is merged now!

**Pull request merged**
