### PR TITLE
[Relay/TOPI][ONNX/TFLite] Refactor MATRIX_SET_DIAG Operator for Relay…

### PR DESCRIPTION
**Pull request by shengxinhu**
Refactor MATRIX_SET_DIAG  operator in Relay/TOPI to support ONNX Trilu operator

### CODE REVIEW

**Comment by AndrewZhaoLuo** [comment]
Hmm this will eventually get merged, I might get to upgrading CI next week

**Comment by AndrewZhaoLuo** [comment]
Working on upgrading onnx right now https://github.com/apache/tvm/issues/9511

**Comment by shengxinhu** [comment]
wait for #9882

**Comment by masahi** [comment]
The new image with updated ONNX should become available by this week.

**Comment by AndrewZhaoLuo** [comment]
New CI image with updated onnx is (finally up)!

**Comment by AndrewZhaoLuo** [comment]
@shengxinhu do you still have interest in working to get this PR merged? If not then I can try to shepard this in new branch.

**Comment by shengxinhu** [comment]
> @shengxinhu do you still have interest in working to get this PR merged? If not then I can try to shepard this in new branch.

Thanks, please shepard it.

**Pull request closed without merging**
