### PR TITLE
[Op] Do not override specified layout in pooling

### PR DESCRIPTION
**Pull request by ghost**
…rt_op_layout.py

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by comaniac** [comment]
Also, please improve the PR title and description. Without a proper title and description, most people like me won't review the PR if I cannot immediately get the sense of its purpose when I'm not free.

**Comment by ccjoechou** [comment]
Sure, thanks for you feedback and I will do both as your comments have described.

FYI –
This is the first PR, which our ML compiler team in Marvell is providing. We are still improving our way to learn and to streamline how we can make contributions to the TVM community.
Later on we will provide other contributions – such as a BYOC from Marvell and etc.

Thanks,


  *   Joe

From: Cody Yu ***@***.***>
Sent: Thursday, October 14, 2021 11:25 AM
To: apache/tvm ***@***.***>
Cc: Joe Chou ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [apache/tvm] [bug] pooling convert layout bug in pooling.cc and in test_pass_conve… (see also issue #8848) (#9235)

External Email
________________________________

Also, please improve the PR title and description. Without a proper title and description, most people like me won't review the PR if I cannot immediately get the sense of its purpose when I'm not free.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_apache_tvm_pull_9235-23issuecomment-2D943609874&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=3LjogBLnHT6OKAPSDS2ag-ybvEkaulCDeHwiTGZ23OQ&s=OvHZ17y6EaSURuFumMnyNC1gaBa1QIEVteChT57iGFM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM636PHUOU5Z6Z7HYHXTXLLUG4N7FANCNFSM5FUWAG4A&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=3LjogBLnHT6OKAPSDS2ag-ybvEkaulCDeHwiTGZ23OQ&s=XLL6bo4iBuAGtCCyfuf0N6YsUVwOUSkY_NrXdVPfbAk&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=3LjogBLnHT6OKAPSDS2ag-ybvEkaulCDeHwiTGZ23OQ&s=NevdqOYoHnuWhZcdAW197V2pRphPd1nEqxjZB1HFkpw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=3LjogBLnHT6OKAPSDS2ag-ybvEkaulCDeHwiTGZ23OQ&s=vI6dYgJdNrcR6KhfMyxwSPHGDM1y5ZJtyPXB-Ai7f24&e=>.

**Comment by ccjoechou** [comment]
@comaniac, @vinx13, @masahi: I have pushed changes based on feedback. Latest changes are now utilizing a new out_layout field of pooling op (similar to what conv op has) so that, when out_layout is specified by user for pooling, pooling op will use and stick to the specified out_layout format.
Otherwise, the original infer layout will be used as originally.
4 new test cases have been added to the test_pass_convert_op_layout.py test suite to illustrate how to specify layout in pooling.

**Comment by comaniac** [comment]
Ah please rebase against to the latest commit. This PR shouldn't have 9k changes...

**Comment by ccjoechou** [comment]
I did use rebase on my side.
But for this time around because I did not know that, for upstreaming further changes, I have to advance my pull request’s base (main) to latest TVM github main again; therefore, the order of my git commands were not correct – leading to the merging situation.

Do you happen to have instructions (or sample links), which is for “github” pull request and allows to do rebase in order upstream new changes?
Can you share those links with us so that we can follow to avoid future git related troubles?
We have our own git server & GUI but different requirements are implemented over there; but, we want to follow TVM github git guidelines.

Thanks,


  *   Joe


From: Cody Yu ***@***.***>
Sent: Monday, October 18, 2021 7:50 PM
To: apache/tvm ***@***.***>
Cc: Joe Chou ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [apache/tvm] [Op] Do not override specified layout in pooling (#9235)

External Email
________________________________

Please use rebase instead of merge. We need to see the correct changes of this PR, and it cannot include the commits from other PRs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_apache_tvm_pull_9235-23issuecomment-2D946321611&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=cvYw2dlkGTNlnqbrVbxm_jJT-EVbz2hXQgh1XeV3fsI&s=-yW2Oqts6oW8PhsVqKlygMxGKQHZWfFSYb0ZvPbkONQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM636PGAEJEDSDXBTXACSH3UHTMGBANCNFSM5FUWAG4A&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=cvYw2dlkGTNlnqbrVbxm_jJT-EVbz2hXQgh1XeV3fsI&s=-jJkbT1vqONySNCUJQ5xWRymSYgJVvp8NNg8xUhTWow&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=cvYw2dlkGTNlnqbrVbxm_jJT-EVbz2hXQgh1XeV3fsI&s=I1dAssFokDD8qTL1IyLWBXLcPq0dglCw26sNYtyTeds&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=84zI-iH2xz28Q_xujSGbjYaq38CgcRgl_vGzCtF6TwQ&m=cvYw2dlkGTNlnqbrVbxm_jJT-EVbz2hXQgh1XeV3fsI&s=CE89y59UuMjK8HE8Ytf9bMy8FLbGK-KvUm3hZ2QeaH8&e=>.

**Pull request closed without merging**
