### PR TITLE
[BYOC] Update CUTLASS backend (SIMT support and codegen clean up)

### PR DESCRIPTION
**Pull request by masahi**
The CUTLASS backend in Relay BYOC has been heavily refactored this month in the `tlcpack/relax` repo (as part of Relax BYOC effort). This PR brings the same change to `apache/main` and also adds SIMT fp32 support. All tests in `test_cutlass.py` pass.

Original PRs
Codegen clean up: https://github.com/tlc-pack/relax/pull/442, https://github.com/tlc-pack/relax/pull/451
SIMT fp32 support: https://github.com/tlc-pack/relax/pull/448

@vinx13

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Thank you @masahi

**Comment by Mousius** [comment]
@tqchen as this isn't on the `unity` branch, could you allow others time to review in line with the code review guidelines?

**Comment by ekalda** [comment]
Did this PR pass CI? I thought the upstream CI is broken with an Android problem.

**Comment by tqchen** [comment]
In this case it is a positive change overall so I think merging would benefit the community. I have also reviewed and confirmed the related logics. Happy to followup with necessary steps if there are more comments.

The android CI breakage is not relevant to the particular change.

**Pull request merged**
