### PR TITLE
[ETHOSN] Support multiply conversion to depthwise

### PR DESCRIPTION
**Pull request by lhutton1**
Multiply can be supported when offloaded to the NPU by a conversion to a depthwise convolution operation. This is only supported when the multiply operation has a single single variable input with the other being a constant of shape [1, ..., C]. This commit adds a new pass "ConvertEquivalents" (name subject to change) to handle this conversion before codegen.

cc @NicolaLancellotti @leandron

### CODE REVIEW

**Review by NicolaLancellotti — APPROVED** [review]
LGTM!

**Comment by lhutton1** [comment]
@tvm-bot rerun

**Review by NicolaLancellotti — APPROVED** [review]

**Review by leandron — APPROVED** [review]
LGTM, thanks @lhutton1 @NicolaLancellotti!

**Comment by leandron** [comment]
@lhutton1 this now has a conflict, so when you have a moment and solve, I'm fine for this to be merged once CI is green again.

**Pull request merged**
