### PR TITLE
[COMMUNITY] @areusch -> PMC

### PR DESCRIPTION
**Pull request by zhiics**
Dear community,

Please join us to welcome @areusch as a new member of the PMC. Andrew has been actively leading and contributing to the design and/or implementation of several components of the project in the community, which at least includes:

* µTVM: rolled out the roadmap of standalone µTVM and organized the µTVM community meetings.

* runtime: AoT runtime and module-based module runtime interface.

* Object systems: proposed to use `Artifact` for better code loading, debugging, and management of codegen.

* CI, documentation, and refactoring of various modules in the system.

In addition, Andrew has been very actively participating the design discussion and sharing his ideas in the forum. He He has been also actively managing the PRs and issues.

* [Commits History ](https://github.com/apache/incubator-tvm/commits?author=aruesch)

* [Code Review](https://github.com/apache/incubator-tvm/issues?q=reviewed-by+%40areusch)

* [Community Forum Summary](https://discuss.tvm.apache.org/u/areusch/summary)

### CODE REVIEW

**Comment by gromero** [comment]
@areusch Cool! Congrats! :)

**Review by mbrookhart — APPROVED** [review]
Woohoo! Congrats Andrew!

**Review by junrushao1994 — APPROVED** [review]
Congrats! Well deserved!!

**Review by manupa-arm — APPROVED** [review]
Congrats!

**Review by jwfromm — APPROVED** [review]

**Comment by tmoreau89** [comment]
Congratulations @areusch, well deserved!!

**Review by tmoreau89 — APPROVED** [review]

**Comment by electriclilies** [comment]
Yay! Congrats Andrew!!

**Comment by leandron** [comment]
Congratulations @areusch !

**Comment by mehrdadh** [comment]
Congrats @areusch!!!

**Comment by shingjan** [comment]
Congrats! @areusch

**Pull request merged**
