### PR TITLE
[Fix] Tensor core type issue for dense

### PR DESCRIPTION
**Pull request by Laurawly**
As mentioned in PR #7146, previous tensor core code lacks type check and this PR is trying to fix that.
cc @jcf94 @merrymercy @Meteorix

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Comment by merrymercy** [comment]
Should we check `data.dtype == "float16" and weight.dtype == "float16"`?
The problem comes from this downcast  
https://github.com/apache/tvm/blob/c02c9c528f91f9be3967b7d9ef9f1847f533590b/python/tvm/topi/cuda/dense_tensorcore.py#L72-L73

**Comment by merrymercy** [comment]
Do we allow `data.dtype == "float32"`?
The problem comes from this downcast, which may cause accuracy problem.
https://github.com/apache/tvm/blob/c02c9c528f91f9be3967b7d9ef9f1847f533590b/python/tvm/topi/cuda/dense_tensorcore.py#L72-L73

**Comment by Laurawly** [comment]
> Do we allow `data.dtype == "float32"`?
> The problem comes from this downcast, which may cause accuracy problem.
> https://github.com/apache/tvm/blob/c02c9c528f91f9be3967b7d9ef9f1847f533590b/python/tvm/topi/cuda/dense_tensorcore.py#L72-L73

Good catch, just removed it.

**Pull request merged**
