### PR TITLE
Add missing shape functions for relay.nn operations

### PR DESCRIPTION
**Pull request by rijulg**
add a few missing shape functions. The change is motivated by the error 
>  Check failed: fshape_func.count(op) > 0 (0 vs. 0) : Internal error, cannot find ShapeFunc for nn.prelu

### CODE REVIEW

**Review by jcf94 — CHANGES_REQUESTED** [review]
Thanks! @rijulg
Let's add some tests on the `tests/python/relay/test_any.py`.

**Comment by rijulg** [comment]
> Thanks! @rijulg
> Let's add some tests on the `tests/python/relay/test_any.py`.

@jcf94 I have added a number of tests, please check if they are ok.

**Comment by junrushao1994** [comment]
@rijulg please fix the lint error. Thanks!

**Comment by rijulg** [comment]
> @rijulg please fix the lint error. Thanks!

Ah, I had forgotten how to access jenkins since my last contribution, hopefully errors will be resolved on the next build. Thanks for pointing it out.

**Review by jcf94 — APPROVED** [review]
Great! LGTM.

**Comment by rijulg** [comment]
@jcf94 I am not receiving the latest error on my local installation, and hence it's difficult for me to debug this. I suspect it might have something to do with the reduced dimension, but I am not sure. Can you please suggest some way to debug and fix the error?

**Comment by jcf94** [comment]
> @jcf94 I am not receiving the latest error on my local installation, and hence it's difficult for me to debug this. I suspect it might have something to do with the reduced dimension, but I am not sure. Can you please suggest some way to debug and fix the error?

The CI failed in `test_any_conv1d_transpose_ncw`.
You can try to run the `test_any.py` if you have cuda environment.

Seems the bug was caused by:
https://github.com/apache/tvm/blob/2c61afa4d1f67c6b41467e94868f6813feb89d6c/python/tvm/topi/cuda/conv1d_transpose_ncw.py#L145

We can correct it by:

```python
 cfg.define_split("tile_n", cfg.axis(n if isinstance(n, int) else 1), num_outputs=4) 
```

**Comment by jcf94** [comment]
Thanks! @rijulg

**Pull request merged**
