### PR TITLE
[Fix][Tutorial][VTA] Update tune_relay_vta.py to support single board

### PR DESCRIPTION
**Pull request by insop**
- support single pynq board run, change is credited to @i24361, https://github.com/i24361/incubator-tvm/blob/0472b1f347976229a29be8a6e60b626a0604c8df/vta/tutorials/autotvm/tune_relay_vta_with_one_board.py
- fixes the save fail
- issues and changes are discussed in https://discuss.tvm.apache.org/t/vta-workaround-for-autotuning-with-one-pynq-z1-board/8091/9

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by insop** [comment]
With this change on top of the latest TVM (28647f2e7a65146724b143098422229346b5db44), here is an example log

```
$ python vta/tutorials/autotvm/tune_relay_vta.py
Extract tasks...
...100%, 0.06 MB, 174 KB/s, 0 seconds passed
...100%, 0.73 MB, 1274 KB/s, 0 seconds passed
Extracted 10 conv2d tasks:
(1, 14, 14, 256, 512, 1, 1, 0, 0, 2, 2)
(1, 28, 28, 128, 256, 1, 1, 0, 0, 2, 2)
(1, 56, 56, 64, 128, 1, 1, 0, 0, 2, 2)
(1, 56, 56, 64, 64, 3, 3, 1, 1, 1, 1)
(1, 28, 28, 128, 128, 3, 3, 1, 1, 1, 1)
(1, 56, 56, 64, 128, 3, 3, 1, 1, 2, 2)
(1, 14, 14, 256, 256, 3, 3, 1, 1, 1, 1)
(1, 28, 28, 128, 256, 3, 3, 1, 1, 2, 2)
(1, 7, 7, 512, 512, 3, 3, 1, 1, 1, 1)
(1, 14, 14, 256, 512, 3, 3, 1, 1, 2, 2)
Tuning...
[Task  1/10]  Current/Best:   17.63/ 116.35 GFLOPS | Progress: (480/480) | 255.47 s Done.
[Task  2/10]  Current/Best:   19.43/ 137.07 GFLOPS | Progress: (576/576) | 291.50 s Done.
[Task  3/10]  Current/Best:    0.00/ 137.87 GFLOPS | Progress: (672/1000) | 365.49 s
```

**Comment by insop** [comment]
@tmoreau89

**Comment by insop** [comment]
I found the change that I picked was already in the PR by created a separate file.
- https://github.com/apache/tvm/pull/6688

**Comment by insop** [comment]
@i24361

**Review by tmoreau89 — APPROVED** [review]
Thank you for the fixes @insop and bringing this script up to date!

**Comment by tmoreau89** [comment]
The PR has been merged.

**Pull request merged**
