### PR TITLE
[WIP][TVM][.NET] Introduce TVM.NET project

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
This PR brings new feature into TVM:
    

- [x] Introduce C-sharp API binding to various existing TVM APIs(Currently limited to only Runtime, but future PRs will cover more.)
- [ ] Introduce TVM.NET a framework for easy integration of TVM runtime into .NET world. This includes integration and deployment(publishing packages).
- [ ] Sample APPs for start.

Development phase-0 is completed!

Please refer [RFC
](https://discuss.tvm.ai/t/introducing-tvm-net-for-bringing-tvm-features-into-net-world/6213)

Welcome for review!
Thanks you very much!

### CODE REVIEW

**Comment by tqchen** [comment]
please mark the PR as draft before it is ready for review to reduce the burden on the CI

**Comment by tqchen** [comment]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by ANSHUMAN87** [comment]
> https://github.blog/2019-02-14-introducing-draft-pull-requests/

@tqchen : Thanks for the suggestion! I missed it, but it seems that already raised PR cant be converted to Draft PR.  Please advise how to proceed, there are 2 ways i can handle it.
   1:> Keep local copy until skeleton is ready, then upload all the changes.
   2:> Close and reopen the PR as Draft.

Thanks!

**Comment by tqchen** [comment]
both sounds fine

**Comment by ANSHUMAN87** [comment]
> both sounds fine

@tqchen : As discussed earlier, i have not uploaded any changes yet to this PR. I think it will be better to setup CI for the Dotnet workspace first. So is it okay, if i upload another PR( a sample program)?
Which will have direct linking to TVM Runtime and a test module to check the execution on the ENV, with that we can setup CI first for a successful run, post that i can upload the working project.

Please provide your valuable opinion. Thanks!

**Comment by tqchen** [comment]
We can start code reviews and getting feedbacks from the community. Since we do want to hold a high standard for new languauge bindings, when we are getting close to merge, we will look into the CI issues. In the meanwhile, please write testcases and run them locally

**Comment by ANSHUMAN87** [comment]
> We can start code reviews and getting feedbacks from the community. Since we do want to hold a high standard for new languauge bindings, when we are getting close to merge, we will look into the CI issues. In the meanwhile, please write testcases and run them locally

@tqchen : Thanks for your feedback! I will start uploading my changes in this PR.

**Comment by ANSHUMAN87** [comment]
@tqchen : I believe phase-0 development is complete now!
Please help review! Thank you very much!

May be we can change the status of the PR now!

**Comment by ANSHUMAN87** [comment]
> @tqchen : I believe phase-0 development is complete now!
> Please help review! Thank you very much!
> 
> May be we can change the status of the PR now!

Gentle ping @tqchen !

**Comment by tqchen** [comment]
Language bindings are important features that we want to hold the highest standard as possible. So we do expect for longer review time, as well as more polishment.  

In a nutshell, what we want is not "an implement" of the feature we want. But to implement the feature in the best possible way so that it can be maintained, reused and developed in the future with minimum techinical debt.

I am not expert in csharp, but by quickly look at the package, I do think it needs mroe careful works to meet the standard of our current language binding. Here are some high level comments:

- Structure:  think about a common structure. Take a look at existing projects for example
   - e.g. mldotnet https://github.com/dotnet/machinelearning/tree/master/src
   - A possible structure for tvm could be `root/donet/src/`
   - I do not see any reason why we need a separate subfolder for each .cs file
   -  We should not include binaries: e.g. add_one.dll into the code repo.
   - There are additional files (Class1) which seems to be created from the the getting started guide but was not used here.
- Naming: I would try to follow other language binding naming convention as much as possible, in particular, the web, java and golang one are good references. e.g. UnmanagedRuntime
- Layers of abstractions: there are see many indirections and manager class(from manged to unmanaged), many of them seems to be un-necessary.  By convention, the FFI layer is un-managed, and all the wrappers on top are managed. Again, jvm runtime would be a good example to follow.
- Given that a language binding needs to be maintained and reviewed separately, we should get someone who is able to collaborate and review the codebase. Since reviewing is as time consuming as implementing the feature, so please try to polish as much as you can.
   - Ideally, we want to have as many vets on the API design as much as possible.

Given the current state, you could try release the package elsewhere and improve it before mainlining it back. Please also feel free to refer to other language bindings for reference.

**Comment by ANSHUMAN87** [comment]
@tqchen : Thank you very much for your enlightening response!
I will definitely work towards attaining similar code standard as per existing runtimes in TVM.

Please bear with me, if i misunderstood some of your comments. I have some queries to those as below:

1. **Folder structure:** You are right it has no significance. It is just a personal choice to me in organizing the files. The reference(mldotnet) you have suggested also follow similar organization of files. 
    But if you think otherwise is more suitable, we can keep all the source codes in one place or maintain Managed & Unmanaged separation similar to JVM runtime(Core & Native).

2. **Naming Convention:** Do you suggest the name change from UnmanagedRuntimeWrapper --> UnmanagedRuntime as an example ?
     
3. **Layers of abstractions:** You are right there is a very thin line boundary between Managed & Unmanaged space. Unmanaged space does not store any memory of its own in most of the cases, it is just an enabler or interface into TVM runtime. If you can provide one specific example which one you want to remove from Unmanged space, may be that might help me understand your comment more clearly.

4. **Package Release:** I am not sure how to release package elsewhere and pertain to same PR. Can you please help me  do it? May be some reference would be helpful.

Please help me clarify above queries.

Thank again!

**Comment by tqchen** [comment]
By packaging the result elsewhere, i mean just create a separate repo that build on top of tvm, once the package get used and starts to mature, then send another PR to the mainline.

**Comment by ANSHUMAN87** [comment]
@tqchen : Thanks a lot! I got your points clearly now!
Will reorganize code as suggested and improvise further!

**Comment by ANSHUMAN87** [comment]
@tqchen : Your review comments are handled now. Please check. Thanks!

**Comment by ANSHUMAN87** [comment]
@tqchen :  I think i have reworked on all your comments now. With the new string marshaling approach, i believe now it is more modular. Can you please take a look, and provide your valuable opinons, if any other improvements can be done. Thanks!

**Comment by tqchen** [comment]
Please be patient.  Careful code reveiws takes time and in many time sthey are as valuable, if not more valuable than the contribution itself.  One way to help review other PRs and get the reviewers to return in favor.

It would be useful to find another person who can co-author, review and further polish the PR, in terms of code-style and the overall implementation, since we need to keep a good maintaince of the language packages beyond a single person.

**Comment by jroesch** [comment]
@tqchen @ANSHUMAN87 I am doing triage, what is the status on this one?

**Comment by tqchen** [comment]
Given the stale state, let us close this for now

**Pull request closed without merging**
