### PR TITLE
Add AdaTune features

### PR DESCRIPTION
**Pull request by limenghao**
Add features in the paper (AdaTune: Adaptive Tensor Program Compilation Made Efficient).
Main changes:
1. In `./python/tvm/autotvm/measure/measure_methods.py`. Add an optional argument `enable_adaptive_evaluator` in the measure_option, when it is set as true, it will use the adaptive evaluator to do the evaluation.
2. Add RFEITuner and RFEICostModel in `tvm/autotvm/tuner/`. Add an optional argument `uncertainty_aware` in the ModelBasedTuner. When it is set true, it will use an dynamic epsilon to control the epsilon-greedy searching process.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @comaniac @cbalint13  @merrymercy @zxybazh @junru can you please help to review the PR?

@limenghao please sync the code with the latest main.

**Comment by comaniac** [comment]
@limenghao please also mark this PR as ready for review if all required changes are already committed.

**Comment by limenghao** [comment]
I changed its status now. It failed to pass some checks, in fact I am new to contributing this and not sure where is the syntax problem. And another question is the added RFEITuner needs extra package requirement of 'scipy', could you please help point out where to set it up properly? Thanks!

**Comment by zxybazh** [comment]
Hi, Menghao, it seems like you have some extra spaces in the end of line in python files. You could check out the required formatting result [here](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7021/4/pipeline). Also, the reason that the Windows build failed seems to be that you need to import `sklearn` instead of `scipy`. @junrushao1994 Do you think it feasible to add a dependency here?

**Comment by comaniac** [comment]
@limenghao we use `black` to format all Python code. Specifically, you can do auto-formatting as follows:
```
pip3 install black
black -l 100 <python file>
```
You can also follow @zxybazh's suggestion to fix the formatting by referring to the CI errors, tho.

For `scipy`, TVM already depends on `scipy`. See `python/gen_requirements.py` for detail (cc @areusch).

**Comment by areusch** [comment]
@comaniac @limenghao can you add any new requirements to python/gen_requirements.py? scipy is already present there, i'm not sure if you need scikit-learn based on skimming?

try not to set any version constraint in there, unless there is a functional reason why we could not upgrade.

**Comment by comaniac** [comment]
@limenghao could you clarify the above questions about using `scipy`?

**Comment by limenghao** [comment]
Sorry for the late reply. Both sklearn and scipy dependencies are required here. I've added the sklearn in the gen_requirements.py now, and the new commit is under checking now.

**Comment by limenghao** [comment]
@comaniac @junrushao1994 With the 'sklearn' added in the gen_requirement.py, the building still reports error in macOS side, do you know how to solve this? Thanks!

**Review by areusch — CHANGES_REQUESTED** [review]
hey @limenghao, can you please fix the line endings in this PR? it looks like you've got windows line endings as part of your PR, so many files appear as if they were entirely rewritten when in fact you've just changed a few lines.

https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

so far as the mac build goes--you will need to adjust the conda build environment in `conda/build-environment.yml` (we are still migrating to the new requirements system). I would like a few more core committers to comment on adding sklearn as a TVM dependency @tqchen @jroesch

**Comment by comaniac** [comment]
Yeah I also have concern of introducing new dependency and would like to hear from more opinions.
Meanwhile, @limenghao, would you please rebase the PR to let it ready for review? For example, this PR should not update submodule suc has `vta-hw`, and should not largely rewrite existing files such as `gen_requirements.py`.

**Comment by ANSHUMAN87** [comment]
@limenghao : Thanks for the PR! I liked the overall concepts explained in the paper "AdaTune: Adaptive Tensor Program Compilation Made Efficient". However when i tried to validate the efficiency improvement compared to base AutoTVM, unable to achieve the published results. I believe i am doing something different than the paper settings. Do you have any suggestion ?

**Comment by limenghao** [comment]
@ANSHUMAN87 Hi, thanks for trying this! Could you be more specific about your setting? The adaptive evaluator works in the occasion when the repeat/number of the measure_option is a big number (like 500), and according to our experiment results in the paper, the search efficiency outperforms than the base AutoTVM in the Transformer encoder tuning case.

**Comment by limenghao** [comment]
@areusch @comaniac I'd like to rebase the code and create another PR which only updates files that should be updated. As my codes might be based on a very older version of tvm. Thanks for your comments.

**Comment by ANSHUMAN87** [comment]
> @ANSHUMAN87 Hi, thanks for trying this! Could you be more specific about your setting? The adaptive evaluator works in the occasion when the repeat/number of the measure_option is a big number (like 500), and according to our experiment results in the paper, the search efficiency outperforms than the base AutoTVM in the Transformer encoder tuning case.
result.
Thanks @limenghao for your reply. Please find below the specific details:

Project: https://github.com/limenghao/AdaTune i was referring to this project while validating the output.

Environment Spec: 
GPU - GeForce RTX 2080 Ti (11 GB)
CPU - Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz

Command used: python3 tune.py --model_name squeezenet_v1.1 --use_gpu True --tuner ada

Tuning Log file : https://drive.google.com/file/d/1T1w_uUVi_gV7zEbge8hysdOt_9DrwL-v/view?usp=sharing

It was running even for complete 1 day, but  did not reach the published result. Please let me know, if anything i missed.
I know its not the right forum, if its okay with you, we can discuss offline as well.

**Comment by jroesch** [comment]
This PR appears to be out of date, please feel free to reopen it if this is not the case.

As part of the new year we are attempting to triage the project's open pull requests to ensure that code which
is ready for review and/or merging receives adequate attention.

Thanks again for your contribution, and feel free to reach out to discuss these changes.

**Pull request closed without merging**
