### PR TITLE
[Lint] Ignore Hexagon generated files in CPP lint

### PR DESCRIPTION
**Pull request by mehrdadh**
This PR adds exclude path to lint command for CPP files.

### CODE REVIEW

**Comment by mehrdadh** [comment]
cc @tkonolige

**Review by tkonolige — APPROVED** [review]
Thanks @mehrdadh. We can remove these checks when the generated files are built out of tree.

**Review by areusch — APPROVED** [review]
we should remove these generated files from the source tree, but given we already .gitignore them, i'm okay with this intermediate hack. let's add a follow-up issue to do this and merge.

**Comment by csullivan** [comment]
Many thanks @mehrdadh @tkonolige @areusch!

**Pull request merged**
