### PR TITLE
[release][v0.9] Remove VTA submodule

### PR DESCRIPTION
**Pull request by driazati**

### CODE REVIEW

**Comment by driazati** [comment]
failures look flaky, merging anyways

**Comment by hirohaku21** [comment]
@driazati @AndrewZhaoLuo 

Hi! I came back to use VTA, but I am confused about why you removed the VTA submodule. 
Did VTA have any critical issues? or temporary development?
Could you tell us any information, please? If you have some discussion article, please provide us.

**Comment by tqchen** [comment]
Thanks @hirohaku21 

VTA is still part of the apache tvm, we are removing it from the tvm release because it is being packaged separately as a separate artifact.

**Comment by hirohaku21** [comment]
@tqchen 
Thank you for your reply!
Ah~ I got it. You align release time between tvm and vta.
So,  [v0.8.0 branch](https://github.com/apache/tvm/tree/v0.8.0) is stable release for VTA and [recent main branch](https://github.com/apache/tvm/tree/20082614be85f14a7d6f4e653f2adcd89d0a3717) is developing release for VTA isn't it?

**Pull request merged**
