### PR TITLE
[Frontend][PaddlePaddle] Add test case for interpolate op convert func…

### PR DESCRIPTION
**Pull request by woobinw**
Add test case for interpolate op convert function #13247 

@heliqi 
@jiangjiajun 
cc @junrushao

### CODE REVIEW

**Review by heliqi — APPROVED** [review]
LGTM

**Review by jiangjiajun — APPROVED** [review]
LGTM

**Comment by junrushao** [comment]
would you like to fix the broken unittest so we could get it in?

**Review by junrushao — APPROVED** [review]
LGTM!

**Pull request merged**
