### PR TITLE
Remove CODEOWNERS

### PR DESCRIPTION
**Pull request by driazati**
See RFC: https://discuss.tvm.apache.org/t/rfc-remove-codeowners/12095

Vote thread: https://github.com/apache/tvm/issues/10471

### CODE REVIEW

**Comment by jroesch** [comment]
cc @driazati @tqchen would it better to disable this mechanism instead of removing/moving the file?

**Comment by Mousius** [comment]
Another option is to break down the various areas so a small change won't ping everyone? Currently it's very broad, and doing a bit of a folder structure clean up may help as the codebase has evolved a bit?

**Comment by driazati** [comment]
> cc @driazati @tqchen would it better to disable this mechanism instead of removing/moving the file?

That would be nice but AFAIK GitHub doesn't have any setting for it so we're stuck with something like this if we want to keep this information around



> Another option is to break down the various areas so a small change won't ping everyone? Currently it's very broad, and doing a bit of a folder structure clean up may help as the codebase has evolved a bit?

@Mousius sorry for the delay, but see the pre-RFC in https://discuss.tvm.apache.org/t/rfc-remove-codeowners/12095, it has a section on this

**Comment by driazati** [comment]
#10471 is closed in favor, this is ready to merge! @areusch

**Comment by driazati** [comment]
See followups in #10575

**Review by areusch — APPROVED** [review]

**Pull request merged**
