### PR TITLE
[FIX] Remove hexagon files built when hexagon is disabled

### PR DESCRIPTION
**Pull request by tkonolige**
This PR just removes the hexagon files from the default build.

Am I missing anything? Tests?

@areusch @kparzysz-quic

### CODE REVIEW

**Comment by kparzysz-quic** [comment]
You need to either delete or comment out everything in `tests/cpp/runtime/hexagon_buffer.cc`.

**Review by kparzysz-quic — APPROVED** [review]

**Comment by csullivan** [comment]
@adstraw's intention with adding these tests was to allow for unit testing of some of the C++ classes that would run pre-commit. Of course in production they run on Hexagon where custom logging is needed, but he has found it useful to have some of these unit tests running on x86 during commit time. If @adstraw prefers to keep these checks would it be acceptable to only enable custom logging when those sources are built for Hexagon? 
```
#if defined(__hexagon__)
#define TVM_LOG_CUSTOMIZE 1
#endif
```

**Comment by kparzysz-quic** [comment]
We should have this functionality tested in CI, but it should be done on Hexagon.  We should figure out how we can run these tests, or their equivalents on simulator.  The Hexagon docker has all the tools that are needed for that.

**Comment by tkonolige** [comment]
@csullivan 's solution seems to satisfy everyone's constraints here. It won't require setting global flags, and it will correctly disable log customization on regular targets. I'll submit a PR with it soon.

**Comment by tkonolige** [comment]
Close in favor of #10587

**Pull request closed without merging**
