### PR TITLE
[Relax][PyTorch] Support tensor manipulation and creation ops for ExportedProgram importer

### PR DESCRIPTION
**Pull request by mshr-h**
Part of #17346 

With this PR, I verified that the following torchvision models can be executed.
- convnext_tiny
- densenet121
- efficientnet_b0
- efficientnet_v2_s
- inception_v3
- maxvit_t
- mnasnet0_5
- mobilenet_v2
- mobilenet_v3_small
- regnet_x_400mf
- resnet18
- resnext50_32x4d
- shufflenet_v2_x0_5
- squeezenet1_0
- swin_t
- swin_v2_t
- vgg11
- vgg11_bn
- vit_b_32
- wide_resnet50_2

### CODE REVIEW

**Comment by mshr-h** [comment]
@tvm-bot rerun

**Review by tqchen — APPROVED** [review]

**Comment by mshr-h** [comment]
@tvm-bot rerun

**Comment by mshr-h** [comment]
Seems like the hexagon test is flaky. cc @tqchen

**Comment by tqchen** [comment]
looks like timeout, maybe we could move some of the integration tests to nightly

**Comment by tqchen** [comment]
@tvm-bot rerun

**Pull request merged**
