### PR TITLE
[Hexagon] Change single dma alloc buffers to be vtcm

### PR DESCRIPTION
**Pull request by nverke**
These need to be global.vtcm scope in order to properly test the single dma schedule. 

cc @adstraw

### CODE REVIEW

**Comment by junrushao** [comment]
Yep I tried it out and see tests failing :-(

**Comment by nverke** [comment]
Hmm which ones failed for you @junrushao?

**Comment by nverke** [comment]
@tvm-bot rerun

**Comment by junrushao** [comment]
The failing case is `test_loading_vtcm_for_vrmpy[1024-1]` in `TestAsyncDMAPipeline` in `test_hexagon/test_async_dma_pipeline.py`.

I spent some time last week looking into this testcase, and it turns out the the older parser cannot recognize `mem_scope="global.vtcm"` (because it's expecting `scope="global.vtcm"` as the input argument) and somehow silently falls back to using `scope="global"`.

**Review by junrushao — APPROVED** [review]
Thank you so much @nverke for following up!

**Pull request merged**
