### PR TITLE
[TOPI][Vulkan, Metal] Avoid passing int64 scalar arg to VK/Metal runtime

### PR DESCRIPTION
**Pull request by masahi**
I hit the error below when running TIR sort/scan on Vulkan backend:
https://github.com/apache/tvm/blob/1831c17998b29f3797f364410980809bfef554ca/src/runtime/pack_args.h#L186 

This is because unlike most other kernels, TIR sort/scan needs to pass an integer scalar from host to GPU, to realize multipass kernel launches:
https://github.com/apache/tvm/blob/1e0d3569b94f650243f4d0ac204d196e3be8b0aa/python/tvm/topi/cuda/sort.py#L203-L206

Currently, `width` argument, which is int64 scalar, is passed to GPU backend runtime. But VK/Metal runtime use the calling convention that is different from the one used in CUDA/OpenCL (search for `PackFuncNonBufferArg`) and VK/Metal runtime don't support passing 64 bit scalar, see:
https://github.com/apache/tvm/blob/1831c17998b29f3797f364410980809bfef554ca/src/runtime/pack_args.h#L41-L49

https://github.com/apache/tvm/blob/1831c17998b29f3797f364410980809bfef554ca/src/runtime/vulkan/vulkan.cc#L1047

The fix to this problem is simply to pass int32 scalar instead, and does cast to int64 inside GPU kernel. This enabled TIR scan tests to pass on Vulkan. It also fixed the runtime error that happened while running TIR sort, but the sort result is still not correct on Vulkan. I suspect there is an issue in our SPIR-V codegen.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks masa, perhaps it is a good time to revisit whether Vulkan metal could work with i64.

**Comment by masahi** [comment]
Does it make sense to use `vkCmdPushConstants` twice, one for 32 bit and another for 64 bit? If that is not possible, I think we need this patch for a workaround.

**Comment by masahi** [comment]
Maybe a more straightforward approach is to send a scalar as a buffer of size 1, just like CUDA/OpenCL backend does.

**Comment by tqchen** [comment]
I see, we can use this workaround for now. But can you please add ICHECKS so we error out when attempting to push a constant that goes beyond the limit?

**Comment by tqchen** [comment]
I take another look and it seems that both vulkan and metal(after metal 2.2) now support i64.

Perhaps we could update the ArgUnion solution of these APIs to allow pass 64 bit integer. For example

```c++
 union ArgUnion64 { 
   int32_t v_int32; 
   uint32_t v_uint32; 
   float v_float32;
   int64_t v_int64;
}'
```
On the device end, always create array of size two `int32_t v_int32[2]`, and read the value from the first element. This would require all arguments to be aligned to 64 bit, given not a lot of arguments are being passed in this way, we should be good.

@masahi do you mind to make that change and test out instead?

**Comment by masahi** [comment]
ok I'll try that

**Comment by tqchen** [comment]
The way device side works is through creating a struct.

say the original function is ```fn(int32 arg0, int64 arg1)```

We generate the following device code:

```
struct ArgBuffer {
   // always generate two int values to pad things to the same alignment
   int32 arg0[2];
   int64 arg1
};

fn (ArgBuffer* arg_buffer) {
   int32 arg0 = arg_buffer->arg0[0];
   int64 arg1 = arg_buffer->arg1;
}
```

**Comment by masahi** [comment]
https://github.com/apache/tvm/pull/7572

**Pull request closed without merging**
