### PR TITLE
Update ethos-u-vela for demo app

### PR DESCRIPTION
**Pull request by mbaret**
Update from ethos-u-vela 2.1.1 -> 3.2.0

### CODE REVIEW

**Comment by mbaret** [comment]
cc @manupa-arm @grant-arm @Mousius

**Review by leandron — APPROVED** [review]
LGTM

**Review by Mousius — APPROVED** [review]

**Review by manupa-arm — APPROVED** [review]
LGTM too! :)

**Comment by Mousius** [comment]
Thanks @mbaret !

**Pull request merged**
