### PR TITLE
[Community] @Lunderberg -> Reviewer

### PR DESCRIPTION
**Pull request by comaniac**
Please join us to welcome @Lunderberg as a new reviewer to TVM. Eric has contributed many important features to the Vulkan backends. He also helps improve TVM docker images, unit tests and documents to make the CI more efficient and reliable.

- [Commits History](https://github.com/apache/tvm/commits?author=Lunderberg )
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:Lunderberg )
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Lunderberg/summary)

### CODE REVIEW

**Comment by junrushao1994** [comment]
Congrats!!

**Comment by csullivan** [comment]
Congratulations! 👏

**Review by tmoreau89 — APPROVED** [review]
Congrats @Lunderberg !

**Comment by Lunderberg** [comment]
Thank you!

**Comment by leandron** [comment]
Well deserved, @Lunderberg!

**Pull request merged**
