### PR TITLE
[RFC]FamilySeer: A new search method for Auto-scheduler

### PR DESCRIPTION
**Pull request by noobotdj**
We write an Pre-RFC(https://discuss.tvm.apache.org/t/rfc-familyseer-a-new-search-method-for-auto-scheduler/11877 ) and waiting for comments from reviewers.

### CODE REVIEW

**Comment by junrushao1994** [comment]
CC: @zxybazh @comaniac @merrymercy

**Comment by comaniac** [comment]
Thanks for the RFC. Would you please file a formal RFC here: https://github.com/apache/tvm-rfcs along with the upstream plan? For example, you have some TODOs in this PR, so it would be good to have a formal RFC and tracking issue for the progress.

**Comment by noobotdj** [comment]
We

**Comment by noobotdj** [comment]
This PR is closed due to a rename branch problem.
Please refer to new PR (https://github.com/apache/tvm/pull/10308)

**Pull request closed without merging**
