### PR TITLE
[Relay][TFLite] Fix in qnn.conv2d when parameter groups not equal to 1

### PR DESCRIPTION
**Pull request by padreofthegame**
Bug observed in TFLite frontend when working with quantized conv2d operator with parameter groups != 1

### CODE REVIEW

**Comment by padreofthegame** [comment]
@tvm-bot rerun

**Comment by ekalda** [comment]
Thanks @padreofthegame for fixing this! Would you mind providing more detail in the commit message body as per our [commit message guideline](https://tvm.apache.org/docs/contribute/pull_request.html#commit-message-guideline), as in, what is the expected behaviour and what was happening before that bugfix?

**Comment by padreofthegame** [comment]
Hello @ekalda, thank you for the comment. 

I will try to explain my observations on this problem.

Basically, I was working with simple quantized tflite model with conv2D and bias_add layer, which was working fine with parameter `groups == 1`, but failing for example with `groups == 2` with error message:

```
TVMError: Traceback (most recent call last):
  12: TVMFuncCall
  11: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::{lambda(tvm::transform::Pass, tvm::IRModule)#7}>(tvm::transform::{lambda(tvm::transform::Pass, tvm::IRModule)#7}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  10: tvm::transform::Pass::operator()(tvm::IRModule) const
  9: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  8: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  7: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  6: tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  5: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::relay::transform::InferType()::{lambda(tvm::IRModule, tvm::transform::PassContext const&)#1}>(tvm::relay::transform::InferType()::{lambda(tvm::IRModule, tvm::transform::PassContext const&)#1})::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  4: tvm::relay::transform::InferType()::{lambda(tvm::IRModule, tvm::transform::PassContext const&)#1}::operator()(tvm::IRModule, tvm::transform::PassContext const&) const [clone .isra.0]
  3: tvm::DiagnosticContext::Render()
  2: tvm::DiagnosticRenderer::Render(tvm::DiagnosticContext const&)
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (tvm::DiagnosticContext)>::AssignTypedLambda<tvm::TerminalRenderer(std::ostream&)::{lambda(tvm::DiagnosticContext const&)#1}>(tvm::TerminalRenderer(std::ostream&)::{lambda(tvm::DiagnosticContext const&)#1})::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::ReportAt(tvm::DiagnosticContext const&, std::ostream&, tvm::Span const&, tvm::Diagnostic const&)
  File "/home/padre/TVM_full_repo/tvm/src/ir/diagnostic.cc", line 264
TVMError: The source maps are not populated for this module.` 
Please use `tvm.relay.transform.AnnotateSpans` `to attach source maps for error reporting.

Error: The Relay type checker is unable to show the following types match:
  Tensor[(16), float32]
  Tensor[(2), float32]
In particular:
  dimension 0 conflicts: 16 does not match 2.
```

While further testing I realized that problem occures every time when the parameter `groups` differ from 1 or depth of input tensor (should be equivalent to depth convolution). When looking deeper into the code I track that problem occurs in qnn/op/convolution.cc, specifically in the part 
```

	AssignType(types[5], DataType::Float(32), weight->shape[i_axis] * weight->shape[o_axis],
               reporter);  // weight_scale

```
Since the `types[5]` parameter corresponds to `kernel_scale`, and is a tensor of length `num_kernels`, `weight->shape[i_axis] * weight->shape[o_axis] `will generally differ from `num_kernels`, thus the error of tensor type matching will occur. 

In solution, I just added an additional if statement that will check if the convolution is depthwise (similar to the code in Conv2dRel), and kept the current workflow, while in other case the shape of `types[5]` will be set according to conv2d requirements.

**Comment by ekalda** [comment]
Thanks for the explanation, makes sense to me :) What I was asking was to amend the *commit message body* as I don't think "There was a bug" is particularly informative in the commit history and doesn't really comply with the commit message guidelines. Some version of what you wrote in the explaining comment (without the stack trace) would do :)

**Review by ekalda — APPROVED** [review]
LGTM!

**Comment by ekalda** [comment]
Thanks @padreofthegame!

**Pull request merged**
