### PR TITLE
Deploy the Pretrained Model on Jetson Nano 

### PR DESCRIPTION
**Pull request by BBuf**
The fork branch corresponding to PR 8878 was accidentally deleted and it can't be merged. This PR will solve the problem, please approve it again, thanks.

@Hzfengsy

### CODE REVIEW

**Comment by Hzfengsy** [comment]
It would be great if you can make the CI green

**Comment by Hzfengsy** [comment]
@BBuf Could you please update this PR? Then we can merge it quickly

**Comment by BBuf** [comment]
> @BBuf Could you please update this PR? Then we can merge it quickly

Ok, I will deal with it quickly.

**Comment by BBuf** [comment]
this pr has passed ci, please merge it. @Hzfengsy

**Review by Hzfengsy — APPROVED** [review]
LGTM. Thanks @BBuf

**Comment by twmht** [comment]
@BBuf 

Have you ever tried to use auto scheduler on jetson nano or xavier nx?

https://discuss.tvm.apache.org/t/compiled-model-from-auto-scheduler-on-jetson-is-pretty-slower-in-jetson-nx/15393

Do you have any idea about the above problem?

**Pull request merged**
