### PR TITLE
[BugFix] fix nvptx not supported by device_enabled error

### PR DESCRIPTION
**Pull request by ZQPei**
Fix Issue https://github.com/apache/tvm/issues/9513.

I think this bug was mistakenly introduced by https://github.com/apache/tvm/pull/8032.

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM. Thanks!

**Comment by ZQPei** [comment]
@junrushao1994 
I think thir pr needs further review, because another error occurs in ci https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9585/1/pipeline/267.

Quoted error is
> E             File "/workspace/src/target/llvm/codegen_nvptx.cc", line 146
E           TVMError: Do not support sync shared.dyn

This error is raised because of `shared.dyn` not supported by "nvptx" target.
And it was previously covered by `device_enabled("nvptx") returning False` in the last few months.

https://github.com/apache/tvm/blob/0a4cc89faf85c474df15bf3ba82ccac89e785fdc/tests/python/unittest/test_tir_ir_builder.py#L499-L552

I have tried to fix it by this commit https://github.com/apache/tvm/pull/9585/commits/a8d14b1890709df8fa3b20a40ea6ac3f54cfb060, and it works fine on my 2080ti gpu card.
But I am not sure if it is really OK.

**Review by vinx13 — APPROVED** [review]
The codegen fix looks good

**Comment by junrushao1994** [comment]
Yeah I think it's reasonable to handle dynamic shared memory this way for now

**Comment by junrushao1994** [comment]
Thank you so much for the fix! @ZQPei

**Pull request merged**
