### PR TITLE
[CI][Fix] Fixing lint

### PR DESCRIPTION
**Pull request by lhutton1**
A linting issue was introduced in #10423, fixing this up.

### CODE REVIEW

**Review by leandron — APPROVED** [review]
LGTM, thanks for the fix @lhutton1

**Comment by lhutton1** [comment]
Hit a flaky test mentioned in #10314, since this PR only fixes linting, I'll re-trigger with the "skip-ci" functionality.

**Comment by leandron** [comment]
> Hit a flaky test mentioned in #10314, since this PR only fixes linting, I'll re-trigger with the "skip-ci" functionality.

I reviewed the changes (given the `[skip ci]` usage) LGTM.

**Comment by leandron** [comment]
This is now merged, thanks @lhutton1 !

**Pull request merged**
