### PR TITLE
[Relay] Fix relay op strategy for cuda dense int8

### PR DESCRIPTION
**Pull request by huochaitiantang**
The topi schedule `dense_int8.cuda` uses dp4a, whose types are int8 * int8 = int32.

This PR could ensure that, the quantized dense ops can find the more efficient schedule `dense_int8.cuda`, instead of `dense_small_batch.cuda` or `dense_large_batch.cuda`.

### CODE REVIEW

**Review by icemelon9 — COMMENTED** [review]
Could you add a test case for dense uint8 in topi?

**Comment by huochaitiantang** [comment]
It seems that the schedule `dense_int8.cuda` does not support the `uint8` dtype, so I remove it. 
And I add an autotvm task extraction test case, which tests relay graphs that contain int8 dense op.

**Review by icemelon9 — APPROVED** [review]
LGTM

**Comment by icemelon9** [comment]
Thanks @huochaitiantang

**Pull request merged**
