### PR TITLE
[BYOC][NNAPI]: Add testing package to ci_cpu image

### PR DESCRIPTION
**Pull request by melsonlai**
This commit adds Android SDK to the ci_cpu image for supporting tests of Android NNAPI BYOC.

See also: 
+ [\[RFC\]\[BYOC\] Android NNAPI Integration](https://discuss.tvm.apache.org/t/rfc-byoc-android-nnapi-integration/9072)
+ PR #8076 

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by melsonlai** [comment]
cc @comaniac @zhiics

**Review by leandron — APPROVED** [review]
Hi @melsonlai, thanks for the PR.

LGTM.

**Review by comaniac — APPROVED** [review]
LGTM.
Link #7995 that is tracking CI updating. Also cc @areusch

**Comment by areusch** [comment]
hi all, i added some updates on #7995 to let you know where we are. given the complexity there, i'd prefer if we could keep this PR out of it and then we can update again after that. The CUDA issues encountered on 18.04 are making this container update more challenging than normal.

**Comment by comaniac** [comment]
Accordingly, we will put this PR on hold for now, and @areusch will merge it when the issues of updating container images are resolved.

**Comment by areusch** [comment]
@melsonlai @comaniac #7995 has landed, since the CI did not fail before, i'm unsure whether we should retest before merging?

**Comment by comaniac** [comment]
Sure we could do that. Please merge this PR when you are going to rebuild the container.

**Comment by mbrookhart** [comment]
Rebuilding containers this week.

Thanks @melsonlai @areusch @comaniac @leandron

**Comment by melsonlai** [comment]
Hi, had the `ci_cpu` container been updated? It's seems that Android SDK is still not there in the Jenkins pipeline.

**Comment by mbrookhart** [comment]
Still working on it :( We've hit lots of incompatible versions and typos in install scripts. See #8177 for details

**Pull request merged**
