### PR TITLE
[CI] Update GPU image for oneflow v0.7

### PR DESCRIPTION
**Pull request by masahi**
Update requested in https://github.com/apache/tvm/pull/11036

Validated in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/253/pipeline

cc @areusch @driazati @BBuf

### CODE REVIEW

**Review by BBuf — APPROVED** [review]

**Comment by BBuf** [comment]
@masahi this pr can be merged!

**Comment by masahi** [comment]
> @masahi this pr can be merged!

We need somebody else's approval cc @leandron @Mousius

**Review by leandron — APPROVED** [review]
LGTM, thanks!

**Comment by leandron** [comment]
Merged now, thanks @masahi!

**Pull request merged**
