### PR TITLE
[CI] Rev ci-cpu to v0.76

### PR DESCRIPTION
**Pull request by leandron**
* This includes changes up to commit 1a95f9bd0.
* Tracking issue is https://github.com/apache/tvm/issues/8782

**Important: there is some ongoing pre-work being done by @jroesch before this can be safely merged, so, in doubt, don't merge it.**

cc @jroesch @areusch @grant-arm

### CODE REVIEW

**Comment by jroesch** [comment]
@leandron this hasn't actually tested that the image works on master, we need to wait on a `ci-staging` push before merging correct?

**Comment by jroesch** [comment]
After this goes green you should be gtg: https://github.com/apache/tvm/tree/ci-docker-staging

**Review by jroesch — APPROVED** [review]
For anyone reading this doesn't click the merge button until the above PR is green.

**Comment by leandron** [comment]
This was tested in this previous job: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/146/pipeline

Is the job wrong somehow? Asking so I can do it correctly next time.

**Comment by areusch** [comment]
ah--just clarifying for @jroesch. 

Jared, it's not generally true right now that the nightly build pipeline will run the built docker images through CI. @leandron is working on that.

However in this case, it appears that he has used ci-docker-staging already to test these containers, since he is a committer. You can verify that in fact he did test these images by looking at the revision in Jenkins: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/146/pipeline/52

For instance here, you can see he tested `tlcpackstaging/ci_cpu:20210815-225913-1a95f9bd0`. So that image is good to go.

In this case, his test also doubled as a test of the docker image override mechanism he built to run these tests nightly.

A slight aside: Please don't update ci-qemu. I am sabotaging our system--I rebuilt that one manually last night and not sure if the new build has not picked up the changes that are already submitted as part of ci-qemu:v0.08.

**Comment by jroesch** [comment]
@areusch ok cool, sorry for misunderstanding here @leandron. Can we add a check box or whatever as part of the process until its fully automated so I can figure out if we need to trigger another build?

**Comment by leandron** [comment]
No worries @jroesch! I hope soon we’ll be ina position to automatically validate the images as well, and the process will be simplified a lot!

I’ll merge this now, as CI is green and this is now ready to go.

Thanks @jroesch and @areusch!

**Pull request merged**
