### PR TITLE
[Unity][nn.module] Rolling KVCache override method

### PR DESCRIPTION
**Pull request by davidpissarra**
Part of the effort in bringing Mistral to the compilation flow with nn.Module on [mlc-llm](https://github.com/mlc-ai/mlc-llm). Adding support for Rolling KVCache override method in the nn.module frontend.

cc @CharlieFRuan

### CODE REVIEW

**Comment by tqchen** [comment]
cc @junrushao @cyx-6

**Comment by junrushao** [comment]
I think we should move all KVCache logic to MLC LLM instead, given we expect plenty of variants of KVCache implementation. @tqchen @davidpissarra what do you guys think?

**Comment by tqchen** [comment]
Yes, i think moving to mlc is OK, we can move back if there is a point of stablization.

**Comment by davidpissarra** [comment]
> I think we should move all KVCache logic to MLC LLM instead, given we expect plenty of variants of KVCache implementation. @tqchen @davidpissarra what do you guys think?

Thanks @junrushao! Makes sense to move KVCache to MLC LLM

**Pull request closed without merging**
