### PR TITLE
[DOC] Improve "Getting Started with TVM" tutorials and fix warnings

### PR DESCRIPTION
**Pull request by merrymercy**
- Improves the "Getting Started with TVM" series tutorials
    - Fix some errors in the [introduction tutorial](https://tvm.apache.org/docs/tutorials/get_started/introduction.html#sphx-glr-tutorials-get-started-introduction-py), which do not accurately describe TOPI or auto-scheduler.
   - Fix broken links.
- Fix other warnings during building the doc.

### CODE REVIEW

**Comment by merrymercy** [comment]
cc @comaniac @hogepodge @junrushao1994

**Review by jcf94 — APPROVED** [review]

**Comment by hogepodge** [comment]
Thank you!

**Review by comaniac — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
Thanks @merrymercy @jcf94 @hogepodge

**Pull request merged**
