### PR TITLE
[Bugfix] Shape inference of weight for grouped `nn.conv3d`

### LINKED ISSUE #11664: [Bug] Weight shape inferred for `nn.conv3d` is wrong when `kernel_size` and `channels` are both provided
### Expected behavior

The following Relay source program should be successfully parsed:

```
#[version = "0.0.5"]
def @main(%x: Tensor[(1, 4, 8, 8, 8), float32], %w: Tensor[(2, 2, 1, 1, 1), float32]) {
    nn.conv3d(%x, %w, kernel_size=[1, 1, 1], channels=2, groups=2)
}
```

Here is the explanation: 4 input channels are divided into 2 groups, with each group taking 2 channels as input. Each group produces 1 output channel. Therefore, there are 2 * 1 = 2 output channels in total. 

### Actual behavior

The Relay type checker reports a type mismatch:

```
error: The Relay type checker is unable to show the following types match:
  Tensor[(4, 0, 1, 1, 1), float32]
  Tensor[(2, 2, 1, 1, 1), float32]
In particular:
  dimension 0 conflicts: 4 does not match 2.  dimension 1 conflicts: 0 does not match 2.
 --> from_string:4:5
   |  
 4 |      nn.conv3d(%x, %w, kernel_size=[1, 1, 1], channels=2, groups=2)
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: The Relay type checker is unable to show the following types match.
In particular `Tensor[(2, 2, 1, 1, 1), float32]` does not match `Tensor[(4, 0, 1, 1, 1), float32]`
 --> from_string:4:5
   |  
 4 |      nn.conv3d(%x, %w, kernel_size=[1, 1, 1], channels=2, groups=2)
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/Users/wzh/tvm-bug/bug_conv3d_kernel_size.py", line 12, in <module>
    mod = parser.parse(src)
  File "/Users/wzh/tvm-dev/python/tvm/parser/__init__.py", line 32, in parse
    return _ffi_api.ParseModuleInContext(source_name, source, init_module, init_meta_table)
  File "/Users/wzh/tvm-dev/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm.error.DiagnosticError: Traceback (most recent call last):
  [bt] (8) 9   libtvm.dylib                        0x0000000118057102 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<void tvm::runtime::TypedPackedFunc<tvm::IRModule (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tvm::runtime::Optional<tvm::IRModule> const&, tvm::runtime::Map<tvm::runtime::String, tvm::runtime::Array<tvm::runtime::ObjectRef, void>, void, void> const&)>::AssignTypedLambda<tvm::parser::$_2>(tvm::parser::$_2, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::'lambda'(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 1090
  [bt] (7) 8   libtvm.dylib                        0x0000000118023d79 tvm::parser::ParseModule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tvm::runtime::Optional<tvm::IRModule> const&, tvm::runtime::Map<tvm::runtime::String, tvm::runtime::Array<tvm::runtime::ObjectRef, void>, void, void> const&) + 425
  [bt] (6) 7   libtvm.dylib                        0x0000000117e892f4 tvm::transform::Pass::operator()(tvm::IRModule) const + 148
  [bt] (5) 6   libtvm.dylib                        0x0000000117e89701 tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const + 753
  [bt] (4) 5   libtvm.dylib                        0x0000000117e8a203 tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const + 819
  [bt] (3) 4   libtvm.dylib                        0x00000001191aa0d5 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<void tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::relay::transform::InferType()::$_2>(tvm::relay::transform::InferType()::$_2)::'lambda'(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 2053
  [bt] (2) 3   libtvm.dylib                        0x0000000117e0da1b tvm::DiagnosticContext::Render() + 459
  [bt] (1) 2   libtvm.dylib                        0x0000000117b2bd29 tvm::runtime::detail::LogFatal::Entry::Finalize() + 89
  [bt] (0) 1   libtvm.dylib                        0x000000011952da28 tvm::runtime::Backtrace() + 24
  File "/Users/wzh/tvm-dev/src/ir/diagnostic.cc", line 105
DiagnosticError: one or more error diagnostics were emitted, please check diagnostic render for output.
```

### Environment

macOS 12.4. Compiled using Clang 13.1.6 with LLVM support. TVM commit [`df4f4c0b4`](https://github.com/apache/tvm/commit/df4f4c0b4bccd775af25967fdf057392c1a2826e). 

### Steps to reproduce

```python
from tvm import parser

src = """
#[version = "0.0.5"]
def @main(%x: Tensor[(1, 4, 8, 8, 8), float32], %w: Tensor[(2, 2, 1, 1, 1), float32]) {
    nn.conv3d(%x, %w, kernel_size=[1, 1, 1], channels=2, groups=2)
}
"""

mod = parser.parse(src)
```

### Possible fix

https://github.com/apache/tvm/blob/df4f4c0b4bccd775af25967fdf057392c1a2826e/src/relay/op/nn/convolution.cc#L444-L451

The condition of this if statement seems to be incorrect. `channels == groups && channels != 1` does not necessarily mean that the convolution is depthwise. The test case shown above is a counterexample. 

A possible fix is to remove this if statement and only keeps the assignment to `wshape` in else branch, since this assignment already covers the case of depthwise convolution.

### PR DESCRIPTION
**Pull request by wzh99**
This PR fixes #11664 according to the proposal in that issue. A test case is added as requested by @ganler.

### CODE REVIEW

**Comment by ganler** [comment]
Hi @masahi could you help enable the CI? Thanks!

**Comment by ganler** [comment]
Thanks @wzh99! Can you further confirm that the new test will fail before the fix commit?

**Comment by wzh99** [comment]
> Thanks @wzh99! Can you further confirm that the new test will fail before the fix commit?

I revert the commit but keep the new test in my local repository. The new test in test_topi_conv3d_ncdhw.py does not fail before the commit. It seems that TOPI can handle this case correctly. The bug I reported in #11664 is only concerned with type inference in Relay but not TOPI. Perhaps we need to add a test case in `test_conv3d_infer_type` of test_op_level2.py if we need to test type inference.

**Comment by wzh99** [comment]
> Thanks @wzh99! Can you further confirm that the new test will fail before the fix commit?

I revert the commit but keep the new test in my local repository. The new test in test_topi_conv3d_ncdhw.py does not fail before the commit. It seems that TOPI can handle this case correctly. The bug I reported in #11664 is only concerned with type inference in Relay but not TOPI. Perhaps we need to add a test case in `test_conv3d_infer_type` of test_op_level2.py if we need to test type inference.

**Comment by ganler** [comment]
@wzh99 Thanks for digging into the issue. Then I think a proper place to put this unit test can be: https://github.com/apache/tvm/blob/main/tests/python/relay/test_type_infer.py

The test can be something like:

```python
def test_conv3d_type_infer():
    x = relay.var("x", shape=(1, 4, 8, 8, 8), dtype="float32")
    out = relay.nn.conv3d(
        x,
        relay.var("weight", shape=(2, 2, 1, 1, 1), dtype="float32"),
        groups=2,
        channels=2,
        kernel_size=[1, 1, 1],
    )

    mod = tvm.IRModule.from_expr(out)
    mod = transform.InferType()(mod)
    tvm.ir.assert_structural_equal(
        mod["main"].body.checked_type, 
        relay.TensorType((...), "float32") # The correct output shape
    )
```

**Comment by wzh99** [comment]
@ganler Thanks for your suggestion. However, I am sorry that I cannot completely agree that this test should be placed in [test_type_infer.py](https://github.com/apache/tvm/blob/main/tests/python/relay/test_type_infer.py). The reason is that the tests in this file are concerned with the language features of Relay itself (tuple, ref, let-binding, ADT, etc.) There are some test cases about operators such as `test_add_broadcast_op`, but I think they are mainly used to test whether the type inference in Relay can support different forms of type relations, instead of whether the type relations of a specific operator is correct. 

I still think that the test case should be placed in [test_op_level2.py](https://github.com/apache/tvm/blob/main/tests/python/relay/test_op_level2.py), because this is the place for testing specific type relations of `nn.conv3d`. I can add the following lines at the end of `test_conv3d_infer_type`:

```
# Infer with groups
x = relay.var("x", relay.TensorType((1, 16, 224, 224, 224), "float32"))
w = relay.var("w", relay.TensorType((4, 4, 1, 1, 1), "float32"))
y = relay.nn.conv3d(x, w, groups=4, kernel_size=(1, 1, 1), channels=4)
yy = run_infer_type(y)
assert yy.checked_type == relay.TensorType((1, 4, 224, 224, 224), "float32")
```

I am new to contributing to TVM and my understanding may not be thorough enough. Please point out if I make any mistakes.

**Comment by ganler** [comment]
@wzh99  I think what you said makes sense as tests in `test_op_level2.py` shares the similar patterns. Previously I suggest `test_type_infer` as I found the bug-introducing point is in the type inference pass.

**Comment by wzh99** [comment]
@ganler I have added the test case in [test_op_level2.py](https://github.com/apache/tvm/blob/main/tests/python/relay/test_op_level2.py). Before the fix is committed, the test fails. As the error message emitted by pytest is long, I only show the part from Relay type inference:
```
The Relay type checker is unable to show the following types match:
  Tensor[(16, 0, 1, 1, 1), float32]
  Tensor[(4, 4, 1, 1, 1), float32]
In particular:
  dimension 0 conflicts: 16 does not match 4.  dimension 1 conflicts: 0 does not match 4.
The Relay type checker is unable to show the following types match.
In particular `Tensor[(4, 4, 1, 1, 1), float32]` does not match `Tensor[(16, 0, 1, 1, 1), float32]`
```
After the commit fix, this test is passed.

**Review by ganler — APPROVED** [review]
LGTM. Thanks for the contribution! @masahi Could you also help take a look?

**Review by masahi — APPROVED** [review]

**Pull request merged**
