### PR TITLE
[TVMScript] Improvements tvm.script.highlight

### PR DESCRIPTION
**Pull request by Lunderberg**
- Automatically use "black" formatter if available.

- Allow overrides of pygmentize style based on environment variable `TVM_PYGMENTIZE_STYLE`.

### CODE REVIEW

**Comment by Lunderberg** [comment]
This PR started from finding that the `dracula` style shows up best in my terminal, and wanted to have a way to enable it as the default pygmentize for my environment.

**Comment by junrushao** [comment]
Using black is format is a great idea! On the other hand, sometimes we want to toggle it off for huge IRs, for example, the winograd TIR has two extremely long lines which we dont really need to read much into: https://gist.github.com/zxybazh/0019023b0796a55c9fadb12593852f84. Would love to get some thoughts from you which one is better: formatting by default or not?

**Comment by Lunderberg** [comment]
Oof, yeah, looks like that one becomes pretty heavily indented with `black`, with several sections starting at indentations around line 60-80.  It looks like it is specifically the nested function calls (here the chain of `T.select`), each of which adds indentation.

I think I'd still lean toward having the formatting enabled by default, since I think it improves readability on average, but it would be good to have a way to disable it when debugging cases where the readability is worsened.  Maybe having the argument default be set by an environment variable, so that the formatting could be enabled/disabled across all calls as needed.

**Comment by Lunderberg** [comment]
Hmm, I'm also wondering on the representation of `T.select`.  Both it and `T.if_then_else` are useful to use in nested chains, which are what causes the poor formatting.  If a nested sequence of `N` select/if_then_else were sugared as a sequence of `2*N + 1` arguments, we could avoid having a lot of the structures that get poorly formatted.  So the winograd TIR example, line 37 would be formatted into ~40 flat lines, instead of the ~80 heavily indented lines that it currently formats into.

```python
B[i, j] = T.Select(
    i % 4 == 3 and j % 4 == 3,
    T.float32(1),
    i % 4 == 3 and j % 4 == 2,
    T.float32(0),
    i % 4 == 3 and j % 4 == 1,
    T.float32(0),
    i % 4 == 3 and j % 4 == 0,
    T.float32(0),
    i % 4 == 2 and j % 4 == 3,
    T.float32(0),
    i % 4 == 2 and j % 4 == 2,
    T.float32(1),
    i % 4 == 2 and j % 4 == 1,
    T.float32(1),
    i % 4 == 2 and j % 4 == 0,
    T.float32(-1),
    i % 4 == 1 and j % 4 == 3,
    T.float32(-1),
    i % 4 == 1 and j % 4 == 2,
    T.float32(1),
    i % 4 == 1 and j % 4 == 1,
    T.float32(-1),
    i % 4 == 1 and j % 4 == 0,
    T.float32(0),
    i % 4 == 0 and j % 4 == 3,
    T.float32(0),
    i % 4 == 0 and j % 4 == 2,
    T.float32(0),
    i % 4 == 0 and j % 4 == 1,
    T.float32(0),
    i % 4 == 0 and j % 4 == 0,
    T.float32(1),
    T.float32(0),
)
```

**Comment by junrushao** [comment]
Some background: The reason that winograd conv2d has such a long chained `T.Select` is that it's used to represent A, B, G matrices, and by unrolling the corresponding loops in our scheduling, the `T.Select` is constant-folded into scalar constants. Therefore there is no performance degradation if scheduled properly.

On sugaring long chained `T.Select`: The usecases of sugaring `T.Select`, if it's only limited to constant matrices in winograd conv, then it's probably less common and I would say it may not be desirable because it requires users to understand a new syntax. 

My two-cents: as long as we have a flag to turn it off, in `.show()` methods, I don't have a strong opinion if it defaults to on or off :-)  Alternatively, when the IR is much longer (e.g. +20 extra lines after formatting), we could print out a doc, saying you may turn formatting off by tweaking the flag, etc.

**Comment by Lunderberg** [comment]
Good point on the `T.Select` optimizing out during unrolling, so it wouldn't be something with semantic meaning early on.  That makes sense on having the flag to disable it the formatting.  Looks like I initially added `black_format=True` as an argument to `cprint`, but not to the methods that call into it.  All the `obj.show()` methods now also have a `black_format=True` argument.

**Review by junrushao — APPROVED** [review]
LGTM!

**Pull request merged**
