### PR TITLE
[Runtime] Compatibility with dmlc::Stream API changes

### PR DESCRIPTION
**Pull request by Lunderberg**
This commit updates TVM implementations of `dmlc::Stream`.  With https://github.com/dmlc/dmlc-core/pull/686, this API now requires the `Write` method to return the number of bytes written.  This change allows partial writes to be correctly handled.

### CODE REVIEW

**Comment by Lunderberg** [comment]
This PR is marked as a draft, until the upstream dmlc changes land.  At that point, this PR will be updated to also include a version bump for `3rdparty/dmlc-core`.

**Comment by Lunderberg** [comment]
Upstream `dmlc-core` changes have landed, and this PR updates the submodule version to include the changes.

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by Lunderberg** [comment]
@tvm-bot rerun

(Rerunning to use CI fix from https://github.com/apache/tvm/pull/17040.)

**Review by tqchen — APPROVED** [review]

**Pull request merged**
