### PR TITLE
[Relax] Require correct input/output shapes `R.call_tir`

### PR DESCRIPTION
**Pull request by Lunderberg**
Prior to this commit, the Relax well-formed checker validated arguments provided to Relax functions, but did not validate arguments provided to `R.call_tir`.  As a result, incorrect arguments from Relax to TIR would not be checked until runtime, if at all.

This commit updates the well-formed checker to verify that `R.call_tir` has received the correct arguments, and has the correct output shape specified in the `out_sinfo` parameter.

### CODE REVIEW

**Comment by Lunderberg** [comment]
The implementation in this PR is similar to https://github.com/apache/tvm/pull/17216, but with a few key changes:

* Unlike #17216, this PR raises an error from the well-formed checker if the shape or dtype of `R.call_tir` arguments mismatch.
* Unlike #17216, this PR still requires a user to explicitly provide the `out_sinfo` argument to `R.call_tir`.

**Comment by Lunderberg** [comment]
All CI tests are passing, with the exception of the `CI / Windows` step, which has the same failures as seen across all PRs (currently being debugged in https://github.com/apache/tvm/pull/17283).  Since the `CI / Windows` is not a required step, this PR is ready for review/merge.

**Comment by Lunderberg** [comment]
@tvm-bot rerun

**Review by tqchen — APPROVED** [review]

**Comment by Lunderberg** [comment]
Looks like the failure on `hexagon/pr-head` is due to a timeout, not an error introduced in this PR.  Of the 8 shards that run Hexagon unit tests, 7 of them finish in about 1h20m.  The 8th node looks like it's being killed after 2 hours, and spends about 50 minutes running `tests/python/contrib/test_hexagon/test_run_unit_tests.py::test_run_unit_tests[]`.

https://github.com/apache/tvm/pull/17334 should resolve the hexagon CI issues by breaking up the single gigantic test, allowing them to be sharded out.

**Comment by Lunderberg** [comment]
@tvm-bot rerun

Since #17334 has landed, the hexagon tests should be better spread out across the 8 shards.

**Pull request merged**
