### PR TITLE
[Tutorial] Fix formatting, grammar, dead link

### PR DESCRIPTION
**Pull request by mkroening**
This fixes a few issues (formatting, dead links, grammar), I encountered when reading the tutorial.

@hogepodge, could you review this?

### CODE REVIEW

**Comment by hogepodge** [comment]
One more comment, if the target link doesn't have a reference tag as shown above, it should be added. Any name that doesn't collide with another tag should work. If you need me to build the docs and check once the patch is up, I'd be happy to help out with that.

**Comment by mkroening** [comment]
I pushed three more commits, the last of which adopts sphinx references.

@hogepodge, it would be great if you could build and check if it works.

**Comment by hogepodge** [comment]
Probably easier to compare from this PR: https://github.com/apache/tvm/pull/9314

**Comment by mkroening** [comment]
@hogepodge, I subtracted #9314 from this PR.

**Comment by mkroening** [comment]
Another spurious error, trying again.

**Pull request merged**
