### PR TITLE
Revert "[SLM] Allow modules to define pre-processing of weights"

### PR DESCRIPTION
**Pull request by tqchen**
Reverts apache/tvm#16757

### CODE REVIEW

**Comment by Lunderberg** [comment]
@tqchen Can you add a unit test demonstrating the behavior to be retained?  Is it only for the string names of symbolic variables, as mentioned in [this comment](https://github.com/apache/tvm/pull/16757#discussion_r1536871492)?

**Comment by tqchen** [comment]
Likely i think it would be primarily two parameters with same `vocab_size` as the dynamic shape.

**Comment by tqchen** [comment]
Happy to also test followup redos of the PR in case we miss other cases

**Comment by MasterJH5574** [comment]
I replied with a test to the other PR before noticing the on-going thread here. https://github.com/apache/tvm/pull/16757#discussion_r1536887971

@tqchen so could you help pasting it into `test_frontend_nn_modules.py`? Then we don't need a separate PR for the test.

**Review by MasterJH5574 — APPROVED** [review]

**Comment by MasterJH5574** [comment]
Merged without the unit test to keep the reversion standalone. Let's add the test case separately. Thank you folks!

**Comment by Lunderberg** [comment]
I have a parametrized version of the test case, along with testing for cases beyond `nn.Linear`, that I'll open as a PR.

**Pull request merged**
