### PR TITLE
[CMSIS-NN] Increase partitioning accuracy for pooling

### PR DESCRIPTION
**Pull request by Mousius**
This ensures that CMSIS-NN is only used when the batch size and layout are correct for the library calls.

### CODE REVIEW

**Comment by leandron** [comment]
cc @ashutosh-arm @grant-arm

**Review by ashutosh-arm — APPROVED** [review]
Thanks @Mousius. Looks good to me. Tagging the issue here: https://discuss.tvm.apache.org/t/cmsis-nn-qnn-max-pool2d-layout-on-cortex-m7-without-npu/12712.

**Review by lhutton1 — APPROVED** [review]
LGTM!

**Comment by lhutton1** [comment]
Thanks @Mousius, @ashutosh-arm, @leandron!

**Pull request merged**
