### PR TITLE
[Unity][Dlight] Add reduction rules

### PR DESCRIPTION
**Pull request by junrushao**
This PR adds a dlight rule that effectively allows fusing all reduction and spatial blocks together and executed within a single GPU kernel. This is meant to schedule softmax, layer norm, RMS norm, etc.

### CODE REVIEW

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
Flaky marked in https://github.com/apache/tvm/issues/15158, maybe we can just fix it along the way

**Comment by junrushao** [comment]
Retriggered

**Comment by tqchen** [comment]
Let us fix the flaky if possible, seems a matter of increase atol and rtol there

**Pull request merged**
