### PR TITLE
Update ICHECK error message with link to documentation page.

### PR DESCRIPTION
**Pull request by mdw-octoml**
This PR updates the error message emitted by ICHECK failures to point to a documentation page, which we can update over time with more information on common failure cases and hints on how to resolve them. Welcome comments on the exact wording and the content of the documentation page.

### CODE REVIEW

**Comment by tqchen** [comment]
@mdw-octoml please fix the lint error, there is already an error handling doc here, would be great to merge the content with that one https://github.com/apache/tvm/blob/main/docs/contribute/error_handling.rst

**Comment by mdw-octoml** [comment]
Fixed the lint error.

The existing error handling doc is for TVM developers, not TVM users. (It is also fairly confusing and includes a lot of details that someone simply using TVM would not need to understand.) Rather than try to have a single doc for both audiences, I think it is best to keep the user documentation separate, so it is less confusing. I added a link from the new doc to the developer doc for those who want to understand the details of how errors are generated.

Let me know what you think!

**Review by michalpiszczek — APPROVED** [review]

**Comment by tqchen** [comment]
Makes sense. Wonders if we can have a better tile. Since it is under how to section, perhaps `Handle Errors`. The flaky error is known in https://github.com/apache/tvm/issues/7870

**Comment by mdw-octoml** [comment]
I changed it to "What to do when encountering TVM errors" -- WDYT?

**Comment by tqchen** [comment]
That sounds good

**Review by jwfromm — APPROVED** [review]
This LGTM, thanks Matt!

**Comment by jwfromm** [comment]
@tkonolige, it looks like this PR hit an error in the VM RPC test. Maybe we need to bump up the delay in the test from 2 seconds to a little longer to guarantee stability?

**Comment by tkonolige** [comment]
Yeah, try bumping it to something larger.

**Comment by mdw-octoml** [comment]
I feel like that should be a separate PR. If you can tell me where to make
the change, I will, but in general one should avoid mixing unrelated
changes in a single PR.

**Comment by mdw-octoml** [comment]
I think I have resolved the merge issue, this should be good to land once CI passes.

**Comment by mdw-octoml** [comment]
@tqchen @jroesch Looks like this is good to land

**Comment by tqchen** [comment]
Thanks @mdw-octoml for contributing. Thanks @michalpiszczek @jwfromm for reviewing

**Pull request merged**
