### PR TITLE
[TRT] Add check to support split op with TRT 5.1.5+

### PR DESCRIPTION
**Pull request by apivovarov**
`SplitOpConverter` uses `nvinfer1::INetworkDefinition::addSlice` which is not available before TRT 5.1.5
This PR adds a check to support split op with TRT 5.1.5+

Related PR: https://github.com/apache/tvm/pull/7967

### CODE REVIEW

**Comment by apivovarov** [comment]
@comaniac @ziyu-guo Can you have a look?

**Review by ziyu-guo — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
LGTM. Please also update the document: https://tvm.apache.org/docs/how_to/deploy/tensorrt.html

**Review by comaniac — APPROVED** [review]

**Comment by apivovarov** [comment]
> LGTM. Please also update the document: https://tvm.apache.org/docs/how_to/deploy/tensorrt.html

Done. Added `conv1d` op to Operator support table as well.

**Comment by apivovarov** [comment]
@masahi @vinx13 @comaniac Can you merge it?

**Comment by comaniac** [comment]
Thanks @apivovarov @ziyu-guo

**Pull request merged**
