### PR TITLE
Add oneflow fronted tutorials

### PR DESCRIPTION
**Pull request by BBuf**
- [x] upgrade oneflow version to v0.7.0 and fix some bug.
- [x] add tutorial for oneflow fronted and run success.

image

### CODE REVIEW

**Comment by BBuf** [comment]
Hello, I want to upgrade the version of oneflow to 0.7.0 and solve the bug caused by the interface change. The local tests has passed. But the tests of running oneflow front-end in ci would fail. It seems that the mirror does not successfully install the oneflow 0.7.0 version. Can you give me some advice? thanks!

@masahi

**Comment by masahi** [comment]
Changing the docker script won't immediately change CI environments. We need to go through proper steps to update CI.

Please send the docker script change in a separate PR.

**Comment by BBuf** [comment]
> Changing the docker script won't immediately change CI environments. We need to go through proper steps to update CI.
> 
> Please send the docker script change in a separate PR.

ok, thanks.

**Comment by BBuf** [comment]
> Changing the docker script won't immediately change CI environments. We need to go through proper steps to update CI.
> 
> Please send the docker script change in a separate PR.

I have solved it in this pr: https://github.com/apache/tvm/pull/11052

**Comment by BBuf** [comment]
@masahi  Hey, there is an error that the flowvision package cannot be found when build docs, but I have pip flowvision in https://github.com/apache/tvm/pull/11052, I don't know why? And the oneflow front-end test also failed, probably because the upgraded image didn't work. It seems that the version of oneflow is still v0.6.0. Do you have any idea? Thanks!

**Comment by masahi** [comment]
CI update needs several steps, changing the docker script is only the first one. The next step is to wait until a new nightly image, containing the change from your PR yesterday, is pushed to https://hub.docker.com/r/tlcpackstaging/ci_gpu/tags.

Then, I'll test that image on the branch https://github.com/apache/tvm/tree/ci-docker-staging. After we pass CI tests on that branch, we'll open a PR to `main` updating `https://github.com/apache/tvm/blob/ci-docker-staging/Jenkinsfile`. CI update is complete after `Jenkinsfile` change is merged.

**Comment by BBuf** [comment]
> CI update needs several steps, changing the docker script is only the first one. The next step is to wait until a new nightly image, containing the change from your PR yesterday, is pushed to https://hub.docker.com/r/tlcpackstaging/ci_gpu/tags.
> 
> Then, I'll test that image on the branch https://github.com/apache/tvm/tree/ci-docker-staging. After we pass CI tests on that branch, we'll open a PR to `main` updating `https://github.com/apache/tvm/blob/ci-docker-staging/Jenkinsfile`. CI update is complete after `Jenkinsfile` change is merged.

Ok, thank you!

**Comment by masahi** [comment]
Running oneflow tests with the new oneflow version resulted in some errors https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/252/pipeline/340

Please take a look

**Comment by BBuf** [comment]
> Running oneflow tests with the new oneflow version resulted in some errors https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/252/pipeline/340
> 
> Please take a look

I have now reinstalled the oneflow v0.7.0 cpu version locally and run this ci failed sample 100 times but without any failed in locally, it's strange.

**Comment by BBuf** [comment]
> Running oneflow tests with the new oneflow version resulted in some errors https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/252/pipeline/340
> 
> Please take a look



> 

I want to confirm whether https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/252/pipeline/340 is running this pr(https://github.com/apache/tvm/pull/11036),  because this pr has changed some bug to adopt oneflow v0.7.0 [in](https://github.com/apache/tvm/pull/11036/files#diff-f157bdee2a307b68e8221725a49b304a12860237afaa562d8d85eaf62e0b7817R274-R1707) 。

**Comment by BBuf** [comment]
@masahi this pr can be merged too, thanks!

**Comment by masahi** [comment]
@BBuf Please run another job, there is unrelated failure on MaxOS build. Glad that there is no error from running oneflow tutorial.

**Comment by BBuf** [comment]
> @BBuf Please run another job, there is unrelated failure on MaxOS build. Glad that there is no error from running oneflow tutorial.

Ok, thanks!

**Comment by masahi** [comment]
Another related failure, please run another job...

**Comment by BBuf** [comment]
> Another unrelated failure, please run another job...

ok

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
@BBuf Merged! finally

**Comment by BBuf** [comment]
> @BBuf Merged! finally

nice, thanks!

**Pull request merged**
