### PR TITLE
[CI] Fix pip cache config bug

### PR DESCRIPTION
**Pull request by mshr-h**
Fix for #9862

### CODE REVIEW

**Comment by jroesch** [comment]
cc @driazati would you review?

**Review by leandron — APPROVED** [review]
LGTM. I made the original change and agree it was not correct.

**Comment by leandron** [comment]
This is merged now, thanks @mshr-h!

**Comment by driazati** [comment]
Also @mshr-h just FYI if you use something like `Fix #9862` rather than `Fix for #9862` GitHub will automatically close that issue when the PR is merged https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by driazati** [comment]
Thanks, looks good! Also @mshr-h just FYI if you use something like `Fix #9862` rather than `Fix for #9862` GitHub will automatically close that issue when the PR is merged https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request merged**
