### PR TITLE
[Hotfix] Mark python-FFI handling with TVM_DLL

### PR DESCRIPTION
**Pull request by Lunderberg**
Bugfix for builds on Windows, which has missing symbol exports.

### CODE REVIEW

**Comment by tqchen** [comment]
you want to place declaration in the header like the others and put TVM_DLL there

**Comment by junrushao** [comment]
We will further need to expose those methods in a `.h` file, wrapped with extern "C", and mark with TVM_DLL :-(  MSVC is weird

**Comment by Lunderberg** [comment]
Whoops, looks like renaming the branch on github accidentally closed the PR.

Thank you on the MSVC weirdnesses, and I've updated the PR to match the way all other C API functions are exposed.  (And took it as an opportunity to add documentation on what I had previously considered internal implementation functions.)

**Comment by junrushao** [comment]
I'd love to get this PR in quickly as well as a hotfix, but seems i'm unable to get around the CI...

**Review by junrushao — APPROVED** [review]

**Comment by Lunderberg** [comment]
> I'd love to get this PR in quickly as well as a hotfix, but seems i'm unable to get around the CI...

I think there's a skip CI flag, though whether it is `[skipci]`, `[Skip_CI]`, or some other value, and whether I'd need to have had it present when the PR was initially submitted, I'm not sure.

**Pull request merged**
