### PR TITLE
[TIR] Moved PrimExpr operator overload from op.h to expr.h

### PR DESCRIPTION
**Pull request by Lunderberg**
If a compilation unit includes `<tvm/ir/expr.h>`, but does not include `<tvm/tir/op.h>`, the operator overloads for `ObjectRef` are declared, but the operator overloads for `PrimExpr` are not.  In this case, any use of `expr_a == expr_b` would use `ObjectRef`'s implementation and compare reference equality of the two expressions, rather than returning a `PrimExpr` that represents the comparison.  By having the operator overloads in the `<tvm/ir/expr.h>` header file, directly adjacent to the `PrimExpr` declaration, the correct overload must be available whenever the `PrimExpr` can be used.

Even though this would only impact `operator==`, `operator!=`, and `operator<`, the three operators defined for `ObjectRef`, this PR moves all operator overloads to `expr.h` for consistency.

The named version of the operators (e.g. `tvm::add`) do not have overloaded variants, and so they are intentionally kept in `<tvm/tir/op.h>`.

### CODE REVIEW

**Comment by Lunderberg** [comment]
Changing this to a draft after further inspection.  There are some cases ([example](https://github.com/apache/tvm/blob/main/include/tvm/topi/transform.h#L96)) that rely on operations between `Integer` instances and integer literals to return a `PrimExpr`, and others that rely on those same expressions returning a `int64_t` ([example](https://github.com/apache/tvm/blob/main/src/tir/analysis/calculate_workspace.cc#L58)).  For now, changing this to a draft for whenever I can return to it.

**Comment by kparzysz-quic** [comment]
> [...] and others that rely on those same expressions returning a `int64_t`

My opinion is that we should allow implicit conversions from C++ builtin types into `PrimExpr`, but make the reverse conversions explicit.

**Comment by kparzysz-quic** [comment]
Added a PR that removes implicit conversion from `Integer` to `int64_t` (linked above).

**Comment by manupa-arm** [comment]
Looks fine to me @Lunderberg !

**Comment by Lunderberg** [comment]
Thank you!

**Review by kparzysz-quic — APPROVED** [review]

**Pull request merged**
