### PR TITLE
[microNPU] Flatten after allocates have been removed in HoistAllocates pass

### PR DESCRIPTION
**Pull request by lhutton1**
Fixes a small issue which caused SeqStmts to get left behind in the body of the inner allocate after hoisting the allocates. Flattening now happens after the mutation has happened, which consequently helps simplify the pass.

The `test_outer_seq_stmt` test case already had this behavior, so a new check has been added to catch this case.

cc @NicolaLancellotti @manupa-arm @ekalda

### CODE REVIEW

**Review by ekalda — APPROVED** [review]
Wow looks much simpler! :)

**Review by manupa-arm — APPROVED** [review]
Thanks @lhutton1 ! looks much better.

**Review by NicolaLancellotti — APPROVED** [review]
LGTM!

**Comment by manupa-arm** [comment]
Thanks all!

**Pull request merged**
