### PR TITLE
[Torch] Various updates for PyTorch frontend  

### PR DESCRIPTION
**Pull request by masahi**
This PR adds various updates to the PyTorch frontend, to fully support the recent transformer based object detection model from facebook, DETR https://github.com/facebookresearch/detr. After this PR, DETR runs on TVM and gets the correct results. TVM with auto scheduled GPU conv2d and batched matmul is 1.4x faster than PyTorch in my environment.

Also added various missing ops reported by hummingbird projects. @interesaaat

* Adds support for ops requested by hummingbird project: `logical_and`, `masked_select`, `sort` and `argsort`. `masked_select` requires VM to run.
* Adds support for `cumsum` and `masked_fill` op, to enable importing DETR https://github.com/facebookresearch/detr. `cumsum` is also requested by hummingbird.
* Fix negative indexing using `mode="wrap"` in Relay `take` op. Without this, the result doesn't match with DETR.
* Remove explicit `broadcast_to` before `batch_matmul`. Without it, memory usage blows up during constant evaluation of DETR. This is the same issue as https://github.com/apache/tvm/pull/6616, please see the explanation there. 
* Add ` torch.nn.Transformer` to the tests.

Since `torch.sort` returns both sorted values and indices while the Relay one doesn't, `torch.sort` conversion is not efficient, ~~especially for multidimensional input (currently does both sort and argsort!). Suggestions for a better implementation are welcome.~~ UPDATE: fixed

please review @siju-samuel @jwfromm @kevinthesun @t-vi

### CODE REVIEW

**Review by siju-samuel — APPROVED** [review]
LGTM

**Review by t-vi — COMMENTED** [review]
Looks good!

> Since torch.sort returns both sorted values and indices while the Relay one doesn't, torch.sort conversion is not efficient, especially for multidimensional input (currently does both sort and argsort!). Suggestions for a better implementation are welcome.

I think [gather](https://tvm.apache.org/docs/api/python/relay/index.html#tvm.relay.gather) is the direct equivalent of how you use take on 1d. Maybe it's worth fixing this in this PR.

**Comment by masahi** [comment]
@t-vi Thanks, I think I tried `gather` before but for some reason I got wrong results, so I gave up `gather`. I tried again now, and it worked :) I don't know what I was doing, but I'm happy now.

**Comment by masahi** [comment]
Thanks @siju-samuel @t-vi

**Pull request merged**
