### PR TITLE
[community] @lunderberg -> Committer

### PR DESCRIPTION
**Pull request by zhiics**
Please join us to welcome @Lunderberg as a new committer to TVM.

Eric has greatly contributed to the testing framework and CI, TIR buffer allocation, and Vulkan backend etc. He has also been actively participating the RFC and forum discussions around the related areas, where he has shared many constructive thoughts and incorporated various helpful suggestions from the others. In addition, Eric has reviewed many PRs, provided various valuable comments, and exchanged ideas with others frequently, which greatly helped the growth of the community.

* [Commits History ](https://github.com/apache/incubator-tvm/commits?author=lunderberg)
* [Code Review](https://github.com/apache/incubator-tvm/issues?q=reviewed-by+%40lunderberg)
* [Community Forum Summary](https://discuss.tvm.apache.org/u/lunderberg/summary)

### CODE REVIEW

**Review by comaniac — APPROVED** [review]
Congrats Eric!

**Review by Hzfengsy — APPROVED** [review]
Congrats 🎉

**Comment by junrushao1994** [comment]
Congrats 🎉 Well deserved!

**Comment by Lunderberg** [comment]
Thank you, all!

**Comment by tqchen** [comment]
Congrats Eric

**Comment by zxybazh** [comment]
Congrats Eric!

**Pull request merged**
