### PR TITLE
[COMMUNITY] Anirudh Sundar Subramaniam -> Committer

### PR DESCRIPTION
**Pull request by junrushao**
Please join me in welcoming Anirudh Sundar Subramaniam (@quic-sanirudh) as a new committer in TVM. Anirudh has been focusing on many aspects of the TVM stack, including LLVM, TIR, Hexagon, TOPI. His activities:
- [Commits History](https://github.com/apache/tvm/commits?author=quic-sanirudh)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:quic-sanirudh)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/sanirudh/summary)

### CODE REVIEW

**Review by masahi — APPROVED** [review]

**Comment by quic-sanirudh** [comment]
Thank you!

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Welcome @quic-sanirudh !

**Comment by quic-sanirudh** [comment]
> Welcome @quic-sanirudh !

Thanks a lot @tqchen. I really enjoy working on TVM.

**Comment by csullivan** [comment]
Congratulations, well deserved!

**Comment by quic-sanirudh** [comment]
> Congratulations, well deserved!

Thanks a lot.

**Pull request merged**
