### PR TITLE
[Frontend][PaddlePaddle] Fix UnboundLocalError: local variable 'shape…

### PR DESCRIPTION
**Pull request by woobinw**
There are a local variable referenced before assignment in convert_interpolate function. I think varible 'size' is real want to be referenced.

@jiangjiajun 
@heliqi 
cc @junrushao

### CODE REVIEW

**Comment by heliqi** [comment]
@woobinw   Can you add a single test for that?

**Review by junrushao — APPROVED** [review]
LGTM!

**Comment by woobinw** [comment]
> @woobinw Can you add a single test case for that?
> 
> https://github.com/apache/tvm/blob/2c1fecd0978d013a552ddb8d5992942acb40e5bc/tests/python/frontend/paddlepaddle/test_forward.py#L911

@heliqi 
Ok！The test case have submited #13277

**Comment by heliqi** [comment]
good job!

**Pull request merged**
