### PR TITLE
[Hexagon] Follow up fixes on PR #9631

### PR DESCRIPTION
**Pull request by mehrdadh**
Follow up fixes on hexagon RPC server.

### CODE REVIEW

**Comment by mehrdadh** [comment]
cc @kparzysz-quic

**Review by tmoreau89 — APPROVED** [review]
LGTM, thanks @mehrdadh

**Comment by kparzysz-quic** [comment]
In https://github.com/apache/tvm/pull/10205/files#diff-699c269e31b524f44d36ad4cc38d82f0e6f7edd8de3a005d583976d09ecb8b9bR198, you don't need to use `new`.  You can statically allocate a local array (i.e. `static uint8_t buffer[...]`) and pass it to the server.

**Review by kparzysz-quic — APPROVED** [review]
LGTM with a nitpick.  It can be addressed later.

**Pull request merged**
