### PR TITLE
Add support for AOT in external code generation tests

### PR DESCRIPTION
**Pull request by Mousius**
This adds support for the external code generation tests to use AOT. As
part of this the existing logic in check_result was split out into
multiple functions, this allows selectively disabling those that aren't
supported such as JSON outputs not being supported in AOT. I've replaced
existing checks to skip tests with @pytest.mark.skipif macros as they've
been moved out of the `check_result` function.

### CODE REVIEW

**Comment by Mousius** [comment]
CC @mbaret

**Review by mbaret — APPROVED** [review]
This looks fine to me, though I was wondering whether you wanted to move the 'check' functions out to some utils/testing folder. If not, happy to merge.

**Comment by Mousius** [comment]
> This looks fine to me, though I was wondering whether you wanted to move the 'check' functions out to some utils/testing folder. If not, happy to merge.

I'll ship this as another patch as this ones already a bit difficult with all the pytest changes.

**Comment by mbaret** [comment]
ping @areusch @comaniac in case you want to take a look, otherwise I'll look to merge.

**Comment by mbaret** [comment]
This is now merged, thanks @Mousius!

**Pull request merged**
