### PR TITLE
[git] Ignore auto-generated micro_tvmc.py example.

### PR DESCRIPTION
**Pull request by Lunderberg**
This file is generated automatically by `tests/scripts/task_convert_scripts_to_python.sh`, added in https://github.com/apache/tvm/pull/10555, and can be generated when running the `ci.py lint` script locally.

### CODE REVIEW

**Comment by driazati** [comment]
Did the same thing in #10701

**Review by leandron — APPROVED** [review]
LGTM

**Comment by leandron** [comment]
Thanks @Lunderberg!

**Comment by Lunderberg** [comment]
Thank you @driazati for pointing that out, and I've made #10760 to remove the duplicate entry.

**Pull request merged**
