### PR TITLE
[FIX,HEXAGON] Gitignore generated Hexagon files

### PR DESCRIPTION
**Pull request by tkonolige**
Ignore these files so they are not accidentally committed.

@kparzysz-quic @adstraw @csullivan

### CODE REVIEW

**Review by csullivan — APPROVED** [review]
LGTM @tkonolige, thanks!

**Review by kparzysz-quic — APPROVED** [review]

**Comment by Lunderberg** [comment]
Good point.  I'll poke around a bit at `Hexagon.cmake` and see if it causes issues to generate the files in the build dir instead.

**Comment by Lunderberg** [comment]
Hmm, looks like it would be a trickier update.  It's pretty easy to change to output to write to the build directory, but hunting down the different include locations for the generated `hexagon_rpc.h` would take more investigation.

**Comment by kparzysz-quic** [comment]
I'll look into this.

**Pull request merged**
