### PR TITLE
[CUTLASS][Ansor] Combine CUTLASS and Ansor

### PR DESCRIPTION
**Pull request by qingchanghan**
**Description**

This PR adds a test script to combine CUTLASS and Ansor, which can use TensorCore kernels by CUTLASS and keep op fusion and automatic tuning of Ansor.

**Modifications**

1. Add a test script to show how to combine CUTLASS and Ansor.
2. Add the `other_targets` parameter for Ansor's `extract_tasks` function, to pass cutlass target to `call_all_topi_funcs`.

**Performance**

* Bert-large
* A10, CUDA 11.8
* FP16
* Input shape: (8, 128)

Latency(ms)

| Ansor (n=3000)   | CUTLASS+TOPI | CUTLASS+Ansor (n=3000) | MetaSchedule (n=3000) | CUTLASS+MetaSchedule (n=3000) |
| ------- | ------------ | ------------- | ------------- | ------------- |
| 55.8870 | 20.2297      | 17.2543       | 19.2774       | 17.5876 |

**Test scripts**

https://github.com/qingchanghan/tvm-cutlass-eval/tree/combine-cutlass-ansor/bert

### CODE REVIEW

**Comment by junrushao** [comment]
This is interesting and extremely helpful! Just curious - have you tried out CUTLASS + MetaSchedule?

**Comment by qingchanghan** [comment]
> This is interesting and extremely helpful! Just curious - have you tried out CUTLASS + MetaSchedule?

Thank you for your advice! I tried CUTLASS + MetaSchedule and completed the test results. The performance diff between CUTLASS+Ansor and CUTLASS+MetaSchedule is negligible. I guess that the time ratio of non-MatMul operations is low in bert model and most tasks are optimized by CUTLASS.

**Comment by qingchanghan** [comment]
Please help review. @masahi @merrymercy @Laurawly @jwfromm @comaniac @tqchen @vinx13 @Hzfengsy @zhiics

**Review by Hzfengsy — APPROVED** [review]

**Review by masahi — COMMENTED** [review]
Please merge your test into `test_cutlass.py` (while disabling the tuning test by default), and remove code duplications.

**Review by junrushao — APPROVED** [review]
LGTM!

**Comment by qingchanghan** [comment]
> Please merge your test into `test_cutlass.py` (while disabling the tuning test by default), and remove code duplications.

Thanks for your review! The merge is done. BTW, I found that there are some errors when calling conv2d test in `test_cutlass.py`. I guess it is the compatibility problem introduced by tvm update. I will try to fix them later.

**Comment by Hzfengsy** [comment]
You could set a follow-up PR to fix that issue, and we can get it in quickly. 

BTW, we are going to make further improvements to Meta-schedule with TensorCore recently, beginning with https://github.com/apache/tvm/pull/13891

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
>  BTW, I found that there are some errors when calling conv2d test in test_cutlass.py

Is that an accuracy error? I'm aware that `assert_allclose` in `test_cutlass.py` can fail depending on CUDA version / card etc.

**Comment by masahi** [comment]
ok residual block fusion seems to be broken. The "residual" tensor is supposed to be passed as a different tensor than the input tensor to conv2d. So there should be 4 inputs, data, weight, bias, residual_tensor (which is the same as data). 

But now we are getting only 3 inputs.

**Comment by masahi** [comment]
@qingchanghan Here is my fix for the broken residual block fusion test submitted to a different repo https://github.com/tlc-pack/relax/pull/380/commits/4911aa142e82db128679b6b08b553cd4b96e1ace. It would be great if you can improve on it (e.g., removing TODO I included) and send it to `main`.

**Comment by qingchanghan** [comment]
> BTW, we are going to make further improvements to Meta-schedule with TensorCore recently, beginning with #13891

This is cool! I will also learn Meta-schedule and keep an eye on it. Looking forward to further improvements!

**Comment by qingchanghan** [comment]
> It would be great if you can improve on it (e.g., removing TODO I included) and send it to `main`.

OK. I'll try.

**Pull request merged**
