### PR TITLE
[ETHOSN] Upgrade NPU driver stack to v22.05

### PR DESCRIPTION
**Pull request by lhutton1**
In updating the driver stack to v22.05 some additional things needed changes:
* Prevent split being offloaded to the NPU which is not supported in
  v22.05.
* Removes compile algorithm configuration option since this was removed
  in v22.05. Versions before v22.05 will use the default option.
* Managing some API changes.
* Updating network compile hashes.
* Updating expected error message for overall scale bounds check.

cc @Leo-arm

### CODE REVIEW

**Comment by lhutton1** [comment]
@tvm-bot rerun

**Comment by lhutton1** [comment]
@tvm-bot rerun

**Comment by lhutton1** [comment]
friendly ping for review. also cc @manupa-arm @leandron

**Comment by lhutton1** [comment]
friendly ping for review

**Review by manupa-arm — APPROVED** [review]
LGTM!

**Comment by lhutton1** [comment]
Thanks @manupa-arm!

**Pull request merged**
