### PR TITLE
[ETHOSN] Add support for 20.11 Ethos-N driver stack release

### PR DESCRIPTION
**Pull request by tristan-arm**
- Updated ethosn relay backend to support 20.11 api changes.
 - Removed legacy support for 20.05.
 - Added a mechanism to specify the ethosn driver stack version.

### CODE REVIEW

**Comment by tristan-arm** [comment]
cc @Leo-arm @u99127 @mbaret @leandron @d-smirnov @grant-arm

**Comment by tqchen** [comment]
cc @mbaret it would be great if you can help to review this PR

**Review by Leo-arm — APPROVED** [review]
LGTM

**Review by mbaret — APPROVED** [review]
Looks good to me to. We're hoping for fewer API changes in future to avoid some of the versioning trouble.

**Comment by mbaret** [comment]
This is merged, thanks @tristan-arm @Leo-arm

**Pull request merged**
