### PR TITLE
[µTVM] Clone Zephyr 2.5.0 from maintenance branch

### PR DESCRIPTION
**Pull request by gromero**
Clone Zephyr 2.5.0 from maintenance branch 'v2.5-branch' instead of from
release tag 'v2.5.0'. The maintenance branch is stable and includes all
the most recent fixes backported to Zephyr 2.5.0.

Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by mehrdadh** [comment]
@gromero thanks for updating the zephyr. After this merges we need to update tlcpack/ci-qemu as well to pass your tests.

**Review by mehrdadh — APPROVED** [review]

**Comment by gromero** [comment]
@tmoreau89 Hi Thierry! I'm wondering if you could please collect that patch now CI is happy with it?

**Review by tmoreau89 — APPROVED** [review]
LGTM

**Comment by tmoreau89** [comment]
Thank you @gromero @mehrdadh the PR has been merged

**Pull request merged**
