### PR TITLE
[Relay] add ShapeFunc for one_hot op

### PR DESCRIPTION
**Pull request by monklof**

### CODE REVIEW

**Comment by monklof** [comment]
@kevinthesun @zhiics

**Comment by tqchen** [comment]
ping @icemelon9 @mbrookhart @zhiics would be great if you can help to take a look.

**Review by mbrookhart — CHANGES_REQUESTED** [review]
Can you add a test that executes one_hot with a dynamic input shape so we hit this code?

**Comment by mbrookhart** [comment]
Otherwise LGTM

**Comment by monklof** [comment]
@mbrookhart okay

**Comment by monklof** [comment]
Hi @mbrookhart Unit tests have been added, it's this what you want?

**Review by icemelon9 — APPROVED** [review]
LGTM

**Review by mbrookhart — APPROVED** [review]

**Comment by mbrookhart** [comment]
Thanks @monklof @icemelon9 @tqchen

**Pull request merged**
