### PR TITLE
[CMAKE] Automatically detect newly added source files

### PR DESCRIPTION
**Pull request by tkonolige**
Before this commit, newly added or removed source files were not detected by cmake. This manifested either as file not found errors from the compiler (when files were deleted) or packedfuncs not being found (when files were added). This commit uses the CONFIGURE_DEPENDS option of cmake's `file(GLOB)` function to ask the build system to check for new files on every rebuild. Checking for new files adds a slight but negligible overhead to each build, but is better than unexpected errors.

Note that the cmake documentation recommends avoiding CONFIGURE_DEPENDS in favor of manually listing all files. This approach has been proposed in the past, but the community did not want to do it.

@electriclilies @junrushao1994 @areusch @jroesch @tqchen @leandron

### CODE REVIEW

**Comment by junrushao1994** [comment]
Some relevant discussion in cmake forum: https://discourse.cmake.org/t/is-glob-still-considered-harmful-with-configure-depends/808

**Comment by areusch** [comment]
@tkonolige which platforms have you tested this on and with what versions of cmake?

**Comment by tkonolige** [comment]
Tested on linux with cmake 3.18 and 3.10 (support for configure_depends was added in 3.12). Are there any more platforms you would like tested? CI should get windows and macOS, but I'm not sure what version there are using.

**Comment by masahi** [comment]
@tkonolige Please resolve the conflict.

**Review by masahi — APPROVED** [review]
I think this is a good change, merging

**Comment by masahi** [comment]
thanks @tkonolige @areusch @junrushao1994

**Pull request merged**
