### PR TITLE
[CI] Update ci_cpu image and build with llvm-15

### PR DESCRIPTION
**Pull request by multiverstack-intellif**
Update docker image tag as a follow up step for https://github.com/apache/tvm/pull/14303.

cc @Hzfengsy @wrongtest-intellif @elvin-n

### CODE REVIEW

**Comment by lhutton1** [comment]
Thanks @multiverstack-intellif, it seems the correct `tlcpackstaging` image was pulled successfully, but there seems to be an sccache error I'm a little unsure about - I'll retrigger to see if it is transient

**Comment by lhutton1** [comment]
@tvm-bot rerun

**Comment by multiverstack-intellif** [comment]
Thanks @lhutton1 , it seems it keeps failing with the same error: "sccache: error: Timed out waiting for server startup." @driazati If possible, could you please help us on this or give any kind of clue? Thanks very much.

**Comment by driazati** [comment]
The error is pretty repeatable in CI which maybe indicates that something is wrong with the new image, it might be worthwhile to see if this replicates locally to determine if it's an issue with the CI machines or the image. I'm not too sure about the particular error though, maybe updating sccache to 0.4.1 (the latest release) would help?

**Comment by lhutton1** [comment]
Thanks for the suggestions @driazati, I did testing of this locally and can confirm the issue. I've bisected the failure to between:
```
tlcpackstaging/ci_cpu:20230321-064144-48193008 -- working (sccache version: 0.3.3)
tlcpackstaging/ci_cpu:20230322-060120-46fb2ff35 -- timeout failure (sccache version: 0.4.0)
```
Note the difference in sccache version.

I wasn't able to get any further before the holidays (back on the 11th Apr), perhaps we can pin to v0.3.3 for now?

**Comment by driazati** [comment]
> Thanks for the suggestions @driazati, I tested this locally and can confirm the issue. I've bisected the failure to between:
> 
> ```
> tlcpackstaging/ci_cpu:20230321-064144-48193008 -- working (sccache version: 0.3.3)
> tlcpackstaging/ci_cpu:20230322-060120-46fb2ff35 -- timeout failure (sccache version: 0.4.0)
> ```
> 
> Note the difference in sccache version.
> 
> I wasn't able to get any further before the holidays (back on the 11th Apr), perhaps we can pin to v0.3.3 for now?

Pinning to 3.3 sounds fine with me

**Comment by multiverstack-intellif** [comment]
A test case seems need modification, llvm-15 omits `pmaddwd` instead of `pmulhw` in this case,  @elvin-n please help review if the change to this case is OK, thanks very much.

**Review by junrushao — APPROVED** [review]
LGTM!

**Pull request merged**
