### PR TITLE
Update QemuTransport#write() to match new write API contract.

### LINKED ISSUE #8728: Possible flakey tests/micro/zephyr/test_zephyr.py "test_relay[mps2_an521]"
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8597/38/pipeline

> tvm._ffi.base.TVMError: MicroSessionTimeoutError: failed to read reply message after timeout 5s

tests/scripts/task_python_microtvm.sh passes all tests internally.

### PR DESCRIPTION
**Pull request by areusch**
* suspect this should fix #8728 
 * forgot to add a loop to write all the data

cc @gromero @junrushao1994

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]

**Comment by junrushao1994** [comment]
The flaky test in auto scheduler is fixed by #8754

**Comment by gromero** [comment]
@areusch Hi. For the records, I still see the `tvm._ffi.base.TVMError: MicroSessionTimeoutError: failed to read reply message after timeout 5s`  exception even with this fix (https://github.com/apache/tvm/pull/8761). I tried against the sine model. I'll continue to investigate more tomorrow.

**Comment by areusch** [comment]
@gromero i also see this but only on `tests/micro/zephyr/test_zephyr.py::test_rpc_large_array[mps2_an521-(16*1024)]` now

**Comment by areusch** [comment]
regardless i think we should still ensure that write() conforms to the API properly. can you let me know which test case you're running?

**Comment by gromero** [comment]
> regardless i think we should still ensure that write() conforms to the API properly. 
@areusch yep, I agree.


> can you let me know which test case you're running?
It's pretty much the sine model in tutorials/micro_tflite.py. I have prepared a branch which reproduces it (after several runs, you know): https://github.com/gromero/tvm/commits/8728

Just clone && cd 8728 && `./run.sh`.  The MLF sine.tar is the same model as in micro_tflite.py but already compiled. The run must crash with:

```
[...]
INFO:__main__:b'/tmp/x20/qemu-hack/qemu-system-arm -cpu cortex-m33 -machine mps2-an521 -nographic -m 16 -vga none -net none -pidfile qemu.pid -chardev pipe,id=con,mux=on,path=/tmp/tmpq4aigpet/fifo -serial chardev:con -mon chardev=con,mode=readline -icount shift=7,align=off,sleep=off -rtc clock=vm -kernel /tmp/x20/build/zephyr/zephyr.elf\n'
qemu-system-arm: warning: nic lan9118.0 has no peer
[02:19:49] /home/gromero/git/tvm/src/runtime/micro/micro_session.cc:367: remote: microTVM Zephyr runtime - running
B
INFO:__main__:b"make[3]: Leaving directory '/tmp/x20/build'\n"
INFO:__main__:b'[100%] Built target run\n'
INFO:__main__:b"make[2]: Leaving directory '/tmp/x20/build'\n"
INFO:__main__:b'/usr/bin/cmake -E cmake_progress_start /tmp/x20/build/CMakeFiles 0\n'
INFO:__main__:b"make[1]: Leaving directory '/tmp/x20/build'\n"
Traceback (most recent call last):
  File "/home/gromero/git/tvm/8728/./an.py", line 38, in <module>
    syslib = session.get_system_lib()
  File "/home/gromero/git/tvm/python/tvm/micro/session.py", line 88, in get_system_lib
    return self._rpc.get_function("runtime.SystemLib")()
  File "/home/gromero/git/tvm/python/tvm/rpc/client.py", line 73, in get_function
    return self._sess.get_function(name)
  File "/home/gromero/git/tvm/python/tvm/runtime/module.py", line 85, in get_function
    check_call(
  File "/home/gromero/git/tvm/python/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: MicroSessionTimeoutError: failed to read reply message after timeout 5s
FAIL
```
Which points  to the timeout happening at https://github.com/gromero/tvm/blob/8728/8728/an.py#L38 , i.e. just after the handshake as you mentioned I believe.  So I don't believe it's related to the model itself. I'm also with that hypothesis in mind that you raised about something fishy in mps2_an521 drivers ... But can't make sense of it yet.

**Comment by gromero** [comment]
@areusch LGTM! Although I think it won't fix totally https://github.com/apache/tvm/issues/8728 this looks correct to me and also there is a chance we will at least reduce the frequency PR 8728 happening in the CI, which is great. Thanks!

**Review by gromero — APPROVED** [review]

**Comment by gromero** [comment]
@areusch btw! the commit message cites PR 8278 (* suspect this should fix #8278) but it's indeed instead 8728! If there is still time...

**Comment by areusch** [comment]
thanks @gromero!

**Pull request merged**
