### PR TITLE
BYODT plays nicely with Relay parser

### PR DESCRIPTION
**Pull request by gussmith23**
Continuation of #8070.

Previously, there were no Bring Your Own Datatypes parser tests included
in the Relay parser tests, so when the Relay parser changed recently,
BYODT's parsing broke. This change fixes the parser and adds a test to
prevent similar breakage in the future.

- BYODT datatypes now use the format "custom_<typename><bits>x<lanes>"
  rather than "custom[<typename>]<bits>x<lanes>"

### CODE REVIEW

**Comment by gussmith23** [comment]
Bump on this, can someone review when they get the chance?

**Comment by gussmith23** [comment]
Bump!

**Comment by areusch** [comment]
@hypercubestart @AndrewZhaoLuo are you able to take a look at this?

**Comment by areusch** [comment]
also cc @junrushao1994

**Review by hypercubestart — APPROVED** [review]
LGTM! Thanks Gus!

**Comment by areusch** [comment]
thanks @gussmith23, can you take a look at the CI failure and sync the PR?

**Pull request closed without merging**
