### PR TITLE
[WIP] [CI] Bump CI GPU image version

### PR DESCRIPTION
**Pull request by guberti**
Thanks to @areusch for rebuilding!

cc @Mousius @driazati

### CODE REVIEW

**Comment by areusch** [comment]
@guberti can you run the generate.py tool?

**Comment by guberti** [comment]
> @guberti can you run the generate.py tool?

@areusch Done, sorry for the wait.

**Comment by areusch** [comment]
@guberti sorry--can you resolve the merge conflict?

**Comment by guberti** [comment]
> @guberti sorry--can you resolve the merge conflict?

@areusch done!

**Pull request merged**
