### PR TITLE
[CI] Fix python file format due to changes in black

### PR DESCRIPTION
**Pull request by mehrdadh**
Due to recent changes to [black](https://github.com/psf/black/pull/1740), we need to reformat all python files to avoid ci issues like [this](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8144/5/pipeline/).

@leandron thanks for pointing out source of this issue.

### CODE REVIEW

**Comment by mehrdadh** [comment]
Other instances of this issue:
https://github.com/apache/tvm/pull/8124
https://github.com/apache/tvm/pull/8185

**Review by leandron — APPROVED** [review]
LGTM, thanks for doing this work

**Comment by mehrdadh** [comment]
cc @tqchen @areusch

**Review by areusch — APPROVED** [review]
thanks @mehrdadh !

**Comment by leandron** [comment]
Thanks @mehrdadh @areusch!

**Pull request merged**
