### PR TITLE
[hot-fix][CI]Disable mypy for ethosu

### PR DESCRIPTION
**Pull request by mikepapadim**
Fix for failing CI on ethosu mypy sanity checks

@tqchen @mehrdadh

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
cc @manupa-arm

**Comment by manupa-arm** [comment]
Thanks for catching this! Any idea why it did not fail before?

cc: @mbaret @ashutosh-arm

**Comment by manupa-arm** [comment]
Thanks @mikepapadim!  but I believe it passed CI with those checks. Did anything change on the CI ?

**Comment by ashutosh-arm** [comment]
Ignoring missing stub warnings can be fixed with this:

 mypy  --check-untyped-defs python/tvm/relay/backend/contrib/ethosu/ --ignore-missing-imports

**Comment by areusch** [comment]
this hit #9013, we also need to fix that.

**Comment by AndrewZhaoLuo** [comment]
Can we set up a big red button that merges something without CI passing?

**Comment by mikepapadim** [comment]
> this hit #9013, we also need to fix that.

This bug hits also stagging Jenkins.

**Comment by mikepapadim** [comment]
@areusch I think this PR can be closed if #9052 get through.

**Comment by junrushao1994** [comment]
i dont think committers have permission to merge a pr without CI green. maybe it's a merge conflict?

**Comment by areusch** [comment]
i think we don't need this anymore. closing, feel free to reopen if we do need it.

**Pull request closed without merging**
