### PR TITLE
[ACL] Adjust mobilenet test for Keras 2.9

### PR DESCRIPTION
**Pull request by leandron**
In Keras 2.7, one "reshape" operator was removed from
the Mobilenet model, making our test which verifies the
number of operators to be incorrect.

This patch adjusts the operator count so that it is in line
with the changes in Keras. For reference, the change in
keras repo was done in hash b6abfaed132 "Remove
unnecessary reshape layer in MobileNet architecture".

cc @lhutton1 @NicolaLancellotti @ashutosh-arm @areusch

### CODE REVIEW

**Review by lhutton1 — APPROVED** [review]
Thanks @leandron, a very subtle change indeed! LGTM!

**Review by ashutosh-arm — APPROVED** [review]
Its interesting that mobilenet has lesser number of reshapes. I am surprised not a lot of networks got affected. LGTM!

**Comment by leandron** [comment]
For reference, this is the change on Keras side:
```
https://github.com/keras-team/keras/commit/b6abfaed1326e3c5e1d233e35c97bde177b562fa
```

**Comment by leandron** [comment]
Thanks @ashutosh-arm @lhutton1 !

**Pull request merged**
