### PR TITLE
[Docker][QEMU] Update gpg server

### PR DESCRIPTION
**Pull request by mehrdadh**
This PR:
- updates gpg server for qemu installation since `keys.gnupg.net` is not reachable.

I have built the docker and ran zephyr tests.

cc @tqchen @areusch @mbrookhart

### CODE REVIEW

**Review by mbrookhart — APPROVED** [review]
Thank you

**Review by leandron — APPROVED** [review]

**Comment by mbrookhart** [comment]
:( @mehrdadh This hit the flakey TF test again. Want to gamble and rebase now, or wait a couple of hours until this :crossed_fingers: fix merges: https://github.com/apache/tvm/pull/8335

**Comment by mehrdadh** [comment]
@mbrookhart I'll rebase now, hopefully that resolves it.

**Comment by mehrdadh** [comment]
@mbrookhart this is a different error.

**Comment by mbrookhart** [comment]
@mehrdadh Looks like another flaky test, there's a PR up to fix it. :(

**Pull request merged**
