### PR TITLE
Update gen_requirements.py with new onnx things 

### PR DESCRIPTION
**Pull request by AndrewZhaoLuo**
Response to https://github.com/apache/tvm/pull/9519 

cc @areusch

### CODE REVIEW

**Comment by AndrewZhaoLuo** [comment]
ping @areusch

**Comment by AndrewZhaoLuo** [comment]
poke  @areusch

**Review by leandron — APPROVED** [review]
LGTM

**Comment by leandron** [comment]
I checked and `onnxoptimizer` publishes packages for python 3.6 to 3.9, so it looks safe to add this dependency.

**Pull request merged**
