### PR TITLE
 [Fix Bug]fix the bugs of keras frontend when parsing LSTM, GRU, RNN layers.

### PR DESCRIPTION
**Pull request by new-TonyWang**
I have encountered "list index out of range" when parsing the keras LSTM. Then I dived in to this problem.

I found that when using keras LSTVM and set "use_bies=False", this would lead to the "list index out of range" exception, because at this time, the **weightList** only contains two tensors, and tvm  will fall on fetching **weightList[2]**. 

So I made a little improvment  by adding *if* statement and added some new test cases.

### CODE REVIEW

**Review by AndrewZhaoLuo — APPROVED** [review]
LGTM, thanks for the contribution!

**Review by AndrewZhaoLuo — COMMENTED** [review]
Looks like you need to run `black` formatter on the files, it's failing our linter

**Comment by new-TonyWang** [comment]
> Looks like you need to run `black` formatter on the files, it's failing our linter

ok, I will do it now

**Comment by new-TonyWang** [comment]
> Looks like you need to run `black` formatter on the files, it's failing our linter

It's finished.Could you please check it out when you are free?

**Pull request merged**
