### PR TITLE
[Autoscheduler][VM] Autoscheduler layout rewrite pass to VM

### PR DESCRIPTION
**Pull request by tmoreau89**
This adds the autoscheduler layout rewrite pass to VM compiler, to brings big performance improvements to any autoscheduler optimized graph. Tested on SSD Resnet34 and saw over 2x speedup.

### CODE REVIEW

**Comment by tmoreau89** [comment]
@junrushao1994 @merrymercy @masahi

**Review by merrymercy — APPROVED** [review]

**Comment by merrymercy** [comment]
How can we address this kind of issue in the future?

Should we organize the optimization passes in `src/relay/backend/vm/compiler.cc` and `src/relay/backend/build_module.cc` into a common place? So we don't need to add them in two places every time.

**Comment by tmoreau89** [comment]
@merrymercy I think that initially the intent for Relay VM compilation was to use the same passes as the graph runtime. I think that the pass manager refactor ended up being applied to graph runtime and not the VM IIRC causing the two to diverge?
@jroesch and @tkonolige has some input on this and we could think of a plan to unify the passes since technically the two runtimes should use the same passes. This could use an RFC but I think everyone will be behind it.

**Comment by tmoreau89** [comment]
@merrymercy please let me know if there are any outstanding changes requested of if we can go ahead and merge this one

**Review by merrymercy — APPROVED** [review]

**Pull request merged**
