### PR TITLE
[cherry-pick][ARITH] Enhance CanonicalSimplify to Simplify ProdDiv and [ci] disable merge

### PR DESCRIPTION
**Pull request by driazati**
This disables the merge to main behavior for this branch and includes the code #14725 to get this to pass CI. This also disables the docker GPU build which is currently broken on this branch and has no bearing on the release (and is being built erroneously anyways since this PR has no docker changes).

### CODE REVIEW

**Comment by ysh329** [comment]
I found there's a test failed: 
image

**Comment by driazati** [comment]
@tvm-bot rerun

**Comment by ysh329** [comment]
Hi @driazati , I tried this test locally and failed log as below:

```shell
$ python3 ./tests/python/unittest/test_arith_canonical_simplify.py
Traceback (most recent call last):
  File "./tests/python/unittest/test_arith_canonical_simplify.py", line 427, in <module>
    test_proddiv_simplify()
  File "./tests/python/unittest/test_arith_canonical_simplify.py", line 398, in test_proddiv_simplify
    ck.verify(flm(x * 32 * x, x), 0)
  File "./tests/python/unittest/test_arith_canonical_simplify.py", line 29, in verify
    assert tvm.ir.structural_equal(res, expected), "\ndata={}\nres={}\nexpected={}".format(
AssertionError:
data=x * 32 * x % x
res=x * 32 * x % x
expected=0
```

**Comment by driazati** [comment]
@ysh329 I believe this PR is exposing a latent bug that was being hidden by the merge before, I think we can fix it by cherry picking #14538, that works locally for me at least

**Comment by driazati** [comment]
> > @ysh329 I believe this PR is exposing a latent bug that was being hidden by the merge before, I think we can fix it by cherry picking #14538, that works locally for me at least
> 
> Fixed with cherry-picked PR #14725. It's a bit strange why the previous PR CI test did not reflect this failed test.

I think because before it was merging the PR from main, so the fix was being applied even though it hadn't been cherry-picked. To avoid the failure in your cherry-pick PR I just added both changes to this one

**Comment by ysh329** [comment]
> > > @ysh329 I believe this PR is exposing a latent bug that was being hidden by the merge before, I think we can fix it by cherry picking #14538, that works locally for me at least
> > 
> > 
> > Fixed with cherry-picked PR #14725. It's a bit strange why the previous PR CI test did not reflect this failed test.
> 
> I think because before it was merging the PR from main, so the fix was being applied even though it hadn't been cherry-picked. To avoid the failure in your cherry-pick PR I just added both changes to this one

Great! Thanks for your work. 😆

**Review by tqchen — APPROVED** [review]

**Pull request merged**
