### PR TITLE
[AutoTVM] Sort arguments of built autotvm func in topological order.

### PR DESCRIPTION
**Pull request by moderato**
Currently, the order of the AutoTVM function arguments might cause confusion in some cases. For example, for a 3x3 conv, the order of `arg_bufs` after calling `s, arg_bufs = task.instantiate(best_config)` is output, filter, input, while for a 1x1 conv, the order is output, input, filter, since it doesn't need padding and thus both input and filter are directly the input_tensors of conv, in which input comes first. This will significantly affect the use of the generated CUDA/asm code externally.

This fix sorts the arguments in topological order.

### CODE REVIEW

**Comment by comaniac** [comment]
The change looks good to me, but I'm not sure if it will affect existing cases. Please try to fix the CI and let's see.
Also cc @merrymercy

**Comment by areusch** [comment]
cc @mbs-octoml @jroesch  we need to address this by providing an explicit pass to thread the argument order through lowering.

**Comment by masahi** [comment]
@moderato Please update.

**Comment by areusch** [comment]
closing due to inactivity, but feel free to reopen!

**Pull request closed without merging**
