### PR TITLE
[skip ci] Fix broken CI when git-merge needs to create a commit.

### PR DESCRIPTION
**Pull request by areusch**
- This fixes an error seen when CI needs to create a merge commit
   to sync the PR. CI started doing this recently to ensure that all
   CI branches use the same commit for their regressions.
 - The error looks like:

        + git merge e370ed459739f5312e45a2fb3a446b120f8ec5d1

        *** Please tell me who you are.

        Run

          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

        to set your account's default identity.
        Omit --global to set the identity only in this repository.

cc @tqchen @driazati @Mousius

### CODE REVIEW

**Comment by areusch** [comment]
Pushed this fix on top of the PR causing the problem, it seems to work: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/areusch-test-jenkinsfile-merge-fix/3/pipeline/

**Review by leandron — APPROVED** [review]
LGTM

**Review by driazati — APPROVED** [review]
thanks for the fix (I had noticed it too #10988), since `tvm-ci/pr-head` was only enabled for a little bit we can't really test this but it's pretty straightforward

**Comment by areusch** [comment]
going to [skip ci] based on branch passing

**Comment by gromero** [comment]
@areusch Thanks for fixing it! I tried to investigate it yesterday but I was not able to reproduce locally (not it's clear why)!

**Pull request merged**
