### PR TITLE
[Relay][VM][RPC]Use a uint64_t to serialize primitive_attrs in the Relay VM to fix 32bit RPC

### PR DESCRIPTION
**Pull request by mbrookhart**
cc @tkonolige 

Ran into this trying to use RPC with the VM onto a 32bit Raspbian OS. Not sure how to test this in CI....

### CODE REVIEW

**Review by tkonolige — APPROVED** [review]
Thanks @mbrookhart!

**Comment by tkonolige** [comment]
I don't think there is a good way to test this on CI.

**Comment by Mousius** [comment]
> Not sure how to test this in CI....

Could you construct a test that goes over 32 entries? It should fail in `ci_i386`.

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Comment by tkonolige** [comment]
> Could you construct a test that goes over 32 entries? It should fail in `ci_i386`.

The problem is that you should not use types that are different sizes on different platforms. Not sure how going over 32 entries would fail on `ci_i386` as it would probably serialize and deserialize just fine. We could possibly try serializing on one platform and deserializing on another but that makes CI really complicated.

**Comment by mbrookhart** [comment]
@Mousius 
> Could you construct a test that goes over 32 entries? It should fail in ci_i386.

I don't think that would do it. The problem is that when I'm tuning on a 64 bit host and measuring on a 32 bit edge device, the size_t on the host is a 64 bit value which gets serialized into a byte stream. When the 32bit edge device tries to read that, it thinks the value should be a 32 bit size_t, and ends up corrupting the data stream as it reads it. I don't think it's possible to test that without running RPC across architectures.

**Review by Mousius — APPROVED** [review]
> @Mousius
> 
> > Could you construct a test that goes over 32 entries? It should fail in ci_i386.
> 
> I don't think that would do it. The problem is that when I'm tuning on a 64 bit host and measuring on a 32 bit edge device, the size_t on the host is a 64 bit value which gets serialized into a byte stream. When the 32bit edge device tries to read that, it thinks the value should be a 32 bit size_t, and ends up corrupting the data stream as it reads it. I don't think it's possible to test that without running RPC across architectures.

Ahh, gotcha, was a naive suggestion on my side. I'd also agree this is also a coding style issue as the Google style guide suggests using fixed type sizes. Thanks for taking the time to clarify it 😸

**Comment by mbrookhart** [comment]
Thanks @tkonolige @junrushao1994 @Mousius

**Comment by areusch** [comment]
hmm it might be possible to write a future test using ci-i386. cc @denise-k could you capture a tracking issue to think about this?

**Pull request merged**
