### PR TITLE
[Fix][Runtime] Use flatBuffersBuffer_ in EdgeTPURuntime::Init()

### PR DESCRIPTION
**Pull request by tk1012**
This PR fixes a bug in `EdgeTPURuntime::Init()`, in which `flatBuffersBuffer_` is not used for initializing `FlatBufferModel`.
This bug causes a SEGV during `TFLiteRuntime::Invoke()`.

This PR also includes a small modification on tests/python/contrib/test_edgetpu_runtime.py to clarify we should pass "edge_tpu" for `tflite_runtime.create()` when using edgetpus.

### CODE REVIEW

**Comment by tk1012** [comment]
According to https://github.com/apache/tvm/pull/4698,  @tmoreau89 , @ZihengJiang, @tqchen  for reviews

**Comment by tmoreau89** [comment]
Thank you @tk1012 ! Which version of tflite was this tested on?

**Comment by tk1012** [comment]
Thank @tmoreau89 for a quick reply.
I tested two versions of tensorflow / tflite.

+ the latest commit hash when I tested (https://github.com/tensorflow/tensorflow/tree/c523f23149c437ae0a5b57527897b6f8355fb4b3)
+ v2.4.1 (https://github.com/tensorflow/tensorflow/tree/9a2545aecc498e7a5e8bf5d63c47af59e1550111)

**Comment by tmoreau89** [comment]
Could you add a comment in the test script which versions of TF it's dependent on? Thanks!

**Comment by tk1012** [comment]
Thank you @tmoreau89 for feedback.
I add a comment for showing the test script was tested on TF v2.4.1.

**Review by tmoreau89 — APPROVED** [review]
Thanks @tk1012 LGTM!

**Comment by tk1012** [comment]
make a tiny fix for passing pylint

**Comment by tmoreau89** [comment]
Thank you @tk1012 the PR has been merged!

**Pull request merged**
