### PR TITLE
[microNPU] Upgrade to 21.11 version of Arm(R) Ethos(TM)-U55 NPU driver

### PR DESCRIPTION
**Pull request by grant-arm**
This PR upgrades the Arm(R) Ethos(TM)-U55 NPU driver to version 21.11

@manupa-arm @ekalda @areusch @Mousius

### CODE REVIEW

**Review by ekalda — APPROVED** [review]
LGTM!

**Comment by manupa-arm** [comment]
Prioritizing the bug fix : https://github.com/apache/tvm/pull/9706 over this one. Hope you dont mind :).

Also, we need to mention this in  https://github.com/apache/tvm/issues/9762.

**Review by manupa-arm — APPROVED** [review]
LGTM!

**Comment by manupa-arm** [comment]
Thanks! @grant-arm @ekalda

**Pull request merged**
