### PR TITLE
[CI] Update ci-gpu image

### PR DESCRIPTION
**Pull request by lhutton1**
The ci-gpu is updated to make changes in #15819 reflect in CI.

cc @ashutosh-arm

### CODE REVIEW

**Review by ashutosh-arm — APPROVED** [review]
LGTM! Thanks @lhutton1 😄

**Review by yongwww — APPROVED** [review]
lgtm, please take a look at the ci errors

**Comment by lhutton1** [comment]
Hit a ```
fatal: unable to access 'https://github.com/apache/tvm.git/': Failed to connect to github.com port 443: Connection timed out
```
on the cortexm build, retriggering...

**Comment by lhutton1** [comment]
closes: #15754

**Review by ashutosh-arm — APPROVED** [review]
LGTM - thanks @lhutton1 :)

**Pull request merged**
