### PR TITLE
Skip stride check if shape is 1 in IsContiguous

### PR DESCRIPTION
**Pull request by yelite**
Skip stride check if shape[k] is 1, where the dimension is contiguous regardless of the value of stride.

For example, PyTorch will normalize stride to 1 if shape is 1.
Related: https://github.com/pytorch/pytorch/commit/ec42ee027867e586ea1c584c7ba7e06dd8b4bcb4

cc @junrushao @zxybazh

### CODE REVIEW

**Review by junrushao — APPROVED** [review]
Please also add a unittest

**Comment by zxybazh** [comment]
Hi Lite, can you please fix the linting issue?

**Comment by yelite** [comment]
I fixed lint and added few unit tests

**Review by zxybazh — APPROVED** [review]
LGTM.

**Pull request merged**
