### PR TITLE
[CI] Update TVM ci-cpu docker image to v0.79

### LINKED ISSUE #9296: [CI Image] Update ci_cpu to v0.79
- [x] S0. Reason: Upcoming Conv2d support in CMSIS NN (https://github.com/apache/tvm/issues/8646) and optimising the AOT tests (https://github.com/apache/tvm/pull/9271)

- [x] S1. Tag of nightly build: `20211004-225913-779a50629`. Docker hub: https://hub.docker.com/layers/tlcpackstaging/ci_cpu/20211004-225913-779a50629/images/sha256-aef4438e0a91d8b16a5da96f4c1885a1de8f386612077519dd491fce9b5b97d6?context=explore

- [x] S2. The nightly is built on TVM commit: `95a20315d0d3403e5eea3bfe6ed5e942a51b169d`. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/77/pipeline

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...

- [ ] S4. Retag `20211004-225913-779a50629` to `v0.79`:
```
docker pull tlcpackstaging/ci_cpu:20211004-225913-779a50629
docker tag tlcpackstaging/ci_cpu:20211004-225913-779a50629 tlcpack/ci-cpu:v0.79
docker push tlcpack/ci-cpu:v0.79
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the `ci-cpu` version on Jenkins

### PR DESCRIPTION
**Pull request by leandron**
Update TVM ci-cpu docker image to v0.79:
 * Requested in #9296
 * Validated at https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/169/pipeline/

Fixes #9296

cc @Mousius @ashutosh-arm @areusch @junrushao1994 @tqchen for reviews

### CODE REVIEW

**Comment by leandron** [comment]
Link to the image: https://hub.docker.com/layers/tlcpack/ci-cpu/v0.79/images/sha256-a099e6c51d4548e41c0c7574933cdf46e041e2fba72ac707222c0604466cee8a?context=explore

**Review by Mousius — APPROVED** [review]
Thanks for this @leandron :smile_cat:

**Comment by manupa-arm** [comment]
Commit : https://github.com/apache/tvm/commit/d2cf72c20e08d8434774da054e3da5417e1ff254

It shows tlcpackstaging/ci_cpu:20211102-232503-054fff568 is used which has the hash : sha256-a099e6c51d4548e41c0c7574933cdf46e041e2fba72ac707222c0604466cee8a which is same as hash in 
https://hub.docker.com/layers/tlcpack/ci-cpu/v0.79/images/sha256-a099e6c51d4548e41c0c7574933cdf46e041e2fba72ac707222c0604466cee8a?context=explore

References :

tlcpack : 

https://hub.docker.com/layers/tlcpackstaging/ci_cpu/20211102-232503-054fff568/images/sha256-a099e6c51d4548e41c0c7574933cdf46e041e2fba72ac707222c0604466cee8a?context=explore

tlcpackstaging : 

https://hub.docker.com/layers/tlcpackstaging/ci_cpu/20211102-232503-054fff568/images/sha256-a099e6c51d4548e41c0c7574933cdf46e041e2fba72ac707222c0604466cee8a?context=explore

Hence approving and waiting for merge after the CI.

**Review by manupa-arm — APPROVED** [review]
LGTM

**Comment by manupa-arm** [comment]
Thanks @leandron @Mousius ! This is merged.

**Pull request merged**
