### PR TITLE
Fix wrong terminology in `tvmc` source

### PR DESCRIPTION
**Pull request by cconvey**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by cconvey** [comment]
cc: @areusch

**Comment by cconvey** [comment]
cc: @jwfromm

**Review by gromero — APPROVED** [review]
@cconvey I think that's correct. For instance, we can now pass a `Runtime()` object and a `Executor()` object (that can be of `aot` or `graph` type) to `relay.build`, so runtime and executor are different concepts, although quite dependent when "running/executing" the runtime.

Please add the tag `[TVMC]` in front of the commit message title and write a commit message quickly explaining the change. Having an empty commit body messages is not a good practice in any case.

As default for the TVM project, when merged to the tree,  a patchset gets the commit title from the PR title and a single patch like this one gets its title from the single patch associated to the PR, so in this case you need to push the commit again.

Thank you.

**Comment by gromero** [comment]
cc @leandron

**Comment by cconvey** [comment]
Thanks @gromero !  Would you mind clarifying part of your comment?

> ... we can now pass a `Runtime()` object and a `Executor()` object

When you write `Runtime()` and `Executor()`, are you referring to _actual_ C++/Python functions or class constructors?  Or should I read that as pseudocode that wouldn't be literally valid in TVM?

**Comment by gromero** [comment]
> Thanks @gromero ! Would you mind clarifying part of your comment?
> 
> > ... we can now pass a `Runtime()` object and a `Executor()` object
> 
> When you write `Runtime()` and `Executor()`, are you referring to _actual_ C++/Python functions or class names? Or should I read that as pseudocode that wouldn't be literally valid in TVM?

@cconvey I had the `Runtime` and `Executor` Python classes in mind yep, the ones found in the source below, which are actually  mapped to  the C++ code found in `./src`, via the CFFI:

https://github.com/apache/tvm/blob/main/python/tvm/relay/backend/executor.py#L27
https://github.com/apache/tvm/blob/main/python/tvm/relay/backend/runtime.py#L27

and used, for instance, like in:

https://github.com/apache/tvm/blob/main/tests/micro/zephyr/test_zephyr_aot.py#L69-L72

But more broadly I was just saying that if I'm not mistaken in the past the concepts of runtime and executor were not as clear as they are now, back when there wasn't  the even the AOT executor and before the discussions/changes around:

https://github.com/apache/tvm/pull/9352

... and I think your patch is fixing what looks a reminiscent code of that period.

**Comment by cconvey** [comment]
Thanks @gromero for all the background information, I find it very helpful!  AFAIK I've addressed your feedback.

**Review by leandron — APPROVED** [review]
LGTM

**Comment by gromero** [comment]
@leandron It seems the CI failed due to an unrelated issue (something related to Ethos-U55 AOT tests, but I can't follow exactly what) Have you ever seen this error before? Is it known to be a flaky test? hmm just realized that @areusch seems to wresting with some ethos-u55 test in here too: https://github.com/apache/tvm/pull/10283#issuecomment-1050695312

@cconvey The CI failed but I can't see how it can be related to your change, hence while we try to understand it better could you please re-trigger the C please? (you can, for example, just do `git --amend --no-edit` to change the commit hash and `push --force` again).

**Review by areusch — APPROVED** [review]
thanks @gromero !

**Comment by areusch** [comment]
@cconvey yeah i think these are the flaky ethos-u tests, can you push again? I think #10020 but unsure if there is a better bug for this particular flake

**Review by jwfromm — APPROVED** [review]
Makes sense to me, thanks @cconvey.

**Comment by cconvey** [comment]
@tqchen Ready for merge

**Pull request merged**
