### PR TITLE
Upgrade to latest version of FVP based on Arm(R) Corstone(TM)-300 software

### PR DESCRIPTION
**Pull request by grant-arm**
This PR updates the `ci_cpu` docker image to use the latest version of the FVP (Fixed Virtual Platform) based on Arm(R) Corstone(TM)-300 software.

@manupa-arm @ekalda @leandron @Mousius @areusch

### CODE REVIEW

**Review by ekalda — APPROVED** [review]
LGTM! :)

**Review by leandron — APPROVED** [review]
Agree with @ekalda, and happy to have this merged when CI is green.

**Comment by manupa-arm** [comment]
@grant-arm lets include this in https://github.com/apache/tvm/issues/9659

**Comment by manupa-arm** [comment]
@jroesch Im furiously trying to get ci-docker-staging job to pass, However, it seems the CI node runs out of memory when it pulls the image. Any ideas are welcome to solve this. cc : @tqchen

**Pull request merged**
