### PR TITLE
[Torch] Fix advanced indexing with NoneType index arguments

### PR DESCRIPTION
**Pull request by padreofthegame**
Suppose to solve issue #12922.

### CODE REVIEW

**Comment by shingjan** [comment]
Thanks for taking a look at this @padreofthegame! Will circle back once this PR is ready for review

**Comment by padreofthegame** [comment]
This solution is very similar to #13306, and represents workaround for the problem mentioned in #12922 for PyTorch models (since advanced indexing does not work the same for example for numpy and for pytorch, I put solution in torch frontend, because issue was reported for torch models). 
Also, I put WIP label only because I am not sure if I managed to cover all possible test cases, so @shingjan you are welcome to try some additional scenarios, and call me out if detect something strange.

**Comment by shingjan** [comment]
@padreofthegame i think this fix is fine in terms of the difference between adv_index of numpy and it of pytorch. There is no numpy frontend for TVM yet. I think overall this PR LGTM. Will be great if @masahi can take a look and approve. Thanks!

**Review by shingjan — APPROVED** [review]
LGTM

**Review by masahi — APPROVED** [review]

**Pull request merged**
