### PR TITLE
[Android][RPC] Fix Vulkan runtime support

### PR DESCRIPTION
**Pull request by AnastasiaStulova**
Update Android RPC app to reflect the new
Vulkan source code tree structure.

closes https://github.com/apache/tvm/issues/8743

### CODE REVIEW

**Comment by AnastasiaStulova** [comment]
@leandron @mbaret

**Review by leandron — APPROVED** [review]

**Comment by leandron** [comment]
cc @tkonolige @echuraev for reviews

**Comment by tkonolige** [comment]
@Lunderberg has been working a lot on this. He should probably review.

**Review by tkonolige — APPROVED** [review]
Seems like we hit issues like this all the time. I think we should be compiling a static version of libtvm_runtime and linking it into libraries instead of doing this ad-hoc #includes.

**Comment by Lunderberg** [comment]
Looks good to me.  There's a few other files in `src/runtime` that I made in the same refactor, but on investigation those were only header files.

@tkonolige Agreed, the ad-hoc lists of files feels really fragile.  It looks like the top-level cmake file has a `BUILD_STATIC_RUNTIME` option, so that probably could be used for a longer-term solution.

**Review by mbaret — APPROVED** [review]
lgtm

**Pull request merged**
