### PR TITLE
[Relay][TE] Use Relay parameter name to generated TE tensor name

### PR DESCRIPTION
**Pull request by Lunderberg**
Previously, the TE placeholders representing relay function parameters were all named `"placeholder"`, which could be difficult to follow when debugging larger functions.

### CODE REVIEW

**Comment by Lunderberg** [comment]
Rebase onto main following #10535

**Comment by Lunderberg** [comment]
Current CI failures due to checks for the name `"placeholder"` in `auto_scheduler` ([link](https://github.com/apache/tvm/blob/main/python/tvm/auto_scheduler/measure.py#L817)).  Will investigate further as time allows, as I'm not sure the history of this check.

**Review by tkonolige — APPROVED** [review]
This is a very helpful change. Thanks @Lunderberg!

**Comment by areusch** [comment]
@Lunderberg what's the status on this one?

**Comment by Lunderberg** [comment]
Currently there's one CI failure that I haven't had time to track down yet.  The error message occurs during memory verification, that a buffer is undefined, but likely is caused by an earlier pass failing to update a buffer.

**Comment by Lunderberg** [comment]
Rebased onto main, since the failing test case was disabled in #10717.

**Comment by Lunderberg** [comment]
I let this one languish long enough that I no longer trust the CI checks to be up-to-date.  Re-running CI.

**Pull request merged**
