### PR TITLE
Fix compilation when __ARM_FEATURE_FP16_SCALAR_ARITHMETIC

### PR DESCRIPTION
**Pull request by MatthewARM**
Signed-off-by: Matthew Bentham <matthew.bentham@arm.com>

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by MatthewARM** [comment]
@mbaret

**Review by giuseros — APPROVED** [review]
LGTM. Could you just add a better description and commit message? Thanks!

**Comment by MatthewARM** [comment]
@giuseros is that better?

**Comment by giuseros** [comment]
Hi @MatthewARM , thanks for addressing my comments! It looks perfect now!

**Review by mbaret — APPROVED** [review]
LGTM, will wait on CI.

**Comment by mbaret** [comment]
CI seems to have crashed/failed for some unrelated reason (ping @tqchen ). Could you try pushing again with some trivial update to retrigger it?

**Comment by tqchen** [comment]
seems was due to timeout, we might need to look into the integration tests being added recently, in particular the ones related to tvmc

**Comment by MatthewARM** [comment]
What should I do? Wait, for now?

**Comment by tqchen** [comment]
The CI outrage problem have been resolved, sorry @MatthewARM for the inconvenience

**Comment by MatthewARM** [comment]
Awesome thanks, no worries.

**Comment by mbaret** [comment]
Thanks @MatthewARM, this is now merged.

**Pull request merged**
