### PR TITLE
[Hexagon] depth_to_space slice op

### PR DESCRIPTION
**Pull request by rasagna-quic**
This pull request adds support to enable fp16 and uint8 support for depth to space operator. This uses layout transform to support the given layouts and the required test cases for verification.

@mehrdadh

### CODE REVIEW

**Comment by mehrdadh** [comment]
@rasagna-quic Please update the PR description.

**Comment by rasagna-quic** [comment]
> @rasagna-quic Please update the PR description.

Thank you @mehrdadh , I have updated the PR description.

**Comment by rasagna-quic** [comment]
@mehrdadh : Gentle reminder!

**Comment by rasagna-quic** [comment]
@jverma-quic @kparzysz-quic can you please review this PR?

**Review by jverma-quic — APPROVED** [review]

**Review by kparzysz-quic — APPROVED** [review]

**Pull request merged**
