### PR TITLE
[ARM][Strategy] Fix is_int8_hw_support check function

### PR DESCRIPTION
**Pull request by mehrdadh**
This PR fixes the `is_int8_hw_support` check function and adds few warning messages when unoptimized schedules are used for ARM targets.

cc @areusch

### CODE REVIEW

**Review by huajsj — APPROVED** [review]
LGTM, thanks @mehrdadh.

**Review by areusch — COMMENTED** [review]
cc @u99127 @Mousius for input here

**Comment by u99127** [comment]
Please add a test or 2  ... 😃 

I'll be able to look at this later in the week. 

Ramana.

**Comment by mehrdadh** [comment]
@u99127 I have added a test. Also looks like there's a bug in [get_arch_version](https://github.com/apache/tvm/blob/3d0fc36ae4967a5ee24a75cff311828447003235/python/tvm/topi/arm_cpu/arm_utils.py#L24) because when I pass `-mattr=v8.4a,+dotprod` in the target, architecture is returned as `8.0` instead of `8.4`.

**Review by areusch — APPROVED** [review]
@u99127 i'll let you have a look as well before we merge

**Comment by u99127** [comment]
> @u99127 I have added a test. Also looks like there's a bug in [get_arch_version](https://github.com/apache/tvm/blob/3d0fc36ae4967a5ee24a75cff311828447003235/python/tvm/topi/arm_cpu/arm_utils.py#L24) because when I pass `-mattr=v8.4a,+dotprod` in the target, architecture is returned as `8.0` instead of `8.4`.

LGTM,  I do think that needs to be fixed separately.

**Pull request merged**
