### PR TITLE
[Hexagon][CI] Updated sha for builder LLVM

### PR DESCRIPTION
**Pull request by joshherr-quic**
Updated sha to deal with some codegen issues that came up with the last version.

### CODE REVIEW

**Comment by mehrdadh** [comment]
@joshherr-quic thanks for the PR! Could you please build the docker locally and run hexagon tests with the simulator?

**Comment by joshherr-quic** [comment]
> @joshherr-quic thanks for the PR! Could you please build the docker locally and run hexagon tests with the simulator?

Will do. Is there a wiki with some quick instructions on how to do this?

**Comment by ibsidorenko** [comment]
Hi, @mehrdadh and @joshherr-quic !
Sorry for stupid question, but when I try to use Hexagon docker I run the following command:
`./docker/bash.sh ci_hexagon`
But as I see from the downloaded image it still uses LLVM-14:
```
$ /opt/clang-llvm/bin/llvm-config --version
14.0.0
```
But even LLVM_SHA=361a27c155ec8b should correspond to LLVM-15.x if I am correct.

What should I do to use up-to-date LLVM version in the docker image? Build the docker locally?

**Comment by joshherr-quic** [comment]
I'm not seeing any codegen errors, but I am seeing a lot of errors 

> Hi, @mehrdadh and @joshherr-quic ! Sorry for stupid question, but when I try to use Hexagon docker I run the following command: `./docker/bash.sh ci_hexagon` But as I see from the downloaded image it still uses LLVM-14:
> 
> ```
> $ /opt/clang-llvm/bin/llvm-config --version
> 14.0.0
> ```
> 
> But even LLVM_SHA=361a27c155ec8b should correspond to LLVM-15.x if I am correct.
> 
> What should I do to use up-to-date LLVM version in the docker image? Build the docker locally?

The docker image you download is built according to the tvm commit that corresponds to [this](https://github.com/apache/tvm/blob/main/Jenkinsfile#L60) commit id. That commit still has llvm 14. The PR that we're looking at merely updates the docker image that would get built for **this** commit. We still need to open another PR to update the commit id in the [Jenkinsfile](https://github.com/apache/tvm/blob/main/Jenkinsfile#L60) so that CI will build the new LLVM version. Only after that follow-up commit will the updated docker with the newer llvm be available.

So your intuition is correct! You would need to build the docker locally to take advantage of the newest LLVM right now. New dockers with new llvm should hopefully be available over the weekend for download.

**Review by driazati — APPROVED** [review]

**Review by mehrdadh — CHANGES_REQUESTED** [review]
waiting for passing test confirmation

**Comment by mehrdadh** [comment]
@ibsidorenko so after @joshherr-quic confirms the tests are passing, we will merge this PR and update the docker image. In the meantime if you need to use docker with updated LLVM, you need to build it locally. We also have automated nightly image build which is published here: https://hub.docker.com/r/tlcpackstaging/ci_hexagon/tags
These images are not necessarily usable because some of them are failing on some tests

**Comment by joshherr-quic** [comment]
I'm seeing a lot of "AttributeError: 'HexagonLauncherSimulator' object has no attribute '_se" errors, but nothing related to codegen...

**Comment by mehrdadh** [comment]
@joshherr-quic where do you see those errors? can you post them here?

**Comment by mehrdadh** [comment]
cc @kparzysz-quic

**Comment by kparzysz-quic** [comment]
The CI tests have passed with docker image built from this.

**Review by mehrdadh — APPROVED** [review]

**Pull request merged**
