### PR TITLE
Use std::optional instead of dmlc::optional, NFC

### PR DESCRIPTION
**Pull request by kparzysz-quic**

### CODE REVIEW

**Review by junrushao1994 — APPROVED** [review]
LGTM. BTW, do you prefer using `tvm::runtime::Optinonal` instead for TVM objects?

**Comment by kparzysz-quic** [comment]
> LGTM. BTW, do you prefer using `tvm::runtime::Optinonal` instead for TVM objects?

I think that `tvm::runtime::Optional` is a part of the packed func interface, so I'm not sure if we can get rid of it.

**Comment by junrushao1994** [comment]
Yeah my question is definitely a bit off the topic, so we don't have to deal with this in this PR - feel free to consider this as a discussion instead.

My point here is that `tvm::runtime::Optional<ObjectRef>` is a simple wrapper of `ObjectRef` which does not incur extra memory overhead, so it could be slightly more efficient. Therefore, when dealing with TVM objects, I usually recommend to use `tvm::runtime::Optional` instead

**Comment by masahi** [comment]
How about we also clean up this? https://github.com/apache/tvm/blob/c8a892b66d22965c42df8384a3d8405d024ddf5f/src/tir/ir/buffer_common.h#L42-L45

**Pull request merged**
