### PR TITLE
[microNPU] Cascader performance model bugfixes

### PR DESCRIPTION
**Pull request by jacobbohlin**
This PR fixes some bugs related to the microNPU performance model in the cascader.

* Fixed incorrect num_blocks calculations for both BufferModes.
* Fixed similar issues with Read/Write byte calculations.
* Fixed an issue where the 'partkernel' flag was not propagated to the performance estimation code.
* Fixed single buffering check incorrectly used output shape and block rather than the input shape and block.
* Fixed block config not aligned to micro block for Elementwise.

This PR builds on and includes the changes in https://github.com/apache/tvm/pull/10508 and will remain as a draft until that is merged.

### CODE REVIEW

**Comment by jacobbohlin** [comment]
@manupa-arm @ekalda @lhutton1 @dchauhan-arm @NicolaLancellotti

**Review by ekalda — APPROVED** [review]
LGTM! :)

**Review by manupa-arm — APPROVED** [review]
LGTM!

**Comment by manupa-arm** [comment]
Thanks @jacobbohlin @ekalda !

**Pull request merged**
