### PR TITLE
add target_host argument to tvmc compile command

### PR DESCRIPTION
**Pull request by pfk-beta**
this solves #11158

### CODE REVIEW

**Review by Mousius — CHANGES_REQUESTED** [review]
Thanks for the fix @pfk-beta, could you please add a test to https://github.com/apache/tvm/blob/main/tests/python/driver/tvmc/test_compiler.py to ensure this doesn't regress in future?

**Comment by pfk-beta** [comment]
Hi @Mousius - sure. Could you tell how to run tests locally?

**Comment by pfk-beta** [comment]
@Mousius  how to check in tests, that module was compiled with target_host?

**Comment by Mousius** [comment]
@pfk-beta you can use the example of how to invoke the CLI directly from here:
https://github.com/apache/tvm/blob/8d4f4dd73ff2d762ade38aa0f9e8e9fba5f933da/tests/python/driver/tvmc/test_command_line.py#L58-L60
And mock `relay.build` as seen here:
https://github.com/apache/tvm/blob/8d4f4dd73ff2d762ade38aa0f9e8e9fba5f933da/tests/python/driver/tvmc/test_compiler.py#L517

Which should give you a `mock_relay` that you can use [assert_called_with](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_called_with) to check that `target_host` is correctly being passed through.

**Comment by Mousius** [comment]
@pfk-beta any updates here? or should we close this for now?

**Comment by pfk-beta** [comment]
> @pfk-beta any updates here? or should we close this for now?

I didn't make any update, I don't see any interested people, so I'm closing.

**Comment by happyme531** [comment]
This PR fixed my problem, it is useful in many cases and shouldn't be closed!

**Comment by pfk-beta** [comment]
@happyme531 I closed it, because I didn't have time to do it, and I didn't have enough knowledge to write tests inside TVM. If you know a little bit about developing TVM, you can copy my MR and write tests for it. I'm not making promise, but I can try to do it in a few days...

**Pull request closed without merging**
