### PR TITLE
[Bugfix][Executor] fix debug_executor function debug_get_output

### PR DESCRIPTION
**Pull request by youxiudeshouyeren**
This pr is to address this issue:https://github.com/apache/tvm/issues/16490

### CODE REVIEW

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
@tvm-bot rerun

**Comment by youxiudeshouyeren** [comment]
@tvm-bot rerun

**Comment by youxiudeshouyeren** [comment]
image
This ERROR doesn't seem to have anything to do with my commits. Is this an error in the tvm ci settings? How can I avoid this error? Thanks！ @Hzfengsy

**Comment by Hzfengsy** [comment]
try rebase to the latest commit

**Comment by youxiudeshouyeren** [comment]
> try rebase to the latest commit

Thanks! It's passed all the checks now.

**Comment by youxiudeshouyeren** [comment]
This pr has been developed and passed all checks. Could you merge it? Thanks！ 
@Hzfengsy

**Comment by Hzfengsy** [comment]
Thanks @youxiudeshouyeren for the fix

**Pull request merged**
