### PR TITLE
[Relay][Parser] support dict attributes parsing

### PR DESCRIPTION
**Pull request by domin1985**
Please review @jroesch

### CODE REVIEW

**Comment by tqchen** [comment]
cc @MarisaKirisame @jroesch @altanh please help to review this PR

**Comment by altanh** [comment]
I'm not super familiar with the interaction between parser and pretty printer, how come changing the printer solves the problem?

**Comment by jroesch** [comment]
I think this is an okay work around for now, ideally we could make the printing a little cleaner but I think the challenge is detecting between typed attributes. In which case are you using this functionality? operators should always have a registered type with them and normal calls shouldn't be using attributes.

**Comment by jroesch** [comment]
cc @domin1985

**Comment by domin1985** [comment]
> cc @domin1985



> I think this is an okay work around for now, ideally we could make the printing a little cleaner but I think the challenge is detecting between typed attributes. In which case are you using this functionality? operators should always have a registered type with them and normal calls shouldn't be using attributes.

Sorry for late reply. This patch is mainly for the sake of extended user defined Ops with DictAttr type. And the relay parser cannot reconstruct this attribute through model stream input generated by printer.

**Comment by masahi** [comment]
@domin1985 Can you update?

**Comment by areusch** [comment]
closing due to inactivity, but feel free to reopen!

**Pull request closed without merging**
