### PR TITLE
Add Compute Library tests to Jenkins for AArch64 CI

### PR DESCRIPTION
**Pull request by u99127**
Now that we have hardware testing on by default, Actually run this.

### CODE REVIEW

**Review by leandron — APPROVED** [review]
LGTM

**Comment by masahi** [comment]
@u99127 @leandron @tqchen  ARM compute lib tests are failing in CI:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/1255/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8366/16/pipeline

**Comment by u99127** [comment]
> @u99127 @leandron @tqchen ARM compute lib tests are failing in CI:
> https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/1255/pipeline
> https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8366/16/pipeline

That is very weird. The same tests were passing locally for a few days which is why I added it in. 

> @u99127 @leandron @tqchen ARM compute lib tests are failing in CI:
> https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/1255/pipeline
> https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8366/16/pipeline

Maybe we should revert this till new docker images are spun up as in #8177  before merging this in ? 

That is the only difference between my environment and the CI environment that is currently running that I can spot.

**Comment by u99127** [comment]
> > @u99127 @leandron @tqchen ARM compute lib tests are failing in CI:
> > https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/1255/pipeline
> > https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8366/16/pipeline
> 
> That is very weird. The same tests were passing locally on my machine that is running Ubuntu 18.04 and pretty much the same environment as in upstream CI for a few days.
> 
> > @u99127 @leandron @tqchen ARM compute lib tests are failing in CI:
> > https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/1255/pipeline
> > https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8366/16/pipeline
> 
> Maybe we should revert this till new docker images are spun up as in #8177 before merging this in ?
> 
> That is the only difference between my environment and the CI environment that is currently running that I can spot. Sorry about the breakage.

Since this is failing -I've put up a revert at #8400

**Pull request merged**
