### PR TITLE
[PTX] Support mma.sp to use Sparse Tensor Cores and refactor mma codegen

### PR DESCRIPTION
**Pull request by yzh119**
Sparse Tensor Cores(STC) was first introduced in the Ampere architecture of NVIDIA GPUs (see [whitepaper](https://www.megware.com/fileadmin/user_upload/LandingPage%20NVIDIA/nvidia-ampere-architecture-whitepaper.pdf)). Up to now, developers can only activate STC by calling wrapped APIs such as `cuSparseLt` or writing PTX assembly code.

Following #9909, this PR support `ptx_mma_sp` intrinsic so as to expose the interface of STC at the TIR level.

This PR also refactors the `ptx_mma.cc` to use template-based codegen.

cc @vinx13 @junrushao1994 @Hzfengsy

### CODE REVIEW

**Comment by yzh119** [comment]
@vinx13 one thing I'm not sure is if we need offset for metadata (which stores the indices information and is always 32bit).

**Comment by vinx13** [comment]
If metadata is stored in a larger buffer, and any some elements of it are passed to mma.sp each time, offset is needed.

#9727 introduced some breaking changes in the semantic of `T.allocate`, we might want to wait until that PR is merged to prevent conflicts.

**Comment by yzh119** [comment]
@vinx13 , refactor of MMA codegen is also finished.

I deleted some unittests such as `s8u832`, `u8s8s32`, `s4u432`, `u4s4s32` because they do not conform to the standard described [here](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-data-types), which requires multiplicands to have the same data type. I wonder are there cases we want these `s8u8s32` in quantization?

**Comment by yzh119** [comment]
okay, it turns out they mean elements inside the two multiplicands must have the same data type, but the two multiplicands can have different data types.

[cutlass](https://github.com/NVIDIA/cutlass/blob/e96f00586c92c2e77575ea4d3d906027595c8d9c/include/cutlass/arch/mma_sm75.h) also support u8s8s32 mma's.

I'll add these tests back.

**Comment by yzh119** [comment]
@vinx13 refactored according to the change in #9727 .

**Pull request merged**
