### PR TITLE
[TENSORRT] Improvements and fixes for TensorRT

### PR DESCRIPTION
**Pull request by mbaret**
A number of small fixes and refactors to improve the robustness of the TensorRT integration.

Co-authored-by: Mark Shields <mbs@octoml.ai>

### CODE REVIEW

**Comment by mbaret** [comment]
cc @mbs-octoml @mikepapadim

**Comment by mbs-octoml** [comment]
The background on the bits I fiddled with:
 - Finish the transition from operator predicate based to pattern based for the partition_for_tensorrt function. The current state in main is broken.
 - Remove choice of operator vs predicate method since they are indistinguishable from the outside.
 - Though most operators can be translated looking only at the operator call, nn.batch_norm can only be translated in the form of a sub-graph `nn.batch_norm(...).0`. So switch the translation to follow the standard composite style.

**Review by mbs-octoml — APPROVED** [review]
LGTM, thank you!

I wonder if we should warn for the conv3d attributes you found  trigger numerical inaccuracy? Say in the predicate?

**Comment by mbaret** [comment]
Unfortunately, the attributes aren't particularly well-defined. For example, in that specific test it was failing with channels between 28 and 45. I think so long as TensorRT is selecting strategies with different numerical behaviour based on tuning we won't be able to give a sane warning here.

**Comment by mikepapadim** [comment]
LGTM, thanks

**Review by mikepapadim — APPROVED** [review]

**Review by jwfromm — APPROVED** [review]
Thanks for these improvements @mbaret, @mikepapadim, and @mbs-octoml!

**Comment by tiandiao123** [comment]
nice job!

**Pull request merged**
