### PR TITLE
[MetaSchedule][Bugfix] Feature: Strides of buffer access

### PR DESCRIPTION
**Pull request by Kathryn-cat**
I fixed a bug in MetaSchedule per_store_feature.cc

### CODE REVIEW

**Comment by junrushao1994** [comment]
Thanks for the contribution! Yes, it's definitely a typo. We would probably have to fix the unittests accordingly

**Comment by zxybazh** [comment]
@tvm-bot rerun

**Comment by zxybazh** [comment]
@tvm-bot rerun

**Comment by Kathryn-cat** [comment]
@tvmbot rerun

**Review by junrushao1994 — APPROVED** [review]
LGTM!

**Pull request merged**
