### PR TITLE
[TIR] IndexMap Simplification Constraints

### PR DESCRIPTION
**Pull request by Lunderberg**
This is a follow-up from https://github.com/apache/tvm/pull/11330.  I really like the functionality that it adds (simplification of transformed indices based on `BlockNode` iteration variables), and would like to expose the functionality for use elsewhere as well.

### CODE REVIEW

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
@Lunderberg The same error happening twice, maybe it is real?

**Comment by Lunderberg** [comment]
Looks like it's a timeout, with both instances being terminated after around 2h08m.  Looks like there's some [bumps to the timeout](https://github.com/apache/tvm/pull/11350) during investigation.

**Comment by Lunderberg** [comment]
Bumped CI to restart, after #11350 merged.

**Comment by csullivan** [comment]
Thanks @Lunderberg @masahi, this is merged.

**Pull request merged**
