### PR TITLE
[CI] add merge_with_main in unity

### PR DESCRIPTION
**Pull request by yongwww**
Add `merge_with_main` in unity. Adjust 5 retries with 2-minute timeout to 3 retries with 5-m timeout as cpu does.

### CODE REVIEW

**Comment by yongwww** [comment]
cc: @lhutton1 @tqchen @vinx13

**Comment by lhutton1** [comment]
Thanks for taking a look into this @yongwww, I'm not too familiar with Jenkins so I'll defer to others for review. Also cc @Liam-Sturge

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot  rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Review by tqchen — APPROVED** [review]

**Pull request merged**
