### PR TITLE
[Topi] Fix arm_cpu bitserial schedule with elemwise ops.

### PR DESCRIPTION
**Pull request by jwfromm**
As noted in #7909, the arm bitserial_conv2d schedule has issues with fused elemwise operators. This turned out to be due to a simple mistake that this PR corrects.

### CODE REVIEW

**Comment by jwfromm** [comment]
@bernhardklein can you give this PR a shot to confirm everything now works as expected?

**Review by comaniac — COMMENTED** [review]
The changes looks good. Thanks @jwfromm.
Also, could we have a test case to cover this chage?

**Comment by jwfromm** [comment]
Yes, just added a test that confirms the issue is resolved.

**Review by comaniac — APPROVED** [review]
LGTM

**Review by jcf94 — APPROVED** [review]

**Comment by bernhardklein** [comment]
@jwfromm seems to work. I could not test it with your branch directly, because I can't compile TVM with it. Cmake complains about something with libbacktrace. However, using your bitserial_conv2d.py file with a current TVM checkout works well and solves the issue.

@jwfromm and @comaniac thank you very much!

Should I close the [issue #7909](https://github.com/apache/tvm/issues/7909) or wait till the merge is done?

**Comment by jwfromm** [comment]
@bernhardklein, I think libbacktrace was recently added to TVM, you may need to do a `git submodule init` -> `git submodule update` to grab it. Waiting for this to merge before closing the issue should be fine.

**Comment by comaniac** [comment]
> Should I close the [issue #7909](https://github.com/apache/tvm/issues/7909) or wait till the merge is done?

I've linked this PR to the issue, so once this PR is merged the issue will be closed automatically.

**Comment by bernhardklein** [comment]
@jwfromm oh yes, you are right libbacktrace was missing and after a `git submodule init`-> `git submodule update` I could compile TVM and further the bit serial ReLU test model works now with your branch.
So the issue seems to be solved. Thank you!

**Comment by jcf94** [comment]
Some error occured. @jwfromm Seems you need to push again to re-triggle the CI...

**Pull request merged**
