### PR TITLE
[FIX] Fix deploy_sparse tutorial

### PR DESCRIPTION
**Pull request by tkonolige**
@areusch

### CODE REVIEW

**Comment by jroesch** [comment]
@tkonolige @areusch can you guys get this green and land?

**Comment by areusch** [comment]
@tkonolige i see, so the problem is that gen_weights was False here? basically my only concern is whether we need to make a more fundamental change to params to fix common use case, at least we should understand and document that.

**Comment by tkonolige** [comment]
The issue is that `load_param_dict` returns a `Map` which does not support mutation from python. I better fix may be to switch `load_param_dict` to returning a `dict` or allow mutation of `Map` from python.

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
yeah just wanted to understand why this changed recently, but now i see the tutorial doesn't actually run in CI

**Pull request merged**
