### PR TITLE
[microTVM] Fix Stack Size Issue for Zephyr AOT Demo on Physical Hardware

### PR DESCRIPTION
**Pull request by mehrdadh**
Due to recent changes in AOT, we need to increase the stack size to pass test_zephyr_aot test.

cc @gromero @areusch

### CODE REVIEW

**Comment by Mousius** [comment]
Did you try adding `--unpacked-api=1` to the target options? That should reduce the stack usage

**Comment by mehrdadh** [comment]
@Mousius That fixed the problem. Thanks for the suggestion.
I'll change this PR to reflect this solution.

**Comment by mehrdadh** [comment]
Update:
adding --unpacked-api=1 option to the target will fix the issue.

**Review by leandron — APPROVED** [review]
LGTM

**Comment by leandron** [comment]
This is now merged, thanks @mehrdadh @Mousius @areusch!

**Pull request merged**
