### PR TITLE
[RPC] Add fail-guard for termination time exception

### PR DESCRIPTION
**Pull request by tqchen**
This PR adds fail-guard to reduce error messages thrown during process termination time. Such error won't trigger test error but will bring extra message during exit time.

### CODE REVIEW

**Review by echuraev — APPROVED** [review]
In general LGTM. One minor question. I didn't see any error messages during RPC termination before. In which scenario, I'll be able to get these import errors?

**Comment by tqchen** [comment]
This would be some rare case that have to do with shutdown orders likely in multi processing. I have observed some flaky ones during purest

**Comment by tqchen** [comment]
Example snippet

```
Exception ignored in: <function Server.__del__ at 0x7fb012d9add0>
Traceback (most recent call last):
  File "/home/tqchen/github/relax/python/tvm/rpc/server.py", line 502, in __del__
  File "/home/tqchen/github/relax/python/tvm/rpc/server.py", line 498, in terminate
  File "/home/tqchen/github/relax/python/tvm/contrib/popen_pool.py", line 145, in kill
  File "/home/tqchen/github/relax/python/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down

```

**Comment by echuraev** [comment]
Thank you for the clarification!

**Pull request merged**
