### PR TITLE
[TVMSCRIPT]Fix script printters StructuralEqual check failed

### PR DESCRIPTION
**Pull request by Beya2019**
fix print bug when call

        @tvm.script.tir
        def printer(a: ty.handle) -> None:
            A = tir.match_buffer(a, (), "float32")
            A[()] = tir.min(2.2, 5.2)
            A[()] = tir.max(tir.float32(2.2), tir.float32(5.2))
            A[()] = tir.min(2.2, 5.0)
          
          func = printer
          rt_func = tvm.script.from_source(tvm.script.asscript(func, True))
          tvm.ir.assert_structural_equal(func, rt_func)

  First parser result(func):

        A[()] = tir.min(tir.float32(2.2000000000000002), tir.float32(5.2000000000000002))
        A[()] = tir.max(tir.cast(tir.float32(2.2000000000000002), "float32"), tir.cast(tir.float32(5.2000000000000002), "float32"))

  Second parser result(rt_func):

        A[()] = tir.min(tir.cast(tir.float32(2.2000000000000002), "float32"), tir.cast(tir.float32(5.2000000000000002), "float32"))
        A[()] = tir.max(tir.cast(tir.cast(tir.float32(2.2000000000000002), "float32"), "float32"), tir.cast(tir.cast(tir.float32(5.2000000000000002), "float32"), "float32"))

Second structure has an extra tir.cast compared the first, because the first structure print the 2.2 to tir.float32(2.2) and the tir.float32(2.2) is parsed to tir.cast(tir.float32(2.2), "float32") in second structure. So, we reduced the printing of tir.float32() wrapper.

Meanwhile, when one operator is 2.0/3.0/4.0 (`(A[()] = tir.min(2.2, 5.0)`),  c++ ostringstream print it to 2/3/4 in default. When entering the second parsing, parser consider it as an integer,  `A[()] = tir.min(2.2000000000000002, 5)`, and report error:
Check failed: (a.dtype() == b.dtype()) is false: TypeError: mismatched types. float32 vs. int32. So we add the `os.setf(std::ios::showpoint);`.

But this method show the 2.0/3.0/4.0 to 2.0000000000000000 which has 17 bits precision value.This print is really not beautiful,
Please review and see if there is a better solution?

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @Beya2019 , can you please add a regression test to cover the case?

**Comment by junrushao1994** [comment]
@jinhongyii and @MasterJH5574 encountered some precision issue if we didn’t print at least 18 digits of a FP32 number

**Comment by MasterJH5574** [comment]
@junrushao1994 I remember the issue is about printing a FP32 number to string and then read it back from the string. The finding/conclusion is that we need to print at least 17 digits so that the two numbers before and after the round trip is the same.

Before the fix, the printer only printed 16 digits for a FP32 number.

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Sorry folks i mistakenly merged this PR. Will bring a followup that fixes the problem

**Pull request merged**
