### PR TITLE
[ETHOSN] Add support for Ethos-N 21.02 driver stack release.

### PR DESCRIPTION
**Pull request by tristan-arm**
- Updated default Ethos-N driver stack to 21.02
  - Fixed some test failures associated with this change

### CODE REVIEW

**Review by Leo-arm — APPROVED** [review]
LGTM. As discussed, some code cleanup can be done once the versions line up a little better in the next month or two.

**Comment by u99127** [comment]
@mbaret  - could you please review this ? And once this is approved we need to request @tqchen or @tmoreau89 to respin docker.ci_cpu images.

**Comment by tristan-arm** [comment]
cc @Leo-arm @u99127 @mbaret @leandron @d-smirnov @grant-arm

**Review by mbaret — APPROVED** [review]
LGTM

**Comment by mbaret** [comment]
Thanks @tristan-arm @Leo-arm, this is now merged.

**Comment by u99127** [comment]
@areusch - could this also get a new ci-cpu image ?

**Comment by areusch** [comment]
sure. I don't believe it is included in #7745

**Pull request merged**
