### PR TITLE
[MSC][Refactor] Support dynamic shape

### PR DESCRIPTION
**Pull request by Archermmt**
Dynamic shapes are recorded as tir.Var + IntImm in relax. This PR create MSCPrim to map the PrimNode in tvm to MSC. The MSCPrim can be codegen to different frameworks to support dynamic shapes, such as dynamic batch in training and dynamic dims in LLM.
MSC records the PrimNode and the relations between PrimNodes as MSCPrims in DAG format, so that the dynamic dim can be described (e.g res_0.shape[0]*2) during codegen.

cc @Hzfengsy

### CODE REVIEW

**Review by Hzfengsy — APPROVED** [review]

**Comment by Archermmt** [comment]
rerun @tvm-bot

**Comment by Archermmt** [comment]
@tvm-bot rerun

**Comment by Archermmt** [comment]
@tvm-bot rerun

**Comment by mshr-h** [comment]
@Archermmt 
wasm ci was failing due to the usage of deprecated API. The issue was solved with https://github.com/apache/tvm/pull/17371
Need to rebase.

**Pull request merged**
