### PR TITLE
[bulitin] Add search sorted builtin

### PR DESCRIPTION
**Pull request by yzh119**
The search sorted function was used in the sparse-tir project to perform binary search on indices array. I need to rebase the sparse-tir repo to relax project so I start to push some changes upstream. This PR adds the search sorted function to TIR built-ins. The semantic of `searchsorted` is the same as numpy's (https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html), we add two arguments `offset_l` and `offset_r` to indicate the interval bound.

@masahi suggests using IRBuilder to define the fine-grained description of binary search. However, at current stage I don't want to decompose the binary search to more fine-grained instructions (this would make the intermediate IR too redundant, and not convenient for scheduling).

I leave the codegen on LLVM a future work.

@MasterJH5574  @junrushao1994

### CODE REVIEW

**Comment by masahi** [comment]
hmm, can TensorIR `Block` be used to "hide" those implementation details while still allowing TIR-native implementation of binary search ops? If not and if we have to resort to backend-specific hard-coding like this, this sounds like a major step backward to me. 

Note that it is not just CUDA and LLVM, there is opencl, metal, spirv...

**Comment by yzh119** [comment]
@masahi yes I understand, I also view it as a backstep. `block` is not designed to do that.

Another feasible solution is to lower the intrinsic in a pass, where we replace the intrinsic with fine-grained instructions like what you did in the IRBuilder, WDYT?

**Comment by masahi** [comment]
Note that we even have relay / topi `searchsorted` op that does exactly the same lower / upper bound search. So adding a new intrinsic doesn't feel right to me.

> block is not designed to do that

I remember hearing that, one of the reasons `Block` was created was to abstract the details of tensorized instructions so that the rest of code don't need to care about it. Here we are not talking about tensorized instruction but I don't really see a big difference.

**Comment by yzh119** [comment]
@masahi Then difference here is whether we perform statement replacement or expression replacement.
What `tensorize` replace are statements rather than expressions.

**Comment by yzh119** [comment]
Yes I'm trying to figure out a way to reuse your op defined in `topi`/`relay`.
How about I trigger a `call_extern` like this:
https://github.com/apache/tvm/blob/174d09ee2cef1ea2caab4c84e0bd58d90c09178f/tests/python/contrib/test_ethosu/test_replace_conv2d.py#L347-L350

**Comment by masahi** [comment]
> Another feasible solution is to lower the intrinsic in a pass, where we replace the intrinsic with fine-grained instructions like what you did in the IRBuilder

Ok, as long as we don't duplicate or backend-specific hard-code, I don't have complaint. Yes, we probably need an extern / packed func call.

**Comment by yzh119** [comment]
Hi @tkonolige @masahi , I decide to emit a `search` block and lower it to statements composed of `WhileNode` in sparse-tir fork. This PR is deprecated, thanks for your suggestions!

**Pull request closed without merging**
