### PR TITLE
[Relay][Layout] Add FInferCorrectLayout for L2 norm layout transform.

### PR DESCRIPTION
**Pull request by blackkker**
The `FInferCorrectLayout` was set to `ElemwiseArbitraryLayout` which is for layout agnostic operators. While L2norm is a lightly-layout sensitive operator with `attrs-axis`. Refered to [Convert Layout Pass](https://tvm.apache.org/docs/arch/convert_layout.html?highlight=pass).
https://github.com/apache/tvm/blob/72b0f5ee34be6acfadf7afc61264eef42b78c789/src/relay/op/nn/nn.cc#L672
When running model, I met a situation:
`%0 = layout_transform(%x, src_layout="NHWC", dst_layout="NCHW") /* ty=Tensor[(1, 64, 56, 56), float32] */;`
`%1 = layout_transform(%weight, src_layout="HWIO", dst_layout="OIHW") /* ty=Tensor[(64, 64, 3, 3), float32] */;`
`%2 = nn.conv2d(%0, %1, padding=[1, 1, 1, 1], channels=64, kernel_size=[3, 3]) /* ty=Tensor[(1, 64, 56, 56), float32] */;`
`%3 = nn.l2_normalize(%2, eps=0.001f, axis=[3]) /* ty=Tensor[(1, 64, 56, 56), float32] */;`

The nn.l2_normalize 's axis didn't change during `InferCorrectLayout`. So i write a `L2NormalizeInferCorrectLayout` for it.
Also, add some tests.

BTW! I'm still new to cpp, please advise if there is anything inappropriate in code. Thanks!
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by blackkker** [comment]
@masahi

**Review by masahi — APPROVED** [review]

**Comment by blackkker** [comment]
How can i rerun CI / Windows (pull_request) without running other part, cause it is time-consuming. @masahi

**Comment by blackkker** [comment]
@tvm-bot rerun CI / Windows (pull_request)

**Comment by masahi** [comment]
@tvm-bot rerun

**Comment by blackkker** [comment]
Can't remember how many times the CI / Windows (pull_request) process has been rerun（failed at CI / Windows:Conda）, is this my problem?

**Comment by blackkker** [comment]
@tvm-bot merge

**Pull request merged**
