### PR TITLE
[Hexagon] Move aot/graph_executor interactions into launcher

### PR DESCRIPTION
**Pull request by Lunderberg**
Follow-up from https://github.com/apache/tvm/pull/10581, applying similar changes to the AOT and graph executor interactions.  This moves the file management and upload/download from the unit tests into the launcher.

### CODE REVIEW

**Review by kparzysz-quic — COMMENTED** [review]
Could you add this to the launcher class, and call functions from it from `Session`?

**Comment by kparzysz-quic** [comment]
Let me think about it for a bit.

**Comment by kparzysz-quic** [comment]
IMO there are two types of interactions with a device: ones that have to do with setting up the device, and ones that have to do with running code on it.  The first group would be, for example, uploading files to it, starting servers, etc, while the second would be loading modules into memory, creating arrays in memory, invoking functions, etc.  The first set would be the responsibility of the launcher, while the second would belong to the session.

In this view, creating executors would belong to the session, so your changes are ok in that sense.  Still, I'd like to make the division of responsibilities clear (not necessarily in this PR though).

Finally, I don't like the idea of passing executor factories to the launcher/session code.  Executor factories are not persistent objects.  What's persistent (i.e. can be saved/loaded) are the actual modules.  We should operate in terms of those instead.  In particular, the `export_library` stuff does not belong in either launcher or session.

**Comment by kparzysz-quic** [comment]
We could have a utility function somewhere in tvm/contrib/hexagon that does the `export_library` together with the link-step workaround.  That should save some work from the tests using AoT.

**Comment by Lunderberg** [comment]
> We could have a utility function somewhere in tvm/contrib/hexagon that does the export_library together with the link-step workaround. That should save some work from the tests using AoT.

Good point, and I like the idea of centralizing the link-step workaround, so it will only need to be removed from one spot once it is not longer needed.  I was thinking that it would make sense to have it directly in `tvm.contrib.hexagon.create_aot_shared`, since right now it is necessary for all invocations.

The utility function would get a lot of the same benefits.  I had been hoping to also avoid requiring functionality tests to handle file management and cleanup, as the file management isn't relevant to the behavior being tested.  I'm open to having a testing-specific utility function, though I'd still prefer having it be part of the session object, as that would allow for additional ergonomic benefits in the future (e.g. Uploads triggered through the session having a session-specific prefix to avoid name collisions, and being cleaned up after the session.)

**Comment by kparzysz-quic** [comment]
Could we have separate function inside `Session` that takes the factory objects (something like `get_executor_from_factory` or something like that)?  Then the other functions would take a module, or module+json.

**Comment by Lunderberg** [comment]
Sure.  I like that division, because it avoids a lot of the argument checks that are necessary if both behaviors are in a single function.

**Review by kparzysz-quic — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
