### PR TITLE
Change new concat

### PR DESCRIPTION
**Pull request by SebastianBoblestETAS**
This is a proposed change to the new topi x86 concat implementation in #11341. It uses simple lists of int instead of `te.tensor.Tensor` for the array offsets and loop variable extents. I have only looked at the generated C code and made sure that the relevant unit tests pass.
New version:
```
 for (int32_t j = 0; j < 4; ++j) {
    concatenate_ext[j] = placeholder[j];
  }
  for (int32_t j1 = 0; j1 < 4; ++j1) {
    concatenate_ext[(j1 + 4)] = placeholder1[j1];
  }
  return 0;
```

Old version: 
```
  void* const_vector_let = (&(global_workspace_6_var[64]));
  void* cumsum_let = (&(global_workspace_6_var[48]));
  for (int32_t i = 0; i < 2; ++i) {
    ((int64_t*)const_vector_let)[i] = ((i == 1) ? (int64_t)4 : ((i == 0) ? (int64_t)4 : (int64_t)0));
  }
  for (int32_t i1 = 0; i1 < 2; ++i1) {
    ((int64_t*)cumsum_let)[i1] = ((i1 == 1) ? (int64_t)4 : (int64_t)0);
  }

  int64_t cumsum_let[2] = {0, 4};

  for (int64_t j = 0; j < ((int64_t*)const_vector_let)[0]; ++j) {
    concatenate_ext[(((int64_t*)cumsum_let)[0] + j)] = placeholder[j];
  }
  for (int64_t j1 = 0; j1 < ((int64_t*)const_vector_let)[1]; ++j1) {
    concatenate_ext[(((int64_t*)cumsum_let)[1] + j1)] = placeholder1[j1];
  }
  return 0;
```

@DzAvril @shtinsa @MichaelJKlaiber @UlrikHjort-Bosch @vdkhoi @masahi

### CODE REVIEW

**Comment by altanh** [comment]
I got some promising improvements with this change (same setup as in https://github.com/apache/tvm/pull/11341#issuecomment-1159309108):
concat_compare
thanks for the PR!

**Review by altanh — APPROVED** [review]

**Comment by masahi** [comment]
@shtinsa I think `const_vector` things are intended to be unrolled during scheduling, which will probably end up in the same clean IR as the new version. That's what we do for winograd convolution, where we use `const_matrix`. Since the new concat is written in IR builder, I'm not sure if we can do the same unrolling for `cumsum` etc here.

**Review by masahi — APPROVED** [review]

**Comment by shtinsa** [comment]
Hello @masahi yes, I saw the const_matrix solution and it works on IR level, but IMHO it looks like as workaround. I suppose it is necessary to extend the codegen part to support `const_vector` with implementation of constexpr analogue from c++17, but for the provided concatenation case it is enough to have following code snippets: 
`static const int cumsum_###[2] = {...};`
`static const int const_vector_###[2] = {...};` 
where array sizes and and array internals should be formed during evaluation of `const_vector` tensors, And they are known in case of static planning, for the case with dynamic planning the concatenation code may have similar structure and `cumsum_###` and `const_vector_###` should be formed for the batch size 1,  but during the execution stage the values from these arrays  should be scaled by batch size value. 
These arrays will be moved to data section within the output so file.

**Comment by shtinsa** [comment]
I watched the stream and it looks like the problem related incorrect fusing of GRU/Attention output. @SebastianBoblest could you please provide test scenario to reproduce the issue?

**Comment by SebastianBoblest** [comment]
> I watched the stream and it looks like the problem related incorrect fusing of GRU/Attention output. @SebastianBoblest could you please provide test scenario to reproduce the issue?

Hi, I will try to create a minimal script for this next week. Thanks for still looking into this!

**Comment by SebastianBoblest** [comment]
> I watched the stream and it looks like the problem related incorrect fusing of GRU/Attention output. @SebastianBoblest could you please provide test scenario to reproduce the issue?

Hi I created a minimal example for an lstm.
It includes the python script, the model and the C sources.
I used the TVM main branch of today.
[concat_example.zip](https://github.com/apache/tvm/files/9018544/concat_example.zip)
.

**Comment by shtinsa** [comment]
Hello, thanks a lot!

**Comment by shtinsa** [comment]
Hello  @SebastianBoblest, sorry for the delayed answer, and I would like to clarify the issue from the sample above. According to the c codegen output I see that new functionality provides following code snippets:
```
TVM_DLL int32_t tvmgen_default_fused_squeeze_concatenate_1(float* placeholder, float* placeholder1, float* placeholder2, float* concatenate_ext, uint8_t* global_const_workspace_14_var, uint8_t* global_workspace_15_var) {
  void* T_squeeze_let = (&(global_workspace_15_var[32]));
  for (int32_t ax0_ax1_fused = 0; ax0_ax1_fused < 3; ++ax0_ax1_fused) {
    ((float*)T_squeeze_let)[ax0_ax1_fused] = placeholder1[ax0_ax1_fused];
  }
  for (int32_t j = 0; j < 3; ++j) {
    concatenate_ext[j] = ((float*)T_squeeze_let)[j];
  }
  for (int32_t j1 = 0; j1 < 2; ++j1) {
    concatenate_ext[(j1 + 3)] = placeholder2[j1];
  }
  return 0;
}

```
Where `squeeze` operation is not fused with `concatenation` code and I suppose you would like to see something like this:
```
TVM_DLL int32_t tvmgen_default_fused_squeeze_concatenate_1(float* placeholder, float* placeholder1, float* placeholder2, float* concatenate_ext, uint8_t* global_const_workspace_14_var, uint8_t* global_workspace_15_var) {
  for (int32_t j = 0; j < 3; ++j) {
    concatenate_ext[j] = placeholder1[j];
  }
  for (int32_t j1 = 0; j1 < 2; ++j1) {
    concatenate_ext[(j1 + 3)] = placeholder2[j1];
  }
  return 0;
}

```
where the first and second loops are fused and the T_squeeze_let buffer removed from the global space?

**Comment by SebastianBoblest** [comment]
> Hello @SebastianBoblest, sorry for the delayed answer, and I would like to clarify the issue from the sample above. According to the c codegen output I see that new functionality provides following code snippets:
> 
> ```
> TVM_DLL int32_t tvmgen_default_fused_squeeze_concatenate_1(float* placeholder, float* placeholder1, float* placeholder2, float* concatenate_ext, uint8_t* global_const_workspace_14_var, uint8_t* global_workspace_15_var) {
>   void* T_squeeze_let = (&(global_workspace_15_var[32]));
>   for (int32_t ax0_ax1_fused = 0; ax0_ax1_fused < 3; ++ax0_ax1_fused) {
>     ((float*)T_squeeze_let)[ax0_ax1_fused] = placeholder1[ax0_ax1_fused];
>   }
>   for (int32_t j = 0; j < 3; ++j) {
>     concatenate_ext[j] = ((float*)T_squeeze_let)[j];
>   }
>   for (int32_t j1 = 0; j1 < 2; ++j1) {
>     concatenate_ext[(j1 + 3)] = placeholder2[j1];
>   }
>   return 0;
> }
> ```
> 
> Where `squeeze` operation is not fused with `concatenation` code and I suppose you would like to see something like this:
> 
> ```
> TVM_DLL int32_t tvmgen_default_fused_squeeze_concatenate_1(float* placeholder, float* placeholder1, float* placeholder2, float* concatenate_ext, uint8_t* global_const_workspace_14_var, uint8_t* global_workspace_15_var) {
>   for (int32_t j = 0; j < 3; ++j) {
>     concatenate_ext[j] = placeholder1[j];
>   }
>   for (int32_t j1 = 0; j1 < 2; ++j1) {
>     concatenate_ext[(j1 + 3)] = placeholder2[j1];
>   }
>   return 0;
> }
> ```
> 
> where the first and second loops are fused and the T_squeeze_let buffer removed from the global space?

Hi @shtinsa,
thanks for taking the time to look into this. Yes I would like exactly the result you describe.

**Pull request merged**
