### PR TITLE
[docker] fixed ci-gpu docker environment path typo.

### PR DESCRIPTION
**Pull request by YubinCao**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by YubinCao** [comment]
Don't konw reviewers about the docker environment setup or cuda. @tqchen help for the review please.

**Comment by jcf94** [comment]
I would like to know which cuda version contains this dir...
I didn't find it in my 10.1 environment......

**Comment by YubinCao** [comment]
> I would like to know which cuda version contains this dir...

It is CUDA 10.0, as following code.
https://github.com/apache/tvm/blob/1a506791ba7b7f041de318b6a83c2a7f080ee1cd/docker/Dockerfile.ci_gpu#L20

The `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04`  cuda related docker file link is [here](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.0/ubuntu16.04-x86_64/base/Dockerfile).

**Comment by YubinCao** [comment]
Add @leandron as reviewer, thanks.

**Review by tqchen — APPROVED** [review]

**Review by leandron — APPROVED** [review]

**Comment by masahi** [comment]
We've got a new flaky test coming from https://github.com/apache/tvm/pull/7613 
@jwfromm

**Pull request merged**
