### PR TITLE
[Hexagon] Disable test_conv2d_nchw.py since it takes 2h in CI

### PR DESCRIPTION
**Pull request by kparzysz-quic**

### CODE REVIEW

**Comment by driazati** [comment]
fyi we were able to hide the runtime in CI via parallelism in #11132, though it'd be nice to see some more careful combing through the runtime to see why it is so long and that the runtime/test signal is valuable (to make sure we're not wasting compute time)

**Comment by mehrdadh** [comment]
This would also disable testing on real hardware. Can you use android_serial_number as 'simulator` to skip this file?

**Comment by kparzysz-quic** [comment]
I'll leave it up to you to decide whether this PR should be merged or not.

**Comment by kparzysz-quic** [comment]
Seems like it isn't needed with the Hexagon tests split into 4 parts.

**Pull request closed without merging**
