### PR TITLE
[Frontend][Tensorflow] Support explicit_paddings for TF 2.x

### PR DESCRIPTION
**Pull request by trevor-m**
* Ignore "_cloned" attr for squeeze.
* Support explicit padding for conv2d, depthwise conv2d, conv2d transpose and max_pool2d.
* Support explicit padding for conv3d also, but TF API doesnt allow you to create a conv3d op with explicit padding so there is no unit test.

### CODE REVIEW

**Comment by FrozenGene** [comment]
I worry we can not ignore it simply. According to doc: https://www.tensorflow.org/api_docs/python/tf/nn/conv2d

> Either the string "SAME" or "VALID" indicating the type of padding algorithm to use, or a list indicating the explicit paddings at the start and end of each dimension. When explicit padding is used and data_format is "NHWC", this should be in the form [[0, 0], [pad_top,pad_bottom], [pad_left, pad_right], [0, 0]]. When explicit padding used and data_format is "NCHW", this should be in the form [[0, 0], [0, 0],[pad_top, pad_bottom], [pad_left, pad_right]].

If `explicit_padding` is not None, we should apply its values. However, @trevor-m you could make a double check.

**Comment by trevor-m** [comment]
> I worry about we can not ignore it simply. According to doc: https://www.tensorflow.org/api_docs/python/tf/nn/conv2d
> 
> > Either the string "SAME" or "VALID" indicating the type of padding algorithm to use, or a list indicating the explicit paddings at the start and end of each dimension. When explicit padding is used and data_format is "NHWC", this should be in the form [[0, 0], [pad_top,pad_bottom], [pad_left, pad_right], [0, 0]]. When explicit padding used and data_format is "NCHW", this should be in the form [[0, 0], [0, 0],[pad_top, pad_bottom], [pad_left, pad_right]].
> 
> If `explicit_padding` is not None, we should apply its values. However, @trevor-m you could make a double check.

Thanks for the review! That is true, I will update this PR to properly support explicit padding.

**Comment by FrozenGene** [comment]
> > I worry about we can not ignore it simply. According to doc: https://www.tensorflow.org/api_docs/python/tf/nn/conv2d
> > > Either the string "SAME" or "VALID" indicating the type of padding algorithm to use, or a list indicating the explicit paddings at the start and end of each dimension. When explicit padding is used and data_format is "NHWC", this should be in the form [[0, 0], [pad_top,pad_bottom], [pad_left, pad_right], [0, 0]]. When explicit padding used and data_format is "NCHW", this should be in the form [[0, 0], [0, 0],[pad_top, pad_bottom], [pad_left, pad_right]].
> > 
> > 
> > If `explicit_padding` is not None, we should apply its values. However, @trevor-m you could make a double check.
> 
> Thanks for the review! That is true, I will update this PR to properly support explicit padding.

Thanks @trevor-m Our convolution op ignore `explicit_padding` attribute simply is wrong too, not only just pooling op. You could correct it too.Thanks.

**Comment by trevor-m** [comment]
@FrozenGene I've updated the PR with explicit padding support. PTAL

I noticed that while many ops now have the "explicit_paddings" attribute, the ability to actually use explicit padding in the TF python API has only exposed it for a few ops.

**Review by FrozenGene — APPROVED** [review]

**Comment by FrozenGene** [comment]
Thanks @trevor-m Merged.

**Pull request merged**
