### PR TITLE
Add Check about negative uint constant

### PR DESCRIPTION
**Pull request by haoyang9804**
Focusing the problem in [here](https://discuss.tvm.apache.org/t/check-failed-value-0u-1-vs-0-at-relay-build/12223). 
As the author said, when we `negative` after `ones_like` a `uint` variable, tvm crashes as expected. But `negative` a uint const would run smoothly. So I tried the following script, only changing `relay.var` to `relay.const`, which should crash but not.
```python
import tvm
from tvm import relay
var_7 = relay.const(1, dtype="uint64")
var_10 = relay.ones_like(var_7)
y = relay.negative(var_10)
F = relay.Function([], y)

mod = tvm.IRModule()
mod['main'] = F
print(mod)
graph, lib, params = relay.build(mod, target='llvm')  # crash

```
I have make the following change to the codebase:
    In `TryConstFold<tir::Sub>`, which is needed for `negative` operator, I add a check about potential negative uint value: If minuend is of uint and it's value is 0 while the subtrahend is of uint, then the difference would be negative and of uint. This situation should be forbidden.

### CODE REVIEW

**Comment by haoyang9804** [comment]
Could any reviewer help take a look about why my commit fails in sanity check? I do not have adequate experience in commiting fixes. Thanks in advance.

**Comment by leeexyz** [comment]
@haoyang9804 You can find the Sanity Check Log [here](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10484/5/pipeline).

change 






```c++
[2022-03-04T06:18:11.419Z] -    ICHECK(!(pa && pa->dtype.is_uint() && pa->value == 0U && b.dtype().is_uint())) << \
[2022-03-04T06:18:11.419Z] -     "Checked failed. Minuend 's value is 0U and it's dtype is uint " << \
[2022-03-04T06:18:11.419Z] -     "while Subtrahend's dtype is uint; which will cause a negative unit";
```
to
```c++
[2022-03-04T06:18:11.419Z] +    ICHECK(!(pa && pa->dtype.is_uint() && pa->value == 0U && b.dtype().is_uint()))
[2022-03-04T06:18:11.419Z] +        << "Checked failed. Minuend 's value is 0U and it's dtype is uint "
[2022-03-04T06:18:11.419Z] +        << "while Subtrahend's dtype is uint; which will cause a negative uint";
```

You'd better run the check locally before sending a PR.
```bash
bash ./tests/scripts/task_lint.sh
```

**Comment by haoyang9804** [comment]
>

**Comment by haoyang9804** [comment]
@leeexyz Thanks for you kind reply. Though I cannot run this lint script locally due to inaccessibility of some files. But finally it works after I change the format of the code.
BTW, could you please help check my commit? I am not sure whether or not my fix violates some principles of TVM

**Comment by haoyang9804** [comment]
Hi @masahi. Would you mind to take a look at this pr. Maybe it's a small problem, but I think it shows an inconsistency between uint const and uint var.

**Review by masahi — APPROVED** [review]

**Pull request merged**
