### PR TITLE
[COMMUNITY] Josh Fromm -> PMC

### PR DESCRIPTION
**Pull request by ZihengJiang**
Dear community:

Please join us to welcome Josh Fromm (@jwfromm) as a new PMC member.

Josh has been continuously working on operator support and robustness across the whole TVM stack (frontend, relay, auto scheduler).

In addition, Josh has been very actively participating in the design discussion and sharing his ideas. He has also been actively managing and reviewing the PRs and issues.

- [Commits History](https://github.com/apache/incubator-tvm/commits?author=jwfromm)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ajwfromm)
- [Community Forum Summary](https://discuss.tvm.ai/u/jwfromm/summary)

### CODE REVIEW

**Review by vinx13 — APPROVED** [review]

**Comment by shingjan** [comment]
congrats @jwfromm !

**Comment by junrushao** [comment]
Congrats!!

**Comment by jwfromm** [comment]
Thank you guys! It's an honor to work with this great community.

**Comment by leandron** [comment]
Congratulations @jwfromm !

**Pull request merged**
