### PR TITLE
[MetaSchedule] Add pass instrument to MetaSchedule api

### PR DESCRIPTION
**Pull request by tkonolige**
Add the `instrument` parameter from the `PassContext` api to the meta schedule tuning api.

@masahi @junrushao

### CODE REVIEW

**Comment by masahi** [comment]
What's the use case of this param during tuning?

**Comment by tkonolige** [comment]
A couple use cases:
- Profiling time spent in each pass during task extraction
- Enabling or disabling passes based on a certain context (a feature of the pass instrument api)

**Comment by masahi** [comment]
Is this needed only if https://github.com/apache/tvm/pull/13470 doesn't get in?

**Comment by tkonolige** [comment]
Yes that is correct.

**Comment by tkonolige** [comment]
@masahi How about we merge this as #13470 is still in discussion?

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
Hopefully we overhaul the current API to clean up mostly unused parameters.

**Pull request merged**
