### PR TITLE
Pass bisection tool using pass_instrument infrastructure

### PR DESCRIPTION
**Pull request by joshherr-quic**
This tool allows the user to bisect a run of passes via the tvm pass instrumentation infrastructure. 
Invocation is:

```
from tvm.relay.debug import PassBisection
with tvm.transform.PassContext(instruments=[PassBisection(limit=N)]):
        ...
```

In addition to the python debugging tool, an additional member has been added to PassInfoNode in order to facilitate prioritizing passes that MUST run in order for Relay/TIR to compile. That is, passes marked with the new run_always flag will ALWAYS run, regardless of the limit. Below is a list of the passes that were marked with this new attribute.

["sequential",
 "InferType",
 "LowerTE",
 "LowerTensorExpr",
 "FuseOps",
 "PlanDevices",
 "PlanDevicesCore",
 "BindTarget",
 "Filter",
 "FoldConstant",
 "DynamicToStatic",
 "SimplifyInference",
 "tir.LowerIntrin",
 "tir.LowerTVMBuiltin",
 "tir.Simplify",
 "tir.MakePackedAPI",
 "tir.VectorizeLoop",
 "tir.StorageFlatten",
 "tir.StorageFlattener",
 "tir.StorageFlatten_impl",
 "tir.BufferShapeLegalize",
 "tir.BufferStrideLegalize"]

These passes were arrived at via trial and error compiling a resnet50 caffe model until it ran with limit=1 (only the first pass runs). It may  not be exhaustive.

### CODE REVIEW

**Review by mbs-octoml — CHANGES_REQUESTED** [review]
Personally I've found just letting compilation run and looking at the debug dump (eg using TVM_LOG_DEBUG="DEFAULT=1") is enough to help me find where things have gone off the rails. However I can see having a hard stop would also be valuable.

The required vs optional distinction is probably going to be fragile, especially since passes often build on each other. But tackling that issue is a design problem on its own (eg can me label passes with 'requires' and have a pass list validation or completion step to 'resolve interpass dependencies'). Would you consider dumbing down this instrument to simply count passes and not try to take on the opt vs req distinction?

Thanks!

**Comment by joshherr-quic** [comment]
> Personally I've found just letting compilation run and looking at the debug dump (eg using TVM_LOG_DEBUG="DEFAULT=1") is enough to help me find where things have gone off the rails. However I can see having a hard stop would also be valuable.
> 
> The required vs optional distinction is probably going to be fragile, especially since passes often build on each other. But tackling that issue is a design problem on its own (eg can me label passes with 'requires' and have a pass list validation or completion step to 'resolve interpass dependencies'). Would you consider dumbing down this instrument to simply count passes and not try to take on the opt vs req distinction?
> 
> Thanks!

That fragility is something I was worried about as well. I think it makes sense to tackle that in a separate PR. I'll go ahead and limit this code to just printing debug info.

**Comment by joshherr-quic** [comment]
@mbs-octoml I went ahead and stripped the instrumentation down to just print debug info..

**Comment by jroesch** [comment]
@joshherr-quic @mbs-octoml can you update this one, CI is red, thanks!

**Comment by masahi** [comment]
cc @mbs-octoml

**Pull request closed without merging**
