### PR TITLE
Pytorch qnn frontend. Avoid explicit pad in case of 'zero_point == 0'

### PR DESCRIPTION
**Pull request by apeskov**
Explicit pad is not required when zero point is zero.

Moreover, explicit pad specification on frontend level looks very suspicious. `qnn.conv2d` semantic already provides a proper handling of pad with non trivial zero point:
https://github.com/apache/tvm/blob/725ae75af4997ff3a5107cc82d64609773de23a0/src/relay/qnn/op/convolution.cc#L224-L226

### CODE REVIEW

**Comment by masahi** [comment]
Explicit pad is necessary for BYOC use cases where we don't use QNN lowering. So the pad value needs to be available at a QNN graph level.

**Comment by apeskov** [comment]
@masahi Thank you for answer. Could you please specify which particular BYOC doesn't support pads for qnn.conv2d? Or you mean that they doesn't support pad with zero point? Does this patch has a conflict with that limitation?

I still need in that PR. In the opposite case I will have to write a pass which will merge pad back to convolution.

**Comment by apeskov** [comment]
In general, current situation when we try to solve some limitation of some BYOC runtime on frontend level is quite suspicious. From my point of view frontend should convert model as is. If BYOC has some limitation it should apply converter passes to try to eliminate these limitations.

**Comment by masahi** [comment]
This is not about a limitation of BYOC. Originally you said "qnn.conv2d semantic already provides a proper handling of pad with non trivial zero point:" but this is not enforced for BYOC cases when this lowering code is not used. 

I think the explicit padding makes the requirement of pad by zero point clearer. Actually QNN didn't properly pad with a zero point until someone pointed out this bug. So I believe it is better to make this requirement obvious rather than relying on each BYOC backend to properly handle pad by zero point.

For your purpose, there is already a pass that folds pad with conv2d https://github.com/apache/tvm/blob/78657e1f8b2c97c3acc389e2b757c6ac8174388d/src/relay/transforms/fold_explicit_padding.cc#L41. You can extend that pass to handle `qnn.conv2d`.

**Pull request closed without merging**
