### PR TITLE
[BUGFIX] Check that virtual device is unchanged in WithFields

### PR DESCRIPTION
**Pull request by electriclilies**
Right now, WithFields doesn't check that the virtual device is unchanged, which is incorrect-- this was either a bug or due to a bad merge. I also set the default value of virtual_device_ to FullyUnconstrainedThis change fixes the problem. 

NOTE: To make sure that virtual_device_ is propagated across the python boundary, I had to visit the field in VisitAttrs. This changes the serialization of the relay expressions.

@mbs-octoml @mikepapadim

### CODE REVIEW

**Review by mbs-octoml — APPROVED** [review]

**Review by mikepapadim — APPROVED** [review]
LGTM, just check the CI

**Comment by electriclilies** [comment]
I also visit the virtual device in the TVMAttrVisitor to ensure that the virtual device is properly copied across the FFI boundary.

**Comment by electriclilies** [comment]
Rebased with #9874

**Review by masahi — APPROVED** [review]

**Comment by electriclilies** [comment]
Thanks @masahi!

**Pull request merged**
