### PR TITLE
Fix use of fallback AutoTVM knobs in default scheduling

### PR DESCRIPTION
**Pull request by elvin-n**
Previously knob values depended on order of explicit cfg update and cfg.define_split calls in fallback mode

I.e. schedule depend where and when default KNOB values are defined. I.e. for [dense x8](https://github.com/apache/tvm/blob/main/python/tvm/topi/x86/dense.py#L168)6 we define a split space and then if we are in fallback mode, we manually point some heuristic factors. And everything works well. But for batch_matmul x86 we define certain values in case of fallback in [compute func first](https://github.com/apache/tvm/blob/main/python/tvm/topi/x86/batch_matmul.py#L74) and only then [in schedule](https://github.com/apache/tvm/blob/main/python/tvm/topi/x86/batch_matmul.py#L120) these values will be overwritten by first pair from search space that is (-1,1).

This fix makes any order of execution reuse predefined values in fallback mode

### CODE REVIEW

**Review by comaniac — COMMENTED** [review]
The fix makes sense to me. Could you add a test case?

**Comment by elvin-n** [comment]
@comaniac will try to add the test

**Comment by junrushao1994** [comment]
That PR looks pretty good. Ping for update :-)

**Review by junrushao1994 — APPROVED** [review]

**Comment by junrushao1994** [comment]
Thanks @elvin-n @comaniac! The PR is merged :-)

**Pull request merged**
