### PR TITLE
[CMSIS-NN] Remove support for the old CMSIS NN project

### PR DESCRIPTION
**Pull request by NicolaLancellotti**
Pr: #13656 adds support for the new CMSIS NN project

After the docker image is updated we can remove support for the old CMSIS NN project.

### CODE REVIEW

**Comment by NicolaLancellotti** [comment]
@mehrdadh @ashutosh-arm

**Comment by mehrdadh** [comment]
I'm gonna update the docker image to 20.04 once this is merged:
https://github.com/apache/tvm/pull/13736
then you can open this PR

**Comment by ashutosh-arm** [comment]
@mehrdadh we would need to merge https://github.com/apache/tvm/pull/13762 before building Cortex-M docker image. Without that change, some Zephyr tests might fail.

**Comment by mehrdadh** [comment]
You need to update the image as well, otherwise it doesn't pass the tests. You can use this image that I just pushed
https://hub.docker.com/layers/tlcpack/ci-cortexm/20230111-165944-a9c6f137d/images/sha256-d6b549d9dd5049b717d8e119477c184b18cc52182169c628e050daa146a98776?context=explore

Also, to actually test the PR you need to also commit this to a TVM branch. Let me know if you don't have access and I will do it.

**Comment by mehrdadh** [comment]
@ashutosh-arm I don't think we need https://github.com/apache/tvm/pull/13762 to merge this. Because Zephyr project API checks for dependency to CMSIS_NN and if the project is not dependent it doesn't need to add CMSIS_NN to generated project

**Comment by mehrdadh** [comment]
Also we could separate updating the image from this PR, I think that should be fine as well

**Comment by mehrdadh** [comment]
https://github.com/apache/tvm/pull/13764 is updating the image.

**Review by ashutosh-arm — APPROVED** [review]
Thanks @NicolaLancellotti. LGTM!

**Comment by NicolaLancellotti** [comment]
I rebased the pr, and CI is now green.

**Pull request merged**
