### PR TITLE
[microTVM][Arduino] Fix Arduino Versions in RVM Build

### PR DESCRIPTION
**Pull request by mehrdadh**
Currently it downloads the latest cli version which causes breaks in RVM build. This PR fixes the version at 0.18.3 which is the version that we have tested the hardware.

Also the SPRESENSE release version was generic which we should fix to 2.2.1 based on the current hack.

cc @areusch @guberti

### CODE REVIEW

**Comment by mehrdadh** [comment]
This version is released here: https://app.vagrantup.com/tlcpack/boxes/microtvm-arduino-0.18.3/versions/0.0.2

**Review by leandron — APPROVED** [review]
LGTM

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
thanks @mehrdadh , the PR is merged!

**Comment by guberti** [comment]
Thanks for the PR @mehrdadh! Recent changes to the Spresense SDK have rendered some of our bugfixes unnecessary, so I'm working on a follow up PR to remove those.

**Comment by mehrdadh** [comment]
@guberti sounds great!

**Pull request merged**
