### PR TITLE
[TE/TIR] Fix create_prim_func to properly handle rank 0 tensors.

### PR DESCRIPTION
**Pull request by tkonolige**
We handle lowering rank 0 tensors by lowering them to rank 1 buffers with a single element.

@junrushao1994 @Hzfengsy @vinx13 @MasterJH5574 @tqchen

### CODE REVIEW

**Comment by junrushao1994** [comment]
@Hzfengsy would you like to take a look at this corner case? Basically it is due to the fact that 0-dimension tensor in Relay is lowered to a block with 0 IterVars, which causes ambiguity with the "opaque" block.

**Review by junrushao1994 — APPROVED** [review]
Thanks for the fix!

**Comment by tqchen** [comment]
Perhaps we should think about proper rank 0 buffer support instead to change to rank 1

**Comment by junrushao1994** [comment]
@tqchen The main problem is the ambiguity introduced by the definition of an opaque block. An alternative approach is that we just add a dummy iter-var in the block with unit extent. What do you think?

**Comment by tqchen** [comment]
I still think it would be great to have first-class 0-rank buffer and compute support, so we do not need to do special casing to handle the items. Such first-class support will bring a lot of benefit later, for example, in the cases such as adding a batching to the entire loop computations

**Comment by tqchen** [comment]
Suggest close this for now and instead move to a tracking issue that tracks the 0-rank support in various places of tensorIR.

**Comment by junrushao1994** [comment]
Given this PR does help some workloads (some subgraphs in BERT) temporarily, and doesn't introduce new problems, let's merge it in and start a tracking issue

**Pull request merged**
