### PR TITLE
[Frontend][Keras] Fix Dense with 3d inputs

### PR DESCRIPTION
**Pull request by trevor-m**
Squeeze takes a list of ints, but keras frontend had a case where it used a single int which caused the following error:

```
TVMError: In function relay.op._make.squeeze: error while converting argument 1: [18:39:52] /home/ubuntu/incubator-tvm/include/tvm/runtime/packed_func.h:1618: ----------------------------------
-----------------------------         
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.   
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
                                                 
  Check failed: type_code_ == kTVMObjectHandle: expected Object but got int
```

### CODE REVIEW

**Comment by trevor-m** [comment]
@siju-samuel @jwfromm @mbrookhart @leandron Could you please review?

**Review by leandron — APPROVED** [review]
LGTM. Just noticed there is one test failing for both keras and tf_keras.

**Review by mbrookhart — APPROVED** [review]

**Comment by trevor-m** [comment]
Thanks for the review @mbrookhart @leandron 
The tests are passing now.

**Comment by mbrookhart** [comment]
Thanks @trevor-m @leandron

**Pull request merged**
