### PR TITLE
Fix compilation errors with clang 11

### PR DESCRIPTION
**Pull request by kparzysz-quic**
- Replace `llvm::MaybeAlign::MaybeAlign()` with `llvm::MaybeAlign()`.
- Use `ICHECK` instead of `assert` in hexagon_module.cc.

### CODE REVIEW

**Comment by masahi** [comment]
`MaybeAlign` change was added in https://github.com/apache/tvm/pull/7617 
I wonder why you hit this code path with clang11?

cc @LuukOddity please confirm if this still builds for you

**Comment by kparzysz-quic** [comment]
I used clang 11 to compile this, not as the source of LLVM libraries.  I use LLVM trunk (i.e. the ToT main branch) for the code generation libraries,

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
Thanks @kparzysz-quic

**Comment by LuukOddity** [comment]
Sorry for the late reply, I see it's already merged. Should I still check @masahi?

**Pull request merged**
