### PR TITLE
Make the TVM targets list available in Python

### PR DESCRIPTION
**Pull request by NicolaLancellotti**
This PR allows to get the names of the available targets in Python

### CODE REVIEW

**Comment by NicolaLancellotti** [comment]
Please, @mbaret can you review?

**Review by comaniac — APPROVED** [review]
LGTM.
cc @junrushao1994

**Review by leandron — APPROVED** [review]

**Review by mbaret — APPROVED** [review]
lgtm too.

**Comment by junrushao1994** [comment]
To clarify, we have `ListTags` to list all the target tags, and this PR further adds the functionality to list target kinds. Is my understanding correct? Thanks a lot!

**Comment by junrushao1994** [comment]
Also CC: @zxybazh

**Review by junrushao1994 — CHANGES_REQUESTED** [review]
The implementation looks good to me. The only thing we probably need to discuss is the name of APIs. In our RFC (https://discuss.tvm.apache.org/t/rfc-tvm-target-specification/6844), we use `kind` or `TargetKind` to indicate the first term in the target string (e.g. `llvm`, `cuda`, `nvptx`, etc). Therefore, to keep things consistent, do you think we should be more specific here and say like `ListTargetKind` instead of using `names`?

**Review by zxybazh — APPROVED** [review]
LGTM.

**Comment by mbaret** [comment]
> Therefore, to keep things consistent, do you think we should be more specific here and say like `ListTargetKind` instead of using `names`?

I would be slightly concerned that the user expectation for ListTargetKind(s) would be a list of TargetKind type, rather than a list of string names. Perhaps `ListTargetKindNames` instead?

**Comment by comaniac** [comment]
I reviewed the changes again based on the discussion. Why don't we just add a syntactic sugar`Target.list_tags().keys()` in the Python side so that we don't need a new function?

**Comment by leandron** [comment]
> I reviewed the changes again based on the discussion. Why don't we just add a syntactic sugar`Target.list_tags().keys()` in the Python side so that we don't need a new function?

I might be wrong, but I was looking into the sources and trying to understand this. When  you mention `list_tags()`, are you referring to `tvm.target.tag.list_tags()`?

If so, I'm not getting what I expected to get from there, is that a bug?
```
>>> tvm.target.tag.list_tags()
{"nvidia/gtx1080ti": cuda -keys=cuda,gpu -arch=sm_61 -max_num_threads=1024 -thread_warp_size=32, "nvidia/rtx2080ti": cuda -keys=cuda,gpu -arch=sm_75 -max_num_threads=1024 -thread_warp_size=32}
```

@junrushao1994, what is the conceptual difference between `kind` and `tag`, in the target jargon?

**Comment by comaniac** [comment]
Ah I messed up with `tag.cc` and `target_kind.cc`...

So basically `kind` refers to the backend, such as `llvm`, `cpu`, `gpu`, `cuda`, and `tag` refers to a complete target string or JSON, such as `cuda -keys=cuda,gpu -arch=sm_61 -max_num_threads=1024 -thread_warp_size=32`. Since target kind is less used and I supposed this PR is for TVMC, I assume TVMC users should mostly just use tags to make sure everything is covered.

**Comment by zxybazh** [comment]
I think the PR is just to demonstrate the supported backend types, which is called `kind`, as @comaniac mentioned. Though accessible via code, a function would be helpful. `tag` is only for the usage of a complete target configuation like pre-defined tags or json target string.

**Comment by leandron** [comment]
> I think the PR is just to demonstrate the supported backend types, which is called `kind`, as @comaniac mentioned. Though accessible via code, a function would be helpful. `tag` is only for the usage of a complete target configuation like pre-defined tags or json target string.

Yes, I can confirm we would like - from this PR - a list of str that contains all `kind` of targets, such as llvm, cuda, opencl, for validation and better error messages on TVMC.

I think the current proposal is not creating a lot of overhead.

My suggestion is to get agreement on the proper name for the function, unless there is a duplication of functionality with something already in the code base - what do you think?

**Comment by zxybazh** [comment]
I agree. For the function name selection, I would prefer to use `ListTargetKind(s)` as @junrushao1994 suggested, somehow more consistent with the meaning of `kind`. `Names` still seem a bit vague for me, but I would also be fine with it.

**Comment by comaniac** [comment]
Agree on the ListTargetKinds in this case. ListTargetKindNames doesn't make it more clear to me.

**Comment by leandron** [comment]
Thanks for the replies @comaniac @zxybazh. One final thing (to get you on the right timezone) - just so that we update gwith a potential final version of the PR.

Any preferences on the Python-side function? At the moment I see it is called `Target.names()`. Shall we change it to  `Target.kinds()` for example, or even to something else?

**Comment by zxybazh** [comment]
On Python-side function, I think `names` is a bit vague. I think `kinds` is more clear and consistent with the `libs` function name.

**Comment by comaniac** [comment]
IMHO, it would be better to use a more consistant name. i.e., `list_kinds`. This also aligns to the naming convension of `list_tags`.

**Comment by leandron** [comment]
> On Python-side function, I think `names` is a bit vague. Instead, `kinds` is more clear and consistent with the other `libs` function name.

I think @comaniac makes a good point for `list_kinds()` - would you agree with that @zxybazh? If so, we’ll update it tomorrow with the resulta of this discussion.

**Comment by zxybazh** [comment]
Oh, I see. It's following the `list_tags` function in `tag.py`. Sounds good to me.

**Comment by junrushao1994** [comment]
Thanks for the discussion, and sorry for the late reply!

To clarify:
- Target `tag`s are an alias and an efficient way to create concrete targets. For example, `nvidia/rtx2080ti` is short for "cuda -arch sm_75 -shared_memory_per_block 49152 -registers_per_block 65536 -thread_warp_size 32".
- Target `kind`s mean specifically the codegen target, i.e. do we codegen to LLVM IR (where the kind is "llvm"), or CUDA C (where the kind is "cuda"), etc.

**Comment by junrushao1994** [comment]
I agree with @leandron and @comaniac. Perhaps a good way is to have both `list_kinds` and `list_tags` correspondingly

**Comment by NicolaLancellotti** [comment]
I renamed "ListAllNames" to "ListTargetKinds" and "names" to "list_kinds".

**Comment by comaniac** [comment]
@junrushao1994 please take a final look to approve and merge.

**Review by junrushao1994 — APPROVED** [review]
Looks good to me! Thanks for the discussion!

**Pull request merged**
