### PR TITLE
[Arith] Updated arith::DetectIterMap to keep extent=1 components

### PR DESCRIPTION
**Pull request by Lunderberg**
Previously, arith::DetectIterMap simplified the output expression by replacing iteration variables with extent==1 with their value.  This prevented the return value from being used in arith::InverseAffineIterMap to solve for the variable, as it no longer existed in the returned expressions.

This commit changes arith::DetectIterMap to keep the iteration variable even if extent==1, and adds a motivating unit test that requires this updated behavior.

### CODE REVIEW

**Comment by Lunderberg** [comment]
Following a discussion with @vinx13.  All tests in `test_arith_iter_affine_map.py` and `test_transform_layout.py` pass locally.  It's possible that the change to `DetectIterMap`'s simplifications will result in failures elsewhere, so I'm watching the CI.

**Comment by Lunderberg** [comment]
CI confirms that there are definitely locations that rely on simplifications being performed as part of `DetectIterMap`.  Taking a glance at the 24 failures, some would be short updates to the test cases, but others fail by breaking internal assumptions.  I've added another commit to maintain the same default behavior of simplifying trivial iterators as part of `DetectIterMap`, but using a flag to maintain them in the output when needed.

**Comment by vinx13** [comment]
To make the API consistent, could you also update the FFI API https://github.com/apache/tvm/blob/main/src/arith/iter_affine_map.cc#L943-L948?

**Review by Hzfengsy — APPROVED** [review]
LGTM, if you can update the FFI API as @vinx13's suggestion

**Comment by Lunderberg** [comment]
Certainly, and thank you for catching it!  The FFI and the Python API have been updated to expose the `simplify_trivial_iterators` argument.

**Review by vinx13 — APPROVED** [review]

**Pull request merged**
