### PR TITLE
Add MicroTVM support for the STM32F746 Discovery board

### PR DESCRIPTION
**Pull request by tom-gall**
This one line patch adds support for the ST STM32F746 Discovery board with µTVM.

Signed-off-by: Tom Gall <tom.gall@linaro.org>

### CODE REVIEW

**Comment by tom-gall** [comment]
@areusch @gromero

**Comment by areusch** [comment]
@tom-gall want to add discovery board to the [list of supported boards](https://github.com/apache/tvm/blob/main/docs/microtvm/index.rst#supported-hardware)? in practice I think we'll likely distribute this elsewhere in the future, but for now it'd be nice to keep it up to date.

**Review by areusch — APPROVED** [review]
@tom-gall @gromero sorry for the delay

@tmoreau89 can you merge?

**Review by tmoreau89 — APPROVED** [review]
LGTM

**Pull request merged**
