### PR TITLE
[Relay][Frontend][Onnx] Set default value of p in LpPool as 2

### PR DESCRIPTION
**Pull request by luyaor**
See https://github.com/apache/tvm/issues/7241

### CODE REVIEW

**Comment by luyaor** [comment]
@jwfromm

**Comment by jwfromm** [comment]
Can you add a test that would trigger the error? Once that's included in this PR it should be good to go. Thanks for identifying and fixing this.

**Comment by tqchen** [comment]
ping @jwfromm @luyaor , it would be great to follow up on this

**Comment by luyaor** [comment]
Hi @jwfromm , I added a testcase.

**Review by jwfromm — APPROVED** [review]
LGTM, thanks for this fix!

**Comment by jwfromm** [comment]
Looks like you just need to format the test file and we can merge.

**Comment by luyaor** [comment]
Hi @jwfromm , what do you mean that `format the test file`? I am a little bit confused.

**Comment by tqchen** [comment]
run `tests/lint/git-black.sh -i upstream/main`

**Pull request closed without merging**
