### PR TITLE
[Fix] Fix some typos.

### PR DESCRIPTION
**Pull request by Yulv-git**
Fix some typos in src/.

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
Can you do one single commit?

**Comment by Yulv-git** [comment]
> Can you do one single commit?

For fear that when all the changes are submitted together, all the changes will be terminated because the CI/CD of a certain change does not pass. And considering that some open source repositories recommend separate PRs when there are many files to be modified, I submitted PRs separately.
If I need to put all the changes into one PR, I will merge it later.

**Comment by masahi** [comment]
Yeah, please merge them into a single PR.

**Comment by Yulv-git** [comment]
> Yeah, please merge them into a single PR.

OK, thanks!

**Review by MarisaKirisame — APPROVED** [review]
LGTM

**Comment by junrushao1994** [comment]
Quiet curious: how did you find out all those typos? This is super cool

**Comment by Yulv-git** [comment]
> Quiet curious: how did you find out all those typos? This is super cool

 Maybe you can see my repo ([Search-for-Typos](https://github.com/Yulv-git/Search-for-Typos)) for details.

**Comment by junrushao1994** [comment]
This is quite cool!! Thanks @Yulv-git for sharing!

**Comment by junrushao1994** [comment]
looks like this PR cannot pass CI due to some changes in CI files. @driazati would you mind helping this PR pass? Would be super helpful to have PRs like this

**Comment by junrushao1994** [comment]
still failed :-(

**Comment by driazati** [comment]
hey @Yulv-git thanks for persisting with this, could you run `black tests/python/frontend/onnx/test_forward.py` to fix the lint error?

**Comment by Yulv-git** [comment]
> hey @Yulv-git thanks for persisting with this, could you run `black tests/python/frontend/onnx/test_forward.py` to fix the lint error?

Sorry, I cannot run `black tests/python/frontend/onnx/test_forward.py` due to environmental problems.

**Comment by driazati** [comment]
looks like we have permission to update your fork branch, I can handle shepherding this through CI in that case

**Comment by Yulv-git** [comment]
> looks like we have permission to update your fork branch, I can handle shepherding this through CI in that case

Thanks for your help.

**Comment by driazati** [comment]
merged! thanks for your patience @Yulv-git

**Pull request merged**
