### PR TITLE
[Frontend, Tensorflow, Tensorflow2] Tensorflow frontend op refactor

### PR DESCRIPTION
**Pull request by rohanmukh**
This PR refactors the current `tensorflow.py` parser and separates the code for the ops into a separate file `tensorflow_ops.py`. The new parser for handling tensorflow2 models in TVM, ie `tensorflow2.py`, imports the existing frontend op codes from `tensorflow.py`. With the current PR both of these frontend codes will import the ops from a common file for the ops in `tensorflow_ops.py`. 

This PR is in line with the original plan of supporting tensorflow2 parser in TVM frontend as in the discussion [#4102 ](https://github.com/apache/tvm/issues/4102) Exact commit plan [here](https://github.com/apache/tvm/issues/4102#issuecomment-784456088).

Co-authored-by: Rohan Mukherjee <mukrohan@amazon.com>
Co-authored-by: Xingyu Zhou <zhoxingy@amazon.com>
Co-authored-by: David Huang <davhuan@amazon.com>
Co-authored-by: Srinidhi Goud <srinidhi.goud29@gmail.com>
Co-authored-by: Xiao <weix@amazon.com>

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by rohanmukh** [comment]
@trevor-m @yongwww  @weixa @zxy844288792 @dvhg @srinidhigoud @zhiics

**Comment by rohanmukh** [comment]
@mbrookhart @srkreddy1238 @kevinthesun @masahi

**Review by trevor-m — APPROVED** [review]
LGTM

**Review by FrozenGene — APPROVED** [review]

**Comment by FrozenGene** [comment]
Thanks @rohanmukh @trevor-m TF2 is one important frontend for TVM users. Great work and let us go on!

**Pull request merged**
