### PR TITLE
[MetaSchedule][Refactor] Clarify Integration Logic

### PR DESCRIPTION
**Pull request by junrushao1994**
Based on @masahi's PR #10578, we are able to further simplify the logic and remove redundancy.

Changes:
- Remove `MetaScheduleContext`, which is not useful any more after Masa's new relay backend;
- Consolidate logic around `ApplyHistoryBest`, and slightly improve the error message;
- Separate `integration.py` into 3 files: `apply_history_best.py`, `extracted_task.py` and `relay_integration.py`;

These changes make future Relax integration easier - the only thing needed is to add `relax_integration.py` without having to worry about potential conflicts.

### CODE REVIEW

**Comment by junrushao1994** [comment]
CC: @YuchenJin @masahi @zxybazh

**Review by masahi — APPROVED** [review]

**Review by YuchenJin — APPROVED** [review]
LGTM! :)

**Review by yongwww — APPROVED** [review]

**Comment by sunggg** [comment]
Overall, LGTM. 
One quick question - it seems like this PR replaces MetaScheduleContext to ApplyHistoryBestContext? 
Does it mean other functionalities, like tuning, does not need any contextual information?

**Comment by junrushao1994** [comment]
@sunggg Thanks for asking!

There is no breaking change in terms of API usage, given ApplyHistoryBest is the only framework-facing integration point. It's still used in the same way like:

```python
with ApplyHistoryBest(database=...):
   ...
```

`MetaScheduleContext` is no longer in use after @masahi's refactoring in both Relay (https://github.com/apache/tvm/pull/10578) and Relax (https://github.com/tlc-pack/relax/pull/92), so it makes sense to just remove it

**Comment by sunggg** [comment]
@junrushao1994 Thank you for the explanation. Makes sense to me.

**Review by zxybazh — APPROVED** [review]
LGTM, thanks for the refactor!

**Pull request merged**
