### PR TITLE
[Codegen][Metal] Disable cross-function call in Metal codegen

### PR DESCRIPTION
**Pull request by MasterJH5574**
This PR restores the Metal codegen to the one before #15835. Due to there will likely be no internal function call in Metal, we think it is safe to do so.

Verified that with this PR, the metal codegen and iPhone codegen will not fail and will work properly.

The reason of the iPhone codegen failure is because the multiple declarations of a same function will lead to multiple emissions of a same structs, which is not recognizable by the metal compiler.

### CODE REVIEW

**Comment by MasterJH5574** [comment]
cc @Lunderberg @tqchen

**Comment by junrushao** [comment]
CC @Lunderberg would you mind taking a look? BTW, is there a way to unit-test it as you enabled a while ago?

**Comment by tqchen** [comment]
Thanks @MasterJH5574 , can you also document the rationale of that we specialize this part. aka we do not have multiple cross function calls, so we can keep the delcaration once to keep things simple

**Comment by MasterJH5574** [comment]
> BTW, is there a way to unit-test it as you enabled a while ago?

Reading the failure reason elaborated here https://github.com/apache/tvm/pull/15835#issuecomment-1789308138, I feel the way to reproduce or test the issue is to
* construct an IRModule where one PrimFunc _containing trailing int/float parameters_ is called at least twice,
* build the IRModule to `iphone` target.

**Comment by Lunderberg** [comment]
If possible, I'd like to fix the functionality and not just revert it.  https://github.com/apache/tvm/pull/14985 and https://github.com/apache/tvm/pull/14862 have been on the back burner for quite a while, mainly due to breakage they cause in `tvm.contrib.ethosu`, but are still changes I'd like to get around to landing at some point.

@MasterJH5574 We should be able to test it in CI, since I added compile-only testing of the metal backend in #15756.  Functionality that isn't tested in CI is inherently unstable, and so CI testing is preferable in addition to local testing.

**Comment by Lunderberg** [comment]
> BTW, is there a way to unit-test it as you enabled a while ago?

The two steps to add a Metal specific unit test are to (1) decorate the test with `@tvm.testing.requires_metal(support_required="compile-only")` and (2) add the test in the `Minimal Metal Compile-Only` section of `.github/workflows/main.yml`.  This only validates the compiler support, as we don't have a CI environment that has Metal GPUs, but that should catch the majority of codegen failure modes.

**Comment by MasterJH5574** [comment]
@Lunderberg I agree that it would be better if the issue can be fixed! For this PR, the overall codegen still bases on the updated codegen flow (we did not revert the previous PR). There is no inter function calls between kernels in Metal, so it is okay to keep the former flow in Metal codegen for now as a swift fix to the codegen issue.

And thanks for the pointer on testing. I will add a test soon.

**Comment by Lunderberg** [comment]
There aren't currently any inter-function calls in Metal, but it is part of my planned implementation for https://github.com/apache/tvm/pull/14985.  Breaking a change apart into the underlying infrastructure changes and the usage of that infrastructure allows the changes to be tested and integrated separately.

**Comment by Lunderberg** [comment]
That said, I have an idea for how to work around the lack of inter-function calls in codegen.  Since we can represent inter-function calls in TIR, we could add a `InlineLocalFunctions` pass that removes any internal private functions that result from the single-module lowering flow.

**Comment by tqchen** [comment]
I like the idea of keeping things simple on specific shader backend like metal, inlining sounds like a good approach

**Comment by MasterJH5574** [comment]
Finished adding a test and included it in “minimal Metal compile-only.” Also added a note in `AddFunction` in codegen_metal.cc

**Review by Lunderberg — CHANGES_REQUESTED** [review]
Given the special packing used for the scalar buffers, and that there's a possibility of a workaround, I think these sections makes sense to revert.

In the `void CodeGenMetal::VisitExpr_(const CallNode* op) override`, can we add an explicit check for the inter-function call?  Otherwise, this falls back to the `CodegenC` default that support it.

```c++
CHECK(!op->op.as<GlobalVarNode>())
    << "CodegenMetal does not support inter-function calls, "
    << "but expression " << GetRef<Expr>(op)
    << " calls PrimFunc " << op->op;
```

**Comment by MasterJH5574** [comment]
Thanks @Lunderberg for the suggestions! Added the check in CallNode visit function.

**Review by Lunderberg — APPROVED** [review]
Thank you, and looks good to me!  The unit test looks really good; I especially like the explanation of the known portions of the failure mode.

**Comment by Lunderberg** [comment]
Circling back to this, I have PR #16184 submitted, which adds a TIR transform that can inline private function calls.  That way, the user-facing functionality of TIR subroutines can be used, without requiring every codegen to natively support subroutines.

**Pull request merged**
