### PR TITLE
[TIR] Change Integer Implicit Conversion Rule to C Standard Way

### PR DESCRIPTION
**Pull request by Johnson9009**
Current integer implicit conversion rule is simple.

- int8 + uint32 -> int32 + int32
- int16 + uint16 -> int16 + int16

This behavior is not same with the C standard, this PR use the C standard rules, so the preceding examples will be changed to something below.

- int8 + uint32 -> uint32 + uint32
- int16 + uint16 -> uint16 + uint16

### CODE REVIEW

**Comment by Johnson9009** [comment]
This PR can fix the issue reported at https://discuss.tvm.apache.org/t/tir-const-1-tir-const-true-throws-valueerror/10667, it do the thing that PR #8706 did passingly.

@tqchen @YuchenJin @junrushao1994 @ganler Please help to review.

**Review by YuchenJin — APPROVED** [review]
LGTM! Thanks @Johnson9009 for the contribution! (I think the CI fail is unrelated to the changes made by this PR.)

**Comment by junrushao1994** [comment]
Also CC @ganler to take a second look :-)

**Comment by junrushao1994** [comment]
I just re-triggered the CI

**Comment by junrushao1994** [comment]
The CI failure is not relevant to this PR. This commit addressed the failure: https://github.com/apache/tvm/commit/f5661f4e78cae5f62bc172559040576cd2fd20f2

**Comment by junrushao1994** [comment]
I rebased the PR to main:HEAD so that it could pass the CI

**Review by ganler — APPROVED** [review]
LGTM.

**Comment by junrushao1994** [comment]
Looks like the PR consistently fails on the following two test cases, and it doesn't seem to be precision issues:

```
FAILED tests/python/frontend/onnx/test_forward.py::test_random_uniform[llvm]
FAILED tests/python/frontend/onnx/test_forward.py::test_random_uniform[cuda]
```

Would you please take a closer look at the specific cases and get them fixed so that we could merge this PR? Thanks a lot!

**Comment by Johnson9009** [comment]
> Looks like the PR consistently fails on the following two test cases, and it doesn't seem to be precision issues:
> 
> ```
> FAILED tests/python/frontend/onnx/test_forward.py::test_random_uniform[llvm]
> FAILED tests/python/frontend/onnx/test_forward.py::test_random_uniform[cuda]
> ```
> 
> Would you please take a closer look at the specific cases and get them fixed so that we could merge this PR? Thanks a lot!

I have found these two test cases will be fail with my patch all the time, after some investigation I found it isn't easy to fix, it will involve at least 2 PR #7083, PR #8426. The implementation of these 2 test cases depends on #7083, and the implementation of #7083 involve lots of integer implicit conversion between "uint64" and "int32".

In short, we need the authors(@jwfromm) of the test cases to confirm whether the golden is correct, and this maybe need the authors(@tkonolige) of PR #7083 to confirm whether the previous integer implicit conversion logic is what they expected firstly.

Let me explain it more detail

https://github.com/apache/tvm/blob/3e0c461f26b5174759dbb932986006f73a94a816/python/tvm/topi/random/kernel.py#L264-L268
For the line 266 code, the type of the expression `tir.const(2 ** 64 - 1, dtype=gen.dtype) - out_len` is something like `uint64 - int32`, this subtraction will call function `BinaryOpMatchTypes` to do the integer implicit conversion, then the expression will be changed to something like `int64(uint64) - int64(int32)`, (this logic is consistent before and after the PR #8706, so we can ignore the changes made by PR #8706 for easier analysis).

So @tkonolige please help to check whether this conversion logic is what you expected(in my opinion, it is wrong for converting tir.const(2**64 - 1, dtype="uint64) to "int64", this will make your number to a negative number). If it is wrong, then it prove that the implementation of PR #7083 maybe can't work because of the original integer implicit conversion logic, and the golden of these test cases maybe wrong.

I found the integer implicit conversion is very important for the implementation of PR #7083, so we should investigate it in more details and discuss whether the C standard integer implicit conversion can meet all our requirements or not.

**Comment by tkonolige** [comment]
@Johnson9009 The correct implementation should be `uint64 - uint64`. In general, all computation in the PRNG kernels should be done with uint64. I'm running a couple randomness test suites to make sure things look good. Right now main fails the tests, but your branch passes. I think you could redo the golden data from the failing tests.

**Comment by junrushao1994** [comment]
Thanks @Johnson9009 for the investigation and @tkonolige for the confirmation!

**Comment by Johnson9009** [comment]
Thank  @tkonolige for the confirmation, I have regolden the test case and all of test cases are passed.

**Review by junrushao1994 — APPROVED** [review]

**Pull request merged**
