### PR TITLE
[Unity][QNN][Hexagon]Support Relax Constants in the QNN TOPI operations

### PR DESCRIPTION
**Pull request by farshidsp**
Support Relax Constants in the QNN TOPI operations. 

@csullivan

### CODE REVIEW

**Comment by mehrdadh** [comment]
Please don't forget `[Unity]` in the PR title for unity PRs.

**Review by janetsc — APPROVED** [review]
Looks good - thanks!

**Review by csullivan — APPROVED** [review]
LGTM, thanks @farshidsp!

**Comment by csullivan** [comment]
Thanks @farshidsp, @janetsc, this is merged!

**Pull request merged**
