### PR TITLE
Deploy the Pretrained Model on Jetson Nano

### PR DESCRIPTION
**Pull request by BBuf**
This PR shows an example of inferring a ResNet pre-trained model on Jetson Nano, hoping to be accepted. Both inference modes (local and rpc remote) can successfully complete the prediction. The following is the test record. 

remote rpc：

图片

local_demo：

图片

### CODE REVIEW

**Comment by junrushao1994** [comment]
I like the idea of this tutorial, but it will be helpful if someone could coach in terms of writing. @ganler @hogepodge would you guys like to help?

**Comment by BBuf** [comment]
> 
> 
> I like the idea of this tutorial, but it will be helpful if someone could coach in terms of writing. @ganler @hogepodge would you guys like to help?

It seems that no response has been received.

**Comment by BBuf** [comment]
@junrushao1994 Hello, can I get more suggestions for this pr? I have submitted it for a week。=.=

**Comment by junrushao1994** [comment]
@Hzfengsy Would you like to take a look?

**Review by Hzfengsy — APPROVED** [review]
LGTM. But we need to rerun the CI before merge. Since this PR has been there a lot of time

**Comment by BBuf** [comment]
> LGTM. But we need to rerun the CI before merge. Since this PR has been there a lot of time

Hello, this pr seems to be stuck in the last step, can you merge it? thanks。

**Comment by areusch** [comment]
hey @BBuf i just got a notification about this PR. would you be up for re-running it through CI? it looks like a pretty great tutorial!

**Pull request closed without merging**
