### PR TITLE
fix pytorch frontend bug

### PR DESCRIPTION
**Pull request by zhaojinxi**
When importing yolov5, inputs contains list.

### CODE REVIEW

**Comment by masahi** [comment]
which yolo5 implementation, and what does the list input correspond to? In general, list inputs should be avoided. Usually there is really no need to have a list input. This one https://github.com/zhiqwang/yolov5-rt-stack works well with TVM.

Also you need to add a test.

**Comment by zhaojinxi** [comment]
@masahi I just use the **yolov5 of  official implementation** https://github.com/ultralytics/yolov5/issues/251, with the command: "python export.py --weights yolov5s.pt --img 640 --include torchscript". Then i get a torchscript model.

compile this model:
shape_dict = {'images': [1,3,640,640]}
model_onnx = onnx.load('yolov5s.onnx')
mod, params = relay.frontend.from_onnx(model_onnx, shape_dict)

then will get a error:
  Check failed: (!checked_type.defined()) is false: Expected Array[RelayExpr], but got Array[index 1: Array]

**Comment by comaniac** [comment]
Looks like you're dealing with a nested input array. I'm not familiar with YOLOv5 so I have no idea how this case is. My question is if there would be any correctness issue in IR or final result if we simplify flat a nested input array to be a tuple.

**Comment by masahi** [comment]
ok I took a look at this model. The input list in question is not the "user input", but it happens in the middle of the model:
```
  %81 : Tensor[] = prim::ListConstruct(%77, %78, %79)
  %82 : (Tensor, Tensor[]) = prim::TupleConstruct(%80, %81)
  return (%82)
```
So although it is correct to say that the `prim::TupleConstruct` converter needs to support a list of tensors, flattening everything as  in this PR is not correct. That would be ok for this model since the constructed tuple is the return value, but otherwise the conversion would be broken.

The following is "more correct", but it only handles one level of nesting. We need to recursively construct a tuple for each tensor list nested within another list. @zhaojinxi Please update the PR with a test case.

```
elif operator == "prim::TupleConstruct":
    inputs_list = []
    for i, _ in enumerate(inputs):
        if isinstance(inputs[i], list):
            inputs_list.append(_expr.Tuple(inputs[i]))
        else:
            assert isinstance(inputs[i], _expr.Expr)
            inputs_list.append(inputs[i])
    outputs[node_name] = _expr.Tuple(inputs_list)
```

**Review by masahi — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by zhaojinxi** [comment]
@masahi Thanks, as you say, we need to handel the nested inputs situation, so I update the code. I have run the evaluation code in tvm, MAP is ok. Test case will update later.

**Comment by masahi** [comment]
The code looks good to me. Coming up with a test case might be hard - I'm ok with merging this as is since the code is simple and obvious.

**Review by masahi — APPROVED** [review]

**Pull request merged**
