### PR TITLE
[Dlight] Change max_threads on CUDA

### PR DESCRIPTION
**Pull request by jinhongyii**
change max number of threads per block from 256 to 1024, which makes rms_norm faster

### CODE REVIEW

**Comment by jinhongyii** [comment]
cc: @junrushao

**Comment by junrushao** [comment]
Given that it’s a global change, is it going to positively or negatively affect other operators on CUDA GPU?

**Comment by jinhongyii** [comment]
It only affects reduction ops. Specifically, in llm, it only means rms_norm and layer_norm. So I believe it's safe to merge

**Comment by junrushao** [comment]
Could you fix the unittests so that I could get it in?

**Review by Hzfengsy — CHANGES_REQUESTED** [review]
It's UNSFAE. As:
1. It's global changes. Although it is only used for specific ops, but it might be used in other cases.
2. For reduction rules, we should also consider the operators that are smaller than 1024

My suggestion is adding analysis in Reduction rules, if the size is large enough, than use 1024, else pick 256

**Comment by jinhongyii** [comment]
When operator is smaller than 1024, suggest_threads_per_block will return the largest thread num that is smaller than loop extent. @Hzfengsy

**Review by Hzfengsy — APPROVED** [review]

**Pull request merged**
