### PR TITLE
[CI] Hotfix Jenkinsfile

### PR DESCRIPTION
**Pull request by tqchen**
Due to the current setup jenkins file changes needs to go through docker staging branch

cc @driazati @areusch

### CODE REVIEW

**Comment by junrushao1994** [comment]
Yeah the recent jenkins change brought a lot of cool features that we all like a lot. Not sure why this regression is introduced, but will be great if we could follow the convention that we test jenkins in [this](https://github.com/apache/tvm/tree/ci-docker-staging) branch

**Review by junrushao1994 — APPROVED** [review]
Let's get it merged quickly!

**Review by driazati — APPROVED** [review]
Thanks for fixing, sorry for breaking again (I had tested it out in the staging Jenkins but the PR branch was not up-to-date with that branch). Having any Jenkinsfile changes go through ci-docker-staging sounds pretty reasonable

**Comment by mbs-octoml** [comment]
Thanks @driazati , no worries about the break, all for The Greater Good.

**Pull request merged**
