### PR TITLE
[KVCache] Fix the reference counter in sequence fork

### PR DESCRIPTION
**Pull request by MasterJH5574**
This PR fixes a sequence reference counter bug in the KV cache: when forking a child sequnece from an existing parent sequence, the reference counter of hte parent sequence was not increased. This leads to error when the child sequence is removed, where we will check the parent's reference counter and find it is 0 and is never changed unexpectedly.

Meanwhile, this PR updates the PagedKVCache tests with some latest changes, including target-aware tile size selection.

### CODE REVIEW

**Comment by MasterJH5574** [comment]
@tvm-bot rerun

**Comment by MasterJH5574** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Comment by MasterJH5574** [comment]
@tvm-bot rerun

**Comment by MasterJH5574** [comment]
@tvm-bot rerun

**Comment by MasterJH5574** [comment]
@tvm-bot rerun

**Review by tqchen — APPROVED** [review]

**Pull request merged**
