### PR TITLE
[Tensorflow] Fix conv2d_transpose for NHWC layout

### PR DESCRIPTION
**Pull request by jikechao**
If "data_format" == "NHWC", the kernel_layout for conv2d_transpose should be "HWOI" rather than "HWIO".

### CODE REVIEW

**Comment by jikechao** [comment]
As we can see in frontend about [conv2d_transpose](https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/keras.py#:~:text=keras_layer.input_shape-,if%20data_layout%20%3D%3D%20%22NHWC%22%3A,kernel_layout%20%3D%20%22HWOI%22,-else%3A)
, the kernel_layout for conv2d_transpose was set as "HWOI" when the data_layout='NHWC', while the Tensorflow frontend set the kernel_layout='HWIO' mistankenly.  I submitted this PR to fix it.

@leandron @vvchernov  Please help me review this PR. Thanks!

**Comment by yongwww** [comment]
@jikechao  it would be good to add test cases for this fix

**Comment by vvchernov** [comment]
Hello @jikechao! Good fix. It looks like misprinting or thoughtless ctr+c, ctr+v from conv condition. I agree with @yongwww CI test is needed to check it

**Comment by jikechao** [comment]
@yongwww @vvchernov Thanks for your review. 
I tried to construct a test case to trigger this bug but failed. By analyzing the source code, I found that the wrong logic statement is in a dead code.  Specifically, when the `op_name=='conv2d_transpose' and layout='NHWC'`, the layout was reset to 'NCHW' in this [line](https://github.com/apache/tvm/blob/778749629c420121fbb9e28e9b356871e95554e8/python/tvm/relay/frontend/tensorflow_ops.py#:~:text=if%20opname%20%3D%3D%20%22conv_transpose%22%20and,%22data_format%22%5D%20%3D%20%22NCHW%22). Thus, the condition `if attr["data_format"] == "NHWC"` always be `False`.  
I deleted the wrong logic in the dead code. Please help me review it again. Thanks!

**Comment by jikechao** [comment]
@echuraev Indeed, this link can't redirect to the highlight place by clicking it directly. As a workaround, you can open this link by copying this link and past it into a new browser window.

I'll add a unit test sooner!

**Review by vvchernov — APPROVED** [review]
LGTM

**Review by echuraev — APPROVED** [review]
LGTM. Thanks. Please fix CI and then it can be merged.

**Comment by jikechao** [comment]
@echuraev CI fixed, could you merge this PR?

**Comment by echuraev** [comment]
@jikechao Thank you for your work :)

**Pull request merged**
