### PR TITLE
[TIR] Fix Bug in VectorizeLoop 

### PR DESCRIPTION
**Pull request by CharlieFRuan**
This PR fixes a bug in vectorize loop introduced related to https://github.com/apache/tvm/pull/16966

The visit to condition can write need scalarize to true then the followup visit to then case can trigger an ICHECK.

The visit to let value can also write need scalarize flag in which case we need to immediately scalarize.

### CODE REVIEW

**Review by lhutton1 — APPROVED** [review]
Thanks for the fix, apologies for missing it previously!

**Comment by tqchen** [comment]
@tvm-bot  rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by ekalda** [comment]
Thanks @tqchen and @CharlieFRuan for the fix!

**Pull request merged**
