### PR TITLE
[Relay][Topi] Fix GPU NMS when return_indices is True

### PR DESCRIPTION
**Pull request by kevinthesun**
@anijain2305 @zhiics @Laurawly

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Comment by kevinthesun** [comment]
@zhiics @anijain2305 @tqchen We need Thrust library for gpu dynamic nms to pass ci.

**Comment by zhiics** [comment]
Can we just enable thrust in the gpu CI script?

**Comment by kevinthesun** [comment]
@zhiics That's a good idea since we will need it for arghwere and topk as well.

**Review by Laurawly — APPROVED** [review]
LGTM

**Review by zhiics — APPROVED** [review]

**Comment by kevinthesun** [comment]
Thanks @anijain2305 @zhiics @Laurawly

**Pull request merged**
