### PR TITLE
[CI] Modify test cases to accommodate the CI upgrades

### PR DESCRIPTION
**Pull request by yongwww**
update with the images built from https://github.com/apache/tvm/pull/14635

Co-authored by @driazati

### CODE REVIEW

**Comment by yongwww** [comment]
It is ready for review now, CI is supposed to be green soon. cc: @tqchen @masahi

**Comment by tqchen** [comment]
@yongwww please resolve the conflict

**Review by leandron — CHANGES_REQUESTED** [review]
HI, thanks for putting all the work to update dependencies.

Can you clarify, before we merge this PR, what is the plan to get these changes in with properly named Docker images, not development image names such as `477529581014.dkr.ecr.us-west-2.amazonaws.com/ci_arm:PR-14635-40ebeb599-30`?

**Comment by yongwww** [comment]
@leandron I am following [the steps](https://tvm.apache.org/docs/contribute/ci.html#updating-a-docker-image-tag) to upgrade the CI. I assume the upgraded images will be built and uploaded into tlcpackstaging after #14635 lands, then I just need to update ci/jenkins/docker-images.ini in this PR to point to the expected newly generated images.

**Comment by yongwww** [comment]
@tvm-bot  rerun

**Comment by yongwww** [comment]
@tvm-bot rerun

**Comment by yongwww** [comment]
The docker images built from the ci upgrade https://github.com/apache/tvm/pull/14635 have been automatically uploaded to tlcpackstaging. In this pr, I have modified the docker-images.ini to point to those newly uploaded images, and CI is green now. Please take a look and help land it if there are no further change requests. cc: @tqchen @leandron @masahi @driazati

**Review by leandron — APPROVED** [review]

**Comment by leandron** [comment]
Thanks @yongwww @tqchen, this is now merged, thanks for the great work!

**Pull request merged**
