### PR TITLE
[Unity][MSC][M0.2] MSCGraph core

### PR DESCRIPTION
**Pull request by Archermmt**
This is a pull request for MSC(Multi-System Compile)
RFC: https://discuss.tvm.apache.org/t/rfc-unity-msc-introduction-to-multi-system-compiler/15251/5
Tracking issue: https://github.com/apache/tvm/issues/15233

This is the first part of Milestone 0: Build MSCGraph core parts. Enable translation between Relay, Relax and MSCGraph without loss information.

To limit each PR in reviewable size, the Milestone 0 will be split into 5 steps:
M0.1: Passes for set name and layout for expressions (src/contrib/msc/transform)
M0.2: MSCGraph core (src/contrib/msc/core/ir/graph && python/tvm/contrib/msc/core/ir/graph)
M0.3: MSCGraph Builder (src/contrib/msc/core/ir/graph_builder)
M0.4: Codegen (src/contrib/msc/core/codegen, src/contrib/msc/framework/tvm/codegen)
M0.5: Translation test (relax/relay test && related helper modules in python)

This PR add the very basic data structure for MSC, thus MSCGraph and WeightGraph.

MSCGraph is a DAG structure built from relax or relay function. It saves the info of every Expr and will be used in all the MSC submodules. Structure of MSCGraph is similar with the tf.Graph in tensorflow, thus a graph has nodes (MSCJoint) and tensors (MSCTensor). Each node has parent and children, and each tensor has producer and consumers. To manage the weights in computational graph, the MSCGraph define some Constants as weights, for example the 2nd input of Call(nn.conv2d) will be defined as a weight("weight") of the node. That is essential when we process the weights in computational graph, especially for training stage.

WeightGraph is a DAG structure built from MSCGraph. It describes the topology of weights in MSCGraph. WeightGraph is needed in weight pruning and mask generation for sparse training, when relationship between weights are necessary to make prune strategy. WeightGraph also contains nodes (WeightJoint) and tensors (MSCTensor).

Tests of the MSCGraph will be added in next step(M0.3 MSCGraph Builder). Because the MSCGraph can only be built from relax or relay, no tests can be execute before we build a MSCGraph.

cc @Hzfengsy

### CODE REVIEW

**Comment by Hzfengsy** [comment]
One general question: Is it possible to add testcase in this PR? If not, please add a todo in the tracking issue, and add them in the following PR.

**Comment by Archermmt** [comment]
//Todo: Add test for M0.2 in M0.3, reason: Graph can tested only by build

**Comment by Archermmt** [comment]
Seems like I have no access to adding labels in tracking issue.... I add a comment to mark that. Test will for MSCGraph will be added in M0.3:MSCGraph Builder

**Review by Hzfengsy — APPROVED** [review]
LGTM. Let's leave it open for another 2 days to see if anyone else would take a look

**Comment by Hzfengsy** [comment]
Thanks @Archermmt

**Pull request merged**
