### PR TITLE
[SUPPORT] Fix RingBuffer ReadWithCallback

### PR DESCRIPTION
**Pull request by tqchen**
This PR bugfixes ring buffer ReadWithCallback when the callback send function read part of the data.
Also backported one robustness fix from unity.

Testcases are added

### CODE REVIEW

**Review by MasterJH5574 — APPROVED** [review]

**Review by junrushao — APPROVED** [review]
LGTM!

**Comment by junrushao** [comment]
Looks like there is a CI outage

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
@tvm-bot  rerun

**Comment by junrushao** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Comment by tqchen** [comment]
@tvm-bot rerun

**Pull request merged**
