### PR TITLE
[BYOC] CUTLASS integration

### PR DESCRIPTION
**Pull request by Laurawly**
As discussed in RFC: https://discuss.tvm.apache.org/t/rfc-byoc-nvidia-cutlass-integration/9147, this PR is a CUTLASS integration of GEMM to TVM. It also includes a profiler to search for best params in CUTLASS.
@masahi Please take over this PR, Thanks!

### CODE REVIEW

**Comment by masahi** [comment]
Thanks @Laurawly, I'll work on this as my top priority!

**Comment by junrushao1994** [comment]
Really cool work @Laurawly!

**Comment by masahi** [comment]
One question for @comaniac: Currently, this integration is implemented with C source backend. But one big use case for cutlass BYOC is for dynamic workloads, for which we cannot do well at the moment. I think C source backend is not compatible with dynamic inputs, is that right? On the other hand, with json codegen/runtime, I can see a way to support dynamic inputs.

However, since cutlass is a template library, the only way it could work with the json codegen/runtime is to instantiate all possible templates that we care about ahead of time, and build them together with `libtvm.so`. I wonder if that is feasible cc @Laurawly.

**Comment by zhiics** [comment]
I think even C source code should be able to handle dynamic shapes as well since it only expects tensors at the runtime, or I might forget something here. But in general, json format is more recommended as it is easier to debug and maintain. It is also more friendly in handling constants.

**Comment by masahi** [comment]
> I think even C source code should be able to handle dynamic shapes as well since it only expects tensors at the runtime

Exactly, I've looked at the code a bit and it seems currently we generate an API that takes `DLTensor`s as inputs, but it passes only raw pointers to the generated backend calls. It is easy to change things a bit to pass shape information as welll.
https://github.com/apache/tvm/blob/3cb838de434f80d584a48a0b41e2a253bb4759ed/src/relay/backend/contrib/codegen_c/codegen_c.h#L176-L185

I'm glad to find at least one path that supports all use cases. For the json codegen/runtime path, I'm not sure how to integrate cutlass's JIT codegen + compile approach with it.

**Comment by masahi** [comment]
> I agree that kernel picking should be handled by the custom runtime.

It would be interesting if we can apply the same logic that AutoTIR would develop soon, since they need to solve the same (or harder) problem anyway. I believe most of our dynamic input use cases have dynamism only in the first (batch) dimension, so things shouldn't be complicated.

**Comment by masahi** [comment]
I think it is reasonable to ask users for an estimate of a range of dynamism. Without such estimate, we just fallback to a default kernel that works on any input shapes, which shouldn't be too slow anyway since it is cutlass, not TVM :) This should be a reasonable trade off between performance and convenience of dynamic models: if they want to run fast on dynamic models, they need to help us, otherwise we cannot guarantee good performance.

I believe even if a network contains many dynamic workloads, there is only one underlying dynamism, from which other dynamic shapes can be derived. For example, MaskRCNN contains some dynamic batch dense, conv2d and conv2d transpose, but all dynamic dims directly correspond to the number of boxes detected, or some numbers derived from it (such as the number of box times * pool window size * feature size, the latter two are fixed numbers). For transformers, I guess the true dynamism is only in sequence length. So I think it wouldn't be too much of an ask to give an estimate of such numbers.

**Comment by masahi** [comment]
This is ready for review. The bulk of PR is a kernel generator taken from cutlass, simplified for our purpose + more epilogue support.

The followings are supported:
* `dense` with bias, bias + relu, and bias + gelu epilogue
* fp16 and fp32 accumulation
* Kernels for Turing and Ampere

The follow-up work will add more features:
* dynamic input (only basic one, the heuristic stuff is complicated so I defer it for future)
* conv2d and batched gemm
* More epilogues to support e2d models. I'm planning to test MaskRCNN, DeeplabV3, EfficientNet v2, and BERT-large. This require some work to extend cutlass (see https://github.com/NVIDIA/cutlass/discussions/347)

Low priority (for me) but things we should support eventually:
* Heuristic for dynamic inputs
* int8 and int4 kernels

**Pull request merged**
