### PR TITLE
[BugFix]: Convert tuple to int

### PR DESCRIPTION
**Pull request by CaptainDuke**
If param stride is tuple, like (1, 1), errors would occur like following:

`
File "xxx/python/tvm/topi/testing/conv2d_hwcn_python.py", line 76, in conv2d_hwcn_python
bt[n, f] += out[::stride, ::stride]
TypeError: slice indices must be integers or None or have an __index__ method
`

Because tuple has not been handled correctly in line: 52

### CODE REVIEW

**Comment by CaptainDuke** [comment]
@tqchen Please review this pr, thanks

**Review by jcf94 — APPROVED** [review]
@CaptainDuke Thanks! Good catch.

**Comment by tqchen** [comment]
Thanks @CaptainDuke can you add a regression test to this bug?

**Comment by CaptainDuke** [comment]
> Thanks @CaptainDuke can you add a regression test to this bug?

Test cases added.
Besides, I found duplicated test cases and changed batch_size from 256 to 128.

**Comment by jcf94** [comment]
> > Thanks @CaptainDuke can you add a regression test to this bug?
> 
> Test cases added.
> Besides, I found duplicated test cases and changed batch_size from 256 to 128.

Thanks! We can merge this after all CI jobs have been cleaned.

**Comment by CaptainDuke** [comment]
> > > Thanks @CaptainDuke can you add a regression test to this bug?
> > 
> > 
> > Test cases added.
> > Besides, I found duplicated test cases and changed batch_size from 256 to 128.
> 
> Thanks! We can merge this once all CI jobs have been cleaned.

Could you please merge this PR? The CI job seems failed due to test_vm_rpc.

**Comment by jcf94** [comment]
> > > > Thanks @CaptainDuke can you add a regression test to this bug?
> > > 
> > > 
> > > Test cases added.
> > > Besides, I found duplicated test cases and changed batch_size from 256 to 128.
> > 
> > 
> > Thanks! We can merge this once all CI jobs have been cleaned.
> 
> @jcf94 Could you please merge this PR? The CI job seems failed due to test_vm_rpc.

E ... This is the limit of Github, I'm not able to merge it if the CI has not passed.
I see that the CI error is not related to this PR, you can try to push a new commit to re-trigger the CI. It may pass next time.

**Comment by CaptainDuke** [comment]
@tqchen @jcf94 
I pushed a new commit again but CI for ARM failed once more. How could I pass this test in a easier way?

```
+ docker/bash.sh tlcpack/ci-arm:v0.03 ./tests/scripts/task_config_build_arm.sh

WORKSPACE: /home/jenkins/workspace/exec_0/tvm/build-arm

DOCKER CONTAINER NAME: tlcpack/ci-arm:v0.03



Running './tests/scripts/task_config_build_arm.sh' inside tlcpack/ci-arm:v0.03...

docker/bash.sh: line 152: docker: command not found

script returned exit code 127
```

**Comment by CaptainDuke** [comment]
@tqchen @jcf94 Ready to merge

**Pull request merged**
