### PR TITLE
[PopenPool] Enable Stdout & Stderr Redirect in PopenPool & PopenWorker

### PR DESCRIPTION
**Pull request by zxybazh**
This PR enables redirection of the standard output stream and standard error stream to given subprocess handler.

This function especially improves the usage of `LocalRunner` because previously a sample candidate's exception during running could print long lines of output, making console logging / notebook logging obsolete. In the meantime, any failure of the candidates are still preserved in the per-task logging files (Schedule, trace & TIR available, doesn't include the stack trace though).

Credits to @Hzfengsy's fix in https://github.com/mlc-ai/relax/pull/6.

### CODE REVIEW

**Comment by zxybazh** [comment]
CC @Hzfengsy @shingjan  @junrushao @tqchen

**Review by shingjan — APPROVED** [review]
LGTM

**Review by Hzfengsy — APPROVED** [review]
LGTM, but I wonder if we can have additional testcases

**Comment by zxybazh** [comment]
> LGTM, but I wonder if we can have additional testcases

Thanks, will add that in a follow up PR!

**Pull request merged**
