### PR TITLE
[Op][Topi] 5 ops can accept unsigned integers as indices

### PR DESCRIPTION
**Pull request by FZYUAN-1**
Hello community,

This PR links to #10064. 5 ops (scatter, scatter_add, scatter_nd, unravel_index, adv_index) accept unsigned integers as indices. Somehow unravel_index with uint indices may raise 
```
Check failed: y != 0 (0 vs. 0) 
```
in function
https://github.com/apache/tvm/blob/e6af87491eb250a3266b1f09b36055c6ee79146b/src/arith/const_int_bound.cc#L486.

I tried to figure out why shape[v] can be 0 in https://github.com/apache/tvm/blob/7b9fd1e2ab5e0af927f202faef5d682706608fc7/include/tvm/topi/transform.h#L383,
but I failed to understand.

Thank reviewers for your help and your time speeding in CR. 

cc @AndrewZhaoLuo

### CODE REVIEW

**Comment by AndrewZhaoLuo** [comment]
Debugging I've worked the issue to likely `src/tir/transforms/narrow_datatype.cc`

**Comment by AndrewZhaoLuo** [comment]
https://github.com/apache/tvm/pull/10102 <-- fix here. There is another error now with unravel index now though. You can try digging more, or you can drop unravel_index for later PR (which I recommend)

**Review by AndrewZhaoLuo — COMMENTED** [review]
LGTM mostly, just lmk the plan to deal with unravel_index

**Comment by FZYUAN-1** [comment]
> LGTM mostly, just lmk the plan to deal with unravel_index

Thanks for your help! I prefer to drop unravel_index and open a PR later.

**Review by AndrewZhaoLuo — APPROVED** [review]
LGTM

**Pull request merged**
