### PR TITLE
[microTVM]Fix dense_dsp schedule in autotuning

### LINKED ISSUE #12270: [Bug][microTVM] dense_dsp ARM schedule is not picked up in autotuning
When we run auto tune function for a model with dense layers, like anomaly detection, we don't see dense_dsp in the extracted tasks.
This was originally reported by @guberti 

cc @alanmacd @gromero

### PR DESCRIPTION
**Pull request by mehrdadh**
This PR fixes #12270 

cc @alanmacd @areusch @gromero @guberti

### CODE REVIEW

**Comment by guberti** [comment]
Currently running a profiling tuning job - will check how this improves performance.

**Comment by mehrdadh** [comment]
@guberti just to clarify, this PR doesn't confirm the performance improvement. It will only fix the bug that was avoiding this schedule to be picked up by auto tunner.

**Review by guberti — COMMENTED** [review]
I can confirm this fixes #12270, as `dense_dsp.arm_cpu` is now picked up. However, it looks like the config string is empty, and there are no possibilities that can be autotuned. See the below tuning output for an anomaly detection model:
```
{"input": ["c -keys=arm_cpu,cpu -device=arm_cpu -link-params=0 -mcpu=cortex-m4 -model=cxd5602gg", "dense_dsp.arm_cpu", [["TENSOR", [1, 640], "int16"], ["TENSOR", [128, 640], "int16"], null, "int32"], {}], "config": {"index": 0, "code_hash": null, "entity": []}, "result": [[0.006714], 0, 30.18607449531555, 1659468884.7003868], "version": 0.2, "tvm_version": "0.10.dev0"}
{"input": ["c -keys=arm_cpu,cpu -device=arm_cpu -link-params=0 -mcpu=cortex-m4 -model=cxd5602gg", "dense_dsp.arm_cpu", [["TENSOR", [1, 128], "int16"], ["TENSOR", [128, 128], "int16"], null, "int32"], {}], "config": {"index": 0, "code_hash": null, "entity": []}, "result": [[0.001282], 0, 27.70340657234192, 1659468913.6762078], "version": 0.2, "tvm_version": "0.10.dev0"}
{"input": ["c -keys=arm_cpu,cpu -device=arm_cpu -link-params=0 -mcpu=cortex-m4 -model=cxd5602gg", "dense_dsp.arm_cpu", [["TENSOR", [1, 128], "int16"], ["TENSOR", [8, 128], "int16"], null, "int32"], {}], "config": {"index": 0, "code_hash": null, "entity": []}, "result": [[9.1e-05], 0, 26.62199854850769, 1659468941.4293904], "version": 0.2, "tvm_version": "0.10.dev0"}
{"input": ["c -keys=arm_cpu,cpu -device=arm_cpu -link-params=0 -mcpu=cortex-m4 -model=cxd5602gg", "dense_dsp.arm_cpu", [["TENSOR", [1, 8], "int16"], ["TENSOR", [128, 8], "int16"], null, "int32"], {}], "config": {"index": 0, "code_hash": null, "entity": []}, "result": [[9.2e-05], 0, 26.441710710525513, 1659468969.0030704], "version": 0.2, "tvm_version": "0.10.dev0"}
{"input": ["c -keys=arm_cpu,cpu -device=arm_cpu -link-params=0 -mcpu=cortex-m4 -model=cxd5602gg", "dense_dsp.arm_cpu", [["TENSOR", [1, 128], "int16"], ["TENSOR", [640, 128], "int16"], null, "int32"], {}], "config": {"index": 0, "code_hash": null, "entity": []}, "result": [[0.006775], 0, 27.223129749298096, 1659468997.4136612], "version": 0.2, "tvm_version": "0.10.dev0"}
```
Note also that the current implementation of `dense_dsp.arm_cpu` is only fast for `int16` values, and we will need a new schedule for better support of `int8`. That is out of the scope of this PR, though.

Thanks for the change!

**Comment by mehrdadh** [comment]
@guberti thanks for running the autotuning job. They config issue is probably related to lack of tiling in the schedule. I will work on that issue in a separate PR.

**Review by areusch — APPROVED** [review]

**Pull request merged**
