### PR TITLE
Fix incorrect device name in TVMC.

### PR DESCRIPTION
**Pull request by mdw-octoml**
Small bug in TVMC where the command line flag expects `--device gpu` but the runner code expects `--device cuda`.

### CODE REVIEW

**Comment by mdw-octoml** [comment]
@euntaik @YuchenJin Not sure what your preference is for the command-line flag for --device in TVMC, this PR makes it "gpu" consistently. Happy to change it to "cuda" if you prefer that.

**Comment by YuchenJin** [comment]
@mdw-octoml Thanks for catching the bug! I missed renaming "gpu" to "cuda" in the command line flag in PR #8032. I prefer  using "cuda" as the device type because it is more consistent with other parts of the tvm code, for example, we are using `tvm.cuda()` now.

**Comment by mdw-octoml** [comment]
Great! Renamed to "cuda".

**Review by YuchenJin — APPROVED** [review]
Looks good to me! Thanks @mdw-octoml!

**Comment by mdw-octoml** [comment]
Who can merge this when CI passes? @jwfromm

**Review by leandron — APPROVED** [review]
> Who can merge this when CI passes? @jwfromm

LGTM - I can merge once CI is clean. I think the current error is not related to the PR, can you just retrigger CI?

**Pull request merged**
