### PR TITLE
Update JSON serialization to annotate type of each `attr`

### PR DESCRIPTION
**Pull request by chanwutk**

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @chanwutk . This would change the general serialization format and would need a bit more discussion. If we need the additional information for say visualizer, we could have an alternative export function

**Comment by jwfromm** [comment]
Just curious, Tianqi, what are the downsides to adding this annotation given that it minimally effects parsing? Having the serialized format be more human readable seems like a good improvement.

**Comment by chanwutk** [comment]
Currently, we have the modified serialization to output JSON like this:
```js
{
  type_key: 'relay.Call',
  attrs: {
    padding: {node: '10'},
    group: {value: '1'},
    ...other_attrs
  }
}
```

If we output it to not change the structure of `attrs` but add `type_attrs` instead, would it be ok?
This way, we do not break the existing schema for the original serialization, but we can still have access to the typing of each attribute
```js
{
  type_key: 'relay.Call',
  attrs: {
    padding: '10',
    group: '1',
    ...other_attrs
  },
  attr_types: {
    padding: 'node',
    group: 'value',
    ...other_attr_types
  }
}
```

**Comment by tqchen** [comment]
@jwfromm the main concern was backward compatibility. 

We need to make sure the serialized data in previous schema being readable under the new setups. That is why I initially suggested to allow an option to output of the new schema. e.g. having something like

```python
# new behavior
result0 = x.save_json(with_typing=True)
result1 = x.save_json(with_typing=False)

x = tvm.ir.load_json(result0)
y = tvm.ir.load_json(result1)

tvm.ir.assert_structural_equal(x, y) 
```

**Comment by areusch** [comment]
i agree with @tqchen we do need to think about backwards compat, but i don't know that prefer introducing yet another graph serialization format. is there any issue with purely additive changes here?

**Comment by jroesch** [comment]
This PR appears to be out of date, please feel free to reopen it if this is not the case.

As part of the new year we are attempting to triage the project's open pull requests to ensure that code which
is ready for review and/or merging receives adequate attention.

Thanks again for your contribution, and feel free to reach out to discuss these changes.

**Pull request closed without merging**
