### PR TITLE
Add pass to fold type transformations into function signature

### PR DESCRIPTION
**Pull request by anwang2009**
As title.

This transformer gives users more control over where preprocessing steps may be located, and what input types their relay program can accept

### CODE REVIEW

**Comment by masahi** [comment]
@anwang2009 Please take a look at the CI problem.

**Comment by AndrewZhaoLuo** [comment]
@anwang2009 do you still have interest in merging this PR?

**Comment by areusch** [comment]
@AndrewZhaoLuo @anwang2009 are you guys doing this as part of #8296 or is that just related?

**Comment by AndrewZhaoLuo** [comment]
@anwang2009 any plans to continue working on this PR?

**Comment by anwang2009** [comment]
Unrelated to that issue linked. I plan to continue working on this, I just need to find the time :upside_down_face:
Sorry for the languishing, I'll try to get something in by start of next week.

**Pull request closed without merging**
