### PR TITLE
[TIR][Schedule] Fix cache_read loc detecting and region_cover checking

### PR DESCRIPTION
**Pull request by multiverstack-intellif**
Fix 2 issues of cache related primitives:
*  Fix region_cover checking for cache related primitives
*  Fix CacheLocDetector for nested SeqStmt
cc @Hzfengsy @wrongtest-intellif

### CODE REVIEW

**Comment by Hzfengsy** [comment]
Could you please add a regression testcase?

**Comment by junrushao** [comment]
@wrongtest-intellif would you like to review this PR? Thanks!

**Comment by multiverstack-intellif** [comment]
> 

Test case added.

**Comment by multiverstack-intellif** [comment]
> Could you please add a regression testcase?

Test case added.

**Review by wrongtest-intellif — APPROVED** [review]
LGTM. It works well for my workloads, thanks very mush!

**Pull request merged**
