### PR TITLE
fix default config path

### PR DESCRIPTION
**Pull request by jhlee525**
Currently, the logic for finding `config.cmake` in `CMakeLists.txt` looks like this

```
if(EXISTS ${CMAKE_CURRENT_BINARY_DIR}/config.cmake)
  include(${CMAKE_CURRENT_BINARY_DIR}/config.cmake)
else()
  if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/config.cmake)
    include(${CMAKE_CURRENT_SOURCE_DIR}/config.cmake)
  endif()
endif()
```

First, it searches from binary dir(usually ./build), then it goes to the source directory(./) if it does not exist. However, I believe it does nothing since there is no config.cmake in the root directory

We can choose another policy from various candidates, like raising an error if not exist or ignoring to use `config.cmake`. I thought using the "sample" `cmake/config.cmake` is the most reasonable solution, I changed `CMakeLists.txt` to find from `./cmake` directory.

It's my first time to commit in here, please let me know if there are any issues! 😄

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @jhlee525 this is the intended behavior that we explicitly ask the user to copy the config.cmake to root or build before edit and update. The idea is that we do not want config to polute the git history. It would be good to add comments to explain this behavior

**Comment by jhlee525** [comment]
If root directory is selected for cmake directory, the logic after `else()` is unnecessary. Because in this case, `${CMAKE_CURRENT_BINARY_DIR}` is as same as `${CMAKE_CURRENT_SOURCE_DIR}`.

And I think my version of modification also does not polute "example config.cmake" because previous logic (copying config.cmake into cmake build directory) is completely compatable.

The main benefit of this PR is to provide one-stop mode build, for the users does not want to configure thier own cmake settings.

But, it's not critical feature for running TVM, i think it would be fine to just removing else() logic, or even keeping it as-is.

**Comment by areusch** [comment]
@jhlee525 we suggest people run `cmake` from the `build` directory, so i'm not sure we intend to support running it from the root. we would like to encourage folks building TVM from source to explicitly configure it as needed. there are scripts to configure TVM as it is configured in the CI underneath tests/scripts/task_config_*.

i think we could clarify the commentary here. i also think we should probably drop support for placing `config.cmake` in the root directory, but @tqchen what are your thoughts? this would clarify we don't expect folks to run cmake there.

**Comment by tqchen** [comment]
@areusch both are fine, although some people might depends on the root dir behavior. I agree that we want to add more documentations about this behavior

**Comment by areusch** [comment]
@tqchen in these cases where we explicitly support two ways of doing things, it would really help us to lay out the exact use case we're actually supporting. otherwise we'll wind up with broader API surfaces that are harder to support. do you know why someone may want to run cmake from root dir?

**Comment by tqchen** [comment]
To clarify, by root dir behavior i actually meant config.cmake in the root but the cmake is run on a separate dir(say build). I agree that the best practice is not run cmake itself from the root(and always use a subdir)

**Comment by Mousius** [comment]
For reference, I use a `config.cmake` in the root `tvm` directory so I can remove `build` without removing all my configuration.

**Comment by areusch** [comment]
right, i guess we have two cases:
1. you want to build with config specific to that build (e.g. build-ci-cpu)
2. you just run one kind of build and want to avoid nuking the config with the build artifacts

in any case, i do think we want people to be explicit. I'm going to close this PR as we don't want to allow folks to fall back on the default config in config.cmake. feel free to reopen if you think i've closed this in error.

**Pull request closed without merging**
