### PR TITLE
[Node] Expose StructuralEqual/Hash handler implemenation to header

### PR DESCRIPTION
**Pull request by masahi**
When we use `StructuralEqual/Hash`, the actual equality testing / hashing work are deferred to `RemapVarSEqualHandler` and `VarCountingSHashHandler` class respectively, defined in `.cc` files. To customize equality / hash behavior, I want to be able to derive from these classes outside of `structural_equal.cc` or `structural_hash.cc`. This is the first step toward replacing my previous attempt https://github.com/apache/tvm/pull/12706 to allow ignoring NDArray raw data in `StructuralEqual/Hash`.

So I propose to expose them as the "default" handler, while still hiding their implementation details. This lets me define a custom hasher that ignores NDArray content simply by:

```
class SHashHandlerIgnoreNDArray : public SHashHandlerDefault {
 protected:
  void DispatchSHash(const ObjectRef& object, bool map_free_vars) override {
    ICHECK(object.defined());
    if (auto ndarray = object.as<runtime::NDArray::Container>()) {
      SHashReducer hash_reduce(this, map_free_vars);
      NDArrayHash(ndarray, &hash_reduce, false);
    } else {
      SHashHandlerDefault::DispatchSHash(object, map_free_vars);
    }
  }
};
```

cc @tqchen @junrushao

### CODE REVIEW

**Comment by junrushao** [comment]
Would love to have @tqchen's thoughts on this :-)

**Comment by tqchen** [comment]
seems to be a fine change, would be good to get another pair of eyes for reviewing

**Review by junrushao — APPROVED** [review]
LGTM

**Comment by masahi** [comment]
@tqchen good to merge?

**Comment by junrushao** [comment]
Sorry for the delay!

**Pull request merged**
