### PR TITLE
[TVMScript] Allow parameters in @T.prim_func definition

### PR DESCRIPTION
**Pull request by Lunderberg**
This extends the existing `@T.prim_func` decorator to accept a keyword-only argument `@T.prim_func(params=param_dict)`, defining a string to object mapping.  This mapping can be used to refer to external parameters from within the `PrimFunc` definition.

### CODE REVIEW

**Comment by Lunderberg** [comment]
I was thinking of this as complementary to the existing `PrimFunc.specialize`.  Where `specialize` can operate on existing `PrimFunc` objects, and can be used from C++, these parameters can only be used when generating a new `PrimFunc` object from Python.

The advantage of using the `prim_func` parameters is that they do not require adding the parameter to the `PrimFunc` arguments and do not require running through an additional transformation, making them easier to read when writing test cases.

**Comment by junrushao1994** [comment]
@Hzfengsy has some preliminary work on metaprogramming. Would you mind sharing?

**Comment by Lunderberg** [comment]
@junrushao1994 Not sure if you're asking me or @Hzfengsy on it, but I'm certainly okay with sharing.  This was useful in some test cases I was sketching out, and figured it would be good to start a conversation on it.

**Comment by junrushao1994** [comment]
Oh sorry for the confusion! I was asking Siyuan

**Comment by Hzfengsy** [comment]
Here is a related PR: https://github.com/apache/tvm/pull/11097

**Comment by Lunderberg** [comment]
Closing in favor of #11097, any deltas can be added in later PRs.

**Pull request closed without merging**
